### ISSUE TITLE
Manage_TrackSideInformation_Integration_Pkg.xscade: Packet contents type clarification

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#100]
node Manage_TrackSideInformation_Integration (...)
returns {
(...)
outputMessage : Common_Types_Pkg::ReceivedMessage_T
(...)
}

node InformationFilter  (...)
returns {
(...)
outMessage : DataDictionary::Message
(...)

as outMessage in InformationFilter produces outputMessage in Manage_TrackSideInformation_Integration, which type should I build the flooding functions (to build track profiles from packet contents from?
Or, more precisely, which of the types will you use to build the information?

I assume it is rather the ReceivedMessage_T, as this seems to be more elaborated already?

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[modeling] Manage_TrackSideInformation_Integration_Pkg.xscade: Packet contents type clarification (#100)" gesendet am 02.02.2015 20:47:12. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by BerndHekele** [comment]
Hi Jakob,
the outputMessage : Common_Types_Pkg::ReceivedMessage_T is relevant for output of the function.
The output of the InformationFilter is only temporary.

cu
Bernd

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] Manage_TrackSideInformation_Integration_Pkg.xscade: Packet contents type clarification (#100)" gesendet am 03.02.2015 09:24:47. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] Manage_TrackSideInformation_Integration_Pkg.xscade: Packet contents type clarification (#100)" gesendet am 03.02.2015 09:24:46. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=
