### ISSUE TITLE
openETCS time base

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#102]
I have not yet seen any discussion on the notion of time in our model/ system

There are two aspects:

Absolute time (time read from a RTC through the runtime), which is relevant for example for timestamps on messages (from STM, to JRU etc.)
Such a time would typically be external to the SCADE generated SW, and could be made available anywhere in the model if a SCADE Signal is used.

For a pure simulation model, time would be modelled in the environment model.

Cycle time

Assuming that the SCADE model is generated into SW that is cyclically being executed on a fixed time base, the notion of time inside the model can be based on counting cycles, which simplifies many tasks.

A SCADE constant with the cycle delay time can be used to adapt the model to different cycle times.

I would like to ask the team which time model you have assumed so far?

We have to align the timing concept across the model.

**Comment by UweSteinkeFromSiemens** [comment]
The decision has been made to not use a fixed cycle time. Therefore, timing calculations based on counting cycles will not work at all.
Instead, the current system time (in ms) is available as an input to the model. Delay calculations must be based upon this system time exclusively. This system time will origin from a hardware real time clock, practically.

**Comment by JakobGartner** [comment]
Thanks

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] openETCS time base (#102)" gesendet am 03.02.2015 14:23:00. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[modeling] openETCS time base (#102)" gesendet am 03.02.2015 14:07:25. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] openETCS time base (#102)" gesendet am 03.02.2015 14:16:15. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=
