### ISSUE TITLE
DMI_Control

### ISSUE THREAD

**Issue by valeriodng** [openETCS/modeling#105]
First overview about messages exchanged among DMI_Control, DMI_Manager and Procedure (SoM of Baseliyos) according with "ERSA DMI-EVC Interface Specification".
Here the links of pdf:

https://github.com/valeriodng/modeling/blob/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Procedure%20and%20DMI%20Management/SequenceDiagrams/DMI_Dynamic_SeqDiagram.PDF

https://github.com/valeriodng/modeling/blob/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Procedure%20and%20DMI%20Management/SequenceDiagrams/DMI_Status_SeqDiagram.PDF

https://github.com/valeriodng/modeling/blob/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Procedure%20and%20DMI%20Management/SequenceDiagrams/DMI_ctrl_DMI_mng_Proc.PDF

- DMI_ctrl_DMI_mng_Proc.pdf describes the interaction during the Start of Mission procedure. Currently an "OpenDesk" signal is missing. 
- DMI_Dynamic_SeqDiagram.pdf and DMI_Status_SeqDiagram.pdf describe the periodical trasmission of messages between DMI_Control and DMI_Manager.

I made this sequence diagrams with Papyrus, here the link of the project:
https://github.com/valeriodng/modeling/blob/32ecc76a865431e3f10ac3655c9e54ee8edeadd2/model/Scade/System/DMI_Control/PapyrusProject/SequenceDiagram_PapyrusProject.zip

@BaseliyosJacob @JakobGartner @BerndHekele

**Comment by christianstahl** [comment]
Ich kehre zur�ck am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[modeling] DMI_Control (#105)" gesendet am 05.02.2015 16:48:49. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by BerndHekele** [comment]
Thanks Valerio.
I now started to work with the structrue.
The discription needs some updating in the interface between DMI-management and procedure. We can add this description after having had some clarification inside the team.

**Comment by BerndHekele** [comment]
Since this work now is part of the ADD I believe we can close this issue.
