### ISSUE TITLE
MA_Section_t (request for clarification on Location Types)

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#118]
(as discussed in group meeting WP3 / Group1, Berlin, 12.02.2015), @JakobGartner 

__Location values__
 * are these location values absolute values or relative values?

__EOA_t / LOA_t__
 * is an EOA_t in a non-final section an LOA_t ?
    - there is no specific LOA_t entry defined

__End Section__
 * The end / final section needs a length ("L_ENDSECTION", Paket 15, Paragraph 7.4.2.4)

Please refer to predefined types as found in Packet_Types_Pkg::P15_Level23_MovementAuthority_T

**Comment by BaseliyosJacob** [comment]
Dear all,

i hope i understand the issue.

From my point of view the MA P 15 comes with a V_LOA - permitted speed at the limit of authority and with T_LOA for time whicht the target speed is valid after receiving in the MA.

The EOA - End of authority is from my point of view the end point after the T-LOA is exceeded.

@JakobGartner: what do you think?

**Comment by JakobGartner** [comment]
Location values:

The data are relative to the position of the train at the beginning of the current life of the ETCS OBU (=since startup)

EOA/ LOA

in my current design there is no specific type for the LOA.
However, the "behaviour" of the end section differs from the prior sections --> an EOA in an end section with a target speed >0 is an LOA

Do you need a flag to say "I am an LOA"?

**Comment by BenjaminBeichler** [comment]
No the Flag is not really needed, but the field LOA needs a better Name
(like LOA_EOA or at least a more descriptive comment) in the Scade Model.
Our group discussed about meaning of EOA_t.Location. We concluded that the
end location of the end_section is missing, which defines the EOA. After a
second review of your structure and the SRS, I think your EOA_t.Location is
always at the end of a MA Section, so the stucture could fit.

But the structure is a bit confusing ... why do we need
MA_Section_t.EOA_t.Timer if we have also the MA_Section_t.SectionTimer or
what is the difference.




-- 
M.Sc. Benjamin Beichler

Universität Rostock, Fakultät für Informatik und Elektrotechnik
Institut für Angewandte Mikroelektronik und Datentechnik

University of Rostock, Department of CS and EE
Institute of Applied Microelectronics and CE

Richard-Wagner-Straße 31
18119 Rostock
Deutschland/Germany

phone: +49 (0) 381 498 - 7278
email: Benjamin.Beichler@uni-rostock.de
www: http://www.imd.uni-rostock.de/

**Comment by T12z** [comment]
This is outdated. Closed by issue starter.
