### ISSUE TITLE
TIMESTAMP needed in Radio Input

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#119]
we need the information when a message has been received in the message fo radio as well.
Is this a parameter for the header?

@UweSteinkeFromSiemens  @stefan-karg

**Comment by stefan-karg** [comment]
We can add this information to the header. Does it make sense to define it in the common header for BG and radio messages? Is the timestamp also needed for BG-messages?

**Comment by UweSteinkeFromSiemens** [comment]
To add timestamps is a good idea anyway. No contradiction.

**Comment by JakobGartner** [comment]
I agree to add the timestamps in the common header

**Comment by BerndHekele** [comment]
Timestamp is added.
