### ISSUE TITLE
Packets_Type_Pkg:: DMI_EVC_status_T

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#131]
Dear Bernd,
@BerndHekele

need for the procedures the following bool inputs from DMI Management:

[ ] DMI Drive ID first validation - data already available
[ ] DMI Train Number validation - data already avallable
[ ] DMI Train Data validation - missing
[ ] DMI Driver ID second  validation  - missing
[ ] DMI Driver Start - could not find 
[ ] DMI Driver acknowledge MA in FS - could not find

Do you need more explanation?

**Comment by BerndHekele** [comment]
I Baseliyos,
you will find the type definition in this location:
https://github.com/openETCS/modeling/blob/master/model/Scade/System/APITypes/DMI_Types_Pkg.xscade.

I added the flagsd which are related to the SoM progress.
I do not understand why the MA in FS can be handled in the same way. I would like to understand the workflow first.

cu
Bernd

**Comment by BerndHekele** [comment]
I close this issue. Flow  is implemented

**Comment by BaseliyosJacob** [comment]
Still missing a valid MA in FS

**Comment by BerndHekele** [comment]
Mocement Authority is not a state of the DMI management.
It might transport information - but not provide status.
The information  typically is either database (Jakob) or Modes and Level.

If you can give no argument I will close this issue today.

**Comment by MariellePetitDoche** [comment]
To enter in FS in Level 2 a valid MA+gradient+ SSP  shall be available on board, but these information are provided by RBC (in level 2) not by DMI.
If necessary, Mode mangaement function launch a request of MA to RBC (message 132), but driver acknoledgement are not requested.
