### ISSUE TITLE
manage_DMI_Output_Pkg..xscade: Missing Train Position Data

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#133]
@UweSteinkeFromSiemens , @JakobGartner , @valeriodng 

For regular display at the DMI I need the following additional fields:
![image](https://cloud.githubusercontent.com/assets/3288918/6318819/f85345c4-baa4-11e4-8e68-aaf1e73725fc.png)

Can trainPositioning provide this data?

kr.
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
Distance to the reference balise: 
If the reference balise is the same as the LRBG, the distance can be calculated simply by subtracting the LRBG location from the current train position. 

Kilometer point + distance to the tunnel area: are yet no topics for the calcuteTrainPosition function

**Comment by JakobGartner** [comment]
We are ignoring TSA up to now.
The other data: agreed with Uwe

**Comment by BerndHekele** [comment]
Corresponding changes done in the model.
Issue closed.
