### ISSUE TITLE
manage_DMI_Output_Pkg..xscade: Missing SpeedSupervision

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#134]
@christianstahl , @valeriodng , @JakobGartner 

For regular dmi update I need the following information:
![image](https://cloud.githubusercontent.com/assets/3288918/6318839/871e4bfa-baa5-11e4-82d2-1a7454dea6a9.png)

Can speedsupervision provide this information?

kr
Bernd

**Comment by JakobGartner** [comment]
Some of these data are directly available from MRSP data in ManageTrackData.
However, there are some derived data as well that Train Supervision will at least have to calculate in order to avoid overlap.

**Comment by christianstahl** [comment]
Except from the two locations, my component can provide you the information. The location are input to speed and distance monitoring or calculated by Benjamin. Regarding M_WARNING, I interpret element over_speed_warning_indication that  the supervision status is equal to overspeed status, warning status or indication status, right? This implies that no_warning=true iff the status is normal status.

**Comment by christianstahl** [comment]
@BerndHekele @vgontier 
The way you have defined the type requires the DMI to determine which speed is valid. As an example, if in CSM (ceiling speed monitoring) and supervision status is normal, speed and distance monitoring will only provide the estimated speed and the permitted speed. As a consequence, DMI has to determine that all other speeds contained in the data type are not valid.

**Comment by BerndHekele** [comment]
Dear Christian,

ERSA uses a predefined init-value for indicating the valid state of the speed. Is this option ok for you?

**Comment by christianstahl** [comment]
Dear Bernd,
do you mean one init values for all speeds or an initi value for each individual speed?

**Comment by BerndHekele** [comment]
Hi Christian,
the following idea can be used:
cUnknownSpeed = -1 .
The actual ERSA implementation makes use of 1023 km/h.

We can specify this constant and you may use it to indicate the state?

cu
Bernd

**Comment by christianstahl** [comment]
OK

**Comment by BerndHekele** [comment]
I close this issue - solution available.
If you do not agree, please reopen.
