### ISSUE TITLE
manage_DMI_Output_Pkg..xscade: Missing Database

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#135]
@JakobGartner ,
Dear Jakob,
for periodic dmi output I need the following information:
![image](https://cloud.githubusercontent.com/assets/3288918/6318850/23ed7f96-baa6-11e4-99bb-74da75f128d7.png)

Where can I find it?

cu
Bernd

**Comment by JakobGartner** [comment]
The contents of packet 15 (MA) are managed by ManageTrackData function.
The contents of packet 3 (NV) are managed by ManageData function.

I will provide a list in order to maintain such open points in order to close them during the integration effort.

**Comment by BerndHekele** [comment]
Dear Jakob,
I want to continue with this interface now.
Do I get the information from the track atlas?

kr
Bernd

**Comment by JakobGartner** [comment]
I have (related) issue #447 on the backlog, and am also working on packet 3 decoding today (#443).

I will add these interfaces to this work complex, as the data are available (will be…) in the Track Atlas.

**Comment by BerndHekele** [comment]
No longer relevant
