### ISSUE TITLE
Data content for initialization data

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#136]
Need a data interface for NID_MN in  Procedured for triggering of Management of Radio Communication.

**Comment by JakobGartner** [comment]
I have not yet seen this information (not on the track and not in the model)

I will put it on the list of open points.

**Comment by BaseliyosJacob** [comment]
Hello Jakob,

the information are in packag 45 - NID_MN
and in packet 42 - NID_RBC, NID_RADIO and Q_SLEEPSESSION.

**Comment by UweSteinkeFromSiemens** [comment]
Both packets have been defined already, including NID_MN.

**Comment by BerndHekele** [comment]
I close this issue - solution available.
