### ISSUE TITLE
New version of sequence diagram

### ISSUE THREAD

**Issue by valeriodng** [openETCS/modeling#137]
I have updated the sequence diagram as discussed in the meeting (23/02/2015 in Munich DB).

Here the link of pdf:
https://github.com/valeriodng/modeling/blob/3f9d2e2442602a3919471e49bbfd0e7403c6195c/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Procedure%20and%20DMI%20Management/SequenceDiagrams/DMIctr_DMI_mng_SoMProc.PDF

here the link of papyrus project:
https://github.com/valeriodng/modeling/blob/3f9d2e2442602a3919471e49bbfd0e7403c6195c/model/Scade/System/DMI_Control/PapyrusProject/SequenceDiagram_DMI_EVC.zip

@BerndHekele @BaseliyosJacob

**Comment by BerndHekele** [comment]
Thanks.
I close the issue - nothing left to do.
