### ISSUE TITLE
Need variables as "valid" for start of mission

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#138]
Need the following variables as "valid" for start of mission as initialisatoin

see § 6.4.3.3

ERTMS/ETCS Level
RBC ID Phone Number
Train position Data
Driver ID
Train Data
Train Running Number

**Comment by JakobGartner** [comment]
see #139

**Comment by BerndHekele** [comment]
I believe the information is availble and close the issue.
Please reopen if I have overseen something,

**Comment by BaseliyosJacob** [comment]
Not solved. Still need the data from a valid source

**Comment by BaseliyosJacob** [comment]
Need it as a persistent database

**Comment by BerndHekele** [comment]
Related to old release
