### ISSUE TITLE
Need MA in Level 2 Mode FS for Start of Misson

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#139]
Dear all,

need MA in Level 2 Mode FS for start of mission procedure.
Will model the procedure to handle the request of MA, but need the MA data.

**Comment by vgontier** [comment]
@BaseliyosJacob 
The MA used for the start of mission is the MA memorized during the End of Mission.
If there is no End of Mission scenario, you have to define the MA yourself.

**Comment by JakobGartner** [comment]
I can provide a startup MA from the ManageData operator.
This would provide a Default value (set by a variable in the simulation environment).
After the review we can extend it to store the last valid MA during End Of Mission.
(On a real HW this would store the data in onboard permanent memory)

**Comment by MariellePetitDoche** [comment]
During start of Mission procedure the "MA" used (E29 in fig1 of SRS §5.4.4)  is not simply the MA received from RBC (via paquet 12 and 15), but the "MA" checked and completed with SSP and gradient as described in condition 10 §4.6.3.

**Comment by BerndHekele** [comment]
Solved in the emantime.
