### ISSUE TITLE
Need V_ura from Odometry

### ISSUE THREAD

**Issue by BenjaminBeichler** [openETCS/modeling#143]
As already mentioned at several places, the formulas for calculation of target limits needs the inaccuracy of the current estimated speed V_est. 

@BerndHekele 
as we agreed on, an inaccuracy needs to be added to the Odometry output for the Speed and Distance Monitoring. I believe that the odometry_T::speed is the value, which is referenced as V_est in the SRS, so maybe we could rename it in some future.

**Comment by BerndHekele** [comment]
@UweSteinkeFromSiemens 
Can we do this change in the odometry data before the freeze?
A solution would be replace the type  the upper and lower interval to the structure including upper and lower limit.
Uwe, can you recommend what to do?

**Comment by UweSteinkeFromSiemens** [comment]
Speed uncertainties could be added to odometry_T by creating a speed type comparable to OdometryLocations_T. 
The impact of such a change to CalculateTrainPosition before the freeze seems controllable.

**Comment by BerndHekele** [comment]
The new type could look like this:
![image](https://cloud.githubusercontent.com/assets/3288918/6389369/c3759f6c-bda3-11e4-861a-bf938fc7bfe0.png)

@BenjaminBeichler @UweSteinkeFromSiemens @stefan-karg  : ok?

**Comment by UweSteinkeFromSiemens** [comment]
From the modeling point of view: ok.

**Comment by stefan-karg** [comment]
From my point of view also ok!

**Comment by UweSteinkeFromSiemens** [comment]
Hallo Bernd,
sobald Du den Typ geändert hast, gib‘ mir bitte Nachricht, damit ich meine Anpassungen vornehmen kann.

Gruß
Uwe

Siemens AG
Mobility
MO MM R&D PTS RAMSS 3
Ackerstr. 22
38126 Braunschweig, Germany
Tel.: +49 531 226-3263
Mobile: +49 173 6243136
mailto:uwe.steinke@siemens.com

Siemens Aktiengesellschaft: Chairman of the Supervisory Board: Gerhard Cromme; Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer; Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Siegfried Russwurm, Ralf P. Thomas; Registered offices: Berlin and Munich, Germany; Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684; WEEE-Reg.-No. DE 23691322
Von: Bernd Hekele [mailto:notifications@github.com]
Gesendet: Donnerstag, 26. Februar 2015 10:40
An: openETCS/modeling
Cc: Steinke, Uwe
Betreff: Re: [modeling] Need V_ura from Odometry (#143)


The new type could look like this:
[image]<https://cloud.githubusercontent.com/assets/3288918/6389369/c3759f6c-bda3-11e4-861a-bf938fc7bfe0.png>

@BenjaminBeichler<https://github.com/BenjaminBeichler> @UweSteinkeFromSiemens<https://github.com/UweSteinkeFromSiemens> @stefan-karg<https://github.com/stefan-karg> : ok?

**Comment by BenjaminBeichler** [comment]
seems to be good ;-)

I would like to see, at least in the comment, that this value is linked to V_ura of the SRS

**Comment by BerndHekele** [comment]
V_ura: the concept is not clear to me. Do you have a proper definition of the value. The SRS seems to be unclear and the translation  of this term does not help either.

I add this comment when I understand the meaning.

**Comment by BenjaminBeichler** [comment]
In my understanding V_ura is the variable v_upper - v_raw_norminal 

but maybe @vgontier know more

**Comment by vgontier** [comment]
@BerndHekele 
@BenjaminBeichler 
For me, v_ura = v_delta0 = compensation of the speed measurement inaccuracy.
= +/- 2km/h if V_est < 30 km/h and lineary up to +/-12km/h at 500 km/h
see subset 26 § 3.13.9.3.2 and subset 41 § 5.3.1.2
See

**Comment by BerndHekele** [comment]
I will document the extended odometry parameter in the ADD and in the code.
I do not plan to document v_ura sincce I'm neither source nor sink for this property

@BenjaminBeichler  can we close this issue?
(Cleanup).

**Comment by BenjaminBeichler** [comment]
I think the common sense is not found ... In my understanding subset 41 defines the borders of several values, so for example V_ura needs to be in the range @vgontier has explained. But the values are measured like the position uncertainty of uwes model.

But I think we could close at this point, the responsible for odometry have  to clarify this
