### ISSUE TITLE
DMI_Types_Pkg:M_WARNING

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#145]
@BerndHekele @vgontier 
Dear Bernd,

the SRS distinguishes five supervision stati (e.g., Table 12 on p.143): normal status, indication status, overspeed status, warning status, intervention status. In addition, an undefined status seems to be necessary.
Comparing the six types from the SRS with the three elements of enumeration M_WARNING, the mapping is not clear to me.
Thank you!

**Comment by BerndHekele** [comment]
@valeriodng 
I will extend the type with the missing information. The DMI controller will select the once which are feasable in the context.
I will close the issue when the DMI-Types have changed.

**Comment by BerndHekele** [comment]
Here is how the solution will look like for supervision:
![image](https://cloud.githubusercontent.com/assets/3288918/6387890/f8e08254-bd92-11e4-801a-da132462d606.png)

The type is also replaced in the interface structure. In addition, your interface is moved to the DMI_Types_Pkg.

**Comment by BerndHekele** [comment]
Correction is available.
I close this issue.
