### ISSUE TITLE
Interface SpeedAndDistanceMonitoring to TIU

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#148]
@BerndHekele @vgontier 
I have checked the types defined in the TIU_Types_Pkg and added an output of type Brake_command_T
to our model. Is there anything more you need?

**Comment by BerndHekele** [comment]
Hi Christian,
looks fine to me.
I recognised a another function using the brakes - Modes - .
Do you also manage inputs from other users or do we need a new block for managing the priuorities?

@JakobGartner  @BaseliyosJacob

**Comment by christianstahl** [comment]
Thanks Bernd! 
During the Group1 workshop in Berlin, we identified the need for an interface to Modes. @vgontier wanted to investigate this in more detail.

**Comment by BerndHekele** [comment]
Linked to #158

**Comment by BerndHekele** [comment]
I cxlose this issue as a duplicate
