### ISSUE TITLE
Interface Management of Sending Radio Information in Start of Mission for RBC Utrecht - Amsterdam

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#157]
Packet 57 (Movement Authority Request Parameter) should be considered, but not in the scope for the iteration in March.

We consider that MA will come with Level 2 and Mode FS.

Need for Interface of Sending Radio Information
[1] interface to Radio for acknowledgement of Position report
1. (Start of Mission position report) Message from Train to RBC: Message 157 + Packet 0
2. (Start of Mission position report confirmed by RBC) Message from RBC to Train: Message 43
2. (Acknowledgement of SoM position report) Message from RBC to Train: Message 146

[2] interface to Radio for acknowledgement of Validation Data (Train Data)
Sequence:
1. (Validation of Data) Message from Train to RBC: Message 129 + Packet 0 + Packet 11
2. (Acknowledgement of Train Data from RBC) Message from RBC to Train: Message 8
3. (Acknowledgement of Acknowledement from Train) Message from Train to RBC: Message 146
4. Not in the scope at the current RBC Utrecht - Amsterdam (Message 41 Train accepted or Message 40 Train rejeceted from RBC to Train)

[3] interface to Radio for sending MA in Start of Mission and Acknowledgement of MA Level 2 for Full Supervision
Sequence:
1. (MA Request) Message from Train to RBC: Message 132 + Packet 0
2. (MA) Message from RBC to Train: Message 3 + Packet 3 + Packet 15 + Packet 21 + Packet 27 + Packet 5
3. (MA Acknowledement) Message from Train to RBC: Message 146

**Comment by JakobGartner** [comment]
Let's discuss this in detail during our meeting tomorrow

On 28.02.2015, at 01:04, Baseliyos Jacob <notifications@github.com> wrote:

Packet 57 (Movement Authority Request Parameter) should be considered, but
not in the scope for the iteration in March.

We consider that MA will come with Level 2 and Mode FS.

Need for Interface of Sending Radio Information
[1] interface to Radio for acknowledgement of Position report
1. (Start of Mission position report) Message from Train to RBC: Message
157 + Packet 0
2. (Start of Mission position report confirmed by RBC) Message from RBC to
Train: Message 43
2. (Acknowledgement of SoM position report) Message from RBC to Train:
Message 146

[2] interface to Radio for acknowledgement of Validation Data (Train Data)
Sequence:
1. (Validation of Data) Message from Train to RBC: Message 129 + Packet 0 +
Packet 11
2. (Acknowledgement of Train Data from RBC) Message from RBC to Train:
Message 8
3. (Acknowledgement of Acknowledement from Train) Message from Train to
RBC: Message 146
4. Not in the scope at the current RBC Utrecht - Amsterdam (Message 41
Train accepted or Message 40 Train rejeceted from RBC to Train)

[3] interface to Radio for sending MA in Start of Mission and
Acknowledgement of MA Level 2 for Full Supervision
Sequence:
1. (MA Request) Message from Train to RBC: Message 132 + Packet 0
2. (MA) Message from RBC to Train: Message 3 + Packet 15 + Packet 21 +
Packet 27 + Packet 5
3. (MA Acknowledement) Message from Train to RBC: Message 146

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/157>.

**Comment by BerndHekele** [comment]
Related to old release
