### ISSUE TITLE
Level_And_Mode_Types_Pkg::T_Data_From_Speed_Supervision needs data from Speed Supervision

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#158]
@JakobGartner , @vgontier , @MariellePetitDoche , @christianstahl , @BenjaminBeichler 
Dear All,
ModeManagement   expects the following information from your function:
![image](https://cloud.githubusercontent.com/assets/3288918/6430342/19e7ca00-c006-11e4-813d-8893f9eb0963.png)

Can you give me a rule how to calculate this from your output or is the information already provided?

kr
Bernd

**Comment by BerndHekele** [comment]
In addition I need a flag "target speed reached"

**Comment by vgontier** [comment]
@BerndHekele , @christianstahl , @MariellePetitDoche , @BenjaminBeichler, @JakobGartner 
After discussion with Marielle, I suggest to provide:
For the first step:
- EOA_overpassed = EOA _Antenna_Overpass (Level 1) OR EAO_Front_End (Level 2/3)
- Target_Speed_Reached
After:
- Estimated_front_End_overpass_SR_Dist
- Train_Speed_Under_Override_Limit
- Override_Function_Active
- Estimat_Front_End_Rear_SSP
(override function and SR mode are out of the perimeter for March)

**Comment by vgontier** [comment]
Script issue :-)
For the first step:

    EOA_overpassed = EOA _Antenna_Overpass (Level 1) OR EAO_Front_End (Level 2/3)
    Target_Speed_Reached 

After:
    Estimated_front_End_overpass_SR_Dist
    Train_Speed_Under_Override_Limit
    Override_Function_Active
    Estimat_Front_End_Rear_SSP (override function and SR mode are out of the perimeter for March)

**Comment by christianstahl** [comment]
@vgontier 
Is EOA_overpassed a single Boolean or a struct?

**Comment by vgontier** [comment]
@christianstahl 
a Boolean

**Comment by BerndHekele** [comment]
I close this issue.
Solution available.
