### ISSUE TITLE
Level_And_Mode_Types_Pkg::T_TrackData needed 

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#159]
@JakobGartner , @MariellePetitDoche 
The track data defined by mode and level need some clarifications.
Which of these data can be provided via our database?

![image](https://cloud.githubusercontent.com/assets/3288918/6430767/66d01306-c018-11e4-8a61-5dca445e171a.png)

kr
Bernd

**Comment by MariellePetitDoche** [comment]
For more details :

– MA_SSP_Gradiant_Available : bool MA, SSP and gradient have been received, checked
and stored on-board from paquet 12, 15, 21 and 27 or message 3 or 33
– Mode_Profile_On_Board : Level_And_Mode_Types_Pkg::T_Mode_Profile from packet
80
– Shunting_granted_By_RBC : bool from message 27 and 28
– Trip_Order_Given_By_Balise : bool
– List_Bg_Related_To_SR_Empty : bool from packet 63
– Stop_If_In_shunting : bool from packet 135
– Stop_If_In_SR : bool from packet 137
– Error_BG_System_Version : bool
– Linking_Reaction_To_Trip : bool
– RBC_Ack_TR_EB_Revocked : bool from message 6
– RBC_Authorized_SR : bool from message 2
– Reversing_Data : Level_And_Mode_Types_Pkg::T_Reversing_Data from packet 138/
139
– T_NVCONTACT_Overpass : bool Maximal time without new safe message overpass
– Emergency_Stop_Message_Received: boolean to describe the reception of Emergency
Stop message from message 15 or 16

**Comment by MariellePetitDoche** [comment]
Level Management needs also:

• conditional transitions: a priority table containing the conditional level transition orders
(from paquet 46)
• level transition priority table: a priority table containing the (non-conditional) level transition
orders (from paquet 41)
• ERTMS capabilities: the ERTMS capabilities of the track
• ackDistance: the maximal distance for driver acknowledge after the level transition (from
paquet 41)
• received L2 L3 MA: a Boolean that indicates that a level 2 or level 3 movement authority for
the track behind the level transition has been received (from paquet 15)
• received L1 MA: a Boolean that indicates that a level 1 movement authority for the track
behind the level transition has been received (from paquet 12)
• received target speed: a Boolean indicating that a target speed for the track behind the level
transition has been received (from paquet 27)

**Comment by BerndHekele** [comment]
No longer relevant
