### ISSUE TITLE
Level_And_Modes_Pkg needs Level Transitions from DB

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#160]
Hi Jakob,
we need an interface from location data to Level Management.
The currently proposed interface looks like this (:
![image](https://cloud.githubusercontent.com/assets/3288918/6438172/102dd5ce-c0c7-11e4-9f65-a9f071ae66d2.png)

Can you provide this interface?
@mgudemann , @JakobGartner

**Comment by JakobGartner** [comment]
The support of the transport with the related packets (41, 46) is completed. 
A small conversion function to extract the data and convert them to the type T_LevelTransition_PriorityTable is still required.

Workload for our team: 1 hour 
This function can equally be done by “anyone” as the read and conversion functions for P41 and P46 existing.

Wherever these packets are on the Amsterdam Utrecht line, these packets are already supported in the track simulation and the related libraries (InfraLib and TrackMessages)

**Comment by JakobGartner** [comment]
this is linked to #159.

The interface is defined, support for P41 and P46 and the related tables will be provided until Jul 2

**Comment by BerndHekele** [comment]
Is this issue still open?
We have a newly defined interface between trackatlas and Modes and Levels implemented.
Can we close?
@JakobGartner , @MariellePetitDoche
