### ISSUE TITLE
ThirdIteration::openETCSArchitectureAndDesignSpecification: pdf cannot be generated

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#163]
The generation of the pdf aborts with the error message: ! LaTeX Error: File `glossaries.sty' not found.

**Comment by stefan-karg** [comment]
You need to install the glossaries package in your LaTex-distribution. The file glossaries.sty is part of the glossaries package.

**Comment by UweSteinkeFromSiemens** [comment]
Texmaker tries to install glossaries.sty, but fails.

**Comment by stefan-karg** [comment]
Are you using MikTeX under Windows as the LaTeX-distribution? If so, try to run the command pdflatex.exe openETCSArchitectureAndDesignSpecification.tex directly via commandline (cmd.exe). The graphical editors sometimes have problems installing the packages.

**Comment by UweSteinkeFromSiemens** [comment]
Yes. Running pdflatex.exe openETCSArchitectureAndDesignSpecification.tex ended up with
"The MiKTeX web service has rejected your request. Possible reason: too many requests arriving from your IP address."

**Comment by BerndHekele** [comment]
There seems to be a general problem with the MikTex Download Server. I get the same error report.
I propose we try again later.

**Comment by UweSteinkeFromSiemens** [comment]
Ok, thanks.

**Comment by BerndHekele** [comment]
For me, the server works now again..
Can you please re-check?

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
Yes, now the download seemed to work properly. 
Unfortunately, a couple of more error messages is produced like: 
* LaTeX Error: Environment landscape undefined.
* Package pdftex.def Error: File `../SysML/FunctionalArchitecture.png' not foun
* ! LaTeX Error: \begin{document} ended by \end{landscape}

**Comment by UweSteinkeFromSiemens** [comment]
Cross check: the pdf generation with the second iteration worked properly without any errors. Therefore, the bug seems to be in the document setup for the third iteration.

**Comment by christianstahl** [comment]
@BaseliyosJacob  @mahlmann 
As \glossentry is not a macro defined in glossary.sty, I think the creator of this document forgot to add the definition of \glossentry.

**Comment by mahlmann** [comment]
I commented out the landscape commands (maybe an additional package has to be loaded in the document preamble?) as well as an includegraphics command for a missing image.

@MariellePetitDoche 
These issues are located in the modes and levels sections, maybe you  can fix this and commit the missing image?

@UweSteinkeFromSiemens 
There seems to be another issue with the glossary. However, for the moment it should be fine to bypass these errors by just pressing return repeatedly in the compile process.

Last but not least I highly recommend to remove the outdated document structure from the document.

**Comment by UweSteinkeFromSiemens** [comment]
In the current state, a lot of warnings occur. The pdf is generated now.

**Comment by christianstahl** [comment]
Macro \glossentry is still not defined and throws about 50 errors.

**Comment by BaseliyosJacob** [comment]
I have updated the LateX and it works without the Level and Mode packet.
@MariellePetitDoche :  Can you fix it?

**Comment by mahlmann** [comment]
@BaseliyosJacob 
I removed the outdated part from the main tex file. The file actually had more than 1600 lines of text -- we should keep the files smaller, this especially holds for the main tex file. This also helps to keep the pdf readable.

Concerning the glossary issue:
The document compiles for me without errors. However, I wonder if we really need a glossary here at all? Maybe we should concentrate on the other content, at least for the moment.

**Comment by BerndHekele** [comment]
The glossary has a high priority. Especially, if we see the  version of this document for the final review.
I do not see a reason to skip it - it worked before reasonable.

**Comment by mahlmann** [comment]
@BerndHekele 
Thanks for your comment. I don't have a problem to keep the glossary in the document at all. However, if we keep it, the reason for this should be that it is needed or considered to be helpful by WP3 or WP4. For the review(ers) it will be of very small value.

**Comment by UweSteinkeFromSiemens** [comment]
With the commits b64a31848009b955cce4bd3d06e47703814ebc02 and b01ac96f038210ba1942b7d875f31efd02a4e146 openETCSArchitectureAndDesign.tex has been modified yesterday. trainPosition.tex is not included any more, and there is no identifiable place yet in the document structure for it.  What's the intention?

**Comment by mahlmann** [comment]
@UweSteinkeFromSiemens 
I just removed everything below the line `\chapter{end of new structure}`, since everything below is supposed to be outdated.

Maybe @BerndHekele or @BaseliyosJacob can help to identify a reasonable place for `trainPosition.tex` in the new structure?

**Comment by BaseliyosJacob** [comment]
Hello Uwe,

i understand that train position and coordinate system should be a macrofunction of 6.2.4. Manage Track Data

**Comment by MariellePetitDoche** [comment]
@mahlmann, @BaseliyosJacob 

I have added the mixing file concerning the picture "FunctionnalArchitecture".
I have added the line "\usepackage{pdflscape}" to allow picture in landscape format.
I have renamed inputed file (introduction -> Introduction, inputsdocument -> Inputsdocument) to  allow pdf generation.
