### ISSUE TITLE
Bug in Mainmenu (Start button)

### ISSUE THREAD

**Issue by valeriodng** [openETCS/modeling#184]
After the validation of DriverID and Train Running Number the Start button is already active. It should be active only after the train data validation and the second validation of train running number.

In the DMI the activation of main menu buttons are managed by DMI_Menu_Request_T in particular by the "available menu" variable (a structured variable). I checked the correct correspondence between buttons and the "available menu" variable and it is right.
Maybe the problem is in DMI manager. @BerndHekele

**Comment by BerndHekele** [comment]
@BaseliyosJacob 
The root cause is in the procedures. 
cu
Bernd

**Comment by BerndHekele** [comment]
Problem solved
