### ISSUE TITLE
Receive Track Data: Naming inconsistency between ADD and SCADE model

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#198]
The functionality which is described in the ADD document in the section "Receive Track Data" is covered by the SCADE model "Manage_TrackSideInformation_Integration". 

We should align the naming inconsistencies. Which name should be changed?

@BerndHekele @BaseliyosJacob

**Comment by BerndHekele** [comment]
The model file is the one to select.

**Comment by BaseliyosJacob** [comment]
Has been changed in the ADD document
