### ISSUE TITLE
Modes::Model does not compile - syntax errors because of missing xscade file

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#199]
Dear Marrielle,
most likely the last commmit was not complete - you model now generates errors.
@MariellePetitDoche

**Comment by MariellePetitDoche** [comment]
Could give the error message ?
I have no such kind of error and I do not know which file is missing.

**Comment by BenjaminBeichler** [comment]
I think the file model/Scade/System/ObuFunctions/ManageLevelsAndModes/Modes/Operator5.xscade is missing. Maybe you only miss to add it to the last commit.

**Comment by BerndHekele** [comment]
I see the following information:  
Loading project Modes.etp...
D:/DB-Data/Github/modeling/model/Scade/System/ObuFunctions/ManageLevelsAndModes/Modes/Operator5.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened. Id=D:\DB-Data\Github\modeling\model\Scade\System\ObuFunctions\ManageLevelsAndModes\Modes\Operator5.xscade

2 semantic error (s)
Warning: The file Operator5.xscade is not referenced in the model.
Successfully loaded project Modes.etp

**Comment by JakobGartner** [comment]
2 Remarks:

1. A file name “Operator5” is not best practise. Please make sure that the operator names are traceable to the file names (the most easy way is to set the related options in the tool settings to ensure that upon creation or renaming the operator is propagated AND you can confirm the file name.

2. If you look at the file view tab you can see whether the file is loaded, recognised as xscade file etc. You can also load it manually there.

Jakob

**Comment by MariellePetitDoche** [comment]
1. I agrre the name is not good, and during my last changed I have  just correct two existing operators, whithout creating a new one.

2. There is a really strange behaviour, as, This operator does not appear in the file view tab, *.xscade is not present, but the line "				<FileRef id="269" persistAs="Operator5.xscade"/> " is present in the *.etp file, and I check the model without problem or warning.

I will correct it.

**Comment by JakobGartner** [comment]
If you use the following settings then you don't need to worry about this
problem anymore

 [image: image1.JPG]

On 13.03.2015, at 10:09, MariellePetitDoche <notifications@github.com>
wrote:


   1.

   I agrre the name is not good, and during my last changed I have just
   correct two existing operators, whithout creating a new one.
   2.

   There is a really strange behaviour, as, This operator does not appear
   in the file view tab, *.xscade is not present, but the line " " is present
   in the *.etp file, and I check the model without problem or warning.

I will correct it.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/199#issuecomment-78879504>.

**Comment by MariellePetitDoche** [comment]
Jakob,

Image is missing.

**Comment by MariellePetitDoche** [comment]
![image1](https://cloud.githubusercontent.com/assets/2233518/6635928/60f8437a-c96b-11e4-9cf5-bd3bb7290eef.jpeg)

**Comment by BerndHekele** [comment]
Dear Marielle,
I want to conclude on this.
Currently, you are using a file for each operator. A file per package would be more handy.
If you agree I can give you some help.

**Comment by MariellePetitDoche** [comment]
Dear Bernd,

As cooperation between Scade and github is not good, and as we want to exploid the Scade model with other tools, I am definitelly  in favour of separate files.

What I do not understand is why  you and Benjamin detect an error in your configuration (during check or simulation I assume)  and I do not as the file is not present. Unfortunately I do not know how to avoid this problem will occur again.

Maybe a common configuration of Scade shall be defined.

**Comment by BenjaminBeichler** [comment]
I also think, overall configuration would be good. I'm confused that this is not set by the template.

But as Marielle I propose a one file per operator policy, since this helps to avoid some problems with git. I handled successfully some conflicts in SCADE Files and it helped to have these things.

**Comment by BerndHekele** [comment]
Dear Marielle,
the error is visible in the files:
![image](https://cloud.githubusercontent.com/assets/3288918/6636849/4580d720-c974-11e4-9855-ecbadecb713c.png)
You just need to delete the shaped file.

**Comment by BerndHekele** [comment]
@BenjaminBeichler : The option was part of the template but disappeared.
We need to clean it.
