### ISSUE TITLE
Testbench_Suite: Findings in the look and feel 

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#201]
As a starting point for the preparation of the Itea Review I want to collect issues which need to be corrected for the presentation at the review.

 - Start Procedure: the reading of location information needs to be integrated in the flow. In detail:  
  - reading a radio message with linking information as soon as radio is available (Bernd)  
  - Moving the TIU button to another panel
  - SpeedSupervision output and TrainPosition output to be verified at the DMI
  - Speed-Limit increased
  - Correct Mode and Level and Icon Display   after Emergency Brake (also DMI)
  - Correct Interval in the4 display for inaccuracies.

Please feel free to comment on the issue. Add your findings.

**Comment by stefan-karg** [comment]
Start Procedure: the reading of location information needs to be integrated in the flow. In detail:

- [ ] reading a radio message with linking information as soon as radio is available (Bernd)
- [x]    Moving the TIU button to another panel
- [ ]    SpeedSupervision output and TrainPosition output to be verified at the DMI
- [ ]    Speed-Limit increased
- [ ]    Correct Mode and Level and Icon Display after Emergency Brake (also DMI)
- [x]    Correct Interval in the4 display for inaccuracies.

**Comment by BerndHekele** [comment]
Done
