### ISSUE TITLE
Updating of Description of Work for WP 3

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#202]
Dear all,

we should go on to update the Description of Work in WP 3.

The last update is 1 year ago.

I understand the coauthors are Marielle Petit Doche, Bernd Hekele and Uwe Steinke.

Can not find a leading author on the list. Just mentioned the team.
Who is the leading author of the document?

Thank you very much

**Comment by BerndHekele** [comment]
I do not want to spoil resources on useless discussions. Therefore, I take this responsibility even though I had not been the main contributer to this document.

I close this issue since there was no other issue linked with it.

kr
Bernd

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

thank you very much for your feedback.

I dont see this issue as a useless discussion since we need an author leader for the DoW that should be the WP 3 leaer in general.

Furthermroe i understand that you will be the author leader for this document. The document doeent have a high priority due to the ITEA review but it should be updated and lead for the next iteration. 

I see some further issues link with the document and therefore we should keep focus on this issue.

Thank you very much

Baseliyos Jacob
