### ISSUE TITLE
Feedback from ERA

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#204]
Dear all,

here the first feedback from the ERA to our model

Prio:

1. Complete a RBC Model for the Utrecht - Amsterdam line
2. Proof of dynamic tests

@Alexander Probst: can you give a feedback on the RBC model?

**Comment by JakobGartner** [comment]
1. A simple RBC model is included in the track model I have provided. This is a rule-based RBC message generator that we can extend to full RBC in future project. 
I think this is a target for the end of project.

2. Please clarify "proof". In formal methods, this has a well defined meaning. Or do you mean we have to demonstrate dynamic tests? Do you have more precise requirements?

**Comment by BerndHekele** [comment]
Related to old release
