### ISSUE TITLE
ETCS DMI Bug

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#209]
Dear all,

allow me to list you the bugs on the current DMI version in priority:

1. Wrong Speed Supervision before start. Speed Supervision on DMI is already present before receiving of MA. But the parameter will be supported with  the MA and information from Train Supervision (Working Group 1)

2. Pointer of the Speedometer is already from the beginning in yellow. Should start with grey, white, then yellow and then red according to the speed parameter on the Speedometer. See § 3.13.10.5.5. Table 15. 

3. Emergency Brake intervention function to handle the information from the Train Supervision is not implemented yet. Emergency Brake intervention will finish in Trip mode. See § 3.13.10.5.5. Table 15. "intervention status".

4. Lokation brake target is not implemented.

5. Planning are according to gradients of MA is not implemented at the moment.

**Comment by JakobGartner** [comment]
#1 will be fixed after discussion between WG1 and me this afternoon.

I believe to have it by Wednesday at latest.

**Comment by BenjaminBeichler** [comment]
I think that issues are solved, isn't it ?
