### ISSUE TITLE
TIU interface description 

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#214]
Dear all,

i recommend to use for the TIU interface description the Subset 119.
Since i think that it is more complete than the subset 34.

**Comment by BerndHekele** [comment]
Can you please ad the link - I cannot see it at the ERA homepage.

**Comment by mahlmann** [comment]
I think this actually is not an issue but an recommendation. Reference to Subset 119 has been added to SysML model (https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC).
