### ISSUE TITLE
Track model: Distance between balise groups

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#222]
Not meeting the linking data.

@BerndHekele

**Comment by BerndHekele** [comment]
Looks now like this:
![image](https://cloud.githubusercontent.com/assets/3288918/6728492/63b0a2f6-ce2a-11e4-8bfd-5911e9e0c2a7.png)

So - technically it is ok but from a track-design point of view the layout shout be better fitting to the SDM scenario.

**Comment by BerndHekele** [comment]
Current Setting:
![image](https://cloud.githubusercontent.com/assets/3288918/6728720/28cc8090-ce2c-11e4-928f-33b66efdcc5f.png)
