### ISSUE TITLE
SDM: Permitted speed at EOA

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#232]
The permitted speed remains at the previous level after EOA (e.g. 80km/h in our scenario). I guess the MRSP should be designed in a way, that at the EOA the MRS is 0. 

Is this assumption correct?
@BenjaminBeichler @T12z @christianstahl

**Comment by BenjaminBeichler** [comment]
No the speed from the MRSP is not train depended as the EOA or MA. I think some problems in the model are left and I have the feeling they are trainsient and also depended on the cycle delay, what they not should be ...

**Comment by BenjaminBeichler** [comment]
@valeriodng @stefan-karg 

I see want your point is... I think there is a Problem at DMI. In TSM the dark grey bar shows the wrong speed, at least not the permitted speed we have as output.

**Comment by valeriodng** [comment]
Ok, I will check it as soon as possible.
