### ISSUE TITLE
SDM/DMI: TargetSpeed jumps at beginning of braking curve

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#235]
When the indication of the target speed 80km/h (km 2.00) starts, the TargetSpeed is higher than the permitted speed (TargetSpeed: 140km/h, permitted speed: 120km/h).

This leads to a wrong indication on the DMI: The circular gauge jumps suddenly from 120 km/h to 140 km/h at the beginning of the braking curve.

@BenjaminBeichler @T12z @valeriodng

**Comment by BenjaminBeichler** [comment]
should be fixed in 721594b19595d1345bca1f6ee0f669aae15f3a30
