### ISSUE TITLE
Emergency brake symbol

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#240]
The emergency brake symbol is not shown in case I overrun the EOA while only driving with a velocity below the release speed. The emergency brake is activated in this case, but the DMI does not show the symbol.

@BenjaminBeichler @T12z @christianstahl @valeriodng

**Comment by T12z** [comment]
Moin,

I am not sure about the case, but eoa may only be service brake. Is the svl at the same location?

I will try to habe a look, but habe no Internet until later. 

Thorsten 

---- stefan-karg schrieb ----

**Comment by BenjaminBeichler** [comment]
In the current testcase SvL and EoA are the same. I have the feeling its more a problem of the DMI, when switching from FS to Trip Mode.

**Comment by valeriodng** [comment]
@stefan-karg do you mean after the kilometer 5000? I checked in debug mode (with a breakpoint on the valid flag of the Icon packet), a  receive no signal, It's always false. If you want we can have a session tomorrow.

**Comment by stefan-karg** [comment]
Thanks to all for the quick reaction! @valeriodng let's have a session tomorrow. Maybe the minimal mode management function does not create all necessary outputs.

**Comment by stefan-karg** [comment]
Problem should be fixed in ab4c335 . The traction cut off signal was not correctly processed by the environment model.
