### ISSUE TITLE
Use Case 10: Change Level 2 Mode FS to Level NTC Mode SN

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#249]
Dear all,

find the Sequence Diagramm for this US on:

https://github.com/openETCS/modeling/blob/master/User%20Stories/User%20Story%2010.pdf

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by MariellePetitDoche** [comment]
What is expected from  me here ?

**Comment by BaseliyosJacob** [comment]
Hello Marielle,

here i expect, as shown in US 10, the transition from Level 2 Mode FS to Level NTC Mode SN when the train is entering the station Utrecht from the free track. The train was in Level 2 Mode FS before.

**Comment by MariellePetitDoche** [comment]
Transition has been implemented but I can not tested it on this specific track.

**Comment by BerndHekele** [comment]
Done.
