### ISSUE TITLE
Use Case 11: Run in Level NTC and Mode SN

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#250]
Dear all,

find the Sequence Diagramm for this US on:

https://github.com/openETCS/modeling/blob/master/User%20Stories/User%20Story%2011.pdf

**Comment by BaseliyosJacob** [comment]
Braking curve for entering the train station and stopping before EoA.

**Comment by BenjaminBeichler** [comment]
as long as the speed supervision gets a valid MA, this Usecase should work.
 
To be more exact, we will guarantee the stopping before SvL in safety critical situations. If EoA and SvL is the same, (no DP and Overlap defined) then of course we will stop before EoA.

**Comment by Rainer-Lampatzer** [comment]
Outdated.
US has been changed several times after last touch and completely changed the content
