### ISSUE TITLE
ADD Document Third Iteration

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#256]
Dear all, 

i will submit the Third Iteration ADD Document next week @14.04.2015 on the ITEA. 
Furthermore the document will be opened for the reviev cycle.

But i still miss some input from the designer:

Allow me to make you a proposal:

So either you can deliever your inputs until the in the ADD or you send me the permission to submit the document without your content until 10.04.2015 14:00 O´clock.
In this case your input will be considered for the 4th iteration of the document.

Open Issues:

5. Runtime API

 - 5.1 Interfaces
 - 5.2 Header

@BerndHekele 

- [x] you want to complete it 
- [ ] or permission to submit it without your content

6.2.1.7 Information Filter
@astante 

- [ ] you want to complete it 
- [ ] or permission to submit it without your content

6.2.4 Manage Track Data
@JakobGartner 

- [ ] you want to complete it 
- [ ] or permission to submit it without your content

6.2.5 Manage Data
@JakobGartner 

- [ ] you want to complete it 
- [ ] or permission to submit it without your content

6.2.6 Manage Outputs
@BerndHekele 

- [ ] you want to complete it 
- [x] or permission to submit it without your content

DMI Controller
@valeriodng a

- [ ] you want to complete it 
- [ ] or permission to submit it without your content

Thank you very much 

Baseliyos Jacob

**Comment by BerndHekele** [comment]
Dear Baseliyos,
I plan to contribute the mssing parts.

**Comment by astante** [comment]
As you can see here: https://github.com/openETCS/modeling/blame/master/openETCS%20ArchitectureAndDesign/ThirdIteration/sections/receivetrackdata.tex I provided some contents 20 days ago. It seems that the generated pdf in the repository is not up-to-date.

**Comment by BaseliyosJacob** [comment]
@astante i can see your content. Is it possible to integrate it again in the new version?

**Comment by BaseliyosJacob** [comment]
@astante Issues solved. Thank you very much. Seems like that i had an old version of the pdf.

Massive Thanks

**Comment by mairamou** [comment]
Ok for me. I prefer to contribute with a description of the complete and integrated versions of "my" modules

**Comment by BerndHekele** [comment]
Dear Baseliyos,
the API part is added.
The other parts will be transfered of the next iteration.

**Comment by mahlmann** [comment]
I will close this issue since the document is being restructured currently.
