### ISSUE TITLE
Request to provide constant path to SCADE integration model

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/modeling#257]
During the last integration tests the root note to the SCADE source code changed. The folder of the last integration was dicontinued.

For further integration tests please provide the infomation about:
- the path to the root node by providing the github path to the root SCADE operator https://github.com/openETCS/modeling/.../*.etp + SCADE path to root operator  of the openETCS OBU

Please do not change the path to the root node in further releases so a regular generation and testing infrastructure can be automised.

@BerndHekele can you name the path to the root node?

**Comment by BerndHekele** [comment]
Dear Mar,
the correct place for this model is here:
https://github.com/openETCS/modeling/tree/master/model/Scade/System/OBU_Integration

This model is not functional yet and not up-to-date. I will give an update on when it will be available tomorrow.
The model used during the demo is meant for the demonstration and not showing the right worksplit in the obu.

cu
Bernd

**Comment by BerndHekele** [comment]
The model is back again in its original location: 
https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_for_ITEA-Review/PositionSimulation/Testbench_Suite/Testbench_Suite.etp

We will discuss the procedure on evolving this model for the openETCS project.

I understand this ussue is closed for now?

cu
Bernd

**Comment by MarcBehrens** [comment]
Yes, thank you Bernd.
For now the issue can be closed.
For the upcoming period I am looking forward to continuously integratable source.
