### ISSUE TITLE
Clarification of Interfaces of Modes and Level functions

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/modeling#272]
In view of integration of these functions a dedicaded Scade project https://github.com/openETCS/modeling/blob/master/model/Scade/System/ObuFunctions/ManageLevelsAndModes/ModesAndLevels/ModesAndLevels.etp has been created.

Check and clarification are necessary for some inputs or outputs:

Interface to DMI:
[ ] How the driver provide level (for example at start of mission) ?

Interface Localisation:
[ ] To check

Interface Speed and Supervision:
[ ] To do 

Interface TIU:
[ ] To check

Interface to Track:
[ ] To clarify

Unknown input:
[ ] To Clarify

**Comment by BerndHekele** [comment]
I want to try an update on this issue:
-[ ] Interface to DMI: the level change procedure is still on work.
-[ ] Interface to localisation: ok?
-[ ] Interface to speed and distance: both directions are still not visible to me.
-[ ] Issues are closed, corrections provided
-[ ] Interface to work: ongoing work

I will proceed next with the M&L issues on the packets from trackside.

**Comment by MariellePetitDoche** [comment]
MĹ module has been completely integrated.
