### ISSUE TITLE
TrackMessages.etp: poor health status

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#273]
TrackMessages.etp is currently inapplicable, but indispensable for migrating to the new byte walker type interfaces.

**Comment by JakobGartner** [comment]
As discussed last week, there are interdependencies between the Balise/Radio Channel and this library.
Standalone it does not provide much value, as the data have to pass the balise/radio channel.
Bernds team and LEA team are working on merging these types. 
Disruptive event ...

**Comment by JakobGartner** [comment]
The model has been updated for the data types that have been moved to Common_Types_Pkg and the model is now free of semantic errors.
Operators "in work" are named as DRAFT_ ... and can't yet be used.
Integration work with the Utrecht- Amsterdam track side work is ongoing, release today-
