### ISSUE TITLE
TrackMessages.etp: RBC to Train packets 41, 57 and 58

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#274]
For implementing user story 7, the RBC to Train packets 41 (Level Transition Order, §7.4.2.9), 57 (MA Request Parameters, $7.4.2.14) and 58 (Position Report Parameters, §7.4.2.15) are needed.

@JakobGartner

**Comment by BaseliyosJacob** [comment]
Hello Alexander,

here is the content of the packages:


NID_PACKET(8bits) = Level Transition Order(41)
Q_DIR(2bits) = Nominal(1)
L_PACKET(13bits) = 89bits(89)
Q_SCALE(2bits) = 1m(1)
D_LEVELTR(15bits) = 801.0m(801)
M_LEVELTR(3bits) = Level 2(3)
L_ACKLEVELTR(15bits) = 210.0m(210)
N_ITER(5bits) = 1(1)
    1: M_LEVELTR[1](3bits) = Level STM(1)
            NID_STM[1](8bits) = ATB
        L_ACKLEVELTR[1](15bits) = 210.0m(210)"


Message from RBC: Level STM(1)	STM National(13)	NID_C(10bits) = 426	 Netherlands	 various projects(426)	NID_RBC(14bits) = 1(1)	> M24 <  NID_MESSAGE(8bits) = General message(24)	L_MESSAGE(10bits) = 23bytes(23)	T_TRAIN(32bits) = 27945.54s(2794554)	M_ACK(1bits) = Acknowledgement required(1)	NID_C(10bits) = 426	 Netherlands	 various projects(426)	NID_BG(14bits) = 353(353)


NID_PACKET(8bits) = Movement Authority Request Parameters(57)
Q_DIR(2bits) = Both directions(2)
L_PACKET(13bits) = 49bits(49)
T_MAR(8bits) = 15s(15)
T_TIMEOUTRQST(10bits) = Not relevant(1023)
T_CYCRQST(8bits) = 30s(30)"

NID_PACKET(8bits) = Position Report Parameters(58)
Q_DIR(2bits) = Both directions(2)
L_PACKET(13bits) = 56bits(56)
Q_SCALE(2bits) = 1m(1)
T_CYCLOC(8bits) = 6s(6)
D_CYCLOC(15bits) = The train has not to report cyclically its location(32767)
M_LOC(3bits) = At each balise(1)
N_ITER(5bits) = 0(0)"

**Comment by aprobst** [comment]
Hello Baseliyos,

thank you for providing the content of the packets. Nevertheless, following operators are missing in the project TrackMessages.etp:

- SEND_WriteRadioPacket041
- SEND_WriteRadioPacket057
- SEND_WriteRadioPacket058
- SEND_SendRadioMessage with input arguments 'M41' (packet 41), 'M57' (packet 57) and 'M58' (packet 58)

These kind of operators are needed to send the RBC messages 24 and 3 in user story 7 with the new data types from Jakob Gärtner.

@JakobGartner

**Comment by JakobGartner** [comment]
They are under construction , partly already existing (even if the names
are different as the SEND operators you see up to now correspond to the
track model.

I can't commit right now as my interconnection is too slow.





On 15 avr. 2015, at 12:50, Alexander Probst <notifications@github.com>
wrote:

Hello Baseliyos,

thank you for providing the content of the packets. Nevertheless, following
operators are missing in the project TrackMessages.etp:

   - SEND_WriteRadioPacket041
   - SEND_WriteRadioPacket057
   - SEND_WriteRadioPacket058
   - SEND_SendRadioMessage with input arguments 'M41' (packet 41), 'M57'
   (packet 57) and 'M58' (packet 58)

These kind of operators are needed to send the RBC messages 24 and 3 in
user story 7 with the new data types from Jakob Gärtner.

@JakobGartner <https://github.com/JakobGartner>

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/274#issuecomment-93348697>.

**Comment by JakobGartner** [comment]
The functionality has been updated:

SIM_SEND_SendRadioMessage now also supports packets 41, 57 and 58
The functions SEND_WritePacket057_IT and SEND_WritePacket058_IT with the relevant sub function tree has been added.
