### ISSUE TITLE
Level_And_Mode_Types_Pkg::T_Level moved 

### ISSUE THREAD

**Issue by BenjaminBeichler** [openETCS/modeling#277]
Another error stopping from compiling the model is the missing definition of T_Level and some constants from Level and Modes.

I think this should be easy solvable by the owner of this model. 

@mgudemann @MariellePetitDoche 

Maybe there is ongoing work, but it is not visible. Otherwise you could also close this issue ...

**Comment by MariellePetitDoche** [comment]
Yes this type has been removed after discussion during a telco as it is redondant with M_LEVEL.

Look on the project ModesAndLevel to have a challenge of stable types with other functions.

**Comment by BenjaminBeichler** [comment]
Since the problems are produced by dmi management, which indeed uses an old state of your project, the pull request #278 removes this old dependency

**Comment by BerndHekele** [comment]
The library has been corrected.
The models compile now with the new types.
I close this issue - or did I miss something?

kr
Bernd
