### ISSUE TITLE
Track- to- train front-end for subset 76 interface: RFC (request for comment)

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#279]
we have been working on a concept for the train-to-track front-end of the OBU since our discussion on friday.

We have identified some differences:

- The current packet data types in Packet_Types_Pkg are a static subset of the SRS packet definitions. 
- The internal structure of the TrackMessages library are now (on purpose) different from the definition in the SRS.

SRS:
- message header
— packet header
—— packet contents
— packet header
—— packet contents
…

SCADE
- message header
- packet header list (metadata)
- packet contents

L_PACKET is not relevant for SCADE
In SCADE, we can calculate the required length of the array from static definitions (for the existing packet types) and from combination of N_ITER and static dimensions for dynamic packet definitions as planned as a future step.

Can we agree on an interface that provides the subset 76 data converted as follows:

(reminder of the SRS structure: 
- message header
— packet header
—— packet contents
— packet header
—— packet contents
…
)

What we would propose is that the data be split as follows:

- message header
— packet header
—— packet contents
- message header
— packet header
—— packet contents

Where the message header is repeated with each packet

packet header and packet contents must be provided as an array of integers [0 ... MAX_SIZE] filled from [0 ... LAST_RELEVANT_ELEMENT] where MAX_SIZE is identical for all packets and the remainder of the array is stuffed with DEFAULT_VALUE

That way, you would have an interface with (physically) always identical dimensions.
The OBU would then get a front-end operator which eats the incoming stream of Subset 76- derived integer arrays.

Precise description of the front end will be provided. 

?

**Comment by MarcBehrens** [comment]
A precise description of the interface will be provided.
