### ISSUE TITLE
UtrechtAmsterdam_oETCS does not compile

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#282]
We would like to integrate a small example track into the test suite.
Can you please make the model compile and indicate which of the tracks can be used for starting testing?

kr
Bernd

**Comment by JakobGartner** [comment]
As the TrackMessages module has been rebuilt, all related SCADE constants have to be redefined to match the track provided by @BaseliyosJacob . 
As there are also some additional requirements from the RBC @aprobst it will need 2 more iterations to have this finally running. (Next update of TrackMessages will cover the RBC needs) 
@mairamou is working on this with prio ASAP.

**Comment by BerndHekele** [comment]
Can we first start with the balise messages?
The current model does not compile - maybe latest changes have not been committed?

**Comment by JakobGartner** [comment]
We start anyway at first with the balise messages.

But they are also on a new track, so it is not yet totally done.

This will come this afternoon, as well as the needed elements for RBC. (two people in parallel)
