### ISSUE TITLE
US-DMI-Planning Area Integration

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#284]
At  Mode FS the planning area needs to be displayed

**Comment by BaseliyosJacob** [comment]
blocked by #496.

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done
