### ISSUE TITLE
US-DMI-Mode Integration

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#285]
On mode changes the DMI implements the interface to the driver.
The following modes are requireds:
 - ntc (ATB) mode sn
 - fs, sb, np, trip, post trip, os sr
Interface to the modes model needs to be implemented in the dmi manager

Covers also text messages for confirmation of level changes

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done
