### ISSUE TITLE
Procedures need to be integrated with Mode and Level Management

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#289]
Mode changes during sstart of mission are not properly implemented in the procedures.

**Comment by BaseliyosJacob** [comment]
issure #482 in relation

**Comment by BaseliyosJacob** [comment]
issue #482 closed

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done.
