### ISSUE TITLE
TrackMessages.etp: No Namespace

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#290]
All types, constants and functions reside in the global namespace. Please assign a namespace, by moving them into a package.

**Comment by JakobGartner** [comment]
I agree. We said we will do that in a next step, in order to have as little delay as possible for the 1st integration.
As a workaround, all operators, types and constants have specific prefixes

**Comment by JakobGartner** [comment]
fixed
