### ISSUE TITLE
Packet_Types_Pkg::P58_PositionReportParameters_T valid flag 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#291]
Contrary to the usual approach, Packet_Types_Pkg::P58_PositionReportParameters_T does not have a valid flag.

Please either indicate that this is correct, or add it. (We will for now assume that it will be added

ETCS_Messaging/TrackMessages does not need valid flags to function, but I guess we want to have a uniform approach)

![screen shot 2015-04-20 at 13 40 52](https://cloud.githubusercontent.com/assets/8400941/7229342/e7e56646-e762-11e4-9083-859abd0156b2.png)

**Comment by BerndHekele** [comment]
Correction for the type is deloivered.
@christianstahl 
This has an impact on the model for position reporting.

**Comment by BerndHekele** [comment]
No impact on other models seen.
I close this issue.
