### ISSUE TITLE
US-RBC-Simulation

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#292]
We need a simulated interfacefrom RBC to EVC.

Known items: (no complete overview)
 - from balise (packets 42, 45)
 - session management at start of mission (packet 3 )
 - movement authority level 2 FS (packet 57, 58)
 - mode changes (packet 41, 
 - Termination of Communication Session
 - validation of train data
 - conditional emergency brake

**Comment by BaseliyosJacob** [comment]
Process is ready. blocked by issue #460 and #497 @jakobgartner .

**Comment by JakobGartner** [comment]
#460 is done.
Working for the first part of the track, I hear the rest shall be ready today.

**Comment by JakobGartner** [comment]
497 is done with exception of the merge of the streams from RBC and balises.

The full track shall be available this evening , right now it is there for the first two sheets.


There is some discussion with @aprobst about how this works, but it works

**Comment by JakobGartner** [comment]
After the last discussion with @aprobst, an integration model that fits the generic track model into the approach used by Alexander on the RBC model has been provided  (US_Integration_June::Amsterdam_Utrecht_Balises_Integration via a572ae6

**Comment by BaseliyosJacob** [comment]
is in the testing phase

**Comment by BaseliyosJacob** [comment]
See #299

**Comment by BaseliyosJacob** [comment]
- [x] Analysis
- [x] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BaseliyosJacob** [comment]
Radio Session has been tested. Testing of train data validation, train position report, Movement Authority and termination of communication session open. Further tests this week.

**Comment by BerndHekele** [comment]
Done.
