### ISSUE TITLE
US-Interface RBC - Simulation to Trackdefinition

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#299]
Interface needs to be  defined.

**Comment by BaseliyosJacob** [comment]
blocked at the moment by issue #460

**Comment by BaseliyosJacob** [comment]
Still blocked by issue #460 @jakobgärtner

**Comment by BaseliyosJacob** [comment]
blocked by issue #460 and #497 @jakobgartner . New datatypes has been modelled in the track description from @jakobartner team. This is confusing since there was another agreeement about the communication between track model and rbc model. This also effects the EVC - RBC communication.

**Comment by JakobGartner** [comment]
the new datatypes were needed because the old ones did not cover the actual data on the track.

**Comment by JakobGartner** [comment]
We will discuss this tomorrow. 

I think with a short explanation this will be clear, it follows the same philosophy that was discussed.
The functionality is also similar, only that it is now modular and distributed instead of in one block.

**Comment by JakobGartner** [comment]
A workaround has been provided so that we can continue while sorting out that data type discussion
This is a duplicate issue with #497.

**Comment by BaseliyosJacob** [comment]
Function is in the testing phase.

**Comment by BaseliyosJacob** [comment]
Need small documentation for the V&V report.

**Comment by BaseliyosJacob** [comment]
- [x] Analysis
- [x] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BaseliyosJacob** [comment]
Have been tested with track and EVC. Works good in the first tests routation.

**Comment by BerndHekele** [comment]
done.
