### ISSUE TITLE
TOOLS_Int_to_NID_LRBG: input "Int_in" is of type bool

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#300]
The input "Int_in" is of type bool. Should be int.

**Comment by JakobGartner** [comment]
fixed

**Comment by UweSteinkeFromSiemens** [comment]
Semantic Warning WAR_508 Unused input at TOOLS_Int_to_NID_LRBG/Int_in/ 
The input variable Int_in is never used.

Semantic Error ERR_516 Undefined variable at TOOLS_Int_to_NID_LRBG/NID_LRBG_out/ 
the output variable NID_LRBG_out has no definition

**Comment by JakobGartner** [comment]
completion bug fixed
