### ISSUE TITLE
Trackmessages Project does not compile

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#301]
TrackMessages does not compile.
I get the following reports:
![image](https://cloud.githubusercontent.com/assets/3288918/7251682/ec3c2150-e82d-11e4-8ad7-7c273c48630c.png)

@JakobGartner

**Comment by JakobGartner** [comment]
As mentioned before, the DRAFT … nodes are incomplete.
This library is in work.

The call tree required for the track model in existence is working.
The model will be updated incrementally, according to the progress on the track side model.

General remark: The current “operation on open heart” is disruptive and will be ongoing for some time.

**Comment by BerndHekele** [comment]
Hi,
I understand your point.
However, we need to have some trust the deliverables are trustworthy.
Basic need is there should not be files missing and functions used inside the test-model do compile.

If this status is reached we can close this issue from my point of view.

br
Bernd

**Comment by JakobGartner** [comment]
todo: 
- complete missing packets
- move pure simulation nodes to trackside simulation 
- move operators, types and constants to packages  
- make private parts private

**Comment by BerndHekele** [comment]
Issue is currently non-blocking.
I close this bug report.
Ongoing work should be reported by other items of the backlog.

Bernd
