### ISSUE TITLE
TrackMessages.etp: Track-to-Train Packet 58 (Incremental distances D_LOC and qualifiers Q_LGTLOC)

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#302]
In the project TrackMessages.etp from @JakobGartner, there is currently a possible restriction for the iterable set (D_LOC, Q_LGTLOC) in packet 58 (see type 'TM_P058' and member 'iterPacket58List'): 

- (D_LOC, Q_LGTLOC)^k, with 1 <= k <= 2, i.e., that only maximum 2 iterations are possible now if N_ITER > 0. This is because the type 'TM_P058Es_T' of the member 'iterPacket58List' is an array of type 'TM_P058E_T' with length 2.

I am not sure if this restriction is correct. According to Subset-040 §4.3.2.1.1g, there should be up to 15 iterations possible. But it is also possible, that I searched at the wrong place. Maybe @BaseliyosJacob can provide more information.

**Comment by BerndHekele** [comment]
Hi Alexander,
your comment is correct.
The deviation in the current implementation is by purpose. It is more convinient in Debug mode to work with smaller definitions of lists.
We should extend this array to the number of reasonable array elements for our implementation until the end of the year. This number is linked to the usecase.

**Comment by JakobGartner** [comment]
The types are derived from the types in Packet_Types_Pkg that are centrally defined.

We have decided to, in a first step, build the transport infrastructure without touching them.

For a real integration with Subset 76- conformal packets we will have to rework all the types with a more generic approach.

This is deferred for now.
