### ISSUE TITLE
Verification 'Receive_TrackSide_Msg', is not able to handle BGs with 8 Telegrams 

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#306]
As the Block 'Receive_TrackSide_Msg', which receives and BaliseTelegrams and builds BGs has the constant "cMaxNoBalises" = 4 it is not able to satisfy SUBSET-026 3.4.1.

This constant limits the Array for TelegramHeader collected in a BG. Respectively, it has to be at least 8 to comply with 3.4.1.1 (eight balises).

As also repeated balises are stored the constant has to be even more then 8.

Thanks
Jan

**Comment by BerndHekele** [comment]
@JakobGartner , @UweSteinkeFromSiemens 
Dear Jan,
this issue has two aspects:
1. The actual number of balises
2. The need to keep duplicates (can we diskcuss this aspekt in another issue?)

Regarding 1: we have chosen to limit the number to a smaller number in order to be more comfortable in testing. In a real model the number(s need to be adjusted. 
This argument is also relevant for other numbers like linking elements or speed profiles.
I would like to get common understanding in openETCS between modeling and validation on the way this shall be handled. 

Please, join into this discussion.

**Comment by UweSteinkeFromSiemens** [comment]
Smaller dimensions are more convenient to handle during debugging. This was the reason why we took them as they are now. Increasing them means simply to increase constants.

**Comment by janWelte** [comment]
Under these circumstances I'll take the first aspect "actual number of balises" as it is, which is not limiting my functional verification aspects. Only be aware that at some point, we have to expand to run all required tests. (BGs with 8 Balises)

I'll take the second issue to another issue, as I need clarification on this issue to understand the expected results for all different modules.

**Comment by JakobGartner** [comment]
The track model supports already up to 8 balises per BG

Sent from my iPhone

On 27.04.2015, at 10:19, Jan Welte <notifications@github.com> wrote:

Under these circumstances I'll take the first aspect "actual number of
balises" as it is, which is not limiting my functional verification
aspects. Only be aware that at some point, we have to expand to run all
required tests. (BGs with 8 Balises)

I'll take the second issue to another issue, as I need clarification on
this issue to understand the expected results for all different modules.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96552660>.

**Comment by BerndHekele** [comment]
There is also an aspect to be changed in the BG-Types.
Im will adjust the balise number to fit to the requirement.

I reopen this issue to cover the type change.

**Comment by janWelte** [comment]
That's correct and helps me to develop all relevant test cases. These will just be failed by the OpenETCS OBU model as they don't handle 8 balises.
Thanks for your work.

-----Ursprüngliche Nachricht-----
Von: Jakob Gärtner [mailto:notifications@github.com] 
Gesendet: Montag, 27. April 2015 10:20
An: openETCS/modeling
Cc: Jan Welte
Betreff: Re: [modeling] Verification 'Receive_TrackSide_Msg', is not able to handle BGs with 8 Telegrams (#306)

The track model supports already up to 8 balises per BG

Sent from my iPhone

On 27.04.2015, at 10:19, Jan Welte <notifications@github.com> wrote:

Under these circumstances I'll take the first aspect "actual number of
balises" as it is, which is not limiting my functional verification
aspects. Only be aware that at some point, we have to expand to run all
required tests. (BGs with 8 Balises)

I'll take the second issue to another issue, as I need clarification on
this issue to understand the expected results for all different modules.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96552660>.

**Comment by JakobGartner** [comment]
1. On Amsterdam Utrecht the max number of balises is 2 per BG so we can
cover all user stories with the existing balise channel
2. The effort to go to 8 balises is limited and lea will support DB in
doing so

But as we work priority driven and the priority is to cover the user
stories this is not an urgent issue




On 27.04.2015, at 14:10, Jan Welte <notifications@github.com> wrote:

That's correct and helps me to develop all relevant test cases. These will
just be failed by the OpenETCS OBU model as they don't handle 8 balises.
Thanks for your work.

-----Ursprüngliche Nachricht-----
Von: Jakob Gärtner [mailto:notifications@github.com
<notifications@github.com>]
Gesendet: Montag, 27. April 2015 10:20
An: openETCS/modeling
Cc: Jan Welte
Betreff: Re: [modeling] Verification 'Receive_TrackSide_Msg', is not able
to handle BGs with 8 Telegrams (#306)

The track model supports already up to 8 balises per BG

Sent from my iPhone

On 27.04.2015, at 10:19, Jan Welte <notifications@github.com> wrote:

Under these circumstances I'll take the first aspect "actual number of
balises" as it is, which is not limiting my functional verification
aspects. Only be aware that at some point, we have to expand to run all
required tests. (BGs with 8 Balises)

I'll take the second issue to another issue, as I need clarification on
this issue to understand the expected results for all different modules.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96552660>.


—
Reply to this email directly or view it on GitHub <
https://github.com/openETCS/modeling/issues/306#issuecomment-96553304> . <
https://github.com/notifications/beacon/ACmA35Ur3B8MPOs13O9DYnAFIvMi3B7kks5oDejIgaJpZM4EG7Lr.gif>


—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96611181>.

**Comment by janWelte** [comment]
As I've already discussed with Bernd this is not an urgent issue for our work, specifically as it is only limited by a constant value, which can be changed immediately.

This is only an issue as 8 Balises is a central point for ETCS and needed in many points to verify overall capability. Therefore, this is just a verification issue. Therefore, do not be concerned with it.

-----Ursprüngliche Nachricht-----
Von: Jakob Gärtner [mailto:notifications@github.com] 
Gesendet: Montag, 27. April 2015 13:20
An: openETCS/modeling
Cc: Jan Welte
Betreff: Re: [modeling] Verification 'Receive_TrackSide_Msg', is not able to handle BGs with 8 Telegrams (#306)

1. On Amsterdam Utrecht the max number of balises is 2 per BG so we can
cover all user stories with the existing balise channel
2. The effort to go to 8 balises is limited and lea will support DB in
doing so

But as we work priority driven and the priority is to cover the user
stories this is not an urgent issue




On 27.04.2015, at 14:10, Jan Welte <notifications@github.com> wrote:

That's correct and helps me to develop all relevant test cases. These will
just be failed by the OpenETCS OBU model as they don't handle 8 balises.
Thanks for your work.

-----Ursprüngliche Nachricht-----
Von: Jakob Gärtner [mailto:notifications@github.com
<notifications@github.com>]
Gesendet: Montag, 27. April 2015 10:20
An: openETCS/modeling
Cc: Jan Welte
Betreff: Re: [modeling] Verification 'Receive_TrackSide_Msg', is not able
to handle BGs with 8 Telegrams (#306)

The track model supports already up to 8 balises per BG

Sent from my iPhone

On 27.04.2015, at 10:19, Jan Welte <notifications@github.com> wrote:

Under these circumstances I'll take the first aspect "actual number of
balises" as it is, which is not limiting my functional verification
aspects. Only be aware that at some point, we have to expand to run all
required tests. (BGs with 8 Balises)

I'll take the second issue to another issue, as I need clarification on
this issue to understand the expected results for all different modules.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96552660>.


—
Reply to this email directly or view it on GitHub <
https://github.com/openETCS/modeling/issues/306#issuecomment-96553304> . <
https://github.com/notifications/beacon/ACmA35Ur3B8MPOs13O9DYnAFIvMi3B7kks5oDejIgaJpZM4EG7Lr.gif>


—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/306#issuecomment-96611181>.

**Comment by JakobGartner** [comment]
Please work with @mairamou for any needs on the track simulation model.

**Comment by BerndHekele** [comment]
Corrections provided for the max number in the input channel.
I close this issue.
Please reopen if you do not agree.
