### ISSUE TITLE
Review of D3.5.2 and 3.6.2  openETCSArchitectureAndDesignSpecification

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#307]
Please review the current deliverable D3.5.2 and 3.6.2 |   openETCS Architecture And Design Specification .

The review is open until  May 22nd.

Document under review: 

 Type   | Name                                                     | due      | pdf | source
----|----|----|---|---
  D3.5.2 and 3.6.2 | OETCS Architecture and Design Specification | April-2015 | [pdf] (https://github.com/openETCS/modeling/blob/master/openETCS%20ArchitectureAndDesign/ThirdIteration/openETCSArchitectureAndDesignSpecification.pdf) | [tex] (https://github.com/openETCS/modeling/blob/master/openETCS%20ArchitectureAndDesign/ThirdIteration/openETCSArchitectureAndDesignSpecification.tex)

Role | Partner 
---|---
Product Owner | @Baseliyos Jacob
Review Team | @BaseliyosJacob , @vgontier , @MarcBehrens , 
Key Customers WP1 | @KlausRuedigerHase  , @idelatorre , @mahlmann 
Key Customers WP2 | @sbaro 
Key Customers WP3 | @faustco @BaseliyosJacob , @MERCEmentre , @UweSteinkeFromSiemens , @christianstahl , @Farhangi , @alexn84 , @VNuhaan , @KlausRuedigerHase @BenjaminBeichler @valeriodng @vgontier @T12z @JakobGartner @mairamou @stefan-karg 
Key Customers WP4 VnV-plan | @MarcBehrens , @vgontier @janWelte
Key Customers WP5 | @didierersa 
Key Customers WP7 | @jastram, @astante 

Please contribute to the review according to the [QA- Review Process](https://github.com/openETCS/governance/blob/master/Review%20Process/OpenETCS_ReviewProcess_0.2.1.pdf?raw=true).

@openETCS/modeling
@openETCS/srs-analysis-committer 

Please mention the issue  # 307 within your issue or contribute with a pull request to the document itself.

Dear All,
we want to get your feedback on the architecture and design document.
Please be aware, we appreciate technical comments as well as comments related to the process or the document structure.

Your comments will be collected via issue-tracker. 
**Deadline is May 22nd of 2015.**

Baseliyos Jacob

**Comment by UweSteinkeFromSiemens** [comment]
https://github.com/openETCS/modeling/blob/master/openETCS%20ArchitectureAndDesign/ThirdIteration/sections/trainPosition.tex has been left out from the document. With intent or faulty?

**Comment by BaseliyosJacob** [comment]
Dear Uwe,

sorry. Was my fault by accident. I add it the train position on the new version on Git hub.

**Comment by mahlmann** [comment]
It has been decided to skip D3.5.2 and D3.6.2. The next iteration documents, i.e. D3.5.3 and D3.6.3, are in preparation. Thus, this issue will be closed.
