### ISSUE TITLE
New Balise Simulation model

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#308]
I have updated and improved the balise simulation model with a lot of help from Jakob

Attention: This is a template library. Operators named "template" must be copied to your project and instantiated there. I will provide detailed documentation tomorrow. Now I first build a track that also sends linking data.

All operators are free of semantic errors and we did some first user validation. 

Enhancements:
BGs now up to 8 balises
balises can now send up to 20 different packets of any kind. New packets can be added without changing the interface.
Balise localisation now works in both directions (also with decreasing train position)
Balise location is now always in reference to the balise with n_pig = 0
Q_DIR is not anymore part of the engineering data but implicitly derived from the balise position

ToDo:
support for engineering data with discontinuous mileage
update radio message library the same way.

**Comment by mairamou** [comment]
please review

**Comment by BerndHekele** [comment]
Dear Mairamou,
I'm using Story00A.
The operator does not throw any balise. You mention some special handling needed to use them.
Can yoi please define what needs to be done?

Thanks
Bernd

**Comment by mairamou** [comment]
Hello Bernd 

When I simulate I can see the balises send the telegram headers- for
example for Balise 364 (see screenshots attached) 

There is only a little problem when the simulation runs while the train
position stays the same, then we get false positives in some exceptional
cases. This will be fixed today. 

Do you have the latest version? We committed an update that corrected an
error that made that the balise data where released but not propagated
to the train. 

There is no special treatment needed when using the tracks. 

The special treatment is only needed when building tracks. 

On 2015-04-25 17:29, Bernd Hekele wrote: 

> Dear Mairamou,
> I'm using Story00A.
> The operator does not throw any balise. You mention some special handling needed to use them.
> Can yoi please define what needs to be done? 
> 
> Thanks
> Bernd 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/308#issuecomment-96223261

**Comment by BerndHekele** [comment]
I see you start in a fairly high position - I will retest.
However, reading the positions, I see BGs 367 and 368 at the same pos.
![image](https://cloud.githubusercontent.com/assets/3288918/7334094/45352cd6-eb88-11e4-9f72-74a5a46f53d1.png)

I assume, the pos gives the absolute position in m?
Or am I wrong?

**Comment by BerndHekele** [comment]
Dear Mairamou,
I tested the balises now - looks ok now with exception of balise 341. Here, only one of the balises is generated.

cu
Bernd

**Comment by mairamou** [comment]
Yes, it was just a first test for the principle. 

I am now building the entire track. 

Step 1- all balises with all packets 5 

Step 2- all other balise packets 

Step 3- all radio packets. 

I expect to need 4 weeks altogether 
the track will "grow" along the data provided by Mr. Baseliyos Jacob 

On 2015-04-25 21:18, Bernd Hekele wrote: 

> Dear Mairamou,
> I tested the balises now - looks ok now with exception of balise 341. Here, only one of the balises is generated. 
> 
> cu
> Bernd 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/308#issuecomment-96264865

**Comment by BerndHekele** [comment]
Since we have a track for first tests it is ok. We are no longer in a hurry.
Can you please nevertheless correct errors on the small track if if we step over?

**Comment by mairamou** [comment]
On 2015-04-25 21:18, Bernd Hekele wrote: 

> Dear Mairamou,
> I tested the balises now - looks ok now with exception of balise 341. Here, only one of the balises is generated. 
> 
> cu
> Bernd 
> 
> --
> Reply to this email directly or view it on GitHub [1].

fixed with the next version 

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/308#issuecomment-96264865

**Comment by mairamou** [comment]
BGs 367 and 368 at the same pos 

- fixed in next version 

I assume, the pos gives the absolute position in m? 

- I am not sure. But I will verify by checking distances on a real map-
There is nowhere a scale on the track layouts; I believe that for now it
doesn't matter, but for the full track we will need to calibrate the
increment. 

On 2015-04-25 20:19, Bernd Hekele wrote: 

> I see you start in a fairly high position - I will retest.
> However, reading the positions, I see BGs 367 and 368 at the same pos. 
> 
> [1] 
> 
> I assume, the pos gives the absolute position in m?
> Or am I wrong? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/3288918/7334094/45352cd6-eb88-11e4-9f72-74a5a46f53d1.png
[2]
https://github.com/openETCS/modeling/issues/308#issuecomment-96255803

**Comment by janWelte** [comment]
I think the problem at this point are the missing distance values in Baseliyos' track [plan on github] (https://github.com/openETCS/modeling/blob/master/User%20Stories/Utrecht%20-%20Amsterdam%20Track%20Example/Daten_Amsterdam_Utrecht.pdf) pictures for Balises 368, 389 and 341. So we cannot check the logical locations.

@BaseliyosJacob: do you the full plan for the pages, which are smaller in your document?

**Comment by JakobGartner** [comment]
I have the nominal locations in an excel file which I will send as soon as
I can connect my laptop .

Am at airport right now ..

Sent from my iPhone

On 27.04.2015, at 09:26, Jan Welte <notifications@github.com> wrote:

I think the problem at this point are the missing distance values in
Baseliyos' track plan on github
<https://github.com/openETCS/modeling/blob/master/User%20Stories/Utrecht%20-%20Amsterdam%20Track%20Example/Daten_Amsterdam_Utrecht.pdf>
pictures for Balises 368, 389 and 341. So we cannot check the logical
locations.

@BaseliyosJacob <https://github.com/BaseliyosJacob>: do you the full plan
for the pages, which are smaller in your document?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/308#issuecomment-96529821>.

**Comment by UweSteinkeFromSiemens** [comment]
The nominal locations are essential, since linking should be based upon these.
Does anybody know, what the field "pos" is intended for, where it is filled with the current values from and what it's dimension is? How is "pos" defined?

**Comment by JakobGartner** [comment]
The excel file contains the nominal positions , identical with the nominal
positions in the map

Pos is a copy / paste value representing the identical nominal positions

When you have the excel file you will be able to cross check of we made a
copy paste error when positioning the balises

If now a balise does not trigger at the right point (linking info diverges
from the nominal engineering positions) we will see that the balise in the
real world is not where it should be .

We then can analyze the jru data and trace the root of the problem

The final track will make sure that with a strictly increasing train
position will trigger the balises according to their nominal positions in
the different sections . For example 352 and 353 are in different sections

Sent from my iPhone

On 27.04.2015, at 09:35, Uwe Steinke <notifications@github.com> wrote:

The nominal locations are essential, since linking should be based upon
these.
Does anybody know, what the field "pos" is intended for, where it is filled
with the current values from and what it's dimension is? How is "pos"
defined?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/308#issuecomment-96535398>.

**Comment by JakobGartner** [comment]
As you see, the nominal positions are “Pos”.

If you find errors, please @mairamou who is maintaining the data in the SCADE model

**Comment by JakobGartner** [comment]
About the dimension :

We believe at the moment that it is in  Q_SCALE resolution but we must yet
confirm

On 27.04.2015, at 09:35, Uwe Steinke <notifications@github.com> wrote:

The nominal locations are essential, since linking should be based upon
these.
Does anybody know, what the field "pos" is intended for, where it is filled
with the current values from and what it's dimension is? How is "pos"
defined?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/308#issuecomment-96535398>.

**Comment by BerndHekele** [comment]
I checked the balsie positions against linking information.
Most data look reasonable (all positions and distances in m (q_scale = 1).

But, balise 366 is in the wrong position.
Maybe a typo?

![image](https://cloud.githubusercontent.com/assets/3288918/7344358/193cdfea-eccb-11e4-917d-b314e69d0978.png)
