### ISSUE TITLE
US-SpeedMonitoring: Impacts of Modes and Level Management on Speedsupervision

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#314]
Analysis is needed on the impact of Modes and Levels on the supervision.

**Comment by BenjaminBeichler** [comment]
with 50a5ee1a8a9b0fdc429fcd2a95ef5b3a3a1e62c9 @vgontier sent a analysis of this interface

what now needs to be decided is, whether the speed supervision module (or Scade Operator) only provide an interface to the modes and levels, which trigger the brakes under the conditions, which are mentioned in the analysis, or the speed supervision determines the triggering conditions.

To take an example: If a unconditional emergency brake command is received, it needs to be checked and accepted in several ways and then the mode needs to be changed and the brakes needs to be applied. 

Now is the question which operator is responsible for receiving, checking and process the acceptance of the driver of this information. 

From my point of view I see not the speed supervision responsible but the modes and level management or another component. Neither the current model nor the Subset 26 Chapter 13. are dealing with modes and levels and I would propose to not introduce new dependencies. The modes and levels management have for example already to deal with the modes in which such messages like unconditional emergency brake commands are valid or not.

But somebody have to generate this information...
@BerndHekele @MariellePetitDoche @JakobGartner @T12z @christianstahl

**Comment by MariellePetitDoche** [comment]
Reception of Unconditionnal emergency Brake message (Mess16) is a condition to switch to  trip mode, and to  command EB from mode management function.

Then, the TrainTrip procedure (§5.11) allow to quit Trip mode and return in a supervision mode. This procedure is implemented in the Mode management function for all which concern mode management (waiting the train is at standstill, request of driver ack, switch to PT/SH/UN/SN mode, wiating of RBC mode revocation,...). Management of report (to RBC for example) or database (deletion of MA and track description) are not covered.

![figure_52_diag](https://cloud.githubusercontent.com/assets/2233518/7416989/64735058-ef63-11e4-8f7c-33651e2890fc.png)

**Comment by vgontier** [comment]
The Speed and Distance Monitoring Model is the only one to activate and desactivate the brakes.
When the Mode and Level Model send a "Trip Mode" State, the Speed and Distance monitoring has to activate the Emergency Brake. 
The unconditional emergency procedure is not an Speed and Distance Monitoring Issue (nor a Mode and Level one), but it is inside the perimeter of group 1 model.
See FT.3.3 "Supervise Unconditional Emergency Stop" of the CORE model : we have to send to Marielle the data "Unconditional Emergency Stop accepted" and she has to return "Train in Trip Mode"

**Comment by BenjaminBeichler** [comment]
OK, If everybody agree, I would propose, that @MariellePetitDoche suggest an Interface from Modes Management, and we adapt our Operator. I think a boolean with "issueEmergencyBrakeFromModes" should be sufficient. If you need also to issue the Service Brake or the Traction-Cut-Off, then generate a separate signal for this.

A valid flag seems not to be needed I think ...

**Comment by MariellePetitDoche** [comment]
As input:
- a boolean to inform that an unconditionnal emergency message has been received (mess16)  in my point of view provided by the function in charge of RBC communication

As output:
- a boolean Emergency_Brake_requested, as this shall be requested for other reasons (at least all the reasons which have as consequences a Trip Mode)
- a boolean Service_brake_Commanded, as this can be requested for other reasons as time-out

Information provided by Speed and Supervision function which  has as consequence a Trip mode is the overpass of an EOA

**Comment by BenjaminBeichler** [comment]
@MariellePetitDoche 

has `Service_brake_Commanded` the same semantics as `Emergency_Brake_requested` , as speed supervision should command the service brake ? Then I propose the same name structure. Otherwise what does the second output mean and could speed supervision ignore it ?

**Comment by MariellePetitDoche** [comment]
I do not understand what you means by "semantics" here.
Indeed Service brake and Emergency brake have different behaviors and are requested in different context (depending if there are or not a safety risk). Several differents reasons and situations request the command of a service brake (for example time-outs)  or emergency-brake (system failure or trip order or direct request from track).
Thus mode and level mangagement function deals with a set of different beahviors. Other functions (tipically speed and supervision in the case of overspeed) can request the command of these brakes.
At the end conjonction of all these commands are send to the TIU to proceed on the brake (I guess it is described in subset 34 "train interfaces").

**Comment by BenjaminBeichler** [comment]
My questions was about the different naming... Why the first one is called `*_commanded` and the other one `*_requested`

If both mean, that the brake should be issued when the flag is true, they should get the same name.

**Comment by MariellePetitDoche** [comment]
Names are linked to the informal description in subset 26 and do not really  matter in theScade model.
We can easily adapt them during nodes integration. This is just a choice linked to a first version, we do not take care of the whole system as the oinformation on the whole were not available.

Besides in the specific case of the brakse, global analysis of the system  shall be made to  decide if we have to  speak on a "brake command" or on a "brake release" : For safety reasons, the brakes are always commanded, and OBU shall compute if they can be released at each cycle.

**Comment by BenjaminBeichler** [comment]
If the names do not matter, I propose the Interface for speed supervision with 2 booleans 

Service_brake_requested_by_modes_and_levels
Emergency_brake_requested_by_modes_and_levels

@BerndHekele @stefan-karg 

I Include this until tomorrow in a new branch called `speedsupervision_interfacechange` and I would propose you reflect the changes for your models and merge the branch into master.

**Comment by BerndHekele** [comment]
The proposal look fine to me.
We can integrate / merge it tomorrow when Stefan is back again.

**Comment by BerndHekele** [comment]
Done.
