### ISSUE TITLE
Error in CheckBG_Consistency_Pkg

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#315]
Package is not merged into the outgoing message.
![image](https://cloud.githubusercontent.com/assets/3288918/7334240/324880d6-eb8e-11e4-8ae1-545e94656414.png)

Can be reproduced using testcase doTestTrackSideIntegration

**Comment by Farhangi** [comment]
only  MetaData fixed by 3cc267bc8a1653af151fac561d18940f930f80f3

**Comment by Farhangi** [comment]
b381168105cae2498ba67b9d6d6cba6994069898
