### ISSUE TITLE
Error in CheckBG_Consistency_Pkg: Missing balise not detected

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#316]
When only one of two balises are passed the error does not recognise the missing balise (indicated by false in the header).

A second error is in this situation in Build BG Message function: counter is wrong.

**Comment by Farhangi** [comment]
Function is implemented according to specification. The behaviour you describe is intended by the specification.

**Comment by janWelte** [comment]
Please indicate the clear distinction between the behavior of all different modules.

The behavior should be as follows:
- Build BG sends only the recognized balise(s) as BG_Message to check
- CheckBG_Consistency identifies that not all telegrams required for the Balise group are recognized in the expected distance (CheckBG_Consistency has to check, whether all detected balise center are inside the range for the balise group and in right order),
- if the Balise is not complete (not consistent), braking actions have to be performed according to 'SUBSET-026_3.16.2.4 for linked and 3.16.2.5 for unlinked
- required information about an incomplete identified BG have to be given to further functions (brake, train position, dmi)
- A function (in our case MenageTrainPosition) will recognize that an announced balise is not found in time and will trigger action in this case (other case as completion related behavior is not covered here)

Please ensure that this behavior is consistent with your understanding.
The functions will be verified according to this behavior.

If there are discussion concerning the split between all moduls, we should clarify these during a telco and document all results.

**Comment by BerndHekele** [comment]
Dear Jan,
this issue is related to a concrete error in the software which was found and corrected. Peymans statement , as well as mine,are related to the correction of this specific error.

I close this issue because the concrete error is corrected.

Your statement is very general. Can you please run a trest and formulate an error report based on this test scenario.
I'm sure we at cover most of the stated behaviour. 
But a verification will definitly improve the trust in the behaviour.

kr
Bernd
