### ISSUE TITLE
BG_Types / Packets_Types_PKG

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/modeling#322]
Some inconsistencies found in this package on some types:

- [ ] P4 : validity, direction, scale and distance are common to  all transition level according subset 26
- [ ] P41, P46: how to detect number of level transition provided ? is there a specific flag to inform if the data are provided ?
- [ ] P46 : validity, direction are common to  all transition level according subset 26
- [ ] P12, P135 and P63 are missing

**Comment by BerndHekele** [comment]
Dear Marielle,
I will analyse the issue and change the data accordingly.

One early remark: the packets missing are most likely not relevant in the communication for the track (we did not see those packets).

This does not mean they are not needed to implement the model.

kr
Bernd

**Comment by BerndHekele** [comment]
P12, P135 and P63 have been added now.
We discussed the general concept of packet definitions in our workshop.
Do we havve other open issues with type definitions for packets?
Otherwise, I propose to close the issue.

kr
Bernd

**Comment by MariellePetitDoche** [comment]
thanks,
Not for the moment thus I close it.
