### ISSUE TITLE
API_RadioCommunication_Pkg: Ambiguities

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#325]
#### Findings: 

1. ***API_RadioCommunication_Pkg::API_EuroRadioOutput_T*** represents the inputs to the mobile terminals. Whereas there are 3 fields (*firstOutput, secondOutput, thirdOutput*) for message transmission to the track / RBC via up to 3 mobiles, only 1 field *radioEVCtoUnit* is availlable for terminal control. 

2. *radioEVCtoUnit* of type ***RadioManagment_T*** is inapplicable for addressing a dedicated mobile terminal. Its field *networkID* of type *NID_MN* is for registering to a mobile network, but cannot serve for terminal selection, since all terminals are usually registered to the same network. 

3. ***API_CommunicationStatus_T*** represents the outputs of the mobile terminals. Different from the input side, there is no data path for receiving datagrams. 

4. The field ***CommunicationSessionNumber*** of *API_CommunicationStatus_T*  is useless for the application, because it is nowhere used on the terminals input side.

5. *API_CommunicationStatus_T.mobileInformation* of type ***radioUnitToEVC_T*** does not indicate the mobile terminal the status belongs to.

6. *API_CommunicationStatus_T.mobileInformation* of type ***radioUnitToEVC_T*** does not provide an acknowledgement of registering or unregistering the mobile terminal.

#### Recommendations: 

The types should be in line with the "separation of concerns" principle and restructered to enable: 

1. **Separate mobile terminals**: each mobile terminal must be accessible separately and therefore should provide its own interface. 

2. **Separate control flow from data flow**: Each mobile terminal should provide separate inputs / outputs for control and data transmission.

**Comment by BerndHekele** [comment]
Dear Uwe,

well observed.

The original implementation of this interface got stuck when  the discussion with radio session management was not possible.
I agree: we should setup a new structure for the radio management functions.
I would like to start the discussion based on the Alstom API which is in my eyes quite well organised for managment of the mobiles.
Do you want to make a scade proposal for the interface or shall I pick the ball?

cu
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
The interface will evolve automatically from analyzing and designing of the RBC handover procedure. Therefore, you may keep the ball dropped.

**Comment by BerndHekele** [comment]
I propose to pick this topic when we integrate the handover to the evc.
I see the issue linked with the change of interfaces to make use of the BCD.
#490

**Comment by BerndHekele** [comment]
Interface Freeze for openETCS.
Needs to be concluded in another project.
