### ISSUE TITLE
LEA RAILERGY backlog week May 11-15, 2015

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#339]
Mairamou:
- Add balise and radio packets to section "Amstel" of Amsterdam- Utrecht
- Position Balises and add balise packets for sections "Bijlmer" , "Bijlmer- Abcoude" and "Abcoude"
--> by end of the week we will have 5% of the US track data completed (if we look at full feature)
--> by the end of the week we will have 50% of the track completed (if we look at balise positions and telegram headers only)

Plan for week after:
- Add balise and radio packets to section "Bijlmer" of Amsterdam- Utrecht
- Position the rest of the balises
-- by the end of the following week we will have 15% of the track data completed (if we look at full feature)
--> by the end of the week we will have the US track completed (if we look at balise positions and telegram headers only)

Jakob:
- Add packet support for missing packets in ETCS_Messaging/TrackMessages/TM::....
- Continue work on MA management 
- Continue work on preparing packet data for MA, MRSP and gradient profile calculation
- Validate the test track

Plan for week after:
- Complete work on MA management 
- Continue work on preparing packet data for MA, MRSP and gradient profile calculation
- Start work on National Values (and other semi- persistent data) management.

--> priorities are now driven by the progress of available packets from the test track

**Comment by BerndHekele** [comment]
Dear Jakob,
as discussed on the workshops this week we can share the work.
I propose Peyman jumps into coding of packets of the TrackMessages.
We should organize a short telco to coordinate activities.

**Comment by JakobGartner** [comment]
Hello Bernd,

I agree.

I propose to give a short training to Peyman next tuesday so that we can share the same pattern (there is something like an internal library that has some specifics), then I can transfer the work on this packet encoding/ decoding library to him.

Jakob

**Comment by JakobGartner** [comment]
As discussed, we meet on Monday for task handover
