### ISSUE TITLE
Allocation of Work: Analysis of National Values

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#340]
National Values are not yet supported in the EVC.
The following tasks are foreseen:
 - definition of the use case for the openetcs  project
 - definition of input structures (packets)
 - definition of interfaces in the obu (access to data)
 - if needed a database.

**Comment by JakobGartner** [comment]
The first question is: is the existing packet definition sufficient or should we extend it to full coverage of the SRS?
A prototype for the latter is already existing, we can walk through it next Tuesday on site at DB
Jakob Gaertner

**Comment by BerndHekele** [comment]
Due to personal collision I prefer to have this discussion on Monday.
Thanks for your support.

Bernd

**Comment by JakobGartner** [comment]
as already agreed: OK for Monday

**Comment by BaseliyosJacob** [comment]
Function will be allocated outside of the EVC but will be part of the EVC Onboard kernel

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done.
