### ISSUE TITLE
Request for Revision

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#350]
Dear Partner,
I provided a draft version of the process description for our WP3 sprint backlog.

https://github.com/openETCS/modeling/wiki/WP3-Scrum-Process

Please, have a closer look at the docuement and send me your ideas.

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
Please differentiate unambiguously in the wiki text between product backlog and WP 3 backlog issues.

**Comment by BerndHekele** [comment]
Done.
