### ISSUE TITLE
TOOLS_Int_to_N_TOTAL coverts N_Total=7 to 6_Balises not 8_Balises

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#351]
Operator has a copy and paste error in it's last if decision as it gives back ENUM_N_TOTAL_6_N_TOTAL instate of ENUM_N_TOTAL_8_N_TOTAL if n_total = 7.

Operator is not able to handle inputs irregular inputs (<0 and >7).

**Comment by JakobGartner** [comment]
Fixed:
- Defined full set of constants for decision diagram conditions (INT_N_TOTAL_1 ...8)
- Added branch for INT_N_TOTAL_8 (integer value = 7)
- Added default decision out-of-bounds values in integer input stream
- Added provisioning for error handling

Applied similar fix to TOOLS_Int_to_N_PIG
