### ISSUE TITLE
TrackAtlasTypes: MAs_t and MA_section_T

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#356]
@BenjaminBeichler 

we need to change these types as you will receive the MA information in a reduced form (no timers) as discussed in Stuttgart.

--> call needed

**Comment by JakobGartner** [comment]
To avoid impact on your work, I propose:
- We leave the type unchanged for now
- You receive the MA info "timing- free" (e.g. timers removed) in the existing type def

**Comment by BenjaminBeichler** [comment]
Currently we don't use the timer fields, but Christian did a unnecessary translation for future propose. Nevertheless, open a branch,make your changes, load it up to github, I fix my things, and if everything is working I will merge it to the master.

**Comment by BenjaminBeichler** [comment]
@JakobGartner 

with 36c4ee2566106ec4b74ccb3e3a219114ce96f672 I removed all usage of the timer variables, therefore you could safely remove them from the current datatype. I also switched from flatten to projections to avoid further problems.

Maybe you want to remove some typos of the definition, then please post again. I would also propose to  have only abbreviation of DP or only the full name DangerPoint and not a mixture.

**Comment by JakobGartner** [comment]
ok, on backlog
