### ISSUE TITLE
Packet 3 definition 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#357]
The existing packet 3 definition is truncated- we need to discuss if to stick with it or to implement it closer or fully SRS conformal

(possible duplicate issue ...)

**Comment by BenjaminBeichler** [comment]
From Speed Supervision I'd like to reference this document: https://github.com/openETCS/validation/blob/master/VnVUserStories/VnVUserStoryURO/05-Work/BrakingCurves/BrakingCurveParameters.pdf

**Comment by BerndHekele** [comment]
On the transport channel we need to be compliant with the SRS.
When providing the data as a service we should be customer orientated.
I understand the data needs to be kept in a store and will be used by many users in the system.
The data is pretty "colorful".
