### ISSUE TITLE
Packet 5 Vanished from Stor00A

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#358]
The current test-track does not include the linking package.
This packet had been already provided in an eartlier delivery.

We need model this for the presentation in Amsterdam!!

@JakobGartner @mairamou

**Comment by mairamou** [comment]
Hello, 

it is possible that it was lost when we moved the operators to new
namespaces. 

I will check and fix the story today. 

Mairamou 

On 2015-05-13 11:30, Bernd Hekele wrote: 

> The current test-track does not include the linking package.
> This packet had been already provided in an eartlier delivery. 
> 
> We need model this for the presentation in Amsterdam!! 
> 
> @JakobGartner [1] @mairamou [2] 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1] https://github.com/JakobGartner
[2] https://github.com/mairamou
[3] https://github.com/openETCS/modeling/issues/358

**Comment by mairamou** [comment]
Fixed.
