### ISSUE TITLE
TEMPLATE_Balise does not let pass data from previous balises in groupe

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#359]
The operator TEMPLATE_Balise includes an operator setting value balise_passed to B_data_out (in contrast to all already specified balises, where this operator is taken out). This changes the value to false even if the Balise is not passed yet and only data from a previous balise in a group is passed through. As the decision which telegram in a BG is send at a time is handled by the bool activation of Balise_Packets, this operator is not needed. 

Please change the TEMPLATE to avoid building incorrect BGs. Thanks.

**Comment by JakobGartner** [comment]
fixed
