### ISSUE TITLE
TrackMessages.etp and CalculateTrainPosition with issues

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#362]
Dear Jakob, Dear Uwe,
currently the calculate train psition does no longer work.
When opening the model calculate train position serious reports are visible:
![image](https://cloud.githubusercontent.com/assets/3288918/7648929/716275c4-fae8-11e4-9e9f-55ac996b49d1.png)

This construct looks misplaced.
The radio header used should be the one from our header definitions and not the one you use when generating messages for UtrechAmsterdam.
We do expect the commion_types header at the edge of the model.

Shall we have a short telco on the issue?

**Comment by JakobGartner** [comment]
Hello,


it seems that three things come together here:

(1) As requested, we have moved the models (also for the TrackMessages) libraries to packages.
The paths have therefore changed.
(2) The types that are in common use (relevant outside of the libraries themselves) have been moved to the Common_Types_Pkg (they don’t exist anymore local in TrackMessages)
(3) in the current track model, as RBC is not yet working. we are emitting the packets exclusively through the balise channel, using the agreed types


I think there will be some work to do to couple Calculate Train Position via the Balise Channel. 

We can talk, of course. I am available until 3pm today.

**Comment by BerndHekele** [comment]
The type available for Uwe is the ReceivedMessage_T.
In my opinion the trackMessages need to concentrate on packets. 
But, if you want to cover the complete message you need to change the input types.

kr
Bernd

**Comment by JakobGartner** [comment]
2 perspectives:

Trackside simulation:

Here we transmit messages that consist of headers (using the predefined types) and packets (In the format that we agreed upon and where the types have been moved to common_types_kg)



Reception at CalculateTrainPosition:

The concept would be that TrackMessages library is used to read the packets, there is no attempt to do more than that from my perspective.

As far as I understand, the balise channel transmits more/different info than is contained in the raw message headers that are sent from the track simulation

**Comment by BerndHekele** [comment]
Maybe Uwe is using the wrong operator?

**Comment by JakobGartner** [comment]
I will have look at it and come back with an analysis ASAP

**Comment by UweSteinkeFromSiemens** [comment]
A few days ago I modified CalculateTrainPosition due to TrackMessages restructuring. 

And now, the function RECV_ReadPacket005 has been removed completely and makes CalculateTrainPosition uncompilable. I don't see the point ...

**Comment by JakobGartner** [comment]
It has not been removed.
Since it is not unpacking a raw packet 5 it has been renamed to reflect the
specific use case.

In discussion with Bernd we saw that some adaptations were needed to make
it compatible with packets now coming via the balise channel



On 18.05.2015, at 16:24, Uwe Steinke <notifications@github.com> wrote:

A few days ago I modified CalculateTrainPosition due to TrackMessages
restructuring.

And now, the function RECV_ReadPacket005 has been removed completely and
makes CalculateTrainPosition uncompilable. I don't see the point ...

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/362#issuecomment-103077221>.

**Comment by UweSteinkeFromSiemens** [comment]
... and what is the new name of RECV_ReadPacket005?

**Comment by JakobGartner** [comment]
RECV_ReadPacket005_ForCalcTrainPos

:-)

**Comment by UweSteinkeFromSiemens** [comment]
ooops... If I remember correctly, this was the component I used originally some modification cycles ago.

**Comment by JakobGartner** [comment]
indeed.

we now reverted back to the original layout.
The intermediate solution was aimed at the simulation model that bypassed the balise channel
