### ISSUE TITLE
TrainPosition_Types:Train_Properties

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#365]
Train Length is defined as "external" type L_TRAIN.
Can we change to L_INTERNAL_T?

kr
Bernd

**Comment by BerndHekele** [comment]
I have a second question to this type:
what is the expected behaviour of the default inaccuracies, e.g., when passing to a new NID_C?
Take national values or stick to general default?

**Comment by UweSteinkeFromSiemens** [comment]
NID_BG and NID_C make up the BG ID. Therefore, passing to a new NID_C is simply passing a different BG with probably different uncertainties. This does not have any impact on the national values as long as these values are not explicitely applied.

**Comment by UweSteinkeFromSiemens** [comment]
I'm not aware where L_TRAIN is used within the models. In principle, there is no restriction to train length measurement in L_INTERNAL_T: But then, the variable must not be named l_train or L_TRAIN. In addition, it requires an architecure component responsible for conversions between L_TRAIN and L_INTERNAL_T. And the commitment, that "Train Length" originates from L_TRAIN by conversion only. These complications did not seem worth to deviate from L_TRAIN, which is clearly defined in Subset 026-7.

**Comment by BerndHekele** [comment]
Conclusion during workshop:
we will use the length in the train data.
We will clarify before changing this type on the additiona information related to min length and max length.

**Comment by UweSteinkeFromSiemens** [comment]
@BerndHekele : is this issue relevant any more? Please close this issue, if appropriate.
