### ISSUE TITLE
US-EVC-Integration Model: Prio 900

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#366]
This issue covers the steps needed for providing an EVC model for verification and validation purposes.
The model does not priorize on showing a nice view like an architecture.

This activity refers to model:  
https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_PreIntegrations/openETCS_EVC/openETCS_EVC.etp

THe following steps are seen:
- [x] Basic Model derived from existing testbench model
- [x] Get Rid of testtools in the model
- [x] Define Input/Output of the model
- [x] Linking EVC model (functionality of Paris Review)
- [x] Adding Modes and Level
- [ ] Adding TrackAtlas
- [ ] Replace Radio Session Management

This list is not complete.

**Comment by BaseliyosJacob** [comment]
Start of Mission interfaces should be ready and will be tested this week.

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done.
