### ISSUE TITLE
EVC: wrong data type for input API_mobileHWStatus

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#368]
The input API_mobileHWStatus has the type int but should have the type MoRC_Pck::mobileHWStatus_Type

Also the routing inside the EVC model is not correct, since the MoRC module gets a constant value. This value should be not constant but delivered by the RTM module from outside. At the moment this is realized via a dropdown box in the GUI.

@BerndHekele

**Comment by BerndHekele** [comment]
Correction available
