### ISSUE TITLE
SpeedAndDistanceMonitoring Integration: Input for Brake from Modes missing

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#373]
@BenjaminBeichler , @T12z 

After our Meeting in Stuttgart I was expecting some input for the brake commands.
I cannot find this input in your model.
Was the understanding wrong?

kr
Bernd

**Comment by BerndHekele** [comment]
Hi,
I need a second interface (for Information Filtering): EB is active.
Can you provide this status?

cu
Bernd

**Comment by BenjaminBeichler** [comment]
the output brakeCmd reflects the status of the emergency brake, I don't know whether it's intended or not, but the output will never be "*_command_not_defined".

@christianstahl : Am I right ?

**Comment by BenjaminBeichler** [comment]
Currently I wait on the explanation of my question in #314 , I don't want to change the interface several times, because o unclear definitions

**Comment by T12z** [comment]
This was fixed mid September by myself. Closed
