### ISSUE TITLE
BaliseLib defined twice

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#375]
The Lib is defined twice.
Please cleanup.

@mairamou  @JakobGartner

**Comment by JakobGartner** [comment]
This is on purpose.
The InfraLib which is a sub-package of Story00A is legacy, we don't want to change it while the "real" InfraLib package in BaliseLib model is undergoing constant changes. We will remove the complete Story00A as soon as the full track is stable and accepted by the team.
