### ISSUE TITLE
Gradient_section_t needs valid flag

### ISSUE THREAD

**Issue by BenjaminBeichler** [openETCS/modeling#380]
Because of the dynamic length of the Gradient Profile, a valid flag is needed to mark the end of the array.

@JakobGartner 
Could you please add this to the TrackAtlasTypes ?

In Addition: If the Gradient Profile have no holes (as we agreed on I believe) , you could remove the gradient section length. Of course we also do not need the LRBG related position.

**Comment by BenjaminBeichler** [comment]
needed for #312

**Comment by JakobGartner** [comment]
done
