### ISSUE TITLE
RECV_ReadPacket005_ForCalcTrainPos: No valid flag set for announced BGs

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#389]
The function does not set the valid flag for an announced linked BGs at its output.
Refer to https://github.com/openETCS/modeling/tree/master/model/Scade/System/OBU_PreIntegrations/TestBenchExample  (7a64359dfcc49b0700bb157e7f57935193d60e6e).

**Comment by UweSteinkeFromSiemens** [comment]
TM::RECV_ReadPacket005_ForCalcTrainPos (currently d57f7bba69093a67253bb6a7b07f0f47c67342da) has been broken by one of the previous modifications.

**Comment by UweSteinkeFromSiemens** [comment]
@mairamou : Since Jakob seems not te be available, is would be great if you could fix this bug.

**Comment by UweSteinkeFromSiemens** [comment]
Info from @janWelte : TOOLS_Int_to_Q_DIR is missing in FirstTest::Story00A_BTM.

**Comment by mairamou** [comment]
Hello Uwe, 

I can now translate Story00A. 

All the called functions are now complete and consistent. 

The update is on Github. 

Jakob has fixed the TrackMessages and I have integrated the update. 

(the issue 389 is however still in work) 

Sorry for the delay, I was sick. 

Mairamou 

On 2015-06-02 09:20, Uwe Steinke wrote: 

> @mairamou [1] : Since Jakob seems not te be available, is would be great if you could fix this bug. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Mairamou Haman Adji
Student Trainee / Embedded Systems
---------------------------
LEA RAILERGY

 

Links:
------
[1] https://github.com/mairamou
[2]
https://github.com/openETCS/modeling/issues/389#issuecomment-107835549
