### ISSUE TITLE
Management of Radio Communication (MoRC): Input Events and Phases

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#390]
The session management requires a collection of different inputs from other components: These are (see https://github.com/openETCS/modeling/tree/master/model/Scade/System/ObuFunctions/Radio/MoRC, MoRC_Pck::obuEventsAndPhases_T) : 

![types](https://cloud.githubusercontent.com/assets/2225951/7748725/42938d6c-ffc7-11e4-833b-4536bc533a06.png)

Please identify, if and which of your components is able to provide this information in parts.

**Comment by MariellePetitDoche** [comment]
Some answers :

- for what concerns the procedure start of mission (atPowerDown, atPowerUp, atStartOfMission, startOfMissionProcedureIsGoingOn, startOfMissionProcedureCompleted, trainIsRejectedByRBC_duringStartOfMission, isPartOfAnOngoingStartOfMissionProcedure, afterDriverEntryOfANewRadioNetworkID
) this event seams to correspond to  different states/events of the flowchart 1  in §45.4.4 of SRS. Indeed from state S0  to S10 (right part of the flowchart) .
From Modes&Levels poitn of view nly the bottom of the flowchart is implemented ie. from S10 and S20  to the different modes. D2, D3 and S2 shall be implementd too.

For all the other part of the diagram it concerns the  MORC and DMI  only and I do not know where it is implemented. I think the best place is in the MORC indeed.

the event "startofMissionEnded" is also an input for M&L  but I don  not know from  where.

- endOfMissionIsExecuted : I provide the information EoM_Procedure_req as output of M&L, look in : Level_And_Mode_Types_Pkg::T_Data_To_BG_Management


- driverClosesTheDeskduringStartOfMission : it is a TIU input  I guess : TIU_Types_Pkg::M_cab_signal_status_T


- driverHasManuallyChangedLevel:  M&L  receive a request and produce a new level. Do you really  need a specific information that a level change come from a driver request or in any  case of level change you have something to  check ?


- trainPassesALevelTransitionBorder : there is a boolean output of M&L "LevelsTransitionPositionPassed" or "TransitionPositionPassed" 

- modeChangeHasToBeReportedToRBC: all mode changes are reported to the RBC via packets 0 or 1. Do you need more ?
However there are some specific information to transmit to BG management (for example to clean BG list,...)  see  Level_And_Mode_Types_Pkg::T_Data_To_BG_Management

**Comment by UweSteinkeFromSiemens** [comment]
Dear Marielle,
the event names reflect the terms given by the SRS as precise as possible with reference to the SRS requirements (see table above). As long as there is no additional description, we should try with our best appproach. @BerndHekele will probably disclose inconsistencies when wiring the compononents in the EVC ...

**Comment by BerndHekele** [comment]
Done
