### ISSUE TITLE
US-Validation of Train Data procedure (EVC  - RBC)

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#394]
Implementing of the validation of train data procedure between EVC and RBC.

EVC is send message 129 + packet 0 and packet  11
RBC is sending Message 8 - ack
EVC is sending Message 146 to RBC

**Comment by BaseliyosJacob** [comment]
Sending of train data will be triggered within MoRC and RBC Handover

**Comment by UweSteinkeFromSiemens** [comment]
Changing and validating train data has to be differentiated from the transmission of train data to the RBC. The transmission can be triggered by the RBC handover and Management of Radio Communication functions, but these will simply transmit available train data and are not involved in validating or changing them.

**Comment by BaseliyosJacob** [comment]
Yes, you are right. But in the case of an RBC handover the trigger will be because of a new session to the 2nd RBC (handover). In this case the message to trigger the validation will be within the procedure to build a new session. Therefore i think that the triggering of the validation process should be a part of building a new session.

**Comment by BerndHekele** [comment]
I started with analysis of the topic (SRS subset 26 section 3.18.3.
I will not cover section 5.17 of the SRS (not relevant and fairly complicated.
I will split the implementation in 2 phases:
* I working model but not fully compliant to the SRS for the running iteration
* Work on full implementation for the next iteration.

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

for the US 7 you are right, that we do not need the 5.17. To complete the US 7 we need to have a full process with the RBC and the OBU to validate the train data. Otherwise we can not transmit from Level NTC to Level 2.

**Comment by BerndHekele** [comment]
I need a clarification of the following section of the SRS (3.18.4.2): 

"In case the safe radio connection is lost before the acknowledgement is received, the Train Data shall be sent again once the safe radio connection has been re-established within the on-going communication session."

Is the safe radio connection the sam as the communication session in 3.18.3.4? Or are these different states of radio?

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done.
