### ISSUE TITLE
BuildBGMessage SCADE model: Review findings

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#40]
The following findings refer to https://github.com/openETCS/modeling/tree/master/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/BaliseGroup/BuildBGMessage https://github.com/openETCS/modeling/commit/da2900a8032dfb9ab5397ee88cf025cfab2a702e#diff-45faa47b22dd629e128942d89acacb35: 

1. manageAdditionalTelegram::diagram_manageAdditionalTelegram: memadditionalTelegram in the upper left corner is without any function and can be replaced by a constant. 

2. manageAdditionalTelegram: Since the implementation leads to outDecodedTelegram := inDecodedTelegram and outcenterOfBalisePosition := incenterOfBalisePosition, the node is without any function.

3. manageTelegram: memBGMessage in the upper left corner has - except reset - only constants as inputs. Therefore, the input constants will be provided as outputs. 

4. manageTelegram: memCollector has - except reset - only constants as inputs. Because storeCollector is set to false, the node will do nothing. 

5. manageTelegram: checkInit: Since the input inCollector never changes, checkInit picks some fields of newTelegram to its outputs. The "isDefined" path within checkInit will never be taken. Is this the intended function? 

6.  manageTelegram: checkTelegram: The inputs newTelegram and BGCollector are derived from the same input "newTelegram". Input BGHeaderArray stays permanently at cemptyHeaderArray. Results in that findTelegram incorporated in checkTelegram will not find anything.

7. BuildBGMessage::memCollector(2): Inputs are constants, except reset. Can be replaced by the constant cCollectorInit.

8. BuildBGMessage::checkOdometry: I'm in doubt, if the result outMessageComplete should only depend on the distance between the actual odometry value and inCollector.balisePosition (=0 from cCollectorInit).

9. BuildBGMessage::IfBlock2, path BGisComplete: Works - except reset - with constants. Does nothing.

10. BuildBGMessage::IfBlock3: Produces no output, does nothing.

**Comment by BerndHekele** [comment]
Cleanup of Issues
