### ISSUE TITLE
US-text message to DMI for level change (EVC - DMI)

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#400]
Implementing of sending and acknowledgement of text messages for level change Level 2 (EVC-DMI).

**Comment by BaseliyosJacob** [comment]
will be tested this week.

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Done.
