### ISSUE TITLE
MoRC / Provide position report: Compilation errors due to change of radio output type (#337)

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#420]
@UweSteinkeFromSiemens @christianstahl 

Dear Uwe, dear Christian,

the radio output type has changed, see #337 .
Please adjust the interfaces in your modules MoRC and Provide position report.

**Comment by christianstahl** [comment]
@stefan-karg 
Fixed for ProvidePositionReport.

**Comment by UweSteinkeFromSiemens** [comment]
Done for MoRC
