### ISSUE TITLE
Q_STATUS data type 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#425]
invalid value missing in enumeration 

7.5.1.134

**Comment by BerndHekele** [comment]
corrected

**Comment by mairamou** [comment]
@JakobGartner now you must fix it in TrackMessages

**Comment by JakobGartner** [comment]
Fixed #425 through 8ed5633 <https://github.com/openETCS/modeling/commit/8ed5633278dee5c0a9ba2a00d1b4655c5350628a>
