### ISSUE TITLE
TrackMessages: Required conversion operators for Radio Session Management and RBC Handover Procedure

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#427]
The RBC Handover and Management of Radio Communication components require these conversion operators: 

**Input conversions (from track to train):** 
Convert ***API_Msg_Pkg::API_TrackSideInput_T*** to structured types of

- packet 42 (radio session management)
- packet 45 (radio network registration order)
- packet 131 ( RBC transition order)
- message 32 (RBC/RIU system version)
- message 38 (initiation of a communication session)
- message 39 (acknowledgement of the termination of a communication session)

**Output conversions: (from train to track):**
Convert structured types to ***Radio_Types_Pkg::Radio_TrainTrack_Message_T***:

- message 154 (no compatible version supported)
- message 155 (initiation of a communication session)
- message 156 (termination of a communication session)
- message 159 (session established)

Required for  #341.

**Comment by JakobGartner** [comment]
42,45,131 available

**Comment by JakobGartner** [comment]
messages have to be composed in track model or RBC model from packets

**Comment by JakobGartner** [comment]
all track-to-train are done.

**Comment by JakobGartner** [comment]
all train to track are done

to do: higher level bus function

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by UweSteinkeFromSiemens** [comment]
Done from my point of view
