### ISSUE TITLE
Inconsistencies in TrackMessages.etp

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#428]
TrackMessages.etp contains inconsistencies that are caused among others by invalid package declarations.

@JakobGartner @mairamou 

![zwischenablage01](https://cloud.githubusercontent.com/assets/10213037/7960596/1349769e-0a02-11e5-993b-19b4eda3623b.jpg)
![zwischenablage02](https://cloud.githubusercontent.com/assets/10213037/7960597/156f26b2-0a02-11e5-90b8-f6b3911f4f4c.jpg)

**Comment by JakobGartner** [comment]
Yes, we know.
We broke it and it is being (quickly) rebuilt bottom- up.
Reason: Make it SRS conformal on trackside.
