### ISSUE TITLE
TM_conversions::RECV_ConvertP005afterRead_Element_CT: valid flag set permanently to "true"

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#431]
The valid flag currently is permanently set to true. 
This leads to permanently announcing ghost BGs ahead with inconsistent data in TestBenchExample.etp.

**Comment by JakobGartner** [comment]
Uwe,

yes, this was a “dirty" workaround.

I have just committed a replacement function, Read_P005_ForCalcTrainPos, which is now able to transport 32 sections and reduces them to BG_Types_Pkg::cMaxNoOfLinkedBGs sections.
This operator is translatable.

I now have to test whether it also works with the “old” Story00A generated data. 
I will let you know.

Jakob

**Comment by JakobGartner** [comment]
You also need a fresh Story00A which has also been updated

**Comment by JakobGartner** [comment]
Due to the fact that we need new data type on the input side, the Story00A does NOT yet work with the new operator.
Wait for UtrechtAmsterdam which is already using the new data types.

(Background: The new types are now structurally 100% SRS compliant)
