### ISSUE TITLE
InformationFilter_Pkg::Common::FIFO buffer plugs with 3 BGs

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#432]
Test :
- running TestExample (807dca94e36ee82e738d846f3978d9aeef4da0c1, 05.06.2015) current Story00A_BTM with acceleration = 100 and initialPosition=5400
- Bug Description:
Buffer in Manage_TrackSideInformation_Integration -> InformationFilter -> MessageBuffer -> FIFO
transmitts only the first 3 Balises (364, 365, 366) and the 7th (341). All 3 Balises in the middle (367,368,369 are blocked. The Problem seams to result from the case that the buffer is limited to 3 entries (SRS conform), but the next_entry variable, which defines the position in the buffer, can reach values up to 6.

**Comment by BerndHekele** [comment]
I did a test on that issue.
I can see a bug in the handling of the buffer in the information filter.
A message from the buffer in the cycle after having received the bg.

kr
Bernd

**Comment by BerndHekele** [comment]
Second error in the same scenario at BG368, B369 and BG341: balise is kept in buffer without reason.

**Comment by astante** [comment]
The problem should be fixed in 6203870896f084cc3733f4bf21a229afc8e8e4e3. and 190f38db1a7b3073abf9b35e2afe44db6a5898c1. I am not able to test it with the TestBenchExample due to errors in that model. As long as it is not expected that messages are written into the transission buffers it should work (transition buffers are currently not finished #280)

**Comment by BerndHekele** [comment]
Dear Jan,

Correction is verified in testexample model.
Solution is availabvle.
Please, start your acceptance test and close the issue after verification.

kr
Bernd

**Comment by BerndHekele** [comment]
Jan,
can you close this issue?

**Comment by janWelte** [comment]
done
