### ISSUE TITLE
Manage_TracksideInformation_Integration: BG 364 reported after passing BG 366

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#435]
While running TestBenchExample: ManageTrackSideInformation_Integration: InformationFilter with

    acceleration = 100.0 and
    initialPosition = 5400.0

in clock cycle 4922 BG 364 is reported to be passed again (BG 364 is the first BG on the track).

**Comment by janWelte** [comment]
This is due to the problem with the filter function see #432
