### ISSUE TITLE
TestBenchExample: BG 367 missed (not found within its expectation window) 

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#436]
While running TestBenchExample: ManageTrackSideInformation_Integration: InformationFilter with

acceleration = 100.0 and
initialPosition = 5400.0

in clock cycle 4067 calculateTrainPosition raises the error flag "linkedBGMissed", because the expectation window for BG 367 has been passed without detecting it.  

The symptom might be affected by #434, therefore #434 should be fixed first before analyzing the cause.

**Comment by janWelte** [comment]
This points are are comming from #432 als this error blocks the reporting of Balises 367, 368 and 369, due to the buffer behavior

**Comment by UweSteinkeFromSiemens** [comment]
Replaced by #911.
