### ISSUE TITLE
SCADE documentation Model and Levels

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#438]
Dear @BerndHekele , @BaseliyosJacob ,

could one of you please generate the SCADE documentation for the Level component? The current version at 
modeling/model/Scade/System/ObuFunctions/ManageLevelsAndModes/Levels 
does not contain screenshots of the model. I need this document to discuss an interface between Levels and Provide Position Report with Matthias Guedemann.
Thanks in advance,
Christian

**Comment by BerndHekele** [comment]
Hi Christian,
you can find the document here:
https://github.com/openETCS/modeling/blob/master/openETCSDesignDocuments/thirdIteration/ModesAndLevels.docx

cu
Bernd
