### ISSUE TITLE
InfraLib::Send_P005 does not exist any more

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#443]
The function InfraLib::Send_P005, used in AmsterdamUtrechtL1::Sheet06_Bijlmer::Packets_BG364_00A/ does not exist any more and prevents code generation for the TestBenchExample. 

Ref.: #434, #319.

**Comment by JakobGartner** [comment]
This was fixed  with 05e1e62

**Comment by UweSteinkeFromSiemens** [comment]
The fix did not succeed. Are you aware, that InfraLib.xscade exists twice? :  
- \modeling\model\Scade\System\TracksideDynamicModel\BaliseLib\InfraLib.xscade
- \modeling\model\Scade\System\BaliseLib\InfraLib.xscade

**Comment by JakobGartner** [comment]
Hmm

I have cleaned up a bit (and removed the old defunct BaliseLib) but on my PC Story00A is working.

Bernd has seen it too …

Recommitted all relevant projects.

**Comment by UweSteinkeFromSiemens** [comment]
Now, code generation is successfull.
