### ISSUE TITLE
Connect MRSP to balise channel, add functionality for SSP construction 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#449]
in TrackAtlas, build MRSP from life track data

**Comment by JakobGartner** [comment]
done for Packet 27 (baseline 2)

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V
