### ISSUE TITLE
Level Transion on Start of Mission

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#455]
@MariellePetitDoche @mgudemann 

Dear Marielle,
we need to trigger a level transition / level initialisation after leaving mode  No Power.
To my knowledge, this is based on the level which was in use at end of mission?

I do not see an appropriate input in level management. (you use a fixed value Level_0 instead).
How did you plan this level initialisation to be entered to the evc?

thanks
Bernd

**Comment by MariellePetitDoche** [comment]
Indeed for the moment the default value is L0.

ETCS Level is one of the information stored on board (§5.4.2.2). How are managed the information stored on board ?
In my point of view, the best solution is a function to manage storage of all the information listed, and use of this data as input of the other functions  at start of mission.

**Comment by MariellePetitDoche** [comment]
We need to clarify how are managed stored information.
Can I consider stored level as an input of my function ?

**Comment by BerndHekele** [comment]
The assumption is correct. We do read stored date from a store at power up. This information includes the last level in use at end of mission (in our scenario ntc would be the correct setting).
In this interface I get also information about levels available in the evc.

.

**Comment by BerndHekele** [comment]
Done.
