### ISSUE TITLE
trackmessages.etp

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#458]
Dear Jakob,
when opening the project for trasfering files to the V16 format I recognised some consistency problems in the files.

I keep them untouched in order not to spoil the files.

Pleasecheck if something is missing and switch to the new format yourselves.

kr
Bernd

**Comment by BerndHekele** [comment]
I also skipped the trackatlas and UtrechtAmsterdam for now.
I'm aware you are active over the weekend.
Can you please take care you save those projects in R16?

**Comment by JakobGartner** [comment]
yes I will save them before monday in R16

**Comment by BerndHekele** [comment]
done
