### ISSUE TITLE
Discussion on triggering radio based Track-to-Train messages in RBC model

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#460]
According to the JRU data from Utrecht - Amsterdam (see file JRU_DATA_Amsterdam_Utrecht.xlsx), some special cases exist that concern the LRBG of a train. Looking e.g. at the cells 2249 - 2594, it can be seen that the RBC sends two movement authorities to the train with a reference to the same LRBG 362 (NID_LRBG=362). 

Triggering seems not so easy because it is tried to model a dynamic situation, which is in reality managed by an interlocking, with static JRU data. From my point of view, NID_LRBG seems not to be enough as a trigger condition (see the special case above). I think that the trigger condition must be refined with the additional information of the distance to the LRBG (D_LRBG).

For a better understanding, I provided a small sequence diagram that tries to show the situation. I hope that it can be used as basis for discussion.

@BaseliyosJacob 
@BerndHekele 
@JakobGartner 
@mairamou 

![conceptualtriggersequencediagram](https://cloud.githubusercontent.com/assets/10213037/8156482/4f34ac10-134d-11e5-9500-80f66837e64a.png)

**Comment by JakobGartner** [comment]
this is done.
