### ISSUE TITLE
TrackMessages and BaliseLib/ InfraLib: Support for multiple packets with same NID_PACKET

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#469]
@JakobGartner 

When building the test tracks, the following cases were encountered:

- several packets are sent >1 time per message. Examples: P42, P65 

We need a universal solution for this. TrackMessages library should be able to transmit such multiple packets.

**Comment by JakobGartner** [comment]
The solution consists of adding virtual NID_PACKET functions (as done for P27).

The effort is about 1h per packet.

This will be needed for all packets in the long term (to support different Q_DIR values)

**Comment by JakobGartner** [comment]
For now, we see 3 packets on the track that need this support for the US.

**Comment by JakobGartner** [comment]
This is done with the related commit (see below).

We now have support for multiple packets of the same type in one message and for different versions (M_VERSION) within the merged message stream.

- transparent support for multiple packets that differ for their Q_DIR
--> the balise/radio channel on the EVC (@BerndHekele) can continue to use the Q_DIR field in the metadata structure for filtering the packets, this concept is not touched 
- transparent support for multiple packets that differ for their ID (for example multiple TSR packets in one message)
--> the balise channel has to do no work at all to handle those multiple instances of the same packet as they are transparent from its point of view (each has a distinct nid_packet)

if you need to extract the real NID_PACKET at any place from a meta data element, please use the access function provided in the TrackMessages library, do not access the raw data directly.

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by JakobGartner** [comment]
this is done of all needed packets in the user stories
