### ISSUE TITLE
procedures.etp:: model does not compile

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#470]
Dear Baseliyos,
the model has at least 2 big issues:
 - interface statusdriverselection should be of a diverent type (maybe M_LEVEL?) and there is an unlinked block in the center of the model: SoM_NTC_SN.
Can you pleasae provide a compilable version of the model?

kr
Bernd

**Comment by BaseliyosJacob** [comment]
New version delitvered on github. Should compile now.

**Comment by BerndHekele** [comment]
ok - thanks.
I recognised the input statusDriverSelection_from_DMI (bool).
What exactly is the function behind this input?

**Comment by BaseliyosJacob** [comment]
Hello Bernd,

the "statusDriverSelection_from_DMI" is a bool at the moment, but should become another value. I expecting here the selection of the Driver. E.g. the driver can select in this case Shunting, None Leaging Mode or Level and Train Data Entry. At this point i expect that the Driver selects to enter the level (NTC in our Case) and next step Train Data Entry.

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

please dont forget that i have an output to Level and Mode Management for "requesting the Change so System National Mode". I havent modelized at the moment the output - just the Trigger. But i need the interface to the Level and Mode Management to trigger it.

**Comment by BerndHekele** [comment]
After todays discussion I'm convinced we need a "levelset by the driver state" in the evc.
I will add this as a part of the upcoming changes.

**Comment by BerndHekele** [comment]
No longer relevant
