### ISSUE TITLE
Testbench_Integration:constants for some DMI-Interfaces missing

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#473]
The model seems to be incomplete. Maybe a file is missing?

![image](https://cloud.githubusercontent.com/assets/3288918/8227854/ad57dfba-15aa-11e5-924a-804ab003ff23.png)

**Comment by BerndHekele** [comment]
@BaseliyosJacob 
Having had a closer look at the issue I recognised the mssing constants vanished from DMI_Control.

**Comment by BaseliyosJacob** [comment]
Hello Bernd,

this interfaces are not connected at the moment since i missing the data package from the DMI Controller.
As soon i have the data package i will connect it and the error should disappear.

**Comment by BerndHekele** [comment]
Dear Stefan,
I analysed the issue.
Root cause is some outdated references in the Integration model.

I have a compilabvle - but not a building - version on my PC.
Is it ok for you if I overwrite the model with the corrections or do you prefer to use your own copy?

**Comment by stefan-karg** [comment]
Dear Bernd,

you can overwrite the version. I will just pull from the github once you are done.
