### ISSUE TITLE
Inconsistencies in conversion operators in TrackMessages.etp

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#474]
Hi @JakobGartner and @mairamou!

I found several small inconsistencies in the conversion operators in TrackMessages.etp

TM_conversions::CAST_D_SECTIONTIMERSTOPLOC_to_int
TM_conversions::CAST_L_MAMODE_to_int
TM_conversions::CAST_L_STOPLX_to_int
TM_conversions::CAST_L_TEXTDISPLAY_to_int
TM_conversions::CAST_L_TRAININT_to_int
TM_conversions::CAST_L_TSR_to_int
TM_conversions::CAST_M_LOC_to_int
TM_conversions::CAST_M_MCOUNT_to_int
TM_conversions::CAST_NID_PRVLRBG_to_int
TM_conversions::CAST_Q_CONFTEXTDISPLAY_to_int
TM_conversions::CAST_T_ENDTIMER_to_int
TM_conversions::CAST_T_OL_to_int
TM_conversions::CAST_T_TRAIN_to_int
TM_conversions::CAST_T_VBC_to_int
TM_conversions::CAST_V_LOA_to_int
TM_conversions::CAST_V_MAMODE_to_int
TM_conversions::CAST_V_MAXTRAIN_to_int
TM_conversions::CAST_V_NVSTFF_to_int
TM_conversions::CAST_V_NVUNFIT_to_int
TM_conversions::CAST_V_RELEASEDP_to_int
TM_conversions::CAST_V_RELEASEOL_to_int
TM_conversions::CAST_V_REVERSE_to_int
TM_conversions::CAST_V_STATIC_to_int
TM_conversions::CAST_V_TRAIN_to_int
TM_conversions::CAST_V_TSR_to_int

These operators should all return an integer value.

=======================================================================

Semantic errors, i.e., that the operators have an inconsistent naming according to your applied patterns:

TM_conversions::CAST_Int_to_Q_TEXTREPORT (should be CAST_Q_TEXTREPORT_to_int)
TM_conversions::CAST_Q_VBCO_to_int (should be CAST_Int_to_Q_VBCO)
TM_conversions::CAST_Q_TRACKINIT_to_int (should be CAST_Int_to_Q_TRACKINIT)
TM_conversions::CAST_Q_TEXTREPORT_to_int (CAST_Int_to_Q_TEXTREPORT)

**Comment by JakobGartner** [comment]
Thanks

I will go through it





On 18.06.2015, at 14:06, Alexander Probst <notifications@github.com> wrote:

Hi @JakobGartner <https://github.com/JakobGartner> and @mairamou
<https://github.com/mairamou>!

I found several small inconsistencies in the conversion operators in
TrackMessages.etp

TM_conversions::CAST_D_SECTIONTIMERSTOPLOC_to_int
TM_conversions::CAST_L_MAMODE_to_int
TM_conversions::CAST_L_STOPLX_to_int
TM_conversions::CAST_L_TEXTDISPLAY_to_int
TM_conversions::CAST_L_TRAININT_to_int
TM_conversions::CAST_L_TSR_to_int
TM_conversions::CAST_M_LOC_to_int
TM_conversions::CAST_M_MCOUNT_to_int
TM_conversions::CAST_NID_PRVLRBG_to_int
TM_conversions::CAST_Q_CONFTEXTDISPLAY_to_int
TM_conversions::CAST_T_ENDTIMER_to_int
TM_conversions::CAST_T_OL_to_int
TM_conversions::CAST_T_TRAIN_to_int
TM_conversions::CAST_T_VBC_to_int
TM_conversions::CAST_V_LOA_to_int
TM_conversions::CAST_V_MAMODE_to_int
TM_conversions::CAST_V_MAXTRAIN_to_int
TM_conversions::CAST_V_NVSTFF_to_int
TM_conversions::CAST_V_NVUNFIT_to_int
TM_conversions::CAST_V_RELEASEDP_to_int
TM_conversions::CAST_V_RELEASEOL_to_int
TM_conversions::CAST_V_REVERSE_to_int
TM_conversions::CAST_V_STATIC_to_int
TM_conversions::CAST_V_TRAIN_to_int
TM_conversions::CAST_V_TSR_to_int

These operators should all return an integer value.

Semantic errors, i.e., that the operators have an inconsistent naming
according to your applied patterns:

TM_conversions::CAST_Int_to_Q_TEXTREPORT (should be
CAST_Q_TEXTREPORT_to_int)
TM_conversions::CAST_Q_VBCO_to_int (should be CAST_int_to_Q_VBCO)
TM_conversions::CAST_Q_TRACKINIT_to_int (should be CAST_int_to_Q_TRACKINIT)
TM_conversions::CAST_Q_TEXTREPORT_to_int (CAST_int_to_Q_TEXTREPORT)

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/474>.

**Comment by JakobGartner** [comment]
Hello Alexander,

thank you very much for your peer review. 
This was addressed in 4dc55ee <https://github.com/openETCS/modeling/commit/4dc55eeaee673c334120aabc6f3f838c26d9d675>



> On 18 Jun 2015, at 14:06, Alexander Probst <notifications@github.com> wrote:
> 
> Hi @JakobGartner <https://github.com/JakobGartner> and @mairamou <https://github.com/mairamou>!
> 
> I found several small inconsistencies in the conversion operators in TrackMessages.etp
> 
> TM_conversions::CAST_D_SECTIONTIMERSTOPLOC_to_int
> TM_conversions::CAST_L_MAMODE_to_int
> TM_conversions::CAST_L_STOPLX_to_int
> TM_conversions::CAST_L_TEXTDISPLAY_to_int
> TM_conversions::CAST_L_TRAININT_to_int
> TM_conversions::CAST_L_TSR_to_int
> TM_conversions::CAST_M_LOC_to_int
> TM_conversions::CAST_M_MCOUNT_to_int
> TM_conversions::CAST_NID_PRVLRBG_to_int
> TM_conversions::CAST_Q_CONFTEXTDISPLAY_to_int
> TM_conversions::CAST_T_ENDTIMER_to_int
> TM_conversions::CAST_T_OL_to_int
> TM_conversions::CAST_T_TRAIN_to_int
> TM_conversions::CAST_T_VBC_to_int
> TM_conversions::CAST_V_LOA_to_int
> TM_conversions::CAST_V_MAMODE_to_int
> TM_conversions::CAST_V_MAXTRAIN_to_int
> TM_conversions::CAST_V_NVSTFF_to_int
> TM_conversions::CAST_V_NVUNFIT_to_int
> TM_conversions::CAST_V_RELEASEDP_to_int
> TM_conversions::CAST_V_RELEASEOL_to_int
> TM_conversions::CAST_V_REVERSE_to_int
> TM_conversions::CAST_V_STATIC_to_int
> TM_conversions::CAST_V_TRAIN_to_int
> TM_conversions::CAST_V_TSR_to_int
> 
> These operators should all return an integer value.
> 
> 

They all did return an integer value technically as the types they return are integers, however this was indeed a completion error. Fixed.

> Semantic errors, i.e., that the operators have an inconsistent naming according to your applied patterns:
> 
> TM_conversions::CAST_Int_to_Q_TEXTREPORT (should be CAST_Q_TEXTREPORT_to_int)
> 
The two operators were mixed up -> int should have been -> Q_TEXTREPORT and vv.
> TM_conversions::CAST_Q_VBCO_to_int (should be CAST_int_to_Q_VBCO
> 
This was a copy/paste and completion error. Fixed- 

> TM_conversions::CAST_Q_TRACKINIT_to_int (should be CAST_int_to_Q_TRACKINIT)
> 
The two operators were mixed up -> int should have been -> Q_TRACKINIT and vv.

> TM_conversions::CAST_Q_TEXTREPORT_to_int (CAST_int_to_Q_TEXTREPORT)
> 
> —
> 

see above, fixed-
