### ISSUE TITLE
Error "Type mismatch" at Manage_TrackSideInformation_Integration/_L14

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#484]
As I try to run the current version of TestBenchExample is get the following error:
Type mismatch at Manage_TrackSideInformation_Integration_Pkg::Manage_TrackSideInformation_Integration/_L14=

with the following detailed hind:
(arity is 5 instead of 6)

It seams to be a problem at the radio intergration, but it makes it implosible for me to run.

**Comment by BerndHekele** [comment]
we had some work on the input channel - especially with the information filter.
Therefore, we needed som adjustments at the interfaces.
You probably need to take the up-to-date model both - for test environment and for the model.

**Comment by janWelte** [comment]
New interface has been adopted.
