### ISSUE TITLE
Wrong Balise Header in Balise AmsterdamUtrechtL1::Sheet06_Bijlmer::Balise_366_0/

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#485]
The Balise Balise_366_0 in  AmsterdamUtrechtL1::Sheet06_Bijlmer::Balise_366_0/ has the Header BG_365_header_B0 included as Parameter.

**Comment by JakobGartner** [comment]
done

**Comment by janWelte** [comment]
Checking the current Story00A, I recognized that the error is not corrected here. It has been corrected in AmsterdamUtrechtL24.xscade but not in AmsterdamUtrechtL1.xscade, where  Story00A takes its data from.

**Comment by JakobGartner** [comment]
ok now

**Comment by janWelte** [comment]
Perfect. Thanks.
