### ISSUE TITLE
US-sending of EVC Messages to RBC

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#486]
if the RBC-version is older than EVC-Version. The messages from EVC to RBC should be adapted to the RBC-version.

**Comment by BaseliyosJacob** [comment]
testing phase of the model

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by Farhangi** [comment]
This topic is now obsolete.
RBC connection will be established.for US7; US8; US9; US10; US12

The termination of RBC has not yet been implemented and is still open.
