### ISSUE TITLE
US-OBU-SysML-Model Prio: tbd

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#489]
As a software architect or validator I want to have SysML models for the openETCS OBU components, which are linked to the corresponding SCADE components and allow hierarchical navigation through the OBU model.

**Comment by mahlmann** [comment]
Relates to openETCS/product-backlog#66 and openETCS/product-backlog#71 
SysML models are also urgently needed for the ADD document, i.e. D3.5.2. 

A SysML model for a select component will be created to serve as an example. Details will follow as soon as the example model is available.

**Comment by mahlmann** [comment]
Brief update: According to Esterel Support linking of SCADE System (SysML) models and corresponding SCADE Suite models is currently not possible. We are looking for a work around.

**Comment by mahlmann** [comment]
A first set of example SysML models can be found at https://github.com/openETCS/modeling/tree/master/model/sysml/WP3ThirdIteration

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V
