### ISSUE TITLE
In structured type TM_baseline2::P072V1_trackside_int_T/ definition has wrong ref to the type identifier X_TEXT_trackside_T/

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#492]
As I tried to use MessageLibBaseline2::Send_P072V1/
I got the error that the structured type TM_baseline2::P072V1_trackside_int_T/ used in this error has an undefined element type as it referes to the wrong type identifier X_TEXT_trackside_T/. The correct reference would be TM::X_TEXT_trackside_T/.

Could you please change this problem, so I can add packets to my test track balises. Thanks

**Comment by JakobGartner** [comment]
done

**Comment by janWelte** [comment]
thanks
