### ISSUE TITLE
Committer Vote for Stefan Karg

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#503]
I want to propose Stefan to become a committer for the modelling team.

Please, support me in this porposal with a quick and clear vote.

@openETCS/modeling-committers 

Kind Regards
Bernd

**Comment by BenjaminBeichler** [comment]
+1

**Comment by JakobGartner** [comment]
I fully agree


Jakob

**Comment by christianstahl** [comment]
+1

**Comment by astante** [comment]
+1

**Comment by Farhangi** [comment]
+1

**Comment by BerndHekele** [comment]
+1
I close this issue.
Welcome Stefan as a committer of WP3.
