### ISSUE TITLE
DMI_Control_Pkg: Level selection woindow freezes.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#511]
Route cause is the missing concept of loca storage by the DMI_Control for the level list.

**Comment by JakobGartner** [comment]
Level priority lists from p41 and p46 are in progress inside the
TrackAtlas.
They are permanently maintained .

We should coordinate to make sure we only do it once and in a consistent
way.



On 2 juil. 2015, at 10:35, Bernd Hekele <notifications@github.com> wrote:

Route cause is the missing concept of loca storage by the DMI_Control for
the level list.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/511>.

**Comment by BerndHekele** [comment]
Hi,
just to avoid confusion: this issue is about the functionality outside the EVC.
It is not related to the track atlas.

**Comment by BerndHekele** [comment]
Workaround is available.
I reduce the priority on the issue.

**Comment by JakobGartner** [comment]
you have de-confused me, thanks

**Comment by BaseliyosJacob** [comment]
@BerndHekele I think this can be closed after last week release

**Comment by BerndHekele** [comment]
Solution works.
Thanks
