### ISSUE TITLE
Provide status of models in the overview on Github

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#514]
WP4 needs an input on the Status of the projects.
Proposal is to have an indication of the status in the overview on Github..

Keywords could be (for discussion):
 - in work
 - ready for integration
 - interfaces frozen
 - model frozen

The states have to be seen in the context of an iteration.
Changing the status might need acceptance by the project team (WP4 + WP3)

Please, feel free to comment.

@MarcBehrens

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
The description is available in the wiki.
I close this issue.
