### ISSUE TITLE
Committer Vote for Thorsten Schulz (URO)

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#518]
@T12z 

Dear Partner,
I want to prpose Thorsten to become a committer.
He has been active in supporting our team already since beginning of the year.

Please, support this request in giving him a quick positive response.

kr
Bernd

**Comment by BenjaminBeichler** [comment]
+1

**Comment by JakobGartner** [comment]
+2

**Comment by christianstahl** [comment]
+1

**Comment by stefan-karg** [comment]
+1

**Comment by BerndHekele** [comment]
Welcome Thorsten in the team.
