### ISSUE TITLE
Change of content of the field "NID_PACKET" in the Metadata 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#523]
@BerndHekele 

We are sharing the type Common_Types_Pkg::MetadataElement_T.

I am already using the field NID_PACKET for transport of complex packets (like P27) in a more rich way: this packet is encoded using multiple sets of metadata entries (1 for the body, 1 for each 1st level iteration).

From the next release of TrackMessages, this kind of encoding will be massively extended.
This data field will then be used by the write and read functions to enable sending and receiving multiple packets of the same type within one message, as well as for ensuring correct decoding of a mixed stream of baseline2 and baseline3 (and in the future also other versions) of packets within the same stream. This may be necessary as mix between of baseline 2 and baseline 3 on balise and radio levels, respectively, is allowed.
The system will also be used to transport P65 which can occur multiple times within one message, and to allow for different packets according to Q_DIR.

I am assuming that your model does not require to inspect NID_PACKET directly.
If however you need to do so, don't access the raw data but use the TrackMessages access function TM::T_extract_nid_packet_from_metadata to get the NID_PACKET value from the metadata.

Please note that you need NO special treatment for P65 from your side as each instance of this packet within the metadata will have its unique identifier inside the NID_PACKET field. 

I am assuming that you use the field Q_DIR to filter the packets according to the balise orientation.

**Comment by BerndHekele** [comment]
Hi Jakob,
we are using NID_PACKET according to the SRS as an int. If you want to extend the metadat we need to find a different solution. Maybe you can show your proposal in a small meeting.

**Comment by JakobGartner** [comment]
NID_PACKET is an int (the type is unchanged) but the value carries is now a longer int.

If you need direct access to the NID_PACKET, I propose to add another field.
We can do a meeting today ify ou want (in your later afternoon)

Jakob

**Comment by BerndHekele** [comment]
The information about the packet id is needed in the information filter.
Alexander makes use of the simple "conversion" - that can be solved with a simple mapping function.
Peyman has to handle packets for TSR special.

So, we have an impact but we can agree on the proposed changed.

cu
Bernd.

**Comment by JakobGartner** [comment]
In order to clarify a bit how the metadata are now built, with a focus on TSR

Each packet is encoded using the following fields:

AAABCCDDD

AAA= NID_PACKET raw (1-255)
B= Q_DIR  (encoded according to SRS)
CC= M_VERSION (encoded according to SRS)
DDD= unique ID


This is needed in order to 

- be able to transport two packets in case they are defined for different Q_DIRs (in the metadata, they need to be unique)
- be able to transport more than one packet per NID_PACKET (like for packet 65). Please note that two complete sets of TSR information (multiple NID_TSR per Q_DIR) may be possible
- be able to transport complex packets with 2 levels of iterations (these are split into virtual packets)

To take the example of packet 27 (SSP), this may look like this:

As an example, there might be 

- 1 P27 for nominal
- 1 P27 for reverse

- The P27 for nominal has N_ITER=12 for the 1st level iterator
- The P27 for reverse has N_ITER=10 for the 1st level iterator
- We have M_VERSION=16 (version 1.0)

The metadata entries will look like this:

27016000 (virtual packet for the “body” of the packet) for Q_DIR=0
27016100 (virtual packet for the 1st iterated section of the SSP; the unique ID is 100 where 1 stands for the 1st iteration level and 00 is the N_ITER of this section)
27016101 (virtual packet for the 1st iterated section of the SSP; the unique ID is 100 where 1 stands for the 1st iteration level and 01 is the N_ITER of this section)
….
27016111 (the last iteration)

For Q_DIR= 1 this will look similar but with 27116000 and so on.

In my understanding, Alexander should have no special treatment per packet ID. He just needs to know that there is a unique packet and to which message it belongs (I may be wrong…).
So when for example we have a relevant Q_DIR=1 he must remove all packets that don’t match this current Q_DIR.
Or if a message is rejected for a specific reason, he must remove all packets that belong to that message.

If I am right, then there is nothing more to do.
If Alexander needs more specific information about the packet ID, I must understand which exactly so that I can provide a matching API function (I prefer an API concept so that we don’t get disrupted if this concept needs to be further developed for example when we get to baseline 4 :-)

For the TSR, it is similar.

Each TSR has its *own* virtual packet.

Let’s take the example that we have, within one message 3 

- 5 revocable TSRs with the NID_TSR 0,1,2,3,4
- 1 non- revocable TSR
- we only get them for 1 Q_DIR=1
- we are on baseline 3 (M_VERSION=32)

The metadata look like this:

65132000 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=0)
65132001 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=1)
65132002 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=2)
65132003 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=3)
65132004 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=4)
65132255 (TSR with Q_DIR=1, M_VERSION=32, and NID_TSR=255, non- revocable TSR)

Which means that from point of view of building a BG or filtering, this should be totally transparent and there is no need at all to inspect the NID_PACKET, as each TSR has its own unique identifier.

Again, if you need to access any information from this meta-id let me know so that you get the right API function quickly.


Of course, all the functions to read a packet after it has passed the input track to train channel are reassembling the information back to a SRS conformal format with the raw NID_PACKET and a valid flag being the first fields of the data structure, and they will also do the steps as needed to build onboard information also from older M_VERSION tracks and can handle different M_VERSION on the balise and radio channels transparently 






Jakob

**Comment by BerndHekele** [comment]
I would like to have an operator  translating your  definition into the relevant components.
We will use this operator wherever we need to know about the packet id or the version.

The input functions sometomes need to work on the packet-id.

**Comment by JakobGartner** [comment]
This is done with commit 7a1ec13

TM::T_decode_metadata_selector: gives nid_packet, m_version, and the unique packet identifier.
TM::T_extract_nid_packet_from_metatdata_selector: gives only nid_packet (but take care, it refers to the "mother" nid_packet, which means that for virtual packets (for packets that are split across multiple metadata entries) it also refers to the nid_packet of the original packet)

**Comment by BerndHekele** [comment]
Thanks.

**Comment by BerndHekele** [comment]
@Farhangi 
Hi Peyman,
can you please also confirm the changes in the CheckBG when it is done?

**Comment by Farhangi** [comment]
In the module CheckBG, NID_PACKET's will be compared, therefore the change has no effect here.
