### ISSUE TITLE
Scope of version information on the track

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#524]
Hello,

@BaseliyosJacob @janWelte @MarcBehrens:
as the track model is now done I will continue to work on improvements, even if now I concentrate on new issue.
We support at the moment the baseline2 information found on the track, but I am tasked to refine that to being able to process any baseline, even if for Amsterdam- Utrecht this only means to restructure the existing functionality in a more clean way. 

I am not sure if I understand the SRS very well:

To take the example:

M32 gives me the information on the version the RBC is using. How long does it stay valid? Until I get a new NID_RBC? A new NID_C? A new M32?

The balise headers give me the information on the version this balise group is using only? Or does it have a longer persistence?

Thanks

@BerndHekele : do you maintain the currently valid version information somewhere ?

@JakobGartner : This could mean some impact on TrackMessages and Data Management

**Comment by aprobst** [comment]
Hello Mairamou,

the sending of message 32 with the RBC version is part of the session establishment process between train and RBC. It is always sent after the RBC receives message 155 (Initiation of a communication session) from the train. It stays valid for the train while the session is established.

See also Subset-026 §3.5.

**Comment by MarcBehrens** [comment]
Hello Mairamou,
are you looking for the validity of the version related to:

- trackside layout or
- information about trackside layout kept on-board?

**Comment by janWelte** [comment]
Hallo Mairamou,

thank you for your work. I've to admit I'm not filly understanding your question. 

All versions communicated by the track are only there to inform the on-board unit about the version use by the respective track object. Therefore the version is only valid for the communication with this respective track object. 

Best regards

Jan

-----Ursprüngliche Nachricht-----
Von: Mairamou Haman Adji [mailto:notifications@github.com] 
Gesendet: Samstag, 4. Juli 2015 12:58
An: openETCS/modeling
Cc: Jan Welte
Betreff: [modeling] Scope of version information on the track (#524)

Hello,

@BaseliyosJacob <https://github.com/BaseliyosJacob>  @janWelte <https://github.com/janWelte>  @MarcBehrens <https://github.com/MarcBehrens> :
as the track model is now done I will continue to work on improvements, even if now I concentrate on new issue.
We support at the moment the baseline2 information found on the track, but I am tasked to refine that to being able to process any baseline, even if for Amsterdam- Utrecht this only means to restructure the existing functionality in a more clean way. 

I am not sure if I understand the SRS very well:

To take the example:

M32 gives me the information on the version the RBC is using. How long does it stay valid? Until I get a new NID_RBC? A new NID_C? A new M32?

The balise headers give me the information on the version this balise group is using only? Or does it have a longer persistence?

Thanks

@BerndHekele <https://github.com/BerndHekele>  : do you maintain the currently valid version information somewhere ?

@JakobGartner <https://github.com/JakobGartner>  : This could mean some impact on TrackMessages and Data Management

**Comment by BaseliyosJacob** [comment]
Hello Mairamou,

you have to consider that

- the RBC can have another version
- the balise can have another version
- the Onboard Unit can have another version

The Onboard Unit hast to cope with the balise and RBC version. That means that the OBU version needs always to be at least equal or higher than the balise or RBC version.

**Comment by mairamou** [comment]
Hello Mr. Jacob, 

yes, this was the reason for my question. 

Our concept is that we have a baseline 3 onboard unit and that we
translate up and down for tracks with older version. 

My question is : how to know when to need to translate or not. 

It is more a question of general ETCS understanding. 

I hear that I will get some "training" from Mr. Behrens. 

Merci 

Mairamou 

On 2015-07-07 04:34, Baseliyos Jacob wrote: 

> Hello Mairamou, 
> 
> you have to consider that 
> 
> * the RBC can have another version
> * the balise can have another version
> * the Onboard Unit can have another version
> 
> The Onboard Unit hast to cope with the balise and RBC version. That means that the OBU version needs always to be at least equal or higher than the balise or RBC version. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/524#issuecomment-119104592

**Comment by MarcBehrens** [comment]
Hello Mairamou,

concerning the versioning of ETCS there are several additional specifications which e.g. focus on avoiding additional investments in migration scenarios mixing balise and radio of different versions.

So it is important to understand some basic principles:
- The trackside sends its version via M_VERSION either via radio Message 32 or balise header.
- The onboard side decides if it can safely operate with the information


from the perspective of the radio session:
- the M_VERSION should stay valid for the session RBC ETCS identity 

from the view of trackside layout:
- plainly communicates it's M_VERSIONS via RBC and Balise
- the session and the information, that the version is accepted on-board, comes with the radio message 159


from onboard perspective:
- the OBU still needs to remember the last successful connection in order to:
  * build up a communication session (SRS 3.5.3.4ff)
  * contact the last known RBC (SRS 7.5.1.96)
- while having mixed incompatible version areas (balise and radio) the non-RBC M_VERSION does not change the operated system version (SRS 3.17.2.7)

I hope this answert most of the questions, in case of open points, do not hesitate to ask.

Best regards,
Marc



SRS - refers to SUBSET-026 v3.3.0 of the TSI-CCS

**Comment by mairamou** [comment]
Thank you very much, Mr. Behrens! 

This is a very helpful overview 

Mairamou 

On 2015-07-07 06:33, Marc Behrens wrote: 

> Hello Mairamou, 
> 
> concerning the versioning of ETCS there are several additional specifications which e.g. focus on avoiding additional investments in migration scenarios mixing balise and radio of different versions. 
> 
> So it is important to understand some basic principles: 
> 
> * The trackside sends its version via M_VERSION either via radio Message 32 or balise header.
> * The onboard side decides if it can safely operate with the information
> 
> from the perspective of the radio session: 
> 
> * the M_VERSION should stay valid for the session RBC ETCS identity
> 
> from the view of trackside layout: 
> 
> * plainly communicates it's M_VERSIONS via RBC and Balise
> * the session and the information, that the version is accepted on-board, comes with the radio message 159
> 
> from onboard perspective: 
> 
> * the OBU still needs to remember the last successful connection in order to: 
> 
> * build up a communication session (SRS 3.5.3.4ff)
> * contact the last known RBC (SRS 7.5.1.96)
> 
> * while having mixed incompatible version areas (balise and radio) the non-RBC M_VERSION does not change the operated system version (SRS 3.17.2.7)
> 
> I hope this answert most of the questions, in case of open points, do not hesitate to ask. 
> 
> Best regards,
> Marc 
> 
> SRS - refers to SUBSET-026 v3.3.0 of the TSI-CCS 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/524#issuecomment-119137103

**Comment by JakobGartner** [comment]
As this track is released, I close this issue now... and the question has been answered
