### ISSUE TITLE
Cleanup of Models: BaliseRadioLocation

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#526]
Can we delete the following model:
https://github.com/openETCS/modeling/tree/master/model/Scade/System/OBU_PreIntegrations/BaliseRadioLocation

Please, do so if no longer used.

**Comment by stefan-karg** [comment]
Dear Bernd,

this depends if we still want to keep the Testbench_Suite model up on the repository. If we want to keep it, we also need the BRL-integration model. Otherwise we can delete it from my point of view, since the sub-modules are meanwhile integrated in the new EVC-model.

**Comment by BerndHekele** [comment]
We are progressing well with the test model.
Therefore, we should clean it now.
