### ISSUE TITLE
Shunting will not display on DMI when Menu is approaching

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#530]
Description will follow

**Comment by BerndHekele** [comment]
The mode is visible now but not selectable.
![image](https://cloud.githubusercontent.com/assets/3288918/8565902/1b069952-255a-11e5-93ee-2a6e37fba5fd.png)

We can check on the correct flow in a common session.

**Comment by BaseliyosJacob** [comment]
Dear Bernd, i think this issue has now not a high priority. I am working at the moment on another issues with higher priority.

**Comment by BaseliyosJacob** [comment]
I assume this can be closed after last week release.
