### ISSUE TITLE
Radio_TrackTrain_Header_T: extension with NID_C and NID_RBC required

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#536]
NID_C and NID_RBC - making up the RBC ID - are not part of Radio_TrackTrain_Header_T. Therefore, the source RBC is not identifiable. The radioDevice field is not unambiguous, since the same radioDevice will subsequently be used with different RBCs.  

Please add NID_C and NID_RBC to Radio_TrackTrain_Header_T.

**Comment by BerndHekele** [comment]
Hi Uwe,
in order to do so I want to clarify some questions:

How is the data flow for this information?   
Is the information added by the RTM (e.g., in addition to the radio dévice?

**Comment by UweSteinkeFromSiemens** [comment]
In the same way as the for the balise datagrams (NID_C and NID_BG), NID_C and NID_RBC identify the source address of the RBC. At least the safety layer needs such kind of information for authentification anyway.  Since NID_C and NID_RBC are not part of telegram header as specified in subset-026, 8.4.4.6.1 (a severe specification bug from my point of view), this information has to be added by the RTM. 
In the model, NID_C and NID_BG are required to identify the source of a radio datagram, because the data streams of both active RBCs have been merged from the API.

**Comment by BerndHekele** [comment]
I agree with your analysis. I would like to keep it out of the header but close to it.
When do you need the information? Since it is an change in the interfaces we will have some side effects.

**Comment by UweSteinkeFromSiemens** [comment]
It is required asap.

**Comment by Farhangi** [comment]
Since the RBC messages are part of a RBC session, and the information (as NID_C and NID_RBC)  is during the session establishment and  the session available.(Packet 42 )
Can we take the information from the session?

**Comment by JakobGartner** [comment]
NID_BG can change with every message. We have to take it from the messages .

In TrackMessages I have defined new trackside types. I propose to discuss
Wednesday


On 13.07.2015, at 16:21, Peyman Farhangi <notifications@github.com> wrote:

Since the RBC messages are part of a RBC session, and the information (as
NID_C and NID_RBC) is during the session establishment and the session
available.(Packet 42 )
Can we take the information from the session?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/536#issuecomment-120944964>.

**Comment by BerndHekele** [comment]
I propose the following definitions:
![image](https://cloud.githubusercontent.com/assets/3288918/8652872/7afa1458-2981-11e5-8253-1ca82bca5e8a.png)

The same type has to be added to the API definition of the messages.
The RTM is responsible for setting the values in the interfaces.

I actually expect from Radio Session Management a list of active RBC's connected to the device id.

The device id is corresponding to the Alstom API definition. 

Just as a remark: we (Uwe and myselves) have an open issue to discuss how the rtm hardware related interfaces should look like.

**Comment by BerndHekele** [comment]
The API interface change:
![image](https://cloud.githubusercontent.com/assets/3288918/8653201/51269794-2983-11e5-9bf6-0d4650026c22.png)

If the definition is fine i will upload the files. It has an impact on API_Types and on Common_Types of the BG-Interface.
@janWelte

**Comment by UweSteinkeFromSiemens** [comment]
If the session management (MoRC) establishes a session, it of course knows the appropriate NID_C and NID_RBC. During RBC-Handover, there can be 2 sessions established concurrently. Due to both receiving the radio datagrams from 2 different RBCs via the same input channel, the input datagrams have to be distinguishable by their source address unambiguously. The deviceID as got from the API is not sufficient because of its transient validity. 
Therefore, NID_C and NID_RBC must be added as source address before the datagrams are routed through the input channel and the subsequent stages, so that the RBC handover function and  the 2 session management instances are able to recognize the source.

**Comment by UweSteinkeFromSiemens** [comment]
sendingRBC_id as proposed must comprise NID_C and NID_RBC. Why not add this information to Radio_TrackTrain_Header_T?

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
I now see compile errors due to the interface change in the following models:
Calculate_Train_Position @UweSteinkeFromSiemens 
MoRC
Manage_Procedures @BaseliyosJacob 

I will make private corrections in my workspace in order to be able to continue.
Please, let me know if you want me to push.
