### ISSUE TITLE
Speed Supervision in Level NTC an Mode SN is not displaying

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#537]
After Start of Mission in Level NTC ATB and Mode SN no Speed Supervision will be displaying on the DMI. The max. speed for NTC ATB is 140 km/h and in train station area 40 km/h. @BenjaminBeichler @T12z you have already an implentation on speed supervision for Level NTC ATB and Mode SN? Thank you very much

**Comment by T12z** [comment]
Nope.The project for implementing ATB has not been grated by the EU :wink: 
Other than that, Supervision shall not really do any supervision in NTC. Or should we?

**Comment by BaseliyosJacob** [comment]
I fully agree. National Systems as ATB are not grated by the EU. But we have to find a solution since we are starting with NTC ATB in Amsterdam train station and end with NTC ATB in Utrecht trainstation. I propose to use a general speed limit of 40 km/h when we are in national system in train station. Is this possible from your side?

**Comment by JakobGartner** [comment]
The National Values provide 40km/h as V_NVONSIGHT, V_NVSTFF and V_NVSHUNT

I propose that we “fake” a bit the mode dependent speed profile by providing this speed also for the mode ATB

Is that somehow reality compliant?

If yes I will implement it 


Jakob

**Comment by BenjaminBeichler** [comment]
Everything we get as MRSP will be supervised, no matter what mode is active, so yes we could do this.

This needs also to be reviewed by modes and levels management people, since they could also brake, when they want and speed supervision will not check mode or level.

**Comment by BaseliyosJacob** [comment]
But we will have the start of mission before the national values. In this case we shoud fake it already in the default of the national values. NTC is always a grey area!

**Comment by BaseliyosJacob** [comment]
@BenjaminBeichler thank you very much for your explanation. You are right this should maybe an input from Mode and Level Management or another cofiguration. It has no effect from the MRSP because it is not ETCS. ETCS is just the Master of the national System. But the train will be supervised by the national system.

**Comment by JakobGartner** [comment]
OK in this case I propose we still do it that way (as we are then in a kind of staff responsible ???

I will read the NS handbook if I find an answer….

**Comment by BenjaminBeichler** [comment]
Another problem I see is that we need a model of the ATB part, if it is interacting with the EVC. Especially brake commands from ATB should be handled by the ETCS EVC somehow. We could provide the same interface as for modes and levels to have a unified braking management in speed supervision, but I don't know whether this goes to far away from what we want.

**Comment by BenjaminBeichler** [comment]
@BaseliyosJacob I know we would not formally need the MRSP, but for supervising the max train speed or max shunting speed, we use the MRSP as the only input, so we need it technically.

**Comment by BaseliyosJacob** [comment]
@BenjaminBeichler but in Level NTC you wont receive a MRSP. Can we fake a fake a MRSP for LEVEL NTC ATB with max. 40 km/h? @JakobGartner 

@JakobGartner i am afraid you wont find a solution for this in the NS Handbook since NTC ATP is a national issue and will be considered in the regular national operatonal rules

**Comment by BaseliyosJacob** [comment]
And the national regular operation rules say 40 km/h max in train station area!! We are considering NTC ATB just within the train station area

**Comment by JakobGartner** [comment]
OK.

Then we have two options:

- we don’t do anything (and consider it outside the system)
- we build a very simple ATB module.


What is a bit ironical is that the national regular operation rules give the same speed as for driver responsible … (which seems to be the objective)

**Comment by T12z** [comment]
Questions have been answered, implementation has been provided by @JakobGartner : The TrackAtlas is currently faking ETCS data (MRSP/MA) from ATB data. SDM thinks it does normal supervision as in ETCS::L2.
There have been follow-up issues, so this issue is stale and I will close.
Thanks contributors for the solution!
