### ISSUE TITLE
BG_Types: incomplete information for Balise errors

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#543]
When passing an incorrect balise the information about the balise group (NID_C and NID_ERRORBG) need to be made available in the system (according to subset 27, section 4.2.4.12

.

**Comment by BerndHekele** [comment]
@Farhangi 
Hi Peyman,
is this implementation complete now in the check?

kr
Bernd

**Comment by Farhangi** [comment]
It is completed now.  https://github.com/openETCS/modeling/commit/66d66335eda5a1b0be4174cc1b239cfc1f216eb7
