### ISSUE TITLE
Committer Vote for Matthieu Poirot (ERSA)

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#546]
@MatthieuPoirot 
@openETCS/modeling-committers 

I want to call for a committer vote for Matthieu Poirot from ERSA.

Your quick feedback is very welcome.

kind regards
Bernd

**Comment by stefan-karg** [comment]
+1

**Comment by Farhangi** [comment]
+1

**Comment by BaseliyosJacob** [comment]
+1

**Comment by JakobGartner** [comment]
+1

**Comment by BerndHekele** [comment]
Thanks for the vote.

Matthieu, welcome in the team
Welcome

**Comment by MatthieuPoirot** [comment]
Thanks to all of you!

Matthieu Poirot
---------------------------------------------------
European Rail Software Applications
5, Rue Maurice Blin
67500 HAGUENAU
France
Tel : (0033) 3 88 07 15 57
Fax : (0033) 3 88 07 15 51
E-mail : matthieu.poirot@ersa-france.com
Internet : http://www.ersa-france.com
---------------------------------------------------
________________________________
