### ISSUE TITLE
SDM does not compile due to renaming of TrackAtlas Types

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#552]
Dear *,
I get errors from SDM modules. Reason is the change of MA type.
Can you please correct.

kr
Bernd

@JakobGartner : can you please coordinate this sort of change?

**Comment by JakobGartner** [comment]
I agree that this change is disruptive.
However we were requested so many times to do a fundamental change here
that expected it to be somehow expected.
In addition this is the first working release of this module that active
integration is anyway needed.




On 13.07.2015, at 12:09, Bernd Hekele <notifications@github.com> wrote:

Dear *,
I get errors from SDM modules. Reason is the change of MA type.
Can you please correct.

kr
Bernd

@JakobGartner <https://github.com/JakobGartner> : can you please coordinate
this sort of change?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/552>.

**Comment by T12z** [comment]
I'm sorry, I tried, but I can't find an easy 1:1 mapping. Naturally there is no diff guiding me along.

There used to be (const) MAMaxSections, which is not referenced any more. A movement authority seems like one section, or will there be many MAs?

This will take more time for me to understand / correct.

**Comment by JakobGartner** [comment]
I think the best way will be a little discussion.
I have proposed this new structure for many reasons (many came from the
open issues ), and was not expecting an integration without a discussion.



On 13.07.2015, at 23:37, Thorsten Schulz <notifications@github.com> wrote:

I'm sorry, I tried, but I can't find an easy 1:1 mapping. Naturally there
is no diff guiding me along.

There used to be (const) MAMaxSections, which is not referenced any more. A
movement authority seems like one section, or will there be many MAs?

This will take more time for me to understand / correct.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/552#issuecomment-121067384>.

**Comment by BerndHekele** [comment]
This is blocking progress on the integration test.
I'm not really pleased with the need for a little discussion..

**Comment by JakobGartner** [comment]
Additional information had been requested. This was not possible without
additional fields.

We can do in a 1:1 discussion as this is a 1:1 interface .

I can also wrap it to unblock, which is what I propose for a quick
workaround


On 14.07.2015, at 08:19, Bernd Hekele <notifications@github.com> wrote:

This is blocking progress on the integration test.
I'm not really pleased with the need for a little discussion..

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/552#issuecomment-121141567>.

**Comment by JakobGartner** [comment]
Pending the discussion between the teams involved, the next release (this morning) will provide an output in the original format (while keeping the new one)

I had expected that we only integrate this work release after today’s call….



Sorry for the confusion.

**Comment by JakobGartner** [comment]
I have put back the original type, the new one stays available in parallel. 
Sorry for having committed without wrapping the side effects .

**Comment by JakobGartner** [comment]
(Export function will be available this morning)

**Comment by BerndHekele** [comment]
Workaround is fine.
