### ISSUE TITLE
Read_P005_ForCalcTrainPos moved to package TM_specific

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#558]
In order to standardise the structure of TrackMessages, the function Read_P005_ForCalcTrainPos has been moved to package TM_specific::Read_P005_ForCalcTrainPos.

It is still available at the old location TM::Read_P005_ForCalcTrainPos for 14 days and will then be deleted at the old path.

**Comment by UweSteinkeFromSiemens** [comment]
calculateTrainPosition has been updated accordingly, can be closed.
