### ISSUE TITLE
Story00A_nominal added

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#559]
@UweSteinkeFromSiemens 

As requested, I have added a "nominal" version of Story00A with push a718450

The difference is that the Balises are now at the "nominal" positions as announced in Packet 5.

What I find interesting is that the Balises are found by the real train with the Q_LOCACC distance from the nominal position (absolute). But if you check the incremental distance, BG366 and BG367 are 2m off the +-2m distance. 

The Excel File that documents this is in the TestTracks folder on the repository. 

This issue follows up the closed issue #434.

**Comment by UweSteinkeFromSiemens** [comment]
Thanks a lot, I will try it.

**Comment by UweSteinkeFromSiemens** [comment]
The train "TestBenchExample" has just  navigated along Track "Story00A_nominal" correctly without detecting any inconsistencies. Great! This issue might be closed.
