### ISSUE TITLE
MA timers handling 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#562]
@T12z 

in MAs_t, you receive some timer information.

Nevertheless we had discussed that it is the TrackAtlas function who will already manage timers.
Do you require timer information anyway or should I set it to "timers off"?

**Comment by T12z** [comment]
We do not utilize timers in our operators, nor even read/reference them.
You are free to do what needs to be done.

**Comment by T12z** [comment]
Answered. Timers are not handled in current releases. Future releases may change this.
