### ISSUE TITLE
TrackMessages:P058_Read... has wrong type

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#563]
The old type is: P58_PositionReportParameters_T (packets_pkg)

@christianstahl : this operator idealy would be used inside the ProvidePositionReport model.
Shall we migrate?

Currently, it is part of the input channel due to historical reasons.

kr
Bernd

**Comment by mairamou** [comment]
A general response: 

- If you need the "original" type, it will be provided. 

Just open an issue with the output type required. 

There was a deep reason (generic handling of message and package
transport) to define new types in TM:: and TM_baseline2 and its sub
packages. 

If you need specific casts/ conversions they will be added as needed. 

Howver, as the "new" types are much closer to the Subset 26 6/7/8 spec
than the "old" ones, it may be a good idea to use them unless there is a
real reason against. 

On 2015-07-14 14:13, Bernd Hekele wrote: 

> The old type is: P58_PositionReportParameters_T (packets_pkg) 
> 
> @christianstahl [1] : this operator idealy would be used inside the ProvidePositionReport model.
> Shall we migrate? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/christianstahl
[2] https://github.com/openETCS/modeling/issues/563

**Comment by BerndHekele** [comment]
... and there is a history where the old types have been used ... 
You can see the old type in this error report. Please provide the mapping.

Thanks
Bernd

**Comment by mairamou** [comment]
The export function has been provided.

The philosophy of TrackMessages, as I have learnt it, was to provide uniform compressed transport for all communications as the parallelised types were not really suitable for beyond initial experiments.

if abstractions of this transport are needed, they are provided by the TrackMessages team.

For P058 this is now done as requested. (response time 2h to completion)

**Comment by BerndHekele** [comment]
Thanks for the quick response.
I will take it in use.

**Comment by BerndHekele** [comment]
But - where can I find it?

**Comment by mairamou** [comment]
TM_specific:: ..... 

On 2015-07-14 17:39, Bernd Hekele wrote: 

> But - where can I find it? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/563#issuecomment-121284825

**Comment by BerndHekele** [comment]
Thanks.
