### ISSUE TITLE
TrackAtlas: Interface to TrainSupervision update 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#564]
@T12z . @BenjaminBeichler 

As discussed yesterday, the type MovementAuthority_t has been updated.

In order to not disrupt the integration process, a new node TrackAtlas_NextGen has been added which can be used for "Local Integration" until TrackAtlas and TrainSupervision work smoothly together.

Main changes:

- Integrated space for L1 MA
- Flags for calculating release speeds onboard 
- "Magic values" in packets already evaluated
- All speeds, distance and times converted to OBU_types_Pkg types

Cheers

**Comment by BerndHekele** [comment]
Hi Jakob,
the model does not compile. There is a null in the types module.
Can you please correct.

kr
Bernd

**Comment by JakobGartner** [comment]
done

**Comment by BerndHekele** [comment]
There is stil a _null in the MA_section_raw definition.
I do not know why but I get a lot og grap when I open the EVC model

**Comment by JakobGartner** [comment]
This type was not in use at all, it can’t have had any side effects, nor could it have blocked any code generation….

I have deleted it for now.

**Comment by BerndHekele** [comment]
I get a strange error from the types (even though I'm not using them for now):

Loading project openETCS_EVC.etp...
(0) : error ERRSEM_TYPE_NOT_DEC : _L117 : TrackAtlasTypes::Overlap_t, The type TrackAtlasTypes::Overlap_t is not declared

I'm now triing again with your second correction.

**Comment by BerndHekele** [comment]
This error is also in the model after pulling your correction.
Maybe you have an typo with this Overlap_t somewhere?

**Comment by JakobGartner** [comment]
well, indeed this type does not exist…
someone is using it.

Which model are you trying to open (your root model)?

**Comment by BerndHekele** [comment]
The evc-model. I just pushed it with problems for saving my results.
If you open it you see this syntax error.

**Comment by BerndHekele** [comment]
I just found the location where it failes. It is in the SDM model (Input).

**Comment by JakobGartner** [comment]
so there is a reference to a type which does not exist——


the caller must fix it

**Comment by JakobGartner** [comment]
I have provided a workaround, will be pushed in some minutes

**Comment by T12z** [comment]
@BerndHekele did you mean the input wrapper? I will check first thing tomorrow.
@JakobGartner cheers for quick fix!

Currently I am having quite annoying problems with Scade crashing when compiling for Simulation which keeps me off my actual work.

**Comment by BerndHekele** [comment]
Thanks.
The evc model is compilable again.

**Comment by T12z** [comment]
@JakobGartner can you please check wheather the type 
`TrackAtlasTypes::MovementAuthoritySectionlist_t` as `TrackAtlasTypes::MovementAuthoritySection_t ^TrackAtlasTypes::MRSPMaxSections`
is correct. I am talking about the array length constant. Even if, may I wish to have the above definition using the constant `TrackAtlasTypes::MAsMaxSections` and that referring to whatever it needs to.

Also, just noting the huge difference between these to constants 10 vs. 200.
_thanks_

**Comment by JakobGartner** [comment]
This was a copy& paste residual error. 
The right dimension is TrackAtlasTypes::MAsMaxSections

But please note that the values of the constants TrackAtlasTypes::MRSPMaxSections and TrackAtlasTypes::MAsMaxSections are designed to be of "any appropriate size".

I di not claim to already have found the ideal size for our use cases. 
In general the required size (especially for the MRSP array) depends on the realities of the track and other the discontinuities in the 11 speed profiles are disjunct or not.

SpeedSupervision will need to iterate on target/speed, target/gradient and ma section arrays of arbitrary size.

**Comment by JakobGartner** [comment]
The type has been updated with 7ca8dca

**Comment by T12z** [comment]
Yes, you are absolutely right, that I shall and do not give a continental about array sizes, unless they are just not right :bowtie:

Anyways, we/I have just found a fundamental misconception about MAs in our package, which came to light by the new type (yes, working on it).
Thooough I am missing the package variable `L_ENDSECTION` which should map to `TrackAtlasTypes::MovementAuthority.l_endsection`.

And you probably might as well have no idea what **V_MAIN** is all about, do you? (the specifications are cryptic)

**Comment by T12z** [comment]
... too much reading the specs.
I just understood your approach, that `l_endsection` ist always in a section in the sections list.
cheers

**Comment by JakobGartner** [comment]
Yes, I have made end section a special one about the sections in the list (but if you like it differently, we can also do that; I only left it like that because of the original approach to “iterate everything”)

V_MAIN: you can ignore it for the moment, this is just provisioning for Level1 MA where this variable counts.

**Comment by T12z** [comment]
Soooo,
I have basically switched to the "next_gen" TrackAtlasTypes, to the boudaries of the speedsupervision_package, with the same old input / output variables just of new type.
Shall I also switch to complex types such as DataForSupervision(_nextGen)_t?

@BerndHekele 
Who integrates the changes of the speedsuper_pkg into the EVC? Does it need to be integrated somewhere else?
Btw. the input `m_level` has been scrapped, it was just the wrong level source. Level from MA seems more apropriate. It will be removed from the interface on next change.
In the EVC-model there is also the type T_Data_From_Speed_Supervision, that I may output as a complex type from the integration operator. Though I am not sure if the item names of the structure are as self-explanatory as needed for me hook up. Should it be done?

There will be a pull-request in a minute just for reference. (It checks fine) As there could be more interface changes, it should be done in one.

**Comment by T12z** [comment]
On the one hand this is done.
There is still some cleanup to be done and bascically there is one more iteration of the interface planned #842 so this issue is superseeded.
closing.
