### ISSUE TITLE
MoRC: blocking issues for session establishment

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#566]
Dear Uwe,

I found two issues in the MoRC module, which currently block the establishment of a radio session. After locally fixing the issues in my working directory, I was able to establish a session correctly. Could you please fix the issues in the public model?

Issue 1 (Operator: Coder_Pkg::genMsgToRBC): 
The variable xT_TRAIN in message number 155 sent by the MoRC module must be set to 0. The RBC model checks this condition as part of the consistency check. Currently the variable is set to the value of T_TRAIN, which is detected as a consistency error in the RBC model.

Issue 2 (Operator: MoRC_Pck::MoRC_Main):
Packet 42 (Session Management) is currently only accepted, when the source is declared as "OBU". In our scenario, this packet has the source "Eurobalise" and has to be also accepted from this source.

**Comment by UweSteinkeFromSiemens** [comment]
I put a temporary fix on github.

**Comment by BerndHekele** [comment]
I close this issue since we have a working solution.
