### ISSUE TITLE
TrackAtlas::TrackAtlas with compile errors

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#567]
Hi,
trackAtlas throws compile error 100 when using the model.

Thanks for the correction.

kr
Bernd

**Comment by JakobGartner** [comment]
Hmm.

Constant changed. (Deleted type reference, Put back the same type reference)

SCADE sometimes doesn’t cleanly load type definitions from other packages…

**Comment by BerndHekele** [comment]
Thanks.
