### ISSUE TITLE
TrackAtlas: output of national values

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#568]
Hi Jakob,
I have seen the definition of the national values from the track-atlas.
Can we have a convertion in Baseline 3 for the output?
Or shall I collect the current needs for a specific operator?

kr
Bernd

**Comment by JakobGartner** [comment]
As I said in our meeting yesterday , packet 27 and packet 3 are in work as
far as the baseline 3 onboard view is concerned.

As we don't have the packet 209 on the Track a first version (with all the
advanced variables set to default ) can be available quickly. (In the next
work release on Tuesday morning )



On 17.07.2015, at 15:36, Bernd Hekele <notifications@github.com> wrote:

Hi Jakob,
I have seen the definition of the national values from the track-atlas.
Can we have a convertion in Baseline 3 for the output?
Or shall I collect the current needs for a specific operator?

kr
Bernd

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/568>.

**Comment by JakobGartner** [comment]
After further analysis, I propose the following:

- TrackAtlas shall continually emit the currently valid "raw" Packet 3 according to baseline 3.
In addition it will emit info about the baseline of the source of the information-
- TrackAtlas is also planned to send information which is specific for the different receivers (=other EVC or external modules) as needed within the specific interfaces (examples for such specific interfaces are DMI, Mode& Level, Supervision...). These interfaces need to be discussed between the module owners and the TrackAtlas team.

**Comment by BerndHekele** [comment]
Done
