### ISSUE TITLE
TrackMessages: Train to Track library

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#571]
- Build new merge operator which manages 
- sending of 1 packet per NID_MESSAGE per T_TRAIN- tick 
- unique T_TRAIN timestamp per packet (at 50ms cycle, this means 5 different T_TRAIN- values per cycle per message type)

Estimated remaining workload: 1 day

**Comment by BaseliyosJacob** [comment]
Duplicate #577

**Comment by JakobGartner** [comment]
done
