### ISSUE TITLE
TrackMessages do not compile.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#578]
Opening the models I see the following report:

Loading project Testbench_Integration.etp...
(0) : error ERRSEM_TYPE_NOT_DEC : MessageBus : M_TrainTrack_Radio, The type M_TrainTrack_Radio is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : MessageBus_out : M_TrainTrack_Radio, The type M_TrainTrack_Radio is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L4 : M_TrainTrack_Radio, The type M_TrainTrack_Radio is not declared

3 semantic error (s)
Successfully loaded project Testbench_Integration.etp

In addition I see an error 100 from your Scade model.

Please correcxt.

**Comment by JakobGartner** [comment]
I would be surprised if this missing reference would have had blocked any code generation as these libraries Train To track are not yet called from anywhere (at least they shouldn’t be)

However, the missing reference has been fixed, and I get no consistency errors on the model.

Please don’t use the train to track stuff before I have released it…


Jakob

**Comment by BerndHekele** [comment]
When I post an issue about compile errors I have a problem which is blocking. the model.
You can easily check on your environment.

**Comment by JakobGartner** [comment]
Jakob Gaertner
As said I have fixed the consistency errors I could see (=which were the
same you mentioned)


On 20.07.2015, at 10:43, Bernd Hekele <notifications@github.com> wrote:

When I post an issue about compile errors I have a problem which is
blocking. the model.
You can easily check on your environment.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/578#issuecomment-122814408>.

**Comment by BerndHekele** [comment]
You are right. The problem is not in the trackMessages.
It is in the Utrecht-Amsterdam track description.
![image](https://cloud.githubusercontent.com/assets/3288918/8772757/1938c07c-2ecf-11e5-99b0-515290e199b3.png)


Shall I open a new issue or is this one enough to get the correction?

**Comment by JakobGartner** [comment]
It’s corrected….

It was a non-error (SCADE refused to see the type update it saw)

**Comment by BerndHekele** [comment]
Thanks.
