### ISSUE TITLE
EB and SB triggered in Level_NTC

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#586]
With the current evc model the eb command and the SB commands are triggered by SDM.
I assume this is reasoned by insufficient data from TrackAtlas in the initialisation state.

I will implement a shortcut in the evc model to avoid a blocking state.
I propose to follow this issue when the next version of both models are available this week.

kr
Bernd.

**Comment by BerndHekele** [comment]
@JakobGartner , @stefan-karg @T12z 

In the scenario we start in level ntc and stay in this level for a couple of hundred meters.
We must obey national speed limitations in this drive.
Can we introduce a "realistic" speed limit out of the track atlas or in the environment  in order to not look silly with the start of this trip?

cu
Bernd

**Comment by BaseliyosJacob** [comment]
Hello,

i propose to use the limit of 40 km/h since we are in station area with NTC.
40 km/h is the max. allowed speed in station areas.

**Comment by T12z** [comment]
I agree, 40 km/h, as it also compares to SR.
Anyways, SDM should either receive a fake MA and a MSRP with 40 km/h limit. Cleaner would be kind of a SR-mode - though that is not yet implemented as far as I understood. Ignoring SDMs output in NTC is still a viable option. I am a bit anxious of the mode transition.

**Comment by T12z** [comment]
This issue is stale. A work-around seems exist and being the last one to comment, I take the stick and close the bug.
