### ISSUE TITLE
Committer Vote for Johannes Kastner from ICS AG

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#588]
BerndHekele commented a day ago
We want to use contributions of Johannes Kastner from ICS AG in WP 3. 
Please, vote for Johannes

Kind Regards
Bernd

@openETCS/modeling-committers l

Please vote for Johannes

**Comment by BaseliyosJacob** [comment]
+ 1

**Comment by Farhangi** [comment]
+1

**Comment by BenjaminBeichler** [comment]
+1

**Comment by BerndHekele** [comment]
+1

**Comment by JakobGartner** [comment]
+1

**Comment by mairamou** [comment]
+1 

On 2015-07-21 15:33, Bernd Hekele wrote: 

> +1 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/588#issuecomment-123305003

**Comment by MatthieuPoirot** [comment]
+1

Matthieu Poirot
---------------------------------------------------
European Rail Software Applications
5, Rue Maurice Blin
67500 HAGUENAU
France
Tel : (0033) 3 88 07 15 57
Fax : (0033) 3 88 07 15 51
E-mail : matthieu.poirot@ersa-france.com
Internet : http://www.ersa-france.com
---------------------------------------------------
________________________________

**Comment by stefan-karg** [comment]
+1

**Comment by BerndHekele** [comment]
Looks we have sufficient votes available.
I close this vote and change the state.
Welcome in the team.

**Comment by BerndHekele** [comment]
Can you please send the Github-Name to the projectoffice?

**Comment by jokade** [comment]
Done -- thanks!
