### ISSUE TITLE
Committer Vote for Alexander Pinnau from ICS AG

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#589]
BerndHekele commented a day ago
We want to use contributions of Alexander Pinnau from ICS AG in WP 3. 
Please, vote for Alexander

Kind Regards
Bernd

@openETCS/modeling-committers l

Please vote for Alexander

**Comment by BaseliyosJacob** [comment]
+ 1

**Comment by stefan-karg** [comment]
+1

**Comment by mairamou** [comment]
+1 

On 2015-07-21 17:35, Baseliyos Jacob wrote: 

> BerndHekele commented a day ago
> We want to use contributions of Alexander Pinnau from ICS AG in WP 3. 
> Please, vote for Alexander 
> 
> Kind Regards
> Bernd 
> 
> @openETCS/modeling-committers [1] l 
> 
> Please vote for Alexander 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/orgs/openETCS/teams/modeling-committers
[2] https://github.com/openETCS/modeling/issues/589

**Comment by Farhangi** [comment]
+1

**Comment by BerndHekele** [comment]
+1

Can you please provide the Git-Name for closing this vote?

**Comment by apinnau** [comment]
My Git-Name is: apinnau

**Comment by BerndHekele** [comment]
Thanks and welcome in the team.

Commtter-Rights are allocated - vote can be closed.
