### ISSUE TITLE
DMI: Yellow ACK border behavior

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#592]
The yellow border of the ACK field for acknowledging the level transition to Level NTC does not disappear on acknowledgement. If the empty ACK field is acknowledged again (= a second click), the yellow border disappears. By clicking on the field again, the blinking yellow border can be toggled.

**Comment by BaseliyosJacob** [comment]
Dear Stefan, this issue seems to be due some timing issues. I think it it is a low priority and therefore i will shift the fix to later.

**Comment by stefan-karg** [comment]
Ok, this is fine with me.

**Comment by BaseliyosJacob** [comment]
Dear Stefan, 

issue is fixed with last commit from me on DMI

**Comment by BaseliyosJacob** [comment]
can you please check it an close the issue if it solved from your point of view.

**Comment by stefan-karg** [comment]
Closed, problem is solved.
