### ISSUE TITLE
Procedures: statusstartofmissionongoing_to_MoRC is true at NP mode

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#594]
If the EVC is in No Power mode, the flag statusstartofmissionongoing_to_MoRC of the procedure module is currently constantly set to true, which triggers the registration of the mobile by the MoRC module.

**Comment by BaseliyosJacob** [comment]
Dear Stefan, should be fixed in the last version. Can you please check it?

**Comment by stefan-karg** [comment]
Dear Baseliyos, this issue is fixed now! The issue of the too early indication of a safe radio connection is most probably related to the connection to the DMI.
