### ISSUE TITLE
PositionReport: Inconsistent output

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#596]
The position report output shows a present flag for the message, but no message is attached.

Visible in the bring-up model.

We can analyse together based on a goto-meeting session?

kr
Bernd

**Comment by christianstahl** [comment]
Sure

**Comment by christianstahl** [comment]
Dear Bernd,

the module has now a new input of T_TRAIN and has been integrated into the EVC model.

Christian

**Comment by christianstahl** [comment]
The bug should be fixed now.
Christian

**Comment by christianstahl** [comment]
Dear Bernd,

the condition whether a report based on packet0 or packet1 is provided is as follows:
if(         the last past BG contains only 1 balise 
    AND noCoordinationSystemHasBeenAssigned=true 
    AND valid=true)
then packet 1
else packet 0

In the model I swapped packet 0 and 1. This is now corrected.

Christian

**Comment by BerndHekele** [comment]
I justz checked the correction of our first problem.
The provide position report is now always on the wire.
I propose we have a look at this problem when you visit us in Munich?

cu
Bernd

**Comment by BerndHekele** [comment]
Hi Christian,
I now managed to analyse the situation in the report.
The selection of report 1 is because you work on an bg with infofrompassing . valid = false.
Actually, in  the data of the test-run the first element of the BGs is not valid.

The second is. 
The build_packets model should make use of the last updated bg element.

kr
Bernd

**Comment by christianstahl** [comment]
Dear Bernd,

>The selection of report 1 is because you work on an bg with infofrompassing . valid = false.
> Actually, in the data of the test-run the first element of the BGs is not valid.
So the test data is not correct?

> The build_packets model should make use of the last updated bg element.
It does. The last updated BG in the list is list[7].

Christian

**Comment by BerndHekele** [comment]
Correction is available, tested and integrated.
