### ISSUE TITLE
Fundamental issues about Amsterdam- Utrecht track model

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#597]
During the documentation work on Amsterdam Utrecht track model I came across a real conceptual problem.
After discussion with @JakobGartner it is like this:

- The balises have been modelled using the planning documents from ProRail
-  the packets have been modelled using the packets received by the JRU

While analysing the balise positions against the linking information, I could see that the two are not consistent.
This is a **static error** as this type of inconsistency does not have anything to do with possible onboard or JRU inaccuracies. 

I had another look at the JRU data. 
The JRU also recorded the distance from the LRBG and the DOUBTOVER/DOUBTUNDER values.
But they are not part of the track model of course but only a documentation of the onboard calculation (which again mixes many errors including odometry)

Our conclusion is:

- The plans are just plans, apparently the real positions of the balises are not very much what was planned (errors up to 9m)
- Probably, the Packet 5 data are more precise than the data in the engineering plans, if not the track could not have been gone operational
--> we should correct the balise positions for *this iteration* to make them consistent with the linking information. If not, we will always run into errors without meaning. (we know already that the two datasets from ProRail/ from the packets also from ProRail) are not consistent)
--> we could think about using the additional JRU data about "where a balise was actually found" in a next iteration track model/and/or an odometer error model. 

If you all agree, I will sit down and build a version of the track model that moves the balise positions to a location consistent with the linking information.

**Comment by janWelte** [comment]
Thank you very much for this detailed analysis and the very good proposal. I've to agree with your conclusion completely and think this would be the best solution.

I only ask you to provide a detailed documentation of all differences you identify and all changes you take, so we have the porper data for validation.

**Comment by mairamou** [comment]
With my next commit, there will be a file "XREF_Balises_... in the
project folder which details my initial findings. 

I will add further analysis step by step as these errors have ripple
effects. 

On 2015-07-23 10:05, Jan Welte wrote: 

> Thank you very much for this detailed analysis and the very good proposal. I've to agree with your conclusion completely and think this would be the best solution. 
> 
> I only ask you to provide a detailed documentation of all differences you identify and all changes you take, so we have the porper data for validation. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/597#issuecomment-124015358

**Comment by janWelte** [comment]
That perfect. I'll make an effort to verify your work to ensure that after this the track is on a good way. Let me know if you need any help.

**Comment by UweSteinkeFromSiemens** [comment]
Dear Mairamou, 
the distance from the LRBG and the DOUBTOVER/DOUBTUNDER values are calculated by the train, i. e. by calculateTrainPosition. Here, more inaccuracies are taken into account, as of odometry, balise antenna detection and others. But these are not track properties. 

For the track, you should base the track on the linking information (D_LINK) and the mounting uncertainties of the balises (Q_LOCACC) only. Within this range as announced by packet 5, each balise must be set on the track, as long as you don't want to generate inconsistency scenarios intentionally.

**Comment by BaseliyosJacob** [comment]
Thats the difference between planning on the desk and realizatio in reality. ProRail is already aware that the planning is not consistent with the real implementation.

**Comment by janWelte** [comment]
The only point I'll never understand is that there has to be a docuent somewhere which lists the real positions, since the data for the packets has to be created depending on the positions. But that's a question for another discussion. Nothing which helps us at the moment.

**Comment by mairamou** [comment]
Hello Mr. Steinke, 

yes I agree. 

The idea was to use the information of the onboard unit calculations to
compare them with ours. (as an additional means of validation) 

I did not intend to mix the doubter/under and locacc issues. 

On 2015-07-23 10:25, Uwe Steinke wrote: 

> Dear Mairamou, 
> the distance from the LRBG and the DOUBTOVER/DOUBTUNDER values are calculated by the train, i. e. by calculateTrainPosition. Here, more inaccuracies are taken into account, as of odometry, balise antenna detection and others. But these are not track properties. 
> 
> For the track, you should base the track on the linking information (D_LINK) and the mounting uncertainties of the balises (Q_LOCACC) only. Within this range as announced by packet 5, each balise must be set on the track, as long as you don't want to generate inconsistency scenarios intentionally. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/597#issuecomment-124020298

**Comment by mairamou** [comment]
We had a file with the planned engineering positions (which are the same
data as you find in the plans that Baseliyos has used to describe the
User Story 

We also have a more detailed file with distances to some locations on
the track (which I don't really understand) 

We have no file that is consistent with the packet data 

I think maybe the files we have were the input to whoever built the
track 

and the packets are the output :-) from whoever built the track 

On 2015-07-23 10:49, Jan Welte wrote: 

> The only point I'll never understand is that there has to be a docuent somewhere which lists the real positions, since the data for the packets has to be created depending on the positions. But that's a question for another discussion. Nothing which helps us at the moment. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/597#issuecomment-124024451

**Comment by mairamou** [comment]
With https://github.com/openETCS/modeling/blob/master/model/Scade/System/TracksideDynamicModel/TestTracks/UtrechtAmsterdam_oETCS/XREF_Balises_Amsterdam_Utrecht.xlsx you find now the reference information about the bailed on the track. I will work on making the track consistent in itself.

**Comment by UweSteinkeFromSiemens** [comment]
For testing, debugging and verification, it would be helpful to proceed in the following way: 
- start with tracks under good weather conditions, i. e. with clean tracks without any inconsistent balise positions and data from balise and radio. This would allow to bring up the OBU functions most easily :-)
- generate derivates of track sections that induce dedicated exceptional conditions (dedicated bad weather effects like a single misplace balise) for testing the OBUs inconsistency handling.

**Comment by JakobGartner** [comment]
I think the first step is to have a track that is statically consistent in itself.
As Amsterdam Utrecht is supposed to be operational, we must assume that there is a consistent version (which is reflected in the JRU data, not in the engineering data)

With the plan as proposed by Mairamou, and supported by WP4, this will be the case today.

And yes, we agree with Uwe who formulated the same idea, but from EVC perspective

**Comment by UweSteinkeFromSiemens** [comment]
It's completely ok for me.

**Comment by mairamou** [comment]
I have done the following updates:
- the XREF has been updated with proposed corrected balise positions, calculated incrementally from the first linked BG (354) using the linking data from P5.
- the model has been updated with the corrected balise positions.
In order to make it traceable, I have used a notation as follows:
ORIGINAL_POSITION + CORRECTION, where CORRECTION is the difference between the engineering data and the proposed corrected position taken from the XREF.

By the way,I found it dangerous to have a BG 36m later than expected. If I look on the track layout, this means that we are often already beyond a signal or switch.

**Comment by UweSteinkeFromSiemens** [comment]
Dear Mairamou, 
the linking information makes up the ideal track description the train gets to know. If it does not meet the position of signals or switches, they have to be shifted on the track to where they are announced ...

**Comment by janWelte** [comment]
First verification results for corrected track implementation

If run the new track in my test model an started to analyse the resulting data to verify the new and corrected track positions. It looked quite good, but small inconsistencies seam to be present. In the following you find the first observations.

Small errors in balise implementation:
- BG 377: wrong BG header (BG 374) applied
- BG 393: wrong Balise header includes for both balises (BG392 B1 und B0)
- BG 442-445 are not implemented in the track (correct?)

further results will be added tomorrow

**Comment by JakobGartner** [comment]
Hmm

I can't confirm the following finding:
BG 377: wrong BG header (BG 374) applied

BG 393: wrong Balise header includes for both balises (BG392 B1 und B0)
has been corrected

As the train stops at BG441 in the user story, they have not been integrated in the track model. (we don't know any possible telegrams)
BG headers are however modelled and could be integrated into the model if required,

**Comment by janWelte** [comment]
Thanks Jakob,

to clarify for BG 377 it's the overall BG Header (Parameter for the over BG Block, not the single Balise header).

For BG 442-445 I wanted to make sure that these are  purposely missing as Mairamou documented them in the same way as all others and in my (probably old) track drawing Baseliyos set "the end" to BG 445. (From my V&V perspective it doesn't change anything as long as the requirements are clear.)

**Comment by JakobGartner** [comment]
You are right.
It is corrected for BG 377
