### ISSUE TITLE
SoM: message 129 should contain packet 0

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#598]
Currently the message 129 (Validated Train Data) contains the packet 1 (special case of position report) instead of packet 0 (Position report). This is not consistent with the sequence depicted in User-Story 7.

**Comment by JakobGartner** [comment]
For the current iteration this can very quickly be fixed as P0 and P1 are identical in structure.
For the next iteration, TrackMessages provides a generic solution

**Comment by BerndHekele** [comment]
It is not a problem of generating the correct packet. Both packets are supported by Provide Position Report.

Povide Position Report selected - based on the balise configuration - packet 1.
We need to check whether the selection of the packets is according to the standard.

Christian, can you make a short assesment please?

@christianstahl

**Comment by christianstahl** [comment]
Dear All,

there is a minor difference between packet0 and packet1: Packet1 contains in addition to the elements of packe0 the element NID_PRVLRBG, i.e., the Id of the previous LRBG.
I propose to add both, packet0 and packet1, to Message 129 (as required in the SRS). Both packets are output of ProvidePositionReport.

Christian

**Comment by BaseliyosJacob** [comment]
From my point of view to be consistent with the JRU data and compliant with the standard message the packet 0 is enough. I think it is not a problem to send both as soon the ETCS OBU is supporting the Packet 1 to send it. In this case the RBC do not have to consider it.

**Comment by BaseliyosJacob** [comment]
The packet 1 is necessary when the orientiatio is unknown due to one balise. But this is not the case on Utrecht - Amsterdam.

**Comment by aprobst** [comment]
I agree with @BaseliyosJacob. Regarding user story 7, the RBC currently supports only packet 0, i.e., that packet 1 is ignored. However, only a correct packet 0 should be send because the position data is stored in the RBC after the position report is received. This is important for triggering a radio message from the track model.

**Comment by aprobst** [comment]
One minor addition: a position report can contain only packet 0 (X)OR packet 1. If the RBC receives a position report with both packets, then the whole message is rejected.

**Comment by BerndHekele** [comment]
Problem is corrected in provide position report.

I close this issue
