### ISSUE TITLE
Compilation issues related to commit c8caa84

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#599]
Dear Uwe,

after pulling your commit c8caa845dc651fd44a74a126501d3d5143d20102, I get the error message, that the package *BasicLocationFunctions_Pkg* is undefined.

**Comment by UweSteinkeFromSiemens** [comment]
Should be fixed now. Due to 16.1 setup, "separate file" flag was set by default unfortunately.

**Comment by stefan-karg** [comment]
Fix works. Thank you, Uwe!
