### ISSUE TITLE
Filter Document Review

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#60]
Please review my document on filtering until 08.12.2014
@mahlmann @astante @BerndHekele @KlausRuedigerHase @Farhangi .

https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information

**Comment by BerndHekele** [comment]
Cleanup of Modelling Issues.
The filter is now implemented and ready for verification.
Should be covered there.
