### ISSUE TITLE
TM_Specific READ operators needed for Mode and Level

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#600]
Dear Mairamou,
I need specific operators to connect with Modes and Level.
The following operators are needed in the upcoming bringup tests:
P15
P41
P46.

Thanks for your support.

Bernd

**Comment by mairamou** [comment]
done.

**Comment by mairamou** [comment]
Just as a remark:
A specific interface between TrackMessages and ML has been agreed which includes status flags for MA as requested by @MariellePetitDoche 

Reading raw P15 may be misleading as several criteria make an MA valid. 
Possibly there is a need for discussion

**Comment by BerndHekele** [comment]
Thanks for this hint.
Do we have this interface already implemented somewhere?
The current and outdated definition of Marielle makes mainly make use of flags.
I'm aware the interface needs changing but Marielle is currently not active.
And I cannot wait until this state changes.

I also need the P21 (gradient) for this interface. 
Would it be possible to provide this data as well?

Thanks a lot for this contribution.
Bernd

**Comment by BerndHekele** [comment]
I just used the operators.
There is a constant with problems in the model: INIT_P15_OBU.

**Comment by BerndHekele** [comment]
Sorry. I just recognised the compile problem is in another unit.

**Comment by JakobGartner** [comment]
There is an interface to ML that I have defined in TrackAtlas, which is in version that I am right now having in final tests. 
This has all the flags as discussed with Marielle (including the flags to announce valid SSP, MA and GP

**Comment by BerndHekele** [comment]
@MariellePetitDoche 
Thanks Jakob,
I will try to link the models without touching the original model of modes and level.

Mariell,
is it possible for you to contribute on this change?

kr
Bernd

**Comment by mairamou** [comment]
done P21 specific extraction

**Comment by BerndHekele** [comment]
Thanks a lot
Bernd

**Comment by JakobGartner** [comment]
TrackAtlas now has a direct connection to Mode and Level Input Management with all data I believe we can find in Track Atlas.

I have analysed the operators:
- Input_MA_SSP_Gradient
- InputTrackManagement

Data are now provided with an interface that connects directly to the inputs of these operators.

See output To_ModeAndLevel in TrackAtlas top level,


Data are now provided in a raw manner, but we could optimise a lot here once @MariellePetitDoche
