### ISSUE TITLE
TA_MA Constants result in 100 Error

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#602]
INIT_P15_OBU
and 
Default_MA_Section
need correction.

Thanks
Bernd

**Comment by JakobGartner** [comment]
OK it seems that the bug that Mairamou has fixed yesterday has not been propagated everywhere

Will fix quickly

**Comment by BerndHekele** [comment]
The commit seems to be buggy.
I now have loading problems with speed supervision.
Can you please check?

**Comment by T12z** [comment]
in my private fork I have the new interfaces integrated. (commit/push is current)
you are invited to pull, I can setup a pull request. As of this very minute I have not yet hooked up the SDM_to_Modes interface internally, but this is due this afternoon / monday. But you may already integrate the new external interface.

**Comment by BerndHekele** [comment]
I need a running model to continue with testing. Currently I'm blocked with the state of the deliverables. Can you both provide a running version for the evc model and give some hint on how to proceed.

**Comment by JakobGartner** [comment]
Am also working and it will work soon. I expect it to be ready before the
weekend

Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



On 24.07.2015, at 10:16, Bernd Hekele <notifications@github.com> wrote:

I need a running model to continue with testing. Currently I'm blocked with
the state of the deliverables. Can you both provide a running version for
the evc model and give some hint on how to proceed.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/602#issuecomment-124428385>.

**Comment by BerndHekele** [comment]
I get the following loading errors when I try to load the model:  
Loading project openETCS_EVC.etp...  
D:\DB-Data\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\SDM_Commands\SDM_Commands.etp(0) : error ERRSYN_REC_LIBRARY : Library D:\DB-Data\Github\modeling\model\Scade\System\ObuFunctions\manageData\manageDMI\manageDMI.etp : recursion detected
D:\DB-Data\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\SpeedSupervision_Integration\SpeedSupervision_Integration.etp(0) : error ERRSYN_REC_LIBRARY : Library D:\DB-Data\Github\modeling\model\Scade\System\ObuFunctions\TrackAtlas\TrackAtlas.etp : recursion detected
(0) : error ERRSEM_TYPE_NOT_DEC : cnoMAs : TrackAtlasTypes::MAs_t, The type TrackAtlasTypes::MAs_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : cNoMRSP : TrackAtlasTypes::MRSP_Profile_t, The type TrackAtlasTypes::MRSP_Profile_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : MRSP_profile : TrackAtlasTypes::MRSP_Profile_t, The type TrackAtlasTypes::MRSP_Profile_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : MRSP_MAs : TrackAtlasTypes::MAs_t, The type TrackAtlasTypes::MAs_t is not declared
(0) : error ERRSEM_VAR_NOT_DEC : Variable manage_DMI_Input_Pkg::cNo_STM : variable not declared
(0) : error ERRSEM_VAR_NOT_DEC : Variable manage_DMI_Input_Pkg::cNo_STM : variable not declared
(0) : error ERRSEM_TYPE_NOT_DEC : TA_toDMI : TrackAtlasTypes::DataForDMI_t, The type TrackAtlasTypes::DataForDMI_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : TA_forSupervision : TrackAtlasTypes::DataForSupervision_t, The type TrackAtlasTypes::DataForSupervision_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : TA_MA_onboard : TrackAtlasTypes::MovementAuthority_t, The type TrackAtlasTypes::MovementAuthority_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L877 : TrackAtlasTypes::MRSP_Profile_t, The type TrackAtlasTypes::MRSP_Profile_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L878 : TrackAtlasTypes::MAs_t, The type TrackAtlasTypes::MAs_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1226 : TrackAtlasTypes::MAs_t, The type TrackAtlasTypes::MAs_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1249 : TrackAtlasTypes::MRSP_Profile_t, The type TrackAtlasTypes::MRSP_Profile_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1248 : TrackAtlasTypes::MovementAuthority_t, The type TrackAtlasTypes::MovementAuthority_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1247 : TrackAtlasTypes::DataForSupervision_t, The type TrackAtlasTypes::DataForSupervision_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1246 : TrackAtlasTypes::DataForDMI_t, The type TrackAtlasTypes::DataForDMI_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1274 : TrackAtlasTypes::DataForDMI_t, The type TrackAtlasTypes::DataForDMI_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1275 : TrackAtlasTypes::DataForSupervision_t, The type TrackAtlasTypes::DataForSupervision_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1276 : TrackAtlasTypes::MovementAuthority_t, The type TrackAtlasTypes::MovementAuthority_t is not declared
(0) : error ERRSEM_TYPE_NOT_DEC : _L1319 : TrackAtlasTypes::DataForDMI_t, The type TrackAtlasTypes::DataForDMI_t is not declared
(0) : error ERRSEM_NODE_DEC : Node manage_DMI_Output_Pkg::DMI_Integrator : node not declared
(0) : error ERRSEM_NODE_DEC : Node SpeedSupervision_Integration_Pkg::SpeedSupervision_Integration : node not declared
(0) : error ERRSEM_NODE_DEC : Node manage_DMI_Input_Pkg::manageDMI_Input : node not declared
(0) : error ERRSEM_NODE_DEC : Node TrackAtlas::TrackAtlas : node not declared

1 syntactic error (s)

26 semantic error (s)
Successfully loaded project openETCS_EVC.etp
Loading library manageDMI.etp...
Failed to load library manageDMI.etp
Loading library SpeedSupervision_Integration.etp...
Failed to load library SpeedSupervision_Integration.etp

**Comment by BerndHekele** [comment]
Dear Jakob,
I just recognised the root cause of our problem.
We have a sequence error between trackatlas and SpeedSupervision.

Can you please take the SpeedSupervision Integration model out of your .etp

Thanks.
Bernd

**Comment by JakobGartner** [comment]
Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



On 24.07.2015, at 12:48, Bernd Hekele <notifications@github.com> wrote:

Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



I just recognised the root cause of our problem.
We have a sequence error between trackatlas and SpeedSupervision.

Can you please take the SpeedSupervision Integration model out of your .etp

Thanks.
Bernd

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/602#issuecomment-124471689>.

**Comment by BerndHekele** [comment]
Dear Jakob,
the dependency is solved now. Thanks.
But we are back to the original const error (100).
No, we get it with the const TA_MA::Decode_P15.

Thanks for the support.
It is sufficeint if we have a clean model on Monday - I skipped today's release and I'm no longer blocked with the testing.

cu
Bernd

**Comment by JakobGartner** [comment]
This should be closable since Monday (July 27)

**Comment by BerndHekele** [comment]
solved
