### ISSUE TITLE
SDM_Commands.etp:: Unnecessary import of project manageDMI.etp

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#604]
Dear Thorsten,
I had a closer look at the current compilation problem.
I recognised the model has manageDMI.etp as library.
This is causing problems due to dependencies in the project - please delete.

It is not necessary to usse the project. If you just need types they are delivered with the API_Types library.

It is not the complete solution - there are dependecies to trackatlas also making some trouble.

Thanks 
Bernd

**Comment by T12z** [comment]
cheers, for the hint
will fix.

I already have noticed the "viel-hilft-viel" includes in the past days (I needed to do some refactoring). It  is just very hard to track/sort out unneeded includes.

**Comment by BerndHekele** [comment]
Thanks.
