### ISSUE TITLE
[Level_And_Mode_Types_Pkg::T_Data_From_Speed_Supervision] request for clarification

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#607]
Hej,

I am hooking up the flags of Level_And_Mode_Types_Pkg::T_Data_From_Speed_Supervision and ran into questions:
 1. Estim_front_End_overpass_SR_Dist
   * Supervision is conceptually not aware of SR mode. As far as I understood I get a "fake" MovementAuthority from TrackAtlas, that runs out at the SR-maximum distance. (am I right @JakobGartner ?) But I cannot distinguish at the moment, so cannot set the flag.
 1. Estim_Front_End_Rear_SSP
 1. Override_Function_Active
   * if this relates to `SRS::3.11 Static Speed Restrictions and Gradients` then Supervision has no clue about this
 1. EOA_Antenna_Overpass
 1. EOA_Front_End
   * we have one output EOA_overpassed that signals essentially both conditions depending on the mode we are in. As ML *and*s with the level (I checked) and eventually *or*s these conditions it should be ok. Or do you require for whatever reason I missed (SR?) that only one condition fires depending on the level?
 1. Train_Speed_Under_Overide_Limit
   * please specify a formular, e.g. (v_est <= v_target) or (v_est <= v_P) ...
   * if this also relates to `3.11` then this is either no part of speedsupervision or needs to be implemented

SpeedSupervision just implements chapter 3.13 of the SRS, notthing else really.

In the end, it might not be that good of an idea to try to fill it inside SpeedSupervision.

cheers,
Thorsten

**Comment by T12z** [comment]
@BerndHekele as the above questions probably run into elaborate things, I will roll back my (so far local) interface changes in the supervision-output and leave things as they are. You can could connect `EOA_overpassed` externally to EOA_* of the above structure in the EVC-model. Everything else cannot be filled by supervision.

**Comment by BerndHekele** [comment]
ok.
Thanks for the information.
To me the requested information looks more like trckAtlas?

**Comment by JakobGartner** [comment]
hello.




> On 24 Jul 2015, at 16:27, Thorsten Schulz <notifications@github.com> wrote:
> 
> Hej,
> 
> I am hooking up the flags of Level_And_Mode_Types_Pkg::T_Data_From_Speed_Supervision and ran into questions:
> 
> Estim_front_End_overpass_SR_Dist
> Supervision is conceptually not aware of SR mode. As far as I understood I get a "fake" MovementAuthority from TrackAtlas, that runs out at the SR-maximum distance. (am I right @JakobGartner <https://github.com/JakobGartner> ?) But I cannot distinguish at the moment, so cannot set the flag.
TrackAtlas is aware of SR mode (but is not yet implementing it)
The plan is to give you the SR speed limit and the SR distance in the form of the related distance information inside the MRSP (after that the speed goes down to 0)
It could be a good idea to give you a set of flags to indicate special profiles if you need special handling.
I have not yet analysed this question-
> 
> Estim_Front_End_Rear_SSP
That is a value I also calculate /(as I need it to set a MA to valid). I can provide the flag. 
> Override_Function_Active
> if this relates to SRS::3.11 Static Speed Restrictions and Gradients then Supervision has no clue about this
I think this is a mode …. at least it is no info that I can see in the packets I receive from the track (until now).

> 
> EOA_Antenna_Overpass
> EOA_Front_End
> we have one output EOA_overpassed that signals essentially both conditions depending on the mode we are in. As ML ands with the level (I checked) and eventually ors these conditions it should be ok. Or do you require for whatever reason I missed (SR?) that only one condition fires depending on the level?
no idea
> 
> Train_Speed_Under_Overide_Limit
> please specify a formular, e.g. (v_est <= v_target) or (v_est <= v_P) ...
> if this also relates to 3.11 then this is either no part of speedsupervision or needs to be implemented
I am aware of the override limit… and once the M/L dependent speed profile is implemented you should also get it inside the MRSP. 
When then you also know the mode/öevel from mode and level are you then ok?

**Comment by T12z** [comment]
This issue is not related to me / SDM anymore. The related flow cannot be filled by SDM and is externalized (as it was before the issue).
Having opened this, and not assigned anyone, I am onto closing this. done.
