### ISSUE TITLE
CheckRadioMessage::Timer Error

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#618]
We have a change in the RBU model.
Packet 57 and 58 are sent with the first general message.

Timer check again hinders passing of the message.

kr
Bernd

**Comment by BerndHekele** [comment]
Some Information:
![image](https://cloud.githubusercontent.com/assets/3288918/9025743/2627e1d4-3913-11e5-84ac-77d20ede48e3.png)

From first view I believe the INT operator is not ok.

kr
Bernd

**Comment by stefan-karg** [comment]
Fixed in 366e364ca1061b242c054c3af0a8e1820d1e399f.
