### ISSUE TITLE
EVC/TrackAtlas: handle MSG15 "Conditional Emergency Stop"

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#621]
Part of #583; sub-tasks:
* [x] receive and process Msg15
* [x] check if min safe front end has already passed the new stop location
* [x] if so, reject Msg15 (send Msg147 with Q_EMERGENCYSTOP=3)
* [x] otherwise acknowledge with Msg147 (Q_EMERGENCYSTOP=0/1)
* [x] pass updated EOA to `TrackAtlas/Build_MA` `Train_Supervision`
* [x] handle revocation of CES (but only propagate it to the outside, when all pending CES have been revoked)

Current limitations:
* ~~multiple concurrent CES not yet supported~~
* `q_dir` and `d_ref` not considered in EOA calculation

**Comment by jokaICS** [comment]
@JakobGartner @christianstahl 
Regarding the management of Conditional Emergency Stop messages: how shall we pass an updated EOA (due to a conditional ES) to Train_Supervision?

**Comment by JakobGartner** [comment]
let me analyse a moment, but for sure it will be inside TrackAtlas.

**Comment by JakobGartner** [comment]
The question is how to:

update the EOA when a conditional ES is received 
update the EOA when a conditional ES is revoked

Do you take care yourself about supervising the safe front-end for accepting/ rejecting a cond- ES?

You could just provide me with the flags (ES Accepted/ Revoked) and the distance from the LRBG

**Comment by jokaICS** [comment]
> update the EOA when a conditional ES is revoked

Haven't considered that case yet -- but do we need to update the EOA when a CES is revoked? When we accept a CES, all MA data beyond the new stop location has to be deleted, so we need to request a new MA anyway, don't we?

> Do you take care yourself about supervising the safe front-end for accepting/ rejecting a cond- ES?

Yes.

> You could just provide me with the flags (ES Accepted/ Revoked) and the distance from the LRBG

OK. According to SRS, there could be multiple CES; but since we only accept an CES if its EOA is more restrictive than the current one, a simple flag for "CES Revoked" should suffice (assuming that we don't change the EOA when a CES is revoked).

**Comment by JakobGartner** [comment]
> On 10 Aug 2015, at 14:57, Johannes Kastner <notifications@github.com> wrote:
> 
> update the EOA when a conditional ES is revoked
> 
> Haven't considered that case yet -- but do we need to update the EOA when a CES is revoked? When we accept a CES, all MA data beyond the new stop location has to be deleted, so we need to request a new MA anyway, don't we?
> 
> 

I found this case a bit tricky, what is if we have several CES? Do you propagate the most restrictive one?
What happens if this is revoked: Usually nothing, because the new EOA would be beyond the old one .

I guess your assumption is right, we need a new MA request. 



> Do you take care yourself about supervising the safe front-end for accepting/ rejecting a cond- ES?
> 
> Yes.
> 
> You could just provide me with the flags (ES Accepted/ Revoked) and the distance from the LRBG
> 
> OK. According to SRS, there could be multiple CES; but since we only accept an CES if its EOA is more restrictive than the current one, a simple flag for "CES Revoked" should suffice (assuming that we don't change the EOA when a CES is revoked).
> 


Yes, I compressed my needs, now expressing more precisely 

- If accepted: Distance and flag “CES received in this cycle”
- if revoked, just a flag “CES revoked in this cycle”

I shall assume that due to the inherent logic, only one CES at a time can have an effect on the EOA.

**Comment by jokaICS** [comment]
> I shall assume that due to the inherent logic, only one CES at a time can have an effect on the EOA.

I agree: whenever we receive a CES, we either accept it (if it is more restrictive than the current EOA), in which case the old EOA is replaced with the new stop location, and all information beyond the new EOA is deleted. Or we reject it, which has no effect on the EOA.

> - if revoked, just a flag “CES revoked in this cycle”

To be in accordance with the SRS, this flag probably must only be set, when **all** pending CES have been revoked. However, I'd like to defer handling of multiple concurrent CES until after we have integrated a first draft of the ES management into the TrackAtlas (handling of concurrent messages should be completely internal to the ES management operator).

BTW: what is the workflow for ES integration? I've created a new top-level operator `Manage_EmergencyStop` in the `EmergencyStop` package of `TrackAtlas.etp` for handling of both, UES and CES (currently it only resides in my personal fork). Will you do the merge/ integration, or should I do it myself?

**Comment by JakobGartner** [comment]
> On 10 Aug 2015, at 16:51, Johannes Kastner <notifications@github.com> wrote:
> 
> I shall assume that due to the inherent logic, only one CES at a time can have an effect on the EOA.
> 
> I agree: whenever we receive a CES, we either accept it (if it is more restrictive than the current EOA), in which case the old EOA is replaced with the new stop location, and all information beyond the new EOA is deleted. Or we reject it, which has no effect on the EOA.
> 
> if revoked, just a flag “CES revoked in this cycle”
> To be in accordance with the SRS, this flag probably must only be set, when all pending CES have been revoked. However, I'd like to defer handling of multiple concurrent CES until after we have integrated a first draft of the ES management into the TrackAtlas (handling of concurrent messages should be completely internal to the ES management operator).
> 
> 

OK

> BTW: what is the workflow for ES integration? I've created a new top-level operator Manage_EmergencyStop in the EmergencyStop package of TrackAtlas.etp for handling of both, UES and CES (currently it only resides in my personal fork). Will you do the merge/ integration, or should I do it myself?
> 

I would recommend that you create a package inside the TrackAtlas project directory, where your component lives. 
I will then handle integration to the top level of this module.
