### ISSUE TITLE
BG_Types_Pkg::cMaxNoOfLinkedBGs should be set to 33

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#624]
... to extend the capacity of announceable BG within one datagram and the overall storage capacity for BGs. 

Assigned to @BerndHekele, due to the current file lock for BG_Types_Pkg.

fyi: @JakobGartner; @BaseliyosJacob

**Comment by BerndHekele** [comment]
I made a quick ccheck on the used types.
The change is not straightforward and needs some preparation.

I propose to defer this change also to the next iteration.

**Comment by BerndHekele** [comment]
Correction implemented.
