### ISSUE TITLE
US 13-16: check balises referenced in User Story Descriptions

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#625]
@BaseliyosJacob could you please check the balises referenced in the User Story Descriptions 13 and 16? BG202 and BG204 are not supported by the current track model a.f.a.i.k.

**Comment by BaseliyosJacob** [comment]
Dear Johannes,

the US 13 does not mean BG. SMB = Signal Marker Board

![image](https://cloud.githubusercontent.com/assets/3975810/9060702/7a95f572-3ab6-11e5-92c9-1c504b126a96.png)


Therefore you the train passes the SMB 202 and SMB 204 instead of light-signal

**Comment by jokaICS** [comment]
Sorry :flushed:, so I will close this issue.
