### ISSUE TITLE
Packet 255 in radio messages

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#626]
Some radio messages contain the packet 255 as last packet. According to 7.4.4.1 in the SRS, the packet 255 is not allowed in radio messages.

**Comment by JakobGartner** [comment]
oh, ok. 
This will be removed.

**Comment by mairamou** [comment]
done

**Comment by JakobGartner** [comment]
@stefan-karg can this be closed?

**Comment by stefan-karg** [comment]
Fixed.
