### ISSUE TITLE
Track adhesion integration

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#627]
If this has been clarified before, sorry, overlooked. 
Shall I model reduced adhesion conditions? 
 * do we honour a driver input (bool) @Berndhekele ? 
 * are there any related messages on the track (I think package 71) @JakobG ?

Other remarks?

**Comment by JakobGartner** [comment]
Jakob Gaertner

No adhesion info
No train specific info
On the current track

We need to look what the new user stories will bring


On 04.08.2015, at 18:09, Thorsten Schulz <notifications@github.com> wrote:

If this has been clarified before, sorry, overlooked.
Shall I model reduced adhesion conditions?

   - do we honour a driver input (bool) @Berndhekele
   <https://github.com/Berndhekele> ?
   - are there any related messages on the track (I think package 71)
   @JakobG <https://github.com/JakobG> ?

Other remarks?

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/627>.

**Comment by T12z** [comment]
Track adhesion functions will not be implemented in the scope of this year's releases.
There is no input data, and the interfaces are lacking certain bits of information.
