### ISSUE TITLE
Radio Header (track to train): NID_LRBG lacks of NID_C information

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#629]
The NID_LRBG field in the radio header Radio_Types_Pkg::Radio_TrackTrain_Header_T received from test environment lacks of NID_C information. 
NID_LRBG is an alternative representation of NID_C and NID_BG. NID_C must not be omitted, since there is no new country field provided as within packets (packet 5, ..).

The bug prevents CalculateTrainPosition from accepting linking information received via radio.

@JakobGartner

**Comment by JakobGartner** [comment]
Radio_Types_Pkg::Radio_TrackTrain_Header_T is not under our umbrella (not myself, not @mairamou )
It is a type that attempts to transport information from the radio decoding channel through the model.

It merges information from different sources while appearing as an actual header which it isn't. 

None of the messages in Subset-026 chapter 8 contains NID_C information. 
The EVC must maintain the currently valid NID_C depending on the packets received from track onboard. 

We have to discuss where to allocate such a function. 

The track (=balise) model and the RBC messages model only reflect Subset-026 chapters 6-8.

For messages, a compressed type is used which is called TM_radio_messages::M_TrainTrackRadio_T.
We use a conversion operator (TM_RBC_conversions::compressed_to_Radio_Track_Train_H) to convert to the type you mentioned (as we did not want to create a big construction site for this iteration).
This operator was part of the models contributed for #497

We can only put information inside that we know... which means, which is extracted from the track to train messages. Non of the Track to Train messages contains NID_C information, hence a model representing them (including a "union" type for the header) cannot carry it either. It must be added onboard. 


I have on my table the task (for next iteration) to deeply analyse the way messages/packets are to be handled in the EVC as they have some hierarchical connection which is not well described in the SRS.

I propose that you hardcode NID_C to 426 for this iteration, if we don't find a better workaround.

**Comment by JakobGartner** [comment]
Looking at it, what track messages does right now is to transport the "raw value" in the range of 0-16777215, and does not do the decoding from the two data fields that are encoded in the variable.

This chain of errors starts already in the script that decodes the JRU data.
Mairamou used the data found there to fill this field ....

I think we have three steps now:

1) workaround: I propose you hardcode it
2) Update of TrackMessages (actually this is in the same class of work as the BCD encoding and the bit-position coded variables) ---> I will open a separate issue for this as we need to coordinate such an action) 
3) Update of the RBC simulation model to reflect the new interpretation of the type

I propose that after implementing the workaround in Calculate Train Position, you assign it back to me.

**Comment by UweSteinkeFromSiemens** [comment]
Thank's a lot for your fast response. Sounds ok, but due to other activities, I will analyze it in detail on monday. 
Nevertheless, as I understand the problem, NID_LRBG is sent from track to train via radio and should pass the EVC input channel unchanged. If NID_C is currently not reflected in NID_LRBG, the chain of bugs may already start in the Subset-026 spec ...

**Comment by JakobGartner** [comment]
I have provided a workaround which is more realistic. 

You can use the operator TM_conversions::DECODE_NID_LRBG in your model. @mairamou will update the simulation model accordingly right now. This change of the simulation model will be transparent for any consumer of NID_LRBG who is ignoring NID_C for now... the others will have to apply the workaround provided. 

The next iteration of TrackMessages will contain this conversion inside its infrastructure (if you use the right types) (you will have to remove that operator locally then)

**Comment by mairamou** [comment]
I have updated Amsterdam Utrecht track.
All messages now have the variable NID_LRBG filled as follows:
XXXXYYYYY 
where X is NID_C and Y is NID_BG.
(NID_C is assumed to be 426 at each section as this is consistent with the position reports I see)

Any user of NID_LRBG received from track must now use the operator TM_conversions::DECODE_NID_LRBG as a workaround until @JakobGartner has updated TrackMessages to support this encoding systematically. 

(the change is NOT transparent to current users of NID_LRBG who just read it as it was a NID_BG)

**Comment by UweSteinkeFromSiemens** [comment]
Dear Mairamou,
is TM_conversions::DECODE_NID_LRBG in line with CalculateTrainPosition_Pkg::BG_utilities_Pkg::nidC_nidBG_2_NIDLRBG/ and CalculateTrainPosition_Pkg::BG_utilities_Pkg::NIDLRBG_2_nidC_nidBG/ ?

**Comment by mairamou** [comment]
hmm, I did not check. As you raised the issue I did not imagine you may have a solution. 

I will have a look and comment but now have mor urgent things to do (documentation with this hell of TeX )

**Comment by JakobGartner** [comment]
In principle it looks like your operators 
CalculateTrainPosition_Pkg::BG_utilities_Pkg::nidC_nidBG_2_NIDLRBG/ and CalculateTrainPosition_Pkg::BG_utilities_Pkg::NIDLRBG_2_nidC_nidBG/ 
are close to  TM_conversions::DECODE_NID_LRBG . 

The main difference is that  TM_conversions::DECODE_NID_LRBG  is decoding the data as encoded by the trackside simulation part (the bit fields are already somehow preprocessed integer values)

**Comment by BerndHekele** [comment]
Is it possible the solution has an impact on the triggering of messages?
Since loading your solution I do not see any triggers from the RBC.

I need an urgent soltion to get rid of this side effect.

cu
Bernd

**Comment by JakobGartner** [comment]
Hmm.

it is possible that RBC is using NID_LRBG? 
But it would be curious because normally the triggering is done before the sending of the message.
The only thing I can imagine is that during the loopback of radio messages through the RBC something funny happens.

Anyway, we can provide a solution quickly. 

I will check with priority #1


Jakob

**Comment by JakobGartner** [comment]
I have rolled the change back, with some additions:

- the “new” encoding is now saved in a package (which is not yet used) for a future change
- the “old” encoding (NID_LRBG = NID_BG) is now used again

- the operator TM_conversions::DECODE_NID_LRBG is now hardcoded to NID_C= 426 to provide transparent behaviour


Does it work again?

The ICS team could, in a future step, simplify the RBC and remove this loopback which is not logic and creates unnecessary dependencies.

**Comment by UweSteinkeFromSiemens** [comment]
XXXXYYYYY, where X is NID_C and Y is NID_BG, and TM_conversions::DECODE_NID_LRBG are in line with CalculateTrainPosition_Pkg::BG_utilities_Pkg::nidC_nidBG_2_NIDLRBG/ and CalculateTrainPosition_Pkg::BG_utilities_Pkg::NIDLRBG_2_nidC_nidBG/.

**Comment by UweSteinkeFromSiemens** [comment]
I just picked the current model "TestbenchIntegration.etp" from github to continue with the analysis from Thursday and see, what has been changed meanwhile. 
I did not use TM_conversions::DECODE_NID_LRBG so far, so the misbehaviour should be similar to what I saw before. 

My findings: 
- After passing BGs 353, 354, 351, the first datagram from radio with linking information is received. 
- NID_LRBG is 42600351: the intention, I suppose, is the equivalence of NID_C = 426, NID_BG = 351 as the reference LRBG. 

Let's calculate: 
- 42600351 d = 10 1000 1010 0000 0111 1001 1111 b. 
- The lower 14 bits are evaluated to NID_BG = 00 0111 1001 1111 b = 1951 d. 
- The upper 12 bits are evaluated to NID_C  =  10 1000 1010 00 b = 2600 d. 
- The upper 12 bits shortened to 10 bits (only 10 bits are foreseen for NID_C): 
1000 1010 00 b = 552 d.

I think, this is not what was intended. I could propably compensate this as a dirty fix at the inputs of calculateTrainPosition, but this might not be the best place.

**Comment by JakobGartner** [comment]
Hello Uwe,

1. The change on the track (adding the NID_C info to NID_LRBG has been since rolled back, as it seemed that the RBC model has some interference with that (it only digests the “BG-only LRBG value)
So, on the current version of the Track Model, all the NID_LRBG values are “wrong again” (using BG only)
2. TM_conversions::DECODE_NID_LRBG, as I wrote, does not decode from bitlevel representation but is using a more high-level integer encoding. (just taking the first integer digits as NID_C, and the last as NID_BG)
3. TM_conversions::DECODE_NID_LRBG now converts the NID_BG - only info from track to NID_C 426 (which is taken from a local constant) and the actual NID_BG, as a workaround until we see what needs to be done on the RBC model which ICS is upgrading.

**Comment by UweSteinkeFromSiemens** [comment]
calculateTrainPosition now comprises a dirty compensation, by using DECODE_NID_LRBG and modifying its output value. ' will see, what yet happens to the linking information (packet 5)...

**Comment by stefan-karg** [comment]
Dear Jakob,

I'm facing the problem at the moment, that the radio messages triggered by the RBC (e.g. NID_MESSAGE 3, which contains the MA) still contain the NID_LRBG = NID_C + NID_BG while the DECODE_NID_LRBG-operator just forwards the value of NID_LRBG to the output NID_BG and sets NID_C constantly to 426 as described above.

I need to access the values of NID_C and NID_LRBG since I need both values for finding the correct reference BG for radio messages in the ValidateDataDirection check.

**Comment by JakobGartner** [comment]
OK. 

It seems that this change was done by Mairamou, but she forgot to push it.

Track Model Amsterdam Utrecht updated.


And I also changed the DECODE_NID_LRBG.

It now only outputs a NID_C if a valid NID_BG is received.

**Comment by UweSteinkeFromSiemens** [comment]
To answer "What happens to the linking information": see #648.

**Comment by UweSteinkeFromSiemens** [comment]
Should have been accomplised. I close this issue.
