### ISSUE TITLE
EVC-Model needs flags for ElementFilter

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#630]
The following information is currently not available:
 - pendingL1Transition
 - pendingL12L3Transition
 - SPPAndGradientOnBoard
 - MACoverNotFullLength

I assume to get the pending flags from Modes and Level Management and the other flags from TrackAtlas.

I'm currently testing a workaround.

**Comment by JakobGartner** [comment]
yes, after first analysis I agree with your assessment.
Actually SPPAndGradientOnBoard can be added with a quick fix, for MACoverNotFullLength I must analyse what it means. Do you have a SRS reference?

**Comment by BerndHekele** [comment]
correction available
