### ISSUE TITLE
Manage_TrackSideInformation_Integration: handling of emergency messages

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#631]
@BerndHekele 
Acc. to §3.16.3.1, the consistency checks (timing, sequence) shall not apply to high priority messages. Bypassing these checks is already supported by setting `Manage_TrackSideInformation_Integration.fullChecks = false`.
However, this input is currently short-circuited to `true`, and it looks to me as if the incoming `API_TrackSideInput_T` does not carry the required message priority information (?).

Should we ignore this issue for now?

**Comment by JakobGartner** [comment]
I cannot speak for the designers of the consistency checks.
But we should assume (in our modules) to receive the information previously treated the right way.
If we look at the message itself, we don't care how it has been filtered before-

so my best advice is: yes, it's not our problem, and we ignore it as far as our work is concerned

**Comment by BerndHekele** [comment]
Hi,
the current solution does not support messages of different priority.
This needs to be added in the next iteration.
The mentioned full-check is more related to speed up test-activities when a temporary workaround might be needed for problems.

**Comment by jokaICS** [comment]
Closed, since it doesn`t concern the actual handling of emergency stop messages by `TrackAtlas` (see #636).
