### ISSUE TITLE
TrackAtlas/Build_MA: reject incoming MAs during active emergency stop

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#632]
Acc. to §3.1.2.4 new movement authorities shall be rejected while there is an active (not-revoked) emergency message. @JakobGartner Can we handle this in `Build_MA`, triggered by a new bool input `rejectNewMA`?

**Comment by JakobGartner** [comment]
Yes if you provide me such flag (meaning that you have an active EM) I can use it.

**Comment by jokaICS** [comment]
Implemented
