### ISSUE TITLE
Bitwalker-Bytewalker-Interface: Transformation required

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#635]
For interfacing the Bitwalker with its C-structured input/output side to the EVC Scade model a transformation between the C structures and the compressed integer arrays of the Scade model is required, to connect the EVC model with I/O subsystems of existing EVC hardware platforms or Test Labs. 

A solution could be found by providing an EVC model with an alternative fassade offering the C-structure side of the Bytewalker at its external interfaces and using the appropriate conversion operators from the TM module. 

@jensgerlach , @JakobGartner , @mairamou, @Assmann-Siemens , @MarcBehrens, @BerndHekele

**Comment by JakobGartner** [comment]
This is a deeper discussion, and several solutions are possible.

I did not have the time yet, but there is a concept that I believe would make it quite simple to transform bit-level SRS conformal information into a format that can the easily be transformed to the integer-based array format.
We should however first clean up the types in general, as there are several topics were the existing (legacy :-) ) types pose problems.

**Comment by UweSteinkeFromSiemens** [comment]
Must have been solved meanwhile. otherwise the integrated EVC model integration would not be working.
