### ISSUE TITLE
TrackAtlas integration

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#639]
The move to NextGen is prepared.

You can replace TrackAtlasNextGen by TrackAtlas. (the old TrackAtlas is deleted, TrackAtlas is now just a copy of ...NextGen)

When done, please close this issue, TrackAtlasNextGen will then be deleted in the next push.

**Comment by T12z** [comment]
Really??
Sorry but I have not renamed this yet, work in progress, will commit next week, still have a bug in my current changes, so I must queue a few days. (also sysml-model has top priority and I wont even make that today :frowning: )

**Comment by T12z** [comment]
update: as I am digging a few holes in my model, I need to delay this a little. Sorry!
(issue hijacked, though blocked by #654)

**Comment by T12z** [comment]
next update: with a recent pull, @JakobGartner, I cannot see the above stated links between nextGen and the new types, but I can still see the old TrackAtlasTypes types. Did I misunderstand something?
