### ISSUE TITLE
When is the train position considered as known?

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#640]
Dear Uwe,

under which conditions is the train position to be considered as known?

Currently we face the problem, that the ValidateDataDirection module needs to know if the train position is known. When we now pass the first BG, the ValidateDataDirection-module obviously gets the information from the CalculateTrainPosition-module, that the train position is unknown (which is in that cycle correct, since the data from the current BG is not processed yet by CTP). 

Is the assumption correct, that the train position is known, if the train has passed an unlinked BG ? (in our case BG352)

**Comment by JakobGartner** [comment]
According to 3.6.1.4 unlinked BGs shall never be used as LRBG
The train position is according to 3.6.1.3, the estimated train front end position, defined by the estimated distance between the LRBG and the front end of the train (along with other criteria for confidence and direction)

I assume therefore that the train position is known as soon as the first LRBG has been passed.


(Answering because I was fighting with the same question right now…, even if in a different context)

**Comment by stefan-karg** [comment]
In this case, we have the following issue:

The first 3 BGs are unlinked (352, 353, 354), since the linking data is transmitted after passing BG 354. Until that point no LRBG is known.

The SRS states, in 3.6.3.1.3.1:

"If the train position is unknown, data received from any transmission medium valid for one direction only (nominal or reverse) shall be rejected by the onboard equipment. Data valid for both directions shall be evaluated (see section 4.8)."

The consequence would be currently, that all packets necessary for establishing the radio session are rejected, since the train position is not known.

After discussing this problem now with Baseliyos, the validate data direction module should take into account, when the train is in level NTC and still process the balises even when the trainPositionKnown-flag set by CalculateTrainPosition is not true, since the behavior in level NTC is not defined by the SRS.

**Comment by JakobGartner** [comment]
lol

welcome to the SRS.





are we sure that they are marked as unlinked , or do we just not have linking information?

a linked balise group is one that is marked as linked, this is independent of actual linking info being available 



BG352 is unlinked

BG353 and BG354 are linked (according to q_link)

according to the justification 3.6.1.4.1 they should hence be known to the RBC, and the position is known.

This is also consistent with the JRU data where the train position trace for LRBG switches from 602 to 353 after passing the BG353

**Comment by JakobGartner** [comment]
it seems that TrainPosition has to take into account this issue.
A workaround could be to use directly the q_linked info from the BGs ?

**Comment by UweSteinkeFromSiemens** [comment]
calculateTrainPosition sets the flag "trainPositionIsUnknown", 
- when no linked BG (which not neccessarily has been announced) has been passed before or 
- if NID_BG of this BG has the special value "Identity is unknown".

Practically, "trainPositionIsUnknown" means that there is no LRBG available to be used as a common location reference BG between track and train. calculateTrainPosition provides the train position within the OBU coordinate system regardless from this flag. 

Please note, that "trainposition" of calculateTrainPositon refers to the trains balise antenna. For the front end, "estimatedFrontEndPosition", "minSafeFrontEndPosition" and "maxSafeFrontEndPosition" are provided.

So, is there a problem any more?

**Comment by UweSteinkeFromSiemens** [comment]
Done.
