### ISSUE TITLE
InformationFilter: When working on Msg 3 : Concept of Delayed Messages does not fit to the use-case

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#646]
When analysing the information filter we had a long discussion on whether complete messages need to be  stored or only packets.

Looking into msg 3 of our 7th scenario, I believe we made the wrond decision.

Msg 3 has packet 41 and packet 15 for nominal direction.

Packet 41 indicates the requested level transition to level 2.
First problem: in the current implementation, the information level 2 transition pending comes from a later cycle back to the entry.
Proposed solution: packet 41 is evaluated as a part of the handling of the incoming message.
Otherwise, the complete message has to be ignored.

Second problem: packet 41 has to be forwarded to level management, packet 15 (and others) have to be stored for after the level transition.

With this use-case, we have two potential reasons for the error: message flow is not correct or the element filter needs to be able to split this information in parts to store and parts to send.

I will take care for a work-around 
@BaseliyosJacob : can you please analyse the use-case.

**Comment by BerndHekele** [comment]
I just recognised the finding was incomplete. The first message 3 after balise 354 is sent for reverse and packet 41 for nominal.
Is this correct?

**Comment by JakobGartner** [comment]
I see this as a part of an overall re- analysis of the message/ packet treatment onboard.

I believe that filtering the messages/ packets and looking at their content (evaluating them) are two orthogonal problems.

We have to ensure a consistent data flow for the messages and packets and maybe simplify the filter (a lot)



I found the documents from Lloyds and from Alstom quite helpful to get an initial understanding 

by the way, are you talking about the RBC message sent for LRBG 354?
All data are consistently for “nominal”, with exception of packet3 which is valid both directions.(for both messages 3 sent with NID_LRBG = (426 , 354) 
(the LRBG354_Pxxx_1 are for the first message 3, the LRBG354_Pxxx_2 for the 2nd)
Q_DIR: 1 = nominal, Q_DIR: 2 = both directions)



BG354 has also been passed in direction “nominal”.

For the P41 problem I lack understanding for now. 

But why does the raw packet 41 need to be stored at the filter? 
Doesn’t M&L handle priority lists?


I guess this will need a whiteboard discussion …

But we should try to avoid to eval packets at multiple points if possible, especially if there are FBY loops and stored messages/ packets involved.

**Comment by JakobGartner** [comment]
The first packet containing level transition info is sent directly from BG354 inside a balise telegram and contains P46 for each direction, separately. 

The nominal info contains also L2 transition info as first element of the iteration (while the main section contains STM/ATB)


The RBC messages 3 for LRBG354 contain only information that is valid for nominal (while P3 is valid for both directions which should also be OK for the nominal pass of BG354)

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

i am not sure that i got your request. But i understand that you need a more refined analysis of the Use Case 7 according to the level transition:

Use Case 7:

Starting at Information from 

BG 354

![image](https://cloud.githubusercontent.com/assets/3975810/9156047/ff20003e-3ecc-11e5-8282-1b008a2930c5.png)

**Comment by BaseliyosJacob** [comment]
Next Step

Message 3

Comes with Packet 15, 21, 27,3, 5,41, 65

Packet 41 Level Transition Order should triggering the Level Transiion change on the Level and Mode Management

![image](https://cloud.githubusercontent.com/assets/3975810/9156077/7c783532-3ece-11e5-82c9-ebc4d85fc721.png)

**Comment by JakobGartner** [comment]
All this is working in the balise model and the radio message model inside
the AmsterdamUtrecht project


On 09.08.2015, at 19:40, Baseliyos Jacob <notifications@github.com> wrote:

Next Step

Message 3

Comes with Packet 15, 21, 27,3, 5,41, 65

Packet 41 Level Transition Order should triggering the Level Transiion
change on the Level and Mode Management

[image: image]
<https://cloud.githubusercontent.com/assets/3975810/9156077/7c783532-3ece-11e5-82c9-ebc4d85fc721.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/646#issuecomment-129221283>.

**Comment by BaseliyosJacob** [comment]
Next Step

After triggering the Mode and Level Management with Packet 41 

--> request to ack Level Change from NTC (ATB) to Level 2 Should be sent to DMI
--> Driver (DMI) will ack the request and mode and level management will change from Level NTC to Level 2

![image](https://cloud.githubusercontent.com/assets/3975810/9156085/e54c449a-3ece-11e5-9227-57ba3c5d48fc.png)

According to 

D_LEVELTR(15bits) = 801.0m(801)
in Packet 41 transition should be not later than in 801 m

--> then change to from Mode SN to Mode FS

--> Level 2 and Mode FS will be displayed on DMI

**Comment by BaseliyosJacob** [comment]
Just a qestion!! I am not familiar with Marielles Modell

But checking here model quickly she implemented the P 41 for level transiton
![image](https://cloud.githubusercontent.com/assets/3975810/9156103/80e251e2-3ecf-11e5-9ce9-06736b6a115d.png)

**Comment by BaseliyosJacob** [comment]
Did anybody check it`? Maybe a priority in Marielles Table is missing!

**Comment by JakobGartner** [comment]
Trackatlas to ModeLevel interface contains priority tables from p41 and p46

Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



On 09.08.2015, at 19:48, Baseliyos Jacob <notifications@github.com> wrote:

Just a qestion!! I am not familiar with Marielles Modell

But checking here model quickly she implemented the P 41 for level transiton
[image: image]
<https://cloud.githubusercontent.com/assets/3975810/9156103/80e251e2-3ecf-11e5-9ce9-06736b6a115d.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/646#issuecomment-129221690>.

**Comment by BerndHekele** [comment]
I have seen message 3 after balise 354  in reverse. Can you please check in the track-model whether this is to be corrected?

**Comment by JakobGartner** [comment]
I have analysed.

The track model does not send any information Q_DIR: “reverse”.

- All packets sent for LRBG=354 are set to "nominal"
- The message 3 sent from Build_RBC_LRBG_354_D_00275_3_M003 and from do not contain any Q_DIR field at all (as Message 3 does not have it at all)

The problem now arises here:

Message 3 is translated into Radio_Types_Pkg::Radio_TrackTrain_Header_T in the operator TM_RBC_conversions::M003_to_Radio_Track_Train_H where Q_DIR (as it is anyway invalid for this Message type) is set to an arbitrary value (which in this case is “reverse”.

Yet another example for this type definition being not very clean, and the need to replace it in the next iteration, as well as the need to have “information not valid” field on all enumerated types (which is also better for clean error handling).
TrackMessages will get a lot of work to do...


So what do we do now?

Obviously it is wrong to rely on a data field (q_dir) for filtering which is nonexistent.
No part of the ReceiveTrackSide should read this. 
A M3 has no Q_DIR info at all (and I am sure that this kind of pseudo-overloading appears at more places)


As a quick workaround I can offer to change TM_RBC_conversions::M003_to_Radio_Track_Train_H so that it takes Q_DIR from a packet that comes with the Message 3, but this is a *DIRTY* solution.

We need to review the way messages are treated overall.

**Comment by BerndHekele** [comment]
Thanks for the analysis.
We do not need a workaround for the issue. Validate Data Direction takes care on using the correct information. Maybe we have a problem caused by the weired use-case where the trainposition is not known due to running in Level NTC.

We will look for a proper correction.

**Comment by BerndHekele** [comment]
We made some progress on the issue noe.
The incorrect direction in the context of msg 3 was caused by the confusion about the Nid_C and NID_BG in messages. This works in the current model.

I'm now forwarding P41 and P15 directly to Mode and Level. (under test).

**Comment by JakobGartner** [comment]
P41 and P15 are already forwarded in the interface from TrackAtlas





On 10.08.2015, at 23:27, Bernd Hekele <notifications@github.com> wrote:

We made some progress on the issue noe.
The incorrect direction in the context of msg 3 was caused by the confusion
about the Nid_C and NID_BG in messages. This works in the current model.

I'm now forwarding P41 and P15 directly to Mode and Level. (under test).

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/646#issuecomment-129612389>.

**Comment by BerndHekele** [comment]
Last time you mentioned the interfaces are not connected yet.
And they did  not fit to the current M&L interface.

And -last but not least - trackatlas is also behind the filter.

**Comment by JakobGartner** [comment]
They have been connected meanwhile and also adapted to the existing
interfaces in the input management part of M&L



On 10.08.2015, at 23:44, Bernd Hekele <notifications@github.com> wrote:

Last time you mentioned the interfaces are not connected yet.
And they did not fit to the current M&L interface.

And -last but not least - trackatlas is also behind the filter.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/646#issuecomment-129620139>.

**Comment by BerndHekele** [comment]
I'll give it a try. I'm now using a model without element-filter. And I connected the first part of the Modes and Level.

**Comment by BerndHekele** [comment]
correction is tested.
