### ISSUE TITLE
Message 3: Gradient profile is missing

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#647]
Dear Mairamou,

in the message 3 with trigger ID 354002753 the packet 21 (Gradient Profile) is missing.

**Comment by mairamou** [comment]
Hmm. 

I disagree. 

Is there a problem with propagation? 

On 2015-08-10 15:46, Stefan Karg wrote: 

> Dear Mairamou, 
> 
> in the message 3 with trigger ID 354002753 the packet 21 (Gradient Profile) is missing. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/openETCS/modeling/issues/647

**Comment by mairamou** [comment]
First bug analysis 

- The data are present (packet data, the track model seems to have no
error) 

However, encoding at TrackMessages seems to have a problem, I will
check. 

Result: Data are input to the compression channel, but not added to the
compressed packets nor the metadata. 

On 2015-08-10 15:46, Stefan Karg wrote: 

> Assigned #647 [1] to @mairamou [2]. 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/openETCS/modeling/issues/647
[2] https://github.com/mairamou
[3] https://github.com/openETCS/modeling/issues/647#event-378004306

**Comment by mairamou** [comment]
I have repaired. 

Reason was "valid" flag at Packet 21 simulation definition set to
'false' 

On 2015-08-10 15:46, Stefan Karg wrote: 

> Assigned #647 [1] to @mairamou [2]. 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/openETCS/modeling/issues/647
[2] https://github.com/mairamou
[3] https://github.com/openETCS/modeling/issues/647#event-378004306

**Comment by stefan-karg** [comment]
The gradient profile is now included. Thank you for your quick support!
