### ISSUE TITLE
TestBench_Integration.etp: incorrect linking messages (packet 5) received via radio

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#648]
While testing the calculateTrainPosition embedded into Testbench_Integration, it could  be observed, 

- that the radio message with linking information to be sent to the train after passing BG 354 or 351 occasionally is not received by calculateTrainPosition
- the linking information occasionally when received from radio, uses BG 351 as LRBG, and announces BG 351 within the same datagram with d_link = 812
- when correct linking information is received after passing BG 351 (LRBG = 351), linking consistency errors occur: 
  - passing BG 355 raises linking consistency error flag “missed” = BG out of range, i. e. found just behind its expectation window)
  - passing BG 356 raises linking consistency error flag “passedBG_foundNotWhereExpected”, (violates its expectation window) 

I suppose, due to the free running simulation stimulated by accelarating the train manually, the effects are not reliable reproducable.

**Comment by BerndHekele** [comment]
This issue is beyond the area where we have released the track.
The linking information has to be sent when the level 2 is activated. In ntc linking information is not relevant.

(And we did not yet manage to switch levels)

**Comment by mairamou** [comment]
It is true for the M3 sent at BG354 that the train is still in STM mode 

However, for the M3 sent after passing BG351, the train is already in
FullSupervision. 

Probably this solves the question why this message is re-sent after
passing BG351: It was not taken into account before. 

Does calcTrainPosition observe the Level? 

On 2015-08-10 17:00, Bernd Hekele wrote: 

> This issue is beyond the area where we have released the track.
> The linking information has to be sent when the level 2 is activated. In ntc linking information is not relevant. 
> 
> (And we did not yet manage to switch levels) 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/648#issuecomment-129482568

**Comment by JakobGartner** [comment]
The Message 3 sent at position BG351 + 54,9 m contains BG354 as value for the LRBG

Packet 5 has, according to the SRS, 1 set of variables (which is mandatory) to announce the next linked BG after the LRBG.
This is announced as BG351 with d_link= 812m
(This structure is translated to the all-iterator structure in the legacy type definition, as requested)

Note that the message 3 (and all its packets) sent after BG351 still refer to BG354, even if the LRBG has now changed to 351. 

The problem seems to be that the system is yet unable to process messages that refer to an LRBG different from (older than) the current one 

The LRBG for a given message stays constant even if the train moves on...

**Comment by JakobGartner** [comment]
We may need to check the trigger mechanism in RBC simulation (make sure that the message is released also when the position is not "exactly hit".

**Comment by jokaICS** [comment]
The trigger window for the message at BG351 + 54,9m is [49,9m; 59,9m], but depending on the current speed + integration step size this might be to small?

**Comment by JakobGartner** [comment]
It is in any case larger than the trigger windows for the balises, which seem to work.

To be discussed with Bernd and Stefan

**Comment by BerndHekele** [comment]
Currently, I have no problems with the window when riding in a moderate speed (100 km/h).
The sporadic behaviour was mainly due to errors - but we are making progress now.

**Comment by jokaICS** [comment]
Just for my reference: what is the time integration step size for the train position simulation (200 ms?)

**Comment by BerndHekele** [comment]
20 ms

**Comment by UweSteinkeFromSiemens** [comment]
@mairamou : calculateTrainPosition does not consider the level. calculateTrainPosition expects to receive only those messages that are appropriate for the current OBU state. 

@BerndHekele : if a message must not be evaluated due to the level, these message must not be forwarded to calculateTrainPosition. This applies to messages from BGs as will as from RBC. => InformationFilter.

@jokaICS : The cycle period of 20 ms might be affected by the PC performance. Therefore, I would not rely on it. 

@JakobGartner : "The problem seems to be that the system is yet unable to process messages that refer to an LRBG different from (older than) the current one" : This is also my impression. Furthermore, the lack of reproducibility within the test environment hinders analysis.

**Comment by UweSteinkeFromSiemens** [comment]
Seems to be outdated.
