### ISSUE TITLE
ModesAndLevelManagment: Level change is not indicated correctly atr the DMI

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#652]
valid flag and ack-requested are not passed to the DMI

**Comment by BerndHekele** [comment]
When changing to level 2 the new and old level are seen in the interface to the DMI.
However, the valid flag is not in use and the ack-request is also false.

I  will provide  a workaround.

**Comment by BerndHekele** [comment]
Status Update:
The Input Model Input of Mode and Level does not consider the q_scale parameter in calculating the distances. Error is in the model Input_Level_Transition.

**Comment by BerndHekele** [comment]
Correction in output model: valid flag also set for level requests (Proposed solution in test).
Correction in input model: make use of q_scale and derive ack-need from distance parameter (proposed solution under test).

Analysis in work for:
announced level is used as next level also outside the levels view.
This results in modes going to trip (some data not yet available).

**Comment by BerndHekele** [comment]
I have just observed a side-effect: level ack is now also requested in the start of mission phase .
I believe this is not according to the startard, @BaseliyosJacob .

**Comment by BerndHekele** [comment]
Solution for side-effect is avaible now.
Analysis of trip-problem: solution in test.

**Comment by BerndHekele** [comment]
Status Update:
Input_Level_Transition sets  transitionType to immediate.

**Comment by BerndHekele** [comment]
Additional Corrections needed in order to model the srs conform ack-window at the end of the passing area.

**Comment by BerndHekele** [comment]
When having started the missin Levels checks on changes Level_NTC = Level_NTC and requests acknowledgment from the driver.
This behaviour is not clear to me - needs clarification.

**Comment by BerndHekele** [comment]
A working correction is now available.
EVC changes to level 2 and mode fs.
The position where this change happens needs a correction. Event shall happen at the position announced with the level transition.

**Comment by MariellePetitDoche** [comment]
Indeed the flags were not used in the models of Mode and Level I  know as the interface was not clearly  defined and the definition of "valid" flag not given.
Could you give me a clear state of the model :
- what is the problem ? a clear scenario of expected behavior and behavior in error will be nice.
- what  changes have been made ?
- what is left to do ?

Besides, i would like to understood your entry model to detect bug : which node do you valid.

**Comment by BerndHekele** [comment]
In the old implementation we had problems in the function driverAck and in the way data is stored.
I have looked for a rather robust solution and have taken the store of the level conditions and other "bits" out of the levels model. 
In addition, some handling of input parameters has been corrected in the level and modes input model.
I believe handling of input parameters is now similar to the handling in modes?
I propose to have a similare way to use interfaces both in modes and levels.

I have currently no remaining open issue with Levels. But I would like to see a confirmation from your side based on a review or test, maybe? I believe, the author in the beginning had a different idea about the sequence of the subfunctions compared to my solution.

**Comment by BerndHekele** [comment]
To answer the last question: I use the evc-model https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_PreIntegrations/openETCS_EVC/openETCS_EVC.etp together with the test model https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_PreIntegrations/Testbench_Integration/Testbench_Integration.etp.
Test case is running start of mission, followed by starting the train to run on a track from Amsterdam to Utrecht.
In this model the change of levels and the change of modes is triggered by elements on the track.
Modes worked very smooth until now - no problems at all - thanks.

**Comment by MariellePetitDoche** [comment]
I do not understand the modification made and in particular the introduction of the new input of M&L " forLevelTransition" of type "Level_And_Mode_Types_Pkg::T_Data_From_TrackForLevelChange".
Now this is used in particular to  compute the information "MA_SSP__Gradient_available" in "Input_MA_SSP_Gradient" which has a strong impact on the mode management and not only on the level management.
For me it is not possible in the current  state of the model and documentation to understand how it is produce this input and his exact meaning.


The information I need for mode and level, concerning MA, SSP  and gradient is that we have received the corresponding packets, correct which contain an information that speed and supervision function can used  (ie. the train is located at the right position),  to  allow to  go in FS mode.
As we discussed in may at Munich, this information is shared by several functions (at least M&L  and speed and supervision) and shall be memorized for several cycles.
For the moment as no flag, and no description are associated to  this input, I can not ensure it is correct.

**Comment by BerndHekele** [comment]
After Re-factoring of Levels the issue can be closed.
New items are covered by issues.
