### ISSUE TITLE
Position report: Scaling problem

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#659]
During the testing phase, we noticed that the trigger for the radio messages is not fired when driving with higher velocities (approx. above 150 km/h).

After analysing the problem, I found that this behaviour is related to the generation of the position report. 
For the generation of packet 0 or 1, the train position is used, which is scaled in 1 cm steps. 

The ProvidePositionReport-module writes the Q_SCALE flag to a 10 cm scale, which does not fit to the values written to D_LRBG.

In consequence the RBC converts the position of the train to the LRBG in a wrong way, which leads to very small windows for triggering the messages.

**Comment by christianstahl** [comment]
Dear Stefan,

thanks for your analysis! In the beginning of the project, we agreed on using the smallest Q_SCALE (i.e. 10cm) in the entire model. If everyone sticks to this rule, Q_SCALE should not be taken into account in any calculation. From your explanation, however, I understand at least the RBC model does. So @BerndHekele and @JakobGartner shall we take Q_SCALE into account? If yes, I can divide D_LRBG by 10 before adding it to the report. Otherwise, the RBC model should be adapted.

Christian

**Comment by jokaICS** [comment]
The RBC can cope with all three Q_SCALEs; so there shouldn't be a problem, as long as the scale set by Q_SCALE matches the actual scale used for D_LRBG (i.e. 10 cm).

**Comment by UweSteinkeFromSiemens** [comment]
Please note, that the resolution of all locations, distances etc. is 1 cm, determined by the standard Obu_BasicTypes_Pkg::L_internal_Type. Therefore, all calculations on distances given by D_* variable with a Q_SCALE factor should be converted into L_internal_Type. 

For the conversion, BasicLocationFunctions_Pkg::scaledDLINK_2_dlink can be used.

**Comment by BerndHekele** [comment]
Thanks for this comment.
I looked into the proposed function yesterday and recognised the routine is very special regarding interfaces.
Or did you add a function just handling the distance?

**Comment by jokaICS** [comment]
> For the conversion, BasicLocationFunctions_Pkg::scaledDLINK_2_dlink can be used.

Good to know... do we have a global "index" of common useful helper functions? while implementing the emergency stop management I constantly feel like I'm re-inventing the wheel.

**Comment by UweSteinkeFromSiemens** [comment]
@BerndHekele : There are several functions dealing with locations and distances in BasicLocationFunctions_Pkg. The idea is to convert all Q_SCALE & D_xxx values into Obu_BasicTypes_Pkg::L_internal_Type and then take the functions provided by BasicLocationFunctions_Pkg for calculations. 

@jokaICS :  I have the same feeling. Unfortunately, there is no such index. And I saw some people reinventing the wheel .

**Comment by christianstahl** [comment]
Thanks for your input! I will scale the D_ values.

**Comment by christianstahl** [comment]
I have uploaded a bugfix.

**Comment by stefan-karg** [comment]
Problem is solved.
