### ISSUE TITLE
MRSP in level NTC

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#661]
Dear Jakob,

currently, the MRSP in level NTC is calculated with a speed of 0, which leads to a intervention by the SDM module.

In level NTC, the EVC does not supervise the speed. From my point of view it would make sense that the TrackAtlas provides an MRSP profile with the speed limit set to the maximum speed of the train (from the train data) as long as the train is running in level NTC.

**Comment by T12z** [comment]
To add on to that,
the above point, to have a general MRSP of the trains maximum speed, would be much appreciated at *any* time. SDM is supposed to supervise the trains maximum speed given by train data. Currently it does not by own means. Always having a train's-max-speed-MRSP would the favourable solution.
cheers!

**Comment by JakobGartner** [comment]
OK, I will do. 

Mode/Level dependent speeds are not yet implemented…. I will start a simple solution for that.

**Comment by JakobGartner** [comment]
This will take 1-2 days….

**Comment by JakobGartner** [comment]
do you mean, that beyond the calculated MRSP you need, in parallel, the max train speed, at each cycle?


> On 13 Aug 2015, at 14:05, Thorsten Schulz <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> To add on to that,
> the above point, to have a general MRSP of the trains maximum speed, would be much appreciated at any time. SDM is supposed to supervise the trains maximum speed given by train data. Currently it does not by own means. Always having a train's-max-speed-MRSP would the favourable solution.
> cheers!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/openETCS/modeling/issues/661#issuecomment-130644320>.
> 

Jakob Gaertner
Managing Director
Local Energy Appliances

Jakob Gaertner
Managing Director
LEA/ Railergy

j.gaertner@lea-energy.com <mailto:j.gaertner@lea-energy.com>

Germany
Tel +49 821 907802-20
Fax +49 821 907802-99
Mob +49 151 25387841

Local Energy Appliances
Am Mittleren Moos 48
86167 Augsburg
Germany
+49 821 907802-0
http://www.lea-energy.com


Cameroon
+237 6 98291601
+237 6 63474987
+237 6 72932861

Local Energy (Cameroon) Sarl
BP14000
Yaoundé
République du Cameroun

**Comment by BerndHekele** [comment]
Hi Jakob,
can you give an update on this issue?
I need the correction for a proper level change to level 2.

kr
Bernd

**Comment by JakobGartner** [comment]
This is in work, an update of TrackAtlas is preparation for tomorrow.

**Comment by stefan-karg** [comment]
Problem solved.
