### ISSUE TITLE
trackatlas looses memory (data for mode and level

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#663]
After receiving data the  information is correctly output to Mode and Level.
But only for one cycle.
In the next cycle the output is set to default again.

I have a temporary solution available.

kr
Bernd

**Comment by JakobGartner** [comment]
It doesn't loose memory.
Marielle told me that an event marker is what she needs.
If more complex behavior is needed, no problem. But then I need to know how
long the flags must be present

Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



On 15.08.2015, at 17:23, Bernd Hekele <notifications@github.com> wrote:

After receiving data the information is correctly output to Mode and Level.
But only for one cycle.
In the next cycle the output is set to default again.

I have a temporary solution available.

kr
Bernd

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/663>.

**Comment by BerndHekele** [comment]
Concept changed in the meantime.
