### ISSUE TITLE
Need for  Library-Routine. Does it exist somewhere

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#669]
I need to find the location of a passed LRBG. LRBG Id has been received via radio.

I see 2 library routines involved which might be existing:

1. Conversion of the LRBG + NID_C received from Balise to NID_LRBG received from radio and vice versa.

2. Routine to pass the list of passed bgs for a given LRBG-ID.

Do we have this in our portfolio somewhere?

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
Yes, I will give you the reference soon.

**Comment by UweSteinkeFromSiemens** [comment]
xxx

**Comment by BerndHekele** [comment]
Thanks.
I will check.
