### ISSUE TITLE
Use Case 2: Train is running after receiving a Movement Authority (MA)

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#67]
Train is running after receving an Movement Authority (MA)

"As the End User (WP1) i want to see a demonstration of a train is running on the Track after receiving a MA."

This should be part of the modelling scope of WP 3.

**Comment by BaseliyosJacob** [comment]
Description:

Train will start of Mission for Level 2. 
The Start of Mission will be splitted in 2 Use Cases.
Use Case 2: Start of Mission - receiving of a MA Authority in Level 2.

Functions:
Procedure: Start of Mission
DMI Management: Display and enter the train parameter
MA Management: Request for MA
Level and Mode Management: Changing from Mode SB to FS

**Comment by BerndHekele** [comment]
Done
