### ISSUE TITLE
RBC-System / Utrecht-Amsterdam Track-Model LRBG without NID_C

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#671]
Hi,
I'm testing the track model in the testbench.
Maybe this is an duplicate??

I receive LRBG 354 in message 3 (without NID_C encoded). 
I thought this issue is solved meanwhile?

kr
Bernd

**Comment by JakobGartner** [comment]
We have rolled this change back because it created problems inside the RBC model which blocked us.
Uwe is using a workaround locally.

**Comment by UweSteinkeFromSiemens** [comment]
At the bottom of the diagram of CalculateTrainPosition_Pkg::msgAdapter_Pkg::msg_2_passedBG/ you may find my temporary patch.

**Comment by BerndHekele** [comment]
Correction Available.
