### ISSUE TITLE
InformationFilter: at change to level 2 stored messages are blocked.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#673]
I have observed some messages 24 blocking the transmission.
Further analysis is needed.

**Comment by BerndHekele** [comment]
Status Update:
General Messages are indeed stored in the buffer of the information filter due to an error.
Workaround is available.

**Comment by BerndHekele** [comment]
Status Update: workaround in manage track-messages available and tested.
Message 3 is now available after change of levels.

**Comment by christianstahl** [comment]
The problem has been solved with the new version of the filter which has been pushed today; see also #707 .
