### ISSUE TITLE
Dynamic Track Model - WP4 handover

### ISSUE THREAD

**Issue by mairamou** [openETCS/modeling#674]
the track model is now released.

Model: https://github.com/openETCS/modeling/tree/master/model/Scade/System/TracksideDynamicModel/TestTracks/UtrechtAmsterdam_oETCS

Documentation: https://github.com/openETCS/modeling/tree/master/model/Scade/System/TracksideDynamicModel/TestTracks/UtrechtAmsterdam_Documentation

@janWelte

**Comment by janWelte** [comment]
First Version of the Verification report is done and can be found under https://github.com/openETCS/validation/blob/master/Reports/VerificationReports/Trackside/. This part covers the design based on all available documentation.

Verification of the data in the SCADE model implementation will follow soon.

Verification Report: [Design Verification Report Trackside Modell] (https://github.com/openETCS/validation/blob/master/Reports/VerificationReports/Trackside/VerfRprt-DynamicTracksideModel_150821-jw-V01.pdf)
