### ISSUE TITLE
TrackMessage-Library: support of Message 16 & 18

### ISSUE THREAD

**Issue by apinnau** [openETCS/modeling#675]
@JakobGartner or @stefan-karg: could you add support for message 16 & 18 to the TM_RBC_conversarion library?

At the moment I can't convert messages 16 or 18 from the internal format (InfraLib::R_data_internal_T) into compressed format (TM::CompressedRadioMessage) because of missing header translation operators.

In my mind I need an expansion of the operator: **TM_RBC_conversions::compressed_to_Radio_Track_Train_H**.

For this expansion also the operators **M016_to_Radio_Track_Train_H** and **M018_to_Radio_Track_Train_H** should be added.

**Comment by JakobGartner** [comment]
OK; I will check, comment and do.

**Comment by JakobGartner** [comment]
Hello Alexander,

the operators to send the message are available, the issue, as you already pointed out, is that the conversion to the the type containing the doomed Radio_Track_Train_H for these types is missing.
It is under construction and be part of the next push

**Comment by JakobGartner** [comment]
@mairamou: can you please add a chapter on “HOWTO build a radio message” using our pattern to your doc ?

**Comment by JakobGartner** [comment]
The model has been updated

**Comment by apinnau** [comment]
The updated model works fine for me (tested with message 16). Thx!

But there are 2 error messages when loading a model which uses the library:

> Loading project Testbench_Integration.etp...
> (0) : error ERRSEM_NODE_DEC : Node TM_RBC_conversions::compressed_to_Radio_Track_Train_H : node not declared
> (0) : error ERRSEM_NODE_DEC : Node TM_RBC_conversions::compressed_to_Radio_Track_Train_H : node not declared
> 
> 2 semantic error (s)
> Successfully loaded project Testbench_Integration.etp

**Comment by JakobGartner** [comment]
your issue is fixed (#676)
