### ISSUE TITLE
TM_RBC_conversions: blocks integration model

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#676]
I'm a bit surprised about this disturbance.
Can you please not block activities on the critical path with activities for next iteration. I'm not aware of mending interface changes.

Loading project Testbench_Integration.etp...
(0) : error ERRSEM_NODE_DEC : Node TM_RBC_conversions::compressed_to_Radio_Track_Train_H : node not declared
(0) : error ERRSEM_NODE_DEC : Node TM_RBC_conversions::compressed_to_Radio_Track_Train_H : node not declared

kr
Bernd

**Comment by JakobGartner** [comment]
you pulled just a bit too early 

fixed

**Comment by BerndHekele** [comment]
Thanks
