### ISSUE TITLE
Use Case 3: ETCS Brake intervention (revokation of MA or not allowed speed)

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#68]
ETCS Brake intervention (revokation of MA or not allowed speed)
Train is running after receving an Movement Authority (MA)

"As the End User (WP1) i want to see a demonstration of a ETCS brake itervention after revokation of a Movement Authority or not allowed speed."

This should be part of the modelling scope of WP 3.

**Comment by BaseliyosJacob** [comment]
Use Case 3 will be splitted in 2 Sub-Use Cases:

Use Case 3.1: overrun of speed.
function:
DMI Management: Display of the parameter
Brake Controll Management: trigger the brake (EB)
TIU Management: Cutting of the tracktion

Use Case 3.2: receiving of CES after revokation of MA
DMI Management: Display of the parameter
Brake Controll Management: trigger the brake (EB)
TIU Management: Cuttion of the tracktion

**Comment by BaseliyosJacob** [comment]
Necessary inputs for testing of Use Case 3:

MA with the EoA, Danger point,  Provided by: track information: Baseliyos Jacob
MRSP Provided by: ?

**Comment by MatthieuPoirot** [comment]
What is the link between CES and MA revokation (MA revokation is only due to timeout of end of section according to SRS). Can you provide more explanation please?

**Comment by T12z** [comment]
Timeouts are not implemented in the EVC. Other than that I cannot help, I am not aquainted with CES.

**Comment by jokaICS** [comment]
"Revoking the MA" is maybe not an accurate term in this case. However, if a CES is accepted, the EOA/SvL must be adjusted according to §3.10.2.2

**Comment by T12z** [comment]
@BaseliyosJacob is there anything left to do here? Else this could be closed
