### ISSUE TITLE
Obu_BasicTypes_Pkg:G_internal_Type - Gradient scaling

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#685]
dear all,
I came across some oddities of the basic gradient type:
 - the comment is already broken "in per 0.1 mill"
 - TrackAtlas imports the Packet_Type G_A directly without scaling, which is in promille

should it be in promille for all? Or in 0.1 promille aka. in 1/10000 (no "per") - and if so, what is the increased resolution good for?

cheers,
Thorsten

PS Bernd, I assigned you as a hub to delegate where needed.

**Comment by UweSteinkeFromSiemens** [comment]
The basic types defined in Obu_BasicTypes_Pkg are recommended for all OBU-internal calculations and data propagation in general. The resolution has been chosen one order better than required at external interfaces; if it should not match the needs currently, you're free to change it after coordination with other users involved.

**Comment by T12z** [comment]
Danke Uwe,
at the moment handling is just *not* consistent / buggy.

I'd personally rather stick with resolution of input (promille) between modules, no additional scaling. Though operator internal calculations should be done at higher resolutions to avoid excessive truncation error propagation. As far as I know, SDM is the only one doing *calculations* on gradients, and derived magnitudes are not of gradient type, so I see no reason for increased resolution.

Can TrackAtlas (aka @JakobGartner ) and DMI (@ ? ) please confirm unscaled handling of gradients? Then only the comment in Obu_BasicTypes needs to be corrected.

**Comment by T12z** [comment]
We have agreed in #708 to keep original packet scaling. Somebody could update the basic_type comment / description to reflect that ... maybe that's me ...

**Comment by UweSteinkeFromSiemens** [comment]
As @BerndHekele has locked Obu_BasicTypes.etp, only he is able to modify G_internal_Type. 
Did you already achieve an agreement on the scale of G_internal_Type?

**Comment by T12z** [comment]
yes, as stated above, scaling shall be as currently in use, that is x * 0.001 / "promille" / same scaling as in the packet. Type comment needs update.

**Comment by JakobGartner** [comment]
TrackAtlas uses, as agreed, scaling as received per packet

**Comment by T12z** [comment]
@JakobGartner sorry, function is fine. I just raised to flag to myself to clean up the type comment, so I can eventually close the issue :)

**Comment by T12z** [comment]
*NMU* ("Non-mainter-upload")
I corrected the comments and with this, finalize it for asignee @BerndHekele
