### ISSUE TITLE
SDM::RSM in Level NTC

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#687]
HiThorsten,
we now observe an brake command when passing bg 353.
In this area SDM switches to RSM.
Questions:
 - where can we influence the Release speed value?
 - I do not understand why this happens.

Mayby we can have a live session on this topic in short-term?
KR
Bernd

**Comment by JakobGartner** [comment]
Release speed ? Is in MA

I will check / debug in TrackAtlas





On 27.08.2015, at 07:47, Bernd Hekele <notifications@github.com> wrote:

HiThorsten,
we now observe an brake command when passing bg 353.
In this area SDM switches to RSM.
Questions:

   - where can we influence the Release speed value?
   - I do not understand why this happens.

Mayby we can have a live session on this topic in short-term?
KR
Bernd

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/687>.

**Comment by T12z** [comment]
In case the release speed is well set, there are quite a few things, that can go wrong in SDM... 
I am available in my office in roughly 30min.

---- Bernd Hekele schrieb ----

**Comment by T12z** [comment]
... and right, why is there RSM in NTC? This sounds genuinly wrong.

---- Bernd Hekele schrieb ----

**Comment by JakobGartner** [comment]
Yes
Track atlas now has a workaround to give NTC Speed limit while in NTC

It is however active even then

I did so to make sure that nobody misses any data

However we can also deactivate it with default behavior for all outputs.

Should we go in that direction

Then we can se which default values are needed to incite the correct
behavior

On 27.08.2015, at 08:54, Thorsten Schulz <notifications@github.com> wrote:

... and right, why is there RSM in NTC? This sounds genuinly wrong.

---- Bernd Hekele schrieb ----

>HiThorsten,
>we now observe an brake command when passing bg 353.
>In this area SDM switches to RSM.
>Questions:
>
>where can we influence the Release speed value?I do not understand why
this happens.
>
>Mayby we can have a live session on this topic in short-term?
>KR
>Bernd
>
>—
>Reply to this email directly or view it on GitHub.￼
>

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/687#issuecomment-135315118>.

**Comment by BerndHekele** [comment]
Thanks for the quick attention, Thorsten.
You can start the testcase in just using the testbench_Integration model.
Maybe it is a good idea you get familiar with this tool anyway.

**Comment by BerndHekele** [comment]
Hi Jakob,
I had some connection problems and did not see your remark for some time. Sorry.
If you see a good way to provide default values for trackatlas during ntc I believe it is a good starting point.
Since you do  net get data from the track before I see a clean structure.

Thanks for the proposal.

**Comment by T12z** [comment]
right now for myself I read, 'get acquainted with the test-bench, before any further discussion'. This may also help with upcoming feature-release. Please allow for some time on this. (I am substantially sidetracked by preparations for the scade conference where we (URO) need to deliver something)

**Comment by T12z** [comment]
it is actually working correctly in the demonstrator branch, so it is not a direct issue of SDM anymore (it was a "not" typo in supervisionmodes interplay)
