### ISSUE TITLE
Interface TIU - Modes&Levels

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/modeling#689]
* Proposition of changes : Using in Modes&Level part the type "TIU_Types_Pkg::TIU_trainStatus_T" in place of "Level_And_Mode_Types_Pkg::T_Cab" : type "Level_And_Mode_Types_Pkg::T_Cab" can be removed, data "TIU_trainStatus" can be directly used as input of ManageLevelAndMode

* Question : for type "TIU_Types_Pkg::Mode_control_and_train_status_T/", what means valid ?
that the information is new ? (in this case some modifications are necessary in "Modes::Interfaces::InputTIUManagement/") or just that the information is checked ?
Thanks to add a clear description in the type definition.

**Comment by BerndHekele** [comment]
Dear Marielle,
I support your proposal for changing the interfaces to the TIU.
To your question: valid means the a fresh signal is sent from the tiu to the evc.
I will update the comments as soon as possible.

**Comment by MariellePetitDoche** [comment]
Both modifications have been done.
Interface concerning Cab input shall be cleaned in open_ETCS_EVC::EVC::diagram_EVC_ModeAndLevel
