### ISSUE TITLE
Use Case 04: Train is reading track information - Train is sending information to the track.

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#69]
Train is reading track information - Train is sending information to the track.

"As the End User (WP1) i want to see a demonstration of reading of track information from the Euroradio or Eurobalise. Furthermore i want to see a demontration of sending of information from the train to the track (Euroradio)

This should be part of the modelling scope of WP 3.

**Comment by BaseliyosJacob** [comment]
Use Case 4 

Functions:
Check track information: Reading track information (packages and messages) (Eurobalise and Euroradio) and checking of consistency
Sending of track information: information to the RBC (messages and packages)

DMI Management: Display of the parameteter

**Comment by BerndHekele** [comment]
Done.
