### ISSUE TITLE
Type definition bugs in type lib models

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#691]
BG_Types and API_Types have been corrected due to compile time bugs emitted when compiling the C code. 

Please adapt your models appropriately. 

@JakobGartner , @jokaICS , @christianstahl

**Comment by BerndHekele** [comment]
Can you please check your model and provide the official corrections as soon as possible. This issue is blocking compilation of an official model.
Sorry for inconvenience - we had not real alternative to be able to get compilable C-Code.

Thanks for your support.
@apinnau

**Comment by JakobGartner** [comment]
done in TrackAtlas for all remaining references including the ones from @christianstahl

**Comment by T12z** [comment]
This might have possibly also solved my compiling issues I had with my new featured (gradient) model. (this was only reported via email internally) Gone, when running the Testbench :+1:

**Comment by BerndHekele** [comment]
Solved
