### ISSUE TITLE
Wrong MRSP after level transition to level 2

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#692]
After the transition to level 2, when the NID_MESSAGE = 3 is received and processed by the TrackAtlas, the MRSP is calculated with the following values:
[0]
- Loc_Abs = 101684
- Loc_LRBG = 101684
- MRS = 0
- valid = true
[1]
- Loc_Abs = 96184
- Loc_LRBG = 96184
- MRS = 0
- valid = true
[2]
- Loc_Abs = 0
- Loc_LRBG = 0
- MRS = 0
- valid = true

So the permitted speed is always zero, which leads to an emergency brake reaction. 

Additionally, the MA does not contain any sections.

To see this behavior, the delivery of the information about the new level to the TrackAtlas was delayed until the message 3 was received.

**Comment by apinnau** [comment]
> Additionally, the MA does not contain any sections.

This issue should be solved through my last commit. The end section (currently the only section which is used in the recorded track messages) is written at the first place of the section list (internal format: TrackAtlasTypes::MovementAuthority_t).

**Comment by stefan-karg** [comment]
Problem solved.
