### ISSUE TITLE
Proposal to use KCG 6.4

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#694]
We discussed this topic in Braunschweig.
We see low risk and high value.
I you have concerns please, comment.

kr
Bernd

**Comment by JakobGartner** [comment]
The move to the new architecture is the best moment of we want to do that.
We could provide a framework for integration including type definitions

On 28.08.2015, at 19:16, Bernd Hekele <notifications@github.com> wrote:

We discussed this topic in Braunschweig.
We see low risk and high value.
I you have concerns please, comment.

kr
Bernd

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/694>.

**Comment by T12z** [comment]
Just too make sure, you talk about KCG 6.4, not the really recrafted 6.5?
I have used 6.4 in many local compilations, never had any issues or anything I stumbled about.
