### ISSUE TITLE
Levels_ Passing the ack-window 

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#696]
When passing the ack window even without ack from the driver the level changes to 2.

In addition, text-message needs to be "cleaned" at the display.

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

i checked the DMI standalone with Ack of Message and it cleans the display.
Therefore i assume that it is not an issue on the DMI!?

**Comment by BerndHekele** [comment]
The problem is analysed.
I will provide a correction in levels as well since the error is related to the changes I put into the model.

I plan to push the model to github in order to get a quick-fix for the demonstration.
@MariellePetitDoche  if you want to take the levels back into your control please feel free to contact me for a handover discussion..

**Comment by BerndHekele** [comment]
Solution tested.
I see still two issues which are not related to levels and I will open new issues.
