### ISSUE TITLE
SDM: ignores brake commands from Mode and Level

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#699]
This is actually a bug and should be corrected to have an appropriate use-case implemented.
Can you do this short-term? Or shall we combine the brake again in the TIU as a workaround?

kr
Bernd

**Comment by T12z** [comment]
In my feature fork this is already implemented/fixed.
(on a status side-note, when I tested on Friday, I encountered a bug in my fork, that I need to fix asap. In particular, deceleration's A_safe is not done right / at all, if there is no gradient given).

**Comment by BerndHekele** [comment]
H iTorsten,
Is your folk based on identical interfaces or do you have need for interface changes?
I prpose we get your corrections in the master branch as soon as possible - if they do not have changed interfaces.

cu
Bernd

**Comment by T12z** [comment]
As far as I remember there should not be any interface changes left, but I will check tonight. I will reply

**Comment by T12z** [comment]
d'oh, Of course it is completely inline with mainline, else I were not able to track current versions of the master branch. But as stated above, A_safe is not built correctly as of now.

**Comment by T12z** [comment]
implemented, though not tested. Please reopen or file a new report if it misbehaves.
