### ISSUE TITLE
Gradient Profiles: semantics of packet 021 with n_iter=0

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#701]
What would be the meaning of a Packet 21 with `n_iter=0`?
It's not explicitly forbidden by the SRS (or is it?); however, §7.5.1.37 implies that the end of the gradient description should be indicated by `G_A=255`, which only makes sense if `n_iter>0` holds (?).

**Comment by T12z** [comment]
As long as there is a packet 21, it will always contain at least one segment (the fields before the n_iter field). I do not see the special value 255 to be mandatory from specification, but you are right, it could be meaningful from description. hmmmmmm, this needs more thinking, but what does the jru data say?

**Comment by jokaICS** [comment]
The JRU data uses a "marker section" with G_A=255.

**Comment by faustco** [comment]
gradient profile:
For the use of an end of profile value (G_A = 255) refer to 026 3.6.3.2.2 d)
the profile must be complete up to EOA 3.7.1.1 c)
the profile must be continuous 3.11.12.2
