### ISSUE TITLE
SpeedSupervision/CSM: transition from Intervention to Normal

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#704]
@T12z 
Could you please check if the behavior of node `CdmTrainSupervisionStatus` in mode CSM/Intervention is correct?

After the SB has been triggered due to overspeed, the state machine toggles between InterventionStatus and NormalStatus (even though the speed is constantly greater than the intervention speed status).
Furthermore, when the speed drops below the permitted speed, the state machine switches back to NormalStatus, but the service brake remains applied. Are there any additional conditions to be met for the service brake to be released?

**Comment by T12z** [comment]
Just a brief acknowledge of the issue.
When driving the "standard" test-scenario I can see the SB being applied and released (as of output of the operator) - so I am not sure if I got you right. We could check for a brief call tomorrow, might be quicker than elaborate in writing.
(random checking of `CdmTrainSupervisionStatus` I will try to avoid, as it was not implemented by myself and is an operator with *slightly elevated* dimension :wink: )

**Comment by jokaICS** [comment]
Quite possible that I didn't set correctly all the required inputs -- if it works on the standard test-scenario, it should be OK for now (since this is our priority for this week :).
