### ISSUE TITLE
M32 on test track Amsterdam-Utrecht send with NID_LRBG 16777215

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#705]
When I run the test track Amsterdam-Utrecht the first radio messages are send in an unexpected way.

Following points are recognized as an unexpected behavior:
1. M32 (LRBG_353_D_00319_2_M032) is send at track distance 1187 with NID_LRBG 16777215
2. M25 with P57,P58 (LRBG_353_D_00431_0_M024) is sent twice at 1191 and 1608 and only acknowledged by the EVC on the first time (correct behavior by EVC)
3. No M24 are sent by the RBC after LRBG_353_D_00431_0_M024 (No valid finding)

Please indicate whether this is a correct behavior and where I can find a proper introduction to the creation of M24s at the RBC, which I need for checking the EVC input channel.

Best regards,

Jan

**Comment by mairamou** [comment]
Hmm 
1. M32 (LRBG_353_D_00319_2_M032) is send at track distance 1187 with NID_LRBG 16777215
This is not correct, but in the constant defining that message NID_LRBG is defined as 353. So I have to check from where that number comes. 
2. On "my" track this message is only defined once. I don't know if the RBC generates it too, it was agreed that RBC builds them all with the exception of this one as it contains packets.
3. The RBC is now handled by @apinnau 

As a general remark, I have not yet updated the model with the findings from your document review,

**Comment by apinnau** [comment]
> 2. On "my" track this message is only defined once. I don't know if the RBC generates it too, it was agreed that RBC builds them all with the exception of this one as it contains packets.

The RBC generates M24 automatically (as a keep alive) if:
1. radio session is established between RBC and EVC (see US-7) and
2. no other message is sent within the "national" time window from the RBC (T_NVCONTACT) --> T_NVCONTACT * 0,75 (safety factor) is used as time trigger for sending M24


* These automatically generated M24 does only contain the variables nid_message, m_version, t_train and no packets
* Additionally there is a M24 generated during session establishment (containing P57 and P58)
@mairamou if your triggered message has the same function (in regard to the session establishment) we has to decide which message should be sent (generated or triggered message)

Unfortunately I'm not able to simulate the testbench_integration model (no KCG).
@janWelte may you check if the main state-machine of the RBC is in the right state after receiving **LRBG_353_D_00431_0_M024** on your test track run? It has to be in: RBC/RBC__ProcessController/SESSION_ESTABLISHED/**RECEIVE_AND_TRIGGER**

**Comment by mairamou** [comment]
Well 

I think you can decide :-) 

- Either you trigger "mine" or you send "yours". If you don't trigger
mine, I don't need to change the track model. 

Mairamou 

On 2015-09-01 12:36, Alexander Pinnau wrote: 

>> * On "my" track this message is only defined once. I don't know if the RBC generates it too, it was agreed that RBC builds them all with the exception of this one as it contains packets.
> 
> The RBC generates M24 automatically (as a keep alive) if:
> 1. radio session is established between RBC and EVC (see US-7) and
> 2. no other message is sent within the "national" time window from the RBC (T_NVCONTACT) --> T_NVCONTACT * 0,75 (safety factor) is used as time trigger for sending M24 
> 
> * These automatically generated M24 does only contain the variables nid_message, m_version, t_train and no packets
> * Additionally there is a M24 generated during session establishment (containing P57 and P58) @mairamou [1] if your triggered message has the same function (in regard to the session establishment) we has to decide which message should be sent (generated or triggered message)
> 
> Unfortunately I'm not able to simulate the testbench_integration model (no KCG).
> @janWelte [2] may you check if the main state-machine of the RBC is in the right state after receiving LRBG_353_D_00431_0_M024 on your test track run? It has to be in: RBC/RBC__ProcessController/SESSION_ESTABLISHED/RECEIVE_AND_TRIGGER 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/mairamou
[2] https://github.com/janWelte
[3]
https://github.com/openETCS/modeling/issues/705#issuecomment-136668977

**Comment by janWelte** [comment]
Thank you both.

The model is sending M024 correctly. (I've made a mistake as for some reason these Messages are not passed through the filter.)

Concerning your trigger discussion I would recommend that the RBC is sending M024s all alone, if this is already implemented. This gives a clear separation.

Best regards,

Jan Welte

**Comment by apinnau** [comment]
After comparison of both messages there are several differences:

automatically generated M24 | triggered M24 | comment
------------ | ------------- | -------------
m_ack = 1 | m_ack = 0 | this M24 has to be acknowledged (see US 7) -> gen. msg. seems correct
nid_lrbg = 0 | nid_lrbg = 353 | I have to fix this
P57: L_PACKET = 0 | P57: L_PACKET = 49 | is actually not evaluated in packet reading operators in OBU (correct me if I'm wrong)
P58: L_PACKET = 0 | P58: L_PACKET = 56 | (see above)

So I will:
- [ ] fix the missing LRBG information (nid_lrbg)
- [ ] remove the trigger (RBC will generate the message automatically)

**Comment by janWelte** [comment]
All your findings are reasonable to cause the regognized bahavior.

If you do the two point everything should work fine.
Thanks

**Comment by apinnau** [comment]
> 1. M32 (LRBG_353_D_00319_2_M032) is send at track distance 1187 with NID_LRBG 16777215

At this time no position report was sent to the RBC. So NID_LRBG=16777215=unknown... But this is consistent to the user story (US 7).

**Comment by apinnau** [comment]
The RBC model and the trigger conditions are corrected. From my point of view the issue can be closed.

**Comment by stefan-karg** [comment]
Can this issue be also closed from your point of view @janWelte ?

**Comment by BerndHekele** [comment]
Cleanup
