### ISSUE TITLE
Position reached indicator for normal Level Transition missing

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#710]
I've checked the interface between the Information Filter and the Level Transition, to understand how information, whcih are blocked before a level transition are needed for the level transition. (e.g. Level Transition from NTC or Level 0 to Level 2 or 3 needs MA)

Thereby, I've recognized that there is no functional block in the computeLeveLTransitions block, which sets the local variable "position_reached" as true for a "normal Level Transition" (only for drive and immidiate). 

This signal is needed in the ComputeTransitionConditions block to transmit the transition condition as true.

**Comment by janWelte** [comment]
If checked this point in depth, as if build a fast block myself on my local system (just contains a comparison, whether the position for a normal Level Transition has been reached). 

Result:
- Level Transition to NTC to Level 2 is performed correctly (no mode change seems to be performed)
- Train is tripped immediately by the SDM function

As I don't want to go further away from my original filter verification, I would ask @MariellePetitDoche and @T12z to have a look in this behavior. If you need more information to reproduce the change I made, please contact me.

**Comment by T12z** [comment]
I have pushed an update, that has been sitting around for a while, maybe this fixes this as well.

From other tests I know that if SDM receives no MovementAuthority it may trip. (From my understanding it should always trip in that case, but this is rather complex when it comes to abrupt (level) changes)

**Comment by janWelte** [comment]
I'll try it with the update, but I think it should be the MA.
This sound reasonable, as the MA is blocked until the Level change takes place and I'm not sure how the information are activated after the Level change between InformationFilter and TrackAtlas. This should probably be a discussion between all involved parties today, as this is form my the main issue for my verification.

**Comment by MariellePetitDoche** [comment]
There have been change in the interface of level modules :
the outputs of the modules are:
- a structure Compatible_Mode_And_Level which contains the current mode and level and the information if there are new or not (if there are new, a border has been passed.
- announced _level_transition for the future transition with all information related (position,...) and associated information "is _available_for_use" (see SRS § 5.10.2.6 to 5.10.2.7.1)

Concerninf the information filter, you can look on §5.10.1.7 and 5.10.1.8

**Comment by janWelte** [comment]
I'm closing this issue, as the new version of Mode and Level handles the Level Transition correctly as far as the indication of a passed level transition point is concerned. If there are other issue concerning the level transition found for the new realise there will be specific issues from V&V.
