### ISSUE TITLE
TrackAtlas now ready for integration testing for demo

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#711]
@MariellePetitDoche : can we make a Gotomeeting tomorrow any time at https://www.gotomeet.me/railergy ?

Then I could fine-tune the interface to you in real-time, all is prepared.

-Gradient Profile is stabilised 
- MRSP (in fact it is only a SSP wrapped as MRSP) is working and integrated

Flags are set permanently for MA, SSP and Gradient Profile available.

(some minor issues remain at stitching Packets 27 together, will be fixed in the morning)

**Comment by MariellePetitDoche** [comment]
Ok.
I will follow the morning telco, then I am available all the day.

**Comment by T12z** [comment]
I have finally merged my cleaned up SDM version. As posted, the bugs in the older version outweigh the bugs in the update.
Now we need to test, that scaling and offsets on lengths/distances/locations are always used correctly.

PS not urgently, but the nextGen naming could be refreshed some stage. The old types have not been referenced for some time.

**Comment by MariellePetitDoche** [comment]
M&L has been integrated with right packet format.
