### ISSUE TITLE
Resolution of Obu_BasicTypes_Pkg::V_internal_Type is questionable low

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#712]
While testing my SDM module I have seen the inputs from Odo stepping a little rough due to low integer resolution in km/h.

*{use namespace Obu_BasicTypes_Pkg::OdometrySpeeds_T}*
Also in the testbench simulation v_safeNominal is smaller than v_rawNominal which is legimit but in the end an unexpected behaviour. Due to, I guess, rounding errors, v_safeNom is sometimes *not* within 98% of v_upper.

I propose to promote V_internal_Type to a higher resolution, that is also in line with other types of physical units. I would go with cm/s as its components are already used in other contexts and would well add a decimal digit in km/h representation. But I apreciate a discussion abou this.

**Comment by T12z** [comment]
after playing with the testbench_integration / demonstrator, it gets clear, that this really is a bug.

**Comment by UweSteinkeFromSiemens** [comment]
Is the bug the low resolution of V_internal_Type or the unexpected behaviour? 

Anyway, I don't mind changing the resolution, since I don't need in my model components. 
Who are the users of V_internal_Type, who have to agree on a modified resolution?

**Comment by T12z** [comment]
the low resolution results in inacceptable behaviour. When approaching low speeds in target speed monitoring the outputs of SDM become "instable" in a way that they start skipping. The behaviour is not erraneous, but hardly usable when presented on a DMI.
I think this needs to be brought up in a meeting, for people to comment on an improved resolution.

**Comment by T12z** [comment]
Poll: 

1. Unit (e.g. for 600 km/h)
 1. cm/s (--> 16667 cm/s)
 2. km/h * 10^-1 (--> 6000 km/10h)
 3. km/h * 10^-2 (--> 60000 km/100h)
2. Timeframe? Any release where this should be done?
3. What should involved?
 * dual model: target/track speeds in km/h and odometry in whatever above, providing own conversion functions (maybe less work)
 * single unit for all speeds

**Comment by T12z** [comment]
There are quite a few consumers of odometry, whos owners need to comment:
 * manageDMI_Output
 * ProvidePositionReport
 * Manage_TrackSideInformation_Integration
 * SpeedSupervision_Integration
 * ML (after handling in integration)
 * calculateTrainPosition
 * TrackAtlas

Also, when converting from higher resolution to km/h, what is considered safe? Round up, round off, round math?

**Comment by UweSteinkeFromSiemens** [comment]
calculateTrainPosition does not make use of speed information.

**Comment by BerndHekele** [comment]
Here is the actual definition of Alstom:
![image](https://cloud.githubusercontent.com/assets/3288918/10014224/1f71cbd4-6118-11e5-9ebf-fd293c611486.png)

(Which means decimeter per sec.)
I support the proposal to use the cm/sec

From the list above only the DMI output is doing calculations on the interfaces. And here I believe the main calculation is done in sdm

**Comment by stefan-karg** [comment]
As decided in todays meeting, the resolution of the odometry speed output was changed to cm/s.

The commit performing this change is 7d14ea8dc2f458e67e041bfe2c61a529fba85a4a

Please adjust the models where necessary: @T12z @BerndHekele @UweSteinkeFromSiemens (?)

**Comment by UweSteinkeFromSiemens** [comment]
I'm not evaluating speed within my models. Therefore, no modification is necessary if the existing types are not modified.

**Comment by T12z** [comment]
Our Scade-License has run out, so I might not be able to fix this today until I get a new lic from Ansys. (We should have taken care of this earlier, our fault)
Sorry.

**Comment by T12z** [comment]
*Update:* I am getting a temporary lic, so I should be able to finish this week.

**Comment by T12z** [comment]
@stefan-karg I just commited SDM adaptions.
I did not change SDM external interfaces, but I can offer to DMI *calculated* speeds, such as interventionSpeed, permittedSpeed ... of `DMI_Types_Pkg::speedSupervisionForDMI_T` in higher V_odometry_Type resolution. As a matter of fact, I currently convert them from V_odometry_Type to V_internal_Type just before writing the output.

Due to Integer-truncation in this translation, this may lead unsynchronized behaviour. If the actual DMI-Implementation can work with higher resolution than km/h, I suggest to switch to V_odometry_Type also in `DMI_Types_Pkg::speedSupervisionForDMI_T::*Speed`. (Work necessary on SDM-side would be to delete the conversion operators before the output)

**Comment by BerndHekele** [comment]
@T12z 
Hi Thorsten,
I do indeed need this correction in the interface to the DMI. Can you please make this change as proposed on your side?
In addition, if we need a convertion from new type to the internal type, do we have a lib function in some place?

kr
Bernd

**Comment by T12z** [comment]
I am importing above stated type from DMI. I will follow that type.
As old *and* new type resolve to int, we should get no generation errors if we switch async. I can't reach the model before Monday. If it is pressing, just delete and shortcut the four instantiations of `TransformV_odoToV_int` in `ObuFunctions/SpeedSupervison/SDM_Commands/CalcDMI_output.xscade`
I made the above stated conversion function, which resembled both internal conversion functions from new and to old type `model/Scade/System/ObuFunctions/SpeedSupervison/SDM_Types/TransformV_odoToV_int.xscade`. I am not sure, if it is marked private, but generally `SDM_Types` is one of these toolbox libraries.
A second note on `V_odoToV_int`: the conversion factor is 27.777... which is rounded to 27. There might be cases where round-up would be better and more so, in the integer division, instead of truncation, math rounding or even round up would be more safe. (That's why I am interested not to use V_int)

**Comment by T12z** [comment]
This is generally implemented. There may be some cleaning left, but this is each module owner's job. If there are new bugs introduced please file a new issue.

**Comment by T12z** [comment]
So I reopen this for simplicity:
@Farhangi The comment I sent Bernd yesterday, elaborate comment will follow.

Toolbox::Physics::PHYSICS_MovementSimulation/
ist fehlerhaft, da wird km/h und m/s etwas durcheinander gebracht.
tmpVelocity wird mal als m/s interpretiert und mal als km/h.

**Comment by T12z** [comment]
From the outside
out.velocity should be real_km/h
out.odometry is odometry_T int_cm/s

![physics simulation](https://cloud.githubusercontent.com/assets/10432699/10602082/8989a2ee-7716-11e5-993f-dc7ee258a3f8.PNG)

local.tmpVelocity is used as real_m/s within the *Driving*-state, below, outside the fsm, tmpVelocity is used as km/h. It may be best, to switch it there, so remove the unreadable box before `TrainModules::ODO` and replace it by out=(int)(in*100), like is done for tmpPosition-parameter.

Due to use of different units, the simulation has become quite obfuscated. There should only exist three types currently: V_internal_Type[km/h](int), V_odometry_Type[cm/s](int), *private*[m/s](real)
