### ISSUE TITLE
Mode and Level interface changes: TrackAtlas

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#714]
Dear Jakob,

due to changes in the M&L-interface, the SCADE check reports two errors in the track atlas:

* Type mismatch at TA_Export::TA_to_ML/_L6=
* Type mismatch at TrackAtlasTypes::DEFAULT_to_Mode_and_Level/

**Comment by JakobGartner** [comment]
done, some changes of a type define in M&L had to be taken into account

**Comment by stefan-karg** [comment]
Thank you for your quick reaction, Jakob! The check does not report any errors anymore.
