### ISSUE TITLE
Mode and Level interface changes: Procedures

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#715]
Dear Baseliyos,

due to changes in the M&L-interface, the Procedures model has to be adjusted to the new interface. The SCADE check reports the following error: 

* Unknown structure label at ManageProcedure_Pkg::Master_Procedure/_L281=

**Comment by BaseliyosJacob** [comment]
Dear Stefan,

i have just updated the changes in the procedure model.
No errors on check.

**Comment by stefan-karg** [comment]
Thank you for your quick reaction, Baseliyos! The check in the integration model does not report any errors any more.
