### ISSUE TITLE
US-OBU-SysML-SCADE-ADD-Consistency

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#716]
As a modeller/validator/user I want the OBU SysML model, SCADE functional model and architecture and design description (ADD, D3.5.x) to be consistent.

**Comment by T12z** [comment]
SysML/SDM is updated, also the screenshot in the ADD images directory (content and dimensions have changed). Updates on ADD-tex will follow, probably after brief notification for exclusive access.

**Comment by mahlmann** [comment]
SysML and ADD can be considered consistent now. Minor pending changes in architecture (e.g. integration of new TrackAtlas or MoRC) will be adjusted in SysML and ADD once they are completed on architecture level.

**Comment by janWelte** [comment]
Thank you very much. I'll now prepare a detailed report based on this.
