### ISSUE TITLE
Repository hygiene: add global .gitignore?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#717]
Dear all,

currently there are a lot of generated files/ binary files under source control. This creates a lot of problems/ unnecessary merges during pull actions, and also makes the repo very fat. Do we really need all these generated files to be under source control? I presume that not all binary files currently under source control were put there deliberately...

As a remedy I propose to use a top-level .gitignore file to exclude `*.o`, `*.ewo` ... by default.

**Comment by T12z** [comment]
There was a discussing about this before: #275 
this is just not respected that much :frowning: 
There was an informal discussion about generated code to be in the repo for verification, but I would also like to see this in a separate repo, branch ... it is just a nuisance.
my proposal for `.gitignore` (as used in SDM):
> /*.err
> /*.ewo
> /*.htm
> /*.vsw
> Simulation
> KCG
> /*.l4
> /*.rqtfimage

**Comment by T12z** [comment]
... and I'd like to see a cleanup of files offending to .gitignore and dead xscade-files.

**Comment by jokaICS** [comment]
> ... and I'd like to see a cleanup of files offending to .gitignore and dead xscade-files.

+1

I'd also suggest to explicitly add
> /.o
> /.dll
> /.exe

and maybe
> /.c
> /.h

since some use configurations other than `Simulation` and `KCG`. Furthermore, we should add the `.gitignore` to the repository.

**Comment by mahlmann** [comment]
We will take action on this in #720 , therefore I propose to close this issue.
