### ISSUE TITLE
Use Case 15: Route is cancelled from the end of route signal. 

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#72]
Route is cancelled from the end of route signal.

As the End User (WP1) i want to see a demonstration of a Train scenario is used on the Amsterdam – Utrecht line, in the event that the route is  cancelled by the Infrastructure Maintenance System.
The end of route signal is S100. The train is stopped in rear of S100 and the route is canceled. This scenario verifies the train behavior on different steps, while the interlocking elements are cleared.

This should be part of the modelling scope of WP 3.

**Comment by BaseliyosJacob** [comment]
Dear all,

find the Sequence Diagramm and Description for this US on:

https://github.com/openETCS/modeling/blob/master/User%20Stories/User%20Story%2015.pdf

https://github.com/openETCS/modeling/blob/master/User%20Stories/Description%20User%20Story%2015.pdf

**Comment by Rainer-Lampatzer** [comment]
Dear @BaseliyosJacob ,

I just analyzed the description of user story 15. And I was really confused by the phrase 

"L2 Mode change FS – OS – FS. ERTMS track uses no TAF mechanism. Late driver response at mode change to OS"

which does not really make sense in combination with the rest of that user story. Then I read the description of user story 14 by random, and there I noticed the same phrase.

Could it be possible that the use of this phrase in the description of user story 15 was inserted by a copy&paste error?

Thanks in advance!

Rainer

**Comment by BaseliyosJacob** [comment]
Dear Rainer,

you are right (copy&paste error). Had the same conversation with Mr. Pröttel yesterday. Its by random the same description of US 14 for US 15. Will change it asap. Please do not consider this description for US 15.

Sorry for the confusion

Greetings

Baseliyos Jacob

Greetings

**Comment by Rainer-Lampatzer** [comment]
RBC works that were obviously still open are done now together with #862

**Comment by Rainer-Lampatzer** [comment]
No content beyond #862
