### ISSUE TITLE
US-Clean-Repository

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#720]
As a modeler I want the modeling repository to not contain any unneeded binary files (e.g. ewo) so that no unnecessary merge conflicts, etc., occur.

@stefan-karg @BerndHekele @JakobGartner 
Please remove unneeded files, consider making use of .gitignore.

**Comment by mahlmann** [comment]
cf. #717 and #275 for previous discussions about this topic.

**Comment by mahlmann** [comment]
In todays DB internal scrum meeting it was decided that @stefan-karg will take action on this.

**Comment by stefan-karg** [comment]
Removed unwanted files in 316d67d62295905688c82c399077ee0b766bcddc
Add gitignore in 5791c4ee792930abd7292a6a6076e3083f0a72c1 and d81e3120b1502d6ec5ff84b4ea2d4f8b5cf02639

If I accidentally deleted files which are needed by someone, please do not hesitate to contact me. Nothing is deleted permanently, all files are still available via the git history.
