### ISSUE TITLE
Use Case 15: small mistake in description

### ISSUE THREAD

**Issue by apinnau** [openETCS/modeling#722]
@BaseliyosJacob 
I think there is a little mistake in the description of the user story 15:
- [...]
- OBU: mode change from Trip to Post Trip
- RBC: sending message 6
- **OBU: sending acknowledgement (:exclamation:Should be message 146 but is labeled as message 136)**
- [...]

**Comment by Rainer-Lampatzer** [comment]
has been done here and later re-done in #862
