### ISSUE TITLE
ADD / D3.5.3 / F2.5: Mode_and_Level documentation

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#724]
Dear @MariellePetitDoche 

with respect to #651 I did a first review of Section 4.6 Mode_and_Level in the ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3) and added some comments and TODOs in this section (I refer to the ADD document for details). I kindly ask you to have a look at these issues and complete the documentation as soon as your open questions regarding the interfaces have been clarified (cf. #711 ).

General remark: *Please do not change the template structure, e.g. do not remove rows from the input/ouput descriptions. If a particular row is not relvant for a specific input/output just state "n/a" there.*

**Comment by MariellePetitDoche** [comment]
There is a structural issue in the document regarding the definition of the data.

- Meaning of some rows (ie. timeconstraints, behaviours,...) in the both kind of table are not clearly defined and it can be discussed if there are useful or not. I t will be great to have an introduction which describe the contents of different kind of table.


- Homogeneity : in the current structure, each function defines on is own way input and output, thus a given data can be defined several times in the document with contradictions. It will be better to define in  separate sections, data and functions. All the data are defined only one time in a "data dictionnary" section (with a table), and in the description of the functions, for the input and output, we keep only a reference to the data defined in the data dictionnary. This allows to share a common definition of the data and to simplify the definition of links between functions (in the current state it is not possible for each person who provides a function to clearly state who is the producer (resp. consummer)  of an input (resp  an output).

**Comment by MariellePetitDoche** [comment]
Peter, several informations have been removed from the mode and level since my last changes.
I have defined the output, but they disappear, and several inputs have been removed.
Picture disappear too.

**Comment by mahlmann** [comment]
Dear Marielle,

concerning the meaning and usefullness of rows (ie. timeconstraints, behaviours,...). This is the outcome of the discussions and requirements from the side of WP4 ( @MarcBehrens , @FrederiqueVallee , @AbdelnasirMohamed ). 

I agree that it would be nice to have a reference component documented properly. I tried my best to get one of the designers to create such a component and have it reviewed by WP4. However, it turned out that this was not possible in due time unfortunately.

Concerning homonogenity, I think this topic has to be discussed by a broader audience. @MarcBehrens @BerndHekele What is your opinion on this? However, we have to keep in mind what can be achieved in the limited time left since the document is overdue already.

Last but not least: Your changes being removed from the document. I did some comments but certainly did not remove anything (at least not intentionally). Please check if you can find your changes in the repositories history -- the good thing about GitHub is that nothing can get lost.

**Comment by mahlmann** [comment]
Dear @MariellePetitDoche 

I checked the git history. Outputs have *never* been updated in file `modeandlevel_V2.tex`. 

There is some documentation of outputs in the outdated file `modeandlevel.tex`. However, this file does of course not follow the new template (i.e. tables) and at first glance I had the impression that there were too many respectively the wrong outputs described. Note that we will only describe outputs of the top level component, i.e.  `Mode_And_Level`. Inputs and outputs of subcomponents like `Level_Management` or `Mode_Management`do not need to be described in the ADD.

There is maybe one more issue: Having had a look at your SCADE model I noticed that there are some subcomponents which currently do not appear in the ADD, e.g.
- `Input`
- `Output`

Please let me know if these should appear in the ADD. In that case I would create the corresponding sections and templates.

Considering that the ADD document is overdue already, I kindly ask you to take action on this issue as soon as possible.

**Comment by mahlmann** [comment]
Dear @MariellePetitDoche 

concerning the SysML diagram we tried to import the diagrams you created using the openETCS tool. However, according to @Farhangi several of the diagrams were broken and could not be opened (Luna and Kepler versions of the openETCS tool have been tried out). So, the bottom line is that we created some minimalistic diagrams in SCADE System (c.f. attached screenshot, the actual model is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC) that should be sufficient for the integration in the ADD document. So, you can consider the SysML part as done for now.
![capture](https://cloud.githubusercontent.com/assets/3638145/10193336/ba6f3b6a-6782-11e5-8e6d-7961424bf1ec.PNG)

Note however that we still need you to updated the textual description in the ADD urgently.

**Comment by MariellePetitDoche** [comment]
New version of ADD pushed.
