### ISSUE TITLE
TM::Read_P045:  "received" and "valid" flags are permanently true

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#725]
The valid flag of the P045_OBU_out output and the "received" output are permanently set to true.

Scenario: connect the output of TM_specific_send::Send_P045_no_merge with the input of TM::Read_P045. 

@mairamou: fyi.

**Comment by UweSteinkeFromSiemens** [comment]
@JakobGartner, @mairamou : would be nice to fix this.

**Comment by mairamou** [comment]
It looks like several "generations" of operators are mixed here. 

I will have a look at it today. 

Mai 

On 2015-09-22 10:23, Uwe Steinke wrote: 

> @JakobGartner [1], @mairamou [2] : would be nice to fix this. 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/JakobGartner
[2] https://github.com/mairamou
[3]
https://github.com/openETCS/modeling/issues/725#issuecomment-142210036

**Comment by mairamou** [comment]
Done

I have added a switch that sets NID_PACKET only to 45 if the valid flag of the legacy type is true.

(the search algorithm in Read_P045 is not built on the valid flag concept but on using rich metadata. If on the input side NID_PACKET <> 0, then the metadata will be filled, hence a false positive for finding a P045 is calculated by Read_P045)

**Comment by mairamou** [comment]
Remark: The change is in the operator TM_conversions::C_P045_onboard_legacy_to_int, so it is on the send side.

**Comment by UweSteinkeFromSiemens** [comment]
Due to interface changes, the test scenario MoRCHO_T_Pkg::tcases::tc_userstory_7_12/SM1:sendRegisterCmd_2_EVC: is not executable currently. I will close this issue anyway.

**Comment by JakobGartner** [comment]
Which?=

**Comment by UweSteinkeFromSiemens** [comment]
@JakobGartner : MoRCHO_T_Pkg::tcases::tc_userstory_7_12/SM1:sendRegisterCmd_2_EVC: Please, don't be worried: I used the scenario for testing MoRC_HO before applying the series of interface changes and the message bus ... As soon as there is time for this, I will reconstruct the scenario again.
