### ISSUE TITLE
Semantic error in Mode and Level

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#726]
Dear Marielle,

in the current version of the Mode and Level module, the SCADE check reports an semantic error:

"Undefined variable at Input/L_result/ : the local variable L_result has no definition"

The corresponding operator is the operator "Input" on top level of your model.

**Comment by MariellePetitDoche** [comment]
Yes I have see this variable which is not used in the diagram, maybe something added by Johannes ?

I will change lots of things in this part of model during the next days, is it possible to limit the changes to avoid conflicts and inconsistencies ?

**Comment by stefan-karg** [comment]
Fixed in e188bbc96b879d0057ce9c8aa40c751feb904d98 .

Thank you for your quick reaction, Marielle!
