### ISSUE TITLE
SDM: freshMRSP

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#727]
Currently, the SDM module does not check the freshMRSP flag, when using the input data in the operator TargetLimits_Pkg::SDMLimitLocations and in the SDM_InputWrapper.

This leads to problems, since at the recalculation of the MRSP, the values currently have invalid values for at least one cycle. The freshMRSP flag is not set in this cycle by the TrackAtlas, but the SDM module uses these invalid values as new MRSP for the operator SDMLimitLocations. In the integration model, this currently leads to an emergency brake intervention, since the speeds are temporarly set to 0 at the level transition. Since the update flag is not set when the speeds are set to 0, they have to be ignored.

**Comment by JakobGartner** [comment]
Hmm

There should be no gap in TrackAtlas MRSP calculation. It happens when ?

**Comment by T12z** [comment]
Gradients are only recalculated on Freshgradient flag, no questions here.

SDM limits does not use any form of caching (yet), this would be part of optimisation and needs a little thinking first. But it does reference MA and MRSP, no matter if it is fresh or not. I do see the fresh flags as a hint for optimisation, not as a valid flag. That said, SDM limits also ignores the valid flag, which could be seen as a bug, but on the other hand, there always has to be a valid MA, not to throw the EB. And as of current architecture, MRSP also always has to be valid, at least containing the train's v_max.

I am open for a discussion about architecture improvements if needed.

---- Jakob Gärtner schrieb ----

>Hmm
>
>There should be no gap in TrackAtlas MRSP calculation. It happens when ?
>
>
>

**Comment by T12z** [comment]
update notice for above comment

**Comment by T12z** [comment]
I think I may close this, as TA is being looked at about this
