### ISSUE TITLE
Please do not change SCADE default config "Simulation"

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#728]
Dear all,

I have one request regarding the SCADE project configurations: it would be really helpful for testing,
if you would not change the default "Simulation" configuration. In particular **please don't change the default output directory or the settings for debugging/ optimization** in this profile. Please make a copy of "Simulation" for your custom settings instead. 

The reason for my request: we have a framework for batch test execution that generates the source code as needed, but since not all of us have access to a KCG license, the batch runner will possibly fail if you modify debug or optimization settings.

Thanks,
Johannes

**Comment by T12z** [comment]
Can you revert non-default settings to what you need?
I think I have changed these settings at multiple occasions in my packages. If not, what are the defaults?

**Comment by jokaICS** [comment]
> Can you revert non-default settings to what you need?

Yes, if it's OK for you, I'll revert the config in the .etp and push the change?

**Comment by T12z** [comment]
Yes, that's fine, go ahead. I have no pending updates locally or planned

**Comment by JakobGartner** [comment]
Die bessere Idee wäre vielleicht gewesen eine eigene Configuration zu machen ?

Mit freundlichen Grüßen 
Cordialement
Best regards 

Jakob Gärtner 
GF/ PDG
Local Energy Appliances
Am Mittleren Moos 48
86167 Augsburg 
Germany
+49 821 907802-20
+49 151 25387841

Local Energy (Cameroon) Sarl 
BP 14000
Yaoundé 
Cameroun 
+237 6 98 29 16 01

j.gaertner@lea-energy.com

**Comment by UweSteinkeFromSiemens** [comment]
Please conform to https://github.com/openETCS/modeling/tree/master/model/Scade/ScadeTemplates . If you want to deviate, please create your own profiles.

**Comment by jokaICS** [comment]
> Die bessere Idee wäre vielleicht gewesen eine eigene Configuration zu machen ?

That's OK for me, but then we need to modify the all involved .etp files.
