### ISSUE TITLE
ADD / D3.5.3 / F2.6: calculateTrainPosition documentation

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#734]
Dear @UweSteinkeFromSiemens,

with respect to #651 I did a first review of Section 5.7 F2.6: calculateTrainPosition in the ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3) and added some comments and TODOs in this section (I refer to the ADD document for details). 

Moreover, the component has been moved up in the hierarchy, so that subcomponents need to be documented now. Note that inputs and outputs of subcomponents shall not be documented in the ADD (we just refer to the SCADE Suite generated documentation instead). Templates for all subcomponents have been created and integrated already to facilitate your work.

Considering that the ADD document is overdue already, I kindly ask you to take action on this issue as soon as possible.

General remark: *Please do not change the template structure, e.g. do not remove rows from the input/ouput descriptions. If a particular row is not relvant for a specific input/output just state "n/a" there.*

**Comment by UweSteinkeFromSiemens** [comment]
@mahlmann : Generating the pdf from D3_5_3.tex ends up with 
![tex_errormsg](https://cloud.githubusercontent.com/assets/2225951/9987895/0c834dbc-604c-11e5-9a1b-9c008e4e0942.png) . 
This bug has to be solved before enhancing the document content.

**Comment by mahlmann** [comment]
@UweSteinkeFromSiemens 
The document compiles for me, sorry the problems seems to be on your side. Consider doing a clean checkout or removing LaTeX auxiluary files (e.g. log,aux,dvi,lof,lot,bit,idx,glo,bbl,ilg,toc,ind,out,blg).

Furthermore I would recommend to use TexStudio for editing, as TeXnicCenter has not been updated for two years and TexStudio supports forward/inverse search natively (a click in  the PDF output will bring up the corresponding line of the source tex file(s)).

**Comment by UweSteinkeFromSiemens** [comment]
Thanks for your advice. Deleting the mentioned files did not succeed. So  I installed TeXStudio in addition, which is after TexMaker and TeXnicCenter the third TeX editor I've been using since the start of the project. With TexStudio, the pdf generation is working appropriately. :-) 
But instead of having 3 editors installed in parallel, is'nt there a steadily maintained, robust and user-friendly editor disburdening the author from editing and allows to focus on writing?

**Comment by mahlmann** [comment]
Since I usually use LaTeX on a MacOS machine, I do not know all the editors available for Windows.

However, so far I encountered only few problems with TeXStudio and it is still maintained. Considering user friendliness, a big plus of this editor is the possibility to use [ctrl]+[LeftMouseButton] in the PDF to bring up the corresponding tex line and vice versa.

**Comment by UweSteinkeFromSiemens** [comment]
Done.
