### ISSUE TITLE
Model and Levels SCADE model

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#74]
I have reviewed the SCADE model of "Mode and Levels".

I have the following remarks and recommendations:

1.
- model and levels are naturally representable in SCADE State Machine Notation
- The model is a flat data flow model which attempts to represent the top level states (=Modes/Levels)
- Please note that no reset, no priorities, no hierarchies can be modelled this way

- Bernard Dion (Esterel CTO) always said: A good SCADE model is always optically beautiful

-- Please reconsider the design.
It should be done with a SSM (SCADE Safe State Machine) - based design
You can have a look at the examples under HELP-EXAMPLES in your SCADE Suite installation. 
(a) the ABC example is good for understanding the hierarchic and concurrent semantics of SSM
(b) the Cruise Control example is good for understanding how to calculate complex conditions for SSM triggers, and also how to mix data flow and SSM in one model

-- I highly recommend that Systerel sends the person who is responsible for modelling to the SCADE training in Munich in January

2. 
- the conditions to trigger a mode and level transition are modelled using table 4.6.2.

- this table is a summary of the following text.
- Please use the text for modelling the M/L SCADE model, as the table is confusing because it cannot be determined whether conditions are meant as pure logical relations (A and B must be true at the same time) or if they are part of some sequential chain of events (A has requested B and B has occurred)

3. We now have defined some User Stories that define some high- level scenarios that we want to demonstrate. Please analyse your set of requirements and set the priorities in a way that you do first what is needed first.

**Comment by BerndHekele** [comment]
Can we close this issue now?
