### ISSUE TITLE
ADD / D3.5.3 / F2.4: TrackAtlas

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#742]
Dear @JakobGartner 

with respect to #651 Section 5.5 "F2.4: TrackAtlas" in the ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3) needs to be updated. As a first step I need you to clarify the desired hierarchy and structure of components.

Looking at the SCADE model I assume that the attached screenshot represents the main component.
![capture](https://cloud.githubusercontent.com/assets/3638145/9934242/582cc68e-5d50-11e5-8960-0d15e9b38163.PNG)

Since we will only describe the direct subcomponents in the ADD this would imply that there will be just the following subcomponents, where only TrackAtlasETCS seems to have major functionality:
![capture](https://cloud.githubusercontent.com/assets/3638145/9934358/f324b8ae-5d50-11e5-98ce-75058f194ffc.PNG)

Please let me know if this is the desired structure for the ADD, i.e.
- TrackAtlas
  - TrackAtlasETCS
  - WA_Speed_NTC

or if TrackAtlasETCS is supposed to be the main component for the ADD.

Once this has been clarified I will create the corresponding document structure including prefilled templates.

**Comment by JakobGartner** [comment]
NO.

the real top- level is the node TrackAtlasETCS.

The level above is only a workaround to attempt to handle some weird effects that occur during level change (level changes before the profiles are available)

You need to build many more chapters :-)

And me too :-(

Jakob

**Comment by mahlmann** [comment]
Ok, thanks for your prompt reply! I will come back to you as soon as the sections and templates have been created.

**Comment by mahlmann** [comment]
@JakobGartner 
TrackAtlas subcomponents have been created and prefilled. Please take action on the documentation of this component asap, as the TrackAtlas documentation has been requested by several partners already.
