### ISSUE TITLE
Levels::SelectHighestPriorityDecision does not consider Active Level in the Conditional List

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#744]
Precondition:
 - level switch from NTC to 2 is completed.
 - P46 has been received before.
 - Not Other Transition is pending.

Input to Levels:
![image](https://cloud.githubusercontent.com/assets/3288918/9935986/214589f8-5d5a-11e5-85ae-8c5b244bf60f.png)

Levels is now starting a level transition based on the priority list.
According to subset26 section 
5.10.3.14.2 If the current level is contained in the priority list of the conditional level transition order,
the onboard shall not change the level.
this is not the correct behaviour.

The error was triggered by a clean-up of data according to subset 26 in the evc:

5.10.3.14.4 In the same way as for a level transition order, the ERTMS/ETCS on-board equipment
shall store the table of ERTMS/ETCS levels supported by trackside.

I need to keep the data on board. I propose to implement a check in the selection to avoid thi situation.

kind regards
Bernd

**Comment by MariellePetitDoche** [comment]
I am currently modifing and correcting the scade model on this part.

Concerning the test, how are you sure that "Not Other Transition is pending." are you sure that no P41 as been received before ?
It does not appear on the picture. Besides we can not see if Level 2 is in or not P46, and thus if it is contained or not.

"this is not the correct behaviour." What is the correct behaviour ?

Could you give on which Balise/ position the problem occur ?

**Comment by BerndHekele** [comment]
This happens after the level has changed. Old P41 entries are deleted in the input when the level changes.
According to SRS the correct behaviour is to stick to the selected level (level 2 in this scenario).

We should take a little time on Monday to discuss the data flow. I can show in the evc model how it looks like in the current implementation.

If you have a correction I would be pleased to test it.

Thanks
Bernd

**Comment by MariellePetitDoche** [comment]
As I said, I'am currently  modifiyng the Level Management part, thus it is too  early to test it.
The behavior can change a lot.

**Comment by BerndHekele** [comment]
That is fine for me.
We need to coordinate this activity very closely.

**Comment by MariellePetitDoche** [comment]
To be tested with new version of M&L

**Comment by stefan-karg** [comment]
Fixed
