### ISSUE TITLE
Levels::Levels do not change in all circumstances

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#745]
Level change requested (P41) from NTC to Level 2
According to Subset 26 section 5.10.3.7.3 the level transition has to happen even if the MA etc are not received.

Current implementation of Levels does not follow this requirement.
(It is possible the original approach of Mathias did).

I believe this behaviour is to be expected for changing from L2 to NTC as well (even though the srs is not really clear on this.

**Comment by MariellePetitDoche** [comment]
Implementation from NTC to Level 2 is done.

From L2 to NTC, no MA provided by trackside (P12 or P15) are concerned here, as in NTC there are not taken into account. But depending of the STM, there can be specific MA from STM (see 5.10.3.10.5), which is not implemented for the moment.

Besides the request of end of session with RBC (5.10.3.10.3) is implemented

**Comment by BerndHekele** [comment]
We have a new levels implementation.
Issue is related to the old implementation.
Closed with the new implementation.
