### ISSUE TITLE
ADD / D3.5.3 / F2.1: Manage_TrackSideInformation_Integration

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#747]
Dear @BerndHekele  

with respect to #651 I did a first review of Section 5.2 "F2.1: Manage_TrackSideInformation_Integration" in the ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3) and added some comments and TODOs in this section (I refer to the ADD document for details). 

Considering that the ADD document is overdue already, I kindly ask you to take action on this issue as soon as possible.

General remark: *Please do not change the template structure, e.g. do not remove rows from the input/ouput descriptions. If a particular row is not relvant for a specific input/output just state "n/a" there.*

**Comment by BerndHekele** [comment]
Draft is available.

**Comment by mahlmann** [comment]
@BerndHekele First of all thanks a lot for the great contribution!

I did another review and corrected some minor issues regarding consistency and the previously discussed LaTeX table issues. 

Moreover, I added some comments as there are some aspects which could be improved in my opinion. This mostly refers to the referencing of input sources respectively output destinations.

**Comment by mahlmann** [comment]
@BerndHekele 
your updates have been reviewed. Please check again to finalize this section.

**Comment by mahlmann** [comment]
@BerndHekele 
There were numerous errors in the description which I fixed. This section should be inline with SysML and SCADE Suite functional model right now. Please check this section so that we can close this issue.

**Comment by mahlmann** [comment]
Section has been completed.
