### ISSUE TITLE
ATTENTION:ADD documents in sections overwritten by accident

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#748]
I just recognised a couple of unexpected commits of tex-files of partners by other partners.
.
We need to sort this out - please make sure you kep your up-to-date files available.

We will discuss the proceeding tomorrow in our telco.

cu
Bernd

@UweSteinkeFromSiemens  @mairamou  @mahlmann @pey

**Comment by JakobGartner** [comment]
We have another strange effect:

My last commit was also strange. I did not intend to merge anything.

I just synced (without no local changes)

Mairamou had a similar effect, Github displayed changes directly after a fresh clone (without any local changes)

**Comment by BerndHekele** [comment]
As I understand the history somebody pushed the old version of a couple of files.
I was just about to push my changes.

With the pull  - my todays's work just vanished without any further notice by smartgit.

I believe we need to revoke a commit - but not without having had a short discussion on the situation.

kr
Bernd.

**Comment by BerndHekele** [comment]
I did a first check on the sysml mode - that looks up-to-date.
The check of the Scade model is started.

**Comment by mahlmann** [comment]
ADD seems to be fine, too.

@BerndHekele Please inform all developers once you finished checking the SCADE model.

**Comment by BerndHekele** [comment]
Scade model looks also up-to-date.
Lets continue working as usual.
