### ISSUE TITLE
ADD / D3.5.3 / F1: Receive Information from Trackside

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#751]
Dear @JakobGartner , @mairamou ,

with respect to #651 Chapter 4 F1: Receive Information from Trackside needs to be completed. Please let me also know if new components need to be created in this chapter.

Considering that the ADD document is overdue already, I kindly ask you to take action on this issue as soon as possible.

General remark: *Please do not change the template structure, e.g. do not remove rows from the input/ouput descriptions. If a particular row is not relvant for a specific input/output just state "n/a" there.*

**Comment by JakobGartner** [comment]
ok will do our best, in function of the project priorities we get assigned …

**Comment by mahlmann** [comment]
Note that #742 (i.e. TrackAtlas documentation) should be of higher priority than this issue.
