### ISSUE TITLE
ADD / D3.5.3 / F2: ETCS Kernel Overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#754]
With respect to #651 and openetcs/product-backlog#32 Section 5.1 _ F2: ETCS Kernel Overview_ needs to be completed.

I will assign this issue to myself, however support from @BerndHekele is needed here.

**Comment by UweSteinkeFromSiemens** [comment]
Please note, that MoRC_Main was enhanced for integration with the new message bus. Therefore, the output msbBus_out  was added to replace MessageToRBC. MoRC_Main itself is subject to be replaced by MoRC_HO afterwards. 
I'm in doubt, if the SysML model and the ADD should be kept in sync with every temporay modification of the SCADE Suite models.
