### ISSUE TITLE
Levels.etp:: model files are not loadable

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#755]
Dear MAriell,
the files currently available on github do not load in Scade Design. Can you please check on delivered files and re-submit.

thanks.
Bernd

**Comment by MariellePetitDoche** [comment]
There are definitely lots of troubles between Scade and github.
All Level models was initially in only one file, which can not allow to improve the thiings.

And the new version of Scade is less stable than the older : I have plenty of craches during saving...And difficulties to reload properly the models then.
I thing the only  thing I hav to do is to rebuild a new model.

**Comment by BerndHekele** [comment]
Can you please fall-back to the version before change and prepare the changes offline?
If needed I can push the old model from my PC.
I can offer to set-tp a session to have a closer look at the files before delivery in  order to simplify the transmission?

cu
Bernd

**Comment by MariellePetitDoche** [comment]
I have fall back before doing change.

But the change of version + refactoring +  compatibility git-huband Scade +  stability with the new version of Scade is really complex.


I think, that it is best if les as possible persons touch the models, as git compare on some files are not possible as the files are too large.

**Comment by MariellePetitDoche** [comment]
New push done.

**Comment by BerndHekele** [comment]
Thanks Marielle,
we still have an problem in the list of linkex xscade files.
Can you please delete the Levels_Pkg.xscade file out of this list:
![image](https://cloud.githubusercontent.com/assets/3288918/10099713/9160393a-638c-11e5-8948-0f2f32f85c82.png)

**Comment by MariellePetitDoche** [comment]
Done.

**Comment by MariellePetitDoche** [comment]
ModesAndLevelsManagement node is ready for test, verification, validation

**Comment by MarcBehrens** [comment]
Thank you for the notice. Currently we are at the architecture verification already taking a peek into the design.

**Comment by MariellePetitDoche** [comment]
Done
