### ISSUE TITLE
RBC_Scenario_Pkg::Compile Error in integration model

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#756]
Hi,
I get the following error out of compilation of our testbench:
![image](https://cloud.githubusercontent.com/assets/3288918/10067247/2017f390-629b-11e5-8836-fb9f045cc9f1.png)

Can you please provide a correction.

Thanks.
Bernd

**Comment by apinnau** [comment]
Should be fixed with last update...

**Comment by BerndHekele** [comment]
solved
