### ISSUE TITLE
GitHub Issues

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#757]
As reported by several people, we had some GitHub issues recently. As presumed by @jokaICS already, this seems to be related to different behaviour with case sensitivity of the varios systems used by the developers (c.f. screenshot)
![capture](https://cloud.githubusercontent.com/assets/3638145/10072035/c669b5e4-62be-11e5-8d0c-bfef3169be2f.PNG)

@jokaICS It would be great if you could further investigate this.

**Comment by BerndHekele** [comment]
@jokaICS  @UweSteinkeFromSiemens 
Looks like the lost files are popping up again.
Can you please check on the files with the wrong location and make sure we can delete this branch as soon as possible.

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
The path scade/system/obufunctions does not exist in my local clone. I don't mind if it would be removed.

**Comment by jokaICS** [comment]
@BerndHekele 
> and make sure we can delete this branch as soon as possible.

Which branch do you mean? Or did you refer to the path `scade/obufunctions/`?

**Comment by jokaICS** [comment]
@UweSteinkeFromSiemens 
> The path scade/system/obufunctions does not exist in my local clone. I don't mind if it would be removed.

Hmm, if you're on windows, the files under `scade/..` are probably mapped to your exsiting `Scade/..`, so I'm not sure that removing these files has no effect...

**Comment by UweSteinkeFromSiemens** [comment]
@jokaICS : if scade/system/obufunctions would be deleted, I will re-add them from my lokal work space. By the way, the path on my local PC is Scade\System\ObuFunctions.

**Comment by JakobGartner** [comment]
my only remark to this issue is that until this week we have been working with the "mixed clients" environment without any problem.

**Comment by BerndHekele** [comment]
@jokaICS 
Indeed, I mean the double folder.
I'm working with plain Windows and cannot see the files or the wrong folders.
Can you see them on ypour machine and maybe delete?

**Comment by jokaICS** [comment]
@BerndHekele  Ok, then I will delete it.

On a side note: maybe setting the git property `core.ignorecase` could help to avoid these issues in the future (although I'm not sure, if we should all set it to `true` or `false`).it's probably best to simply delete these files. See [git-config](https://www.kernel.org/pub/software/scm/git/docs/git-config.html).

**Comment by UweSteinkeFromSiemens** [comment]
My local clone comprises a config file with ignorecase = true. Is'nt this file sychronized on github as other versioned files?

**Comment by stefan-karg** [comment]
In my clone (Windows 7, git-client: TortoiseGit) the setting  ignorecase = true is also set.
We also checked the setting of the official github-client for Mac OS X, there the setting is also set to true.

**Comment by mairamou** [comment]
I also have it "true" 

On 2015-09-24 14:57, Stefan Karg wrote: 

> In my clone (Windows 7, git-client: TortoiseGit) the setting ignorecase = true is also set.
> We also checked the setting of the official github-client for Mac OS X, there the setting is also set to true. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/757#issuecomment-142919589

**Comment by mahlmann** [comment]
I think this GitHub issue has been solved in the meantime, thus this issue will be closed.
