### ISSUE TITLE
Entering Trip Mode does not trigger the expected reaction

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#758]
Due to the problem in track data, the train has entered the Trip mode. 

Due to 4.4.13 This mode should command the emergency brakes and give an indication to the driver.
None of this happened on my system.

Is this functionality not implemented yet? At least the brake should be activated.

**Comment by BerndHekele** [comment]
Hi Jan,
function is implemented but to be corrected.
We recognized this error as well and need to analyse the root-cause.

Thanks
Bernd

**Comment by janWelte** [comment]
The DMI message to acknowledge for the drive that TR is entered is incorrectly shown when the train reaches speed 0 in TR mode.

**Comment by BerndHekele** [comment]
Done.
