### ISSUE TITLE
Linking information in LRBG362_P005_1

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#760]
If checked the new linking information and found that there is also a mistake in the linking information from LRBG362 (same in the package for the TestA01 track with BG362.

Here section 2 names the BG368 instate of the correct BG366. This tripos the train again.

![image](https://cloud.githubusercontent.com/assets/2719967/10078303/59c2b0dc-62e4-11e5-9a1e-3b3ed9cd0e2a.png)

**Comment by stefan-karg** [comment]
Corrected.
