### ISSUE TITLE
Testbench_Integration: error during compilation of SDY1_MainScreen

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#762]
When I try to run the Testbench_Integration, I get the following error during compilation:
```
I0001: SCADE RP Simu Version 6.6.1 i8 (c) Esterel Technologies 2010-2015 started at 2015-09-25T09:16:31.
I0005: Command line: ScadeRPSimu.exe -outdir C:\openETCS\System\OBU_PreIntegrations\Testbench_Integration\SimuBernd\SDY1_MainScreen\Code -prefix SDY1_MainScreen_ C:\openETCS\System\OBU_PreIntegrations\DebugPanel\MainScreen.rgfx "C:\Program Files\Esterel Technologies\SCADE R16.2.1\SCADE LifeCycle\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt" "C:\Program Files\Esterel Technologies\SCADE R16.2.1\SCADE LifeCycle\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft" C:\openETCS\System\OBU_PreIntegrations\DebugPanel\colorTable.sct "C:\Program Files\Esterel Technologies\SCADE R16.2.1\SCADE LifeCycle\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt" "C:\Program Files\Esterel Technologies\SCADE R16.2.1\SCADE LifeCycle\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst"
E0104: C:\openETCS\System\OBU_PreIntegrations\DebugPanel\MainScreen.rgfx:1498: Too many parameters "TextColor_disable".
E0104: C:\openETCS\System\OBU_PreIntegrations\DebugPanel\MainScreen.rgfx:1590: Too many parameters "TextColor_disable".
E0104: C:\openETCS\System\OBU_PreIntegrations\DebugPanel\MainScreen.rgfx:1682: Too many parameters "TextColor_disable".
I0006: Generated file: C:\openETCS\System\OBU_PreIntegrations\Testbench_Integration\SimuBernd\SDY1_MainScreen\Code\ScadeRPSimu.log
I0002: SCADE RP Simu finished with 3 error(s) at 2015-09-25T09:16:32.
```

Can anybody confirm/ reproduce this problem?

**Comment by stefan-karg** [comment]
Dear Johannes,

can you please try the following steps to solve the problem:

* Open the project "System\OBU_PreIntegrations\DebugPanel\MainScreen.rgfx" in SCADE RapidPrototyper
* Open the graphical panel (located in the "Graphical Panels" section left in the screen)
* Use Object->Update all references and Object->Update all behaviors

![update](https://cloud.githubusercontent.com/assets/1040937/10096600/314c9502-6373-11e5-9e07-776cf2b2e166.png)

This solved the issues for me while compiling the RapidPrototyper panels.

**Comment by jokaICS** [comment]
@stefan-karg your tip solved the issue, thanks for your support.

**Comment by BerndHekele** [comment]
The problem is stip apperent in the installation when you start fresh.
I keep this issue open for information.

**Comment by BerndHekele** [comment]
@stefan-karg 
We have a real problem with this model now.
It seems to be "out-of-control".

we need a different solution for this function.

cu
Bernd
