### ISSUE TITLE
ManageLevels: unconnected operator 

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#764]
@MariellePetitDoche `ManageLevels` contains an unconnected operator which prevents the current HEAD from compiling.

**Comment by MariellePetitDoche** [comment]
As said several time, this part is on going work. With element regulary pushed to avoid to lost my work by inconsistencies between github and scade.

Thus please DO NOT TOUCH this part on github, Thanks to an imprudent automatic merge this week-end I have still lost my work on last week.

**Comment by jokaICS** [comment]
Well, couldn't you open a separate branch for your refactoring and provide a compiling dummy implementation on the master? I don't want to touch your model parts -- it's just a problem for me when the model won't compile after a pull/push. I really need a working EVC to get on with my activities...

**Comment by BerndHekele** [comment]
@jokaICS 
We also suffer under this circumstances.
We have chosen a temporary solution which is based on using the deliverable of ModeAndLevel from September 22nd 18:24.
I propose we have a short agreement on how to resolve this impediment in tomorrows telco.
This issue is a duplicate to: #755

**Comment by jokaICS** [comment]
@BerndHekele thanks for the info, than I will use that commit as well.
