### ISSUE TITLE
Train_position : Min Safe rear end

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/modeling#766]
@UweSteinkeFromSiemens ,

for some requirements (5.10.3.3.3, 5.10.3.6.2, 5.10.3.10.3 of SRS) I need to know "Min safe rear end" of the train.

I do not found this information in the structured type trainPosition_T.
Do you compute it ?

**Comment by UweSteinkeFromSiemens** [comment]
The rear end is only one subtraction far away. It is no problem to add this information to the output. Since until now, even the front end was not requested from other functions. 😊
I will provide the rear end with th

**Comment by UweSteinkeFromSiemens** [comment]
The rear end is only one subtraction far away. It is no problem to add this information to the output. Since until now, even the front end was not requested from other functions. 😊
I will provide the rear end with the next update.

**Comment by MariellePetitDoche** [comment]
Thanks Uwe.

I use exactly for the moment::
 estimatedFrontEndPosition
maxSafeFrontEndPostion

**Comment by UweSteinkeFromSiemens** [comment]
... and you will get the same kind of information for the rear end.

**Comment by UweSteinkeFromSiemens** [comment]
... and is available on github now.

**Comment by BerndHekele** [comment]
This interface change has an impact on other models!!!
I see impact in the following models:
- ProvidePositionReport_Pkg @christianstahl 
- ValidateDataDirection_Pkg @berndhekele
 - CheckBGConsistency_Pkg::@berndhekele

please make a quick fix for those problems.

**Comment by MariellePetitDoche** [comment]
It is perfect for me.

**Comment by UweSteinkeFromSiemens** [comment]
Unavoidably the added field ofa structured type affects all components using this type.

**Comment by UweSteinkeFromSiemens** [comment]
Done.
