### ISSUE TITLE
ADD / D3.5.3 / introduction and chapter I: high level review of openETCS Architecture and Design Specification chapter 1

### ISSUE THREAD

**Issue by michaelmoensters** [openETCS/modeling#770]
Hello, I'm Michael from the DLR in Braunschweig. My task is to help Marc with the verification of the deliverable D3_5_3 ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3). Related to: https://github.com/openETCS/validation/issues/305
So I made a high level review and found some points.

questions referring to deliverable D3_5_3 (as of 23.09.15):

page iii:
- why was the track Utrecht - Amsterdam chosen? unfortunately there is no explanation

page 1:
- mistake: genereation => generation

page 4:
- bullet point 4 sounds unclear; the term 'ERMTS Track' is not mentioned there, maybe it should be?

page 5:
- composition of figure 1 is difficult to understand
- the red line is not explained in an adequate way, more explanation would be better
- the so called blue line seems to be black, so the colour has to be corrected
- the blue line is not explained in an adequate way, more explanation would be better

page 6:
- some terms in figure 2 are difficult to read, because the font size is too small (e. g. in the yellow boxes)
- maybe it is confusing for the reader, when BTM and Euroradio are packed together in one module 
(on the rolling stock/vehicle BTM and Euroradio are two different modules, which are separated physically)

page 7:
- some terms in figure 4 are difficult to read, because the font size is too small (e. g. in the yellow boxes)

**Comment by mahlmann** [comment]
Dear @michaelmoensters 

thanks for your feedback. Please note however that these chapters have by no means been completed yet and will be subject of a major revision (amongst textual improvements all figures will be replaced by figures generated from the new SysML model). For the revision we will of course take your comments into account.

**Comment by mahlmann** [comment]
Document has been released, issue will be closed.
