### ISSUE TITLE
Levels::RequestAck with positioning error

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#771]
I'm testing level transitions with indication of a position.
In the calculation of the appropiate action the referenceLocation (the Location of the LRBG) is not considered.
![image](https://cloud.githubusercontent.com/assets/3288918/10246276/0989521a-6910-11e5-918f-18fe95b53c16.png)

![image](https://cloud.githubusercontent.com/assets/3288918/10246302/3c8c4d34-6910-11e5-9a0f-5f4c2ce83799.png)

The calculation should be based on D_AREA = D_AREA + reference.

cu
Bernd

**Comment by BerndHekele** [comment]
A second finding at exactly the position where the Level Transition is received in ManageLevels (same cycle as situation above):
 - the Level is changed immediatly at reception of the level transition
 - the Levels requests SB. This conclusion is not clear to me.

![image](https://cloud.githubusercontent.com/assets/3288918/10246505/48ae4462-6912-11e5-9e4b-2e0c80e3e38b.png)

![image](https://cloud.githubusercontent.com/assets/3288918/10246578/dc7b5bd0-6912-11e5-9f9a-37e5e991b949.png)

**Comment by MariellePetitDoche** [comment]
The first problem shall be correct at the input in NormalTransition node with a clear indication that the distance provided by packet 41 is relative to the balise position and not absolu:
When building level transition info, referenceLocation input shall be added to D_LevelTr (transformed) to calculate "position".

Same kind of problems can occurred for mode transition.

For the second problem, the immediate change is linked to the same problem.
Then I do not understood how "Levels requests SB" ? SB = StandBy or Service brake ?
If Service brake, there is due to the same problem.

**Comment by MariellePetitDoche** [comment]
I will not be to the office before next  Thursday, thus I will not have scade licence to make the change before.

**Comment by MariellePetitDoche** [comment]
Same corrections will be necessary in node Inputs_Modes and down to build the information relative to modes profiles, reversing and staff responsible.

**Comment by BerndHekele** [comment]
Thanks for the quick response.
We have two options now to proceed:
a) we wait until you are back in the office and continue next week. This implies we need to maintaine the old levels for some time for other testers.
b) I try to take your advice and prepare / do some of the corrections on my own.
What do you prefer?

cu
Bernd

**Comment by MariellePetitDoche** [comment]
![normalcondition](https://cloud.githubusercontent.com/assets/2233518/10247128/07220dd0-6917-11e5-9a6c-b1267888b36e.png)

I think second solution is the best for your current test, simply add a "plus" operator in NormalTransition in ModesAndLevelsManagement package as indicated in the picture.

For modes you can continue your tests without impact

**Comment by BerndHekele** [comment]
Thanks. I will follow your advice.

**Comment by BerndHekele** [comment]
@BaseliyosJacob 
I'm preparing a workaround which will allow testing with this model according to the track-description.

**Comment by BerndHekele** [comment]
@BaseliyosJacob 
I have implemented a small workaround in the evc model which allows for testing without having the fully working levels model the workaround does not bypass levelmanagement. It changes the level order to immediate and to happen about the position where it is expected.
 
However, testing the planning area is currently not possible because of missing workarounds in the trackatlas.
@stefan-karg @JakobGartner

**Comment by BaseliyosJacob** [comment]
Hello Bernd,

we should test on monday with @stefan-karg the work around in the DMI since he has push it on Git hub. Maybe there are missing some fixes on the master branch.

@stefan-karg i will be in Berlin on Monday but we can have a short session in the morning.!

**Comment by BerndHekele** [comment]
@MariellePetitDoche 
I tested the following corection in Normal_Transition:
![image](https://cloud.githubusercontent.com/assets/3288918/10275939/e57afa66-6b4b-11e5-8f12-ddf5098a244f.png)

The correction works. 
I see more Problems in the sequence and will open issues for each topic seperately.

**Comment by MariellePetitDoche** [comment]
Modification put on github for input of level and Modes.
