### ISSUE TITLE
TrackAtlas::Missing workaround

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#772]
In the current model on github I do not see a working workaround which allows testing planning area.
Can you please push the used solution on github.
I also expect corrections of known problems - please confirm the master branch is up-to-date.

kr
Bernd

**Comment by stefan-karg** [comment]
Dear Bernd,

the correction of the TrackAtlas was made in commit 89383d30350491b70d9364878f829d006af78a5c. In my clone, this change is made on the master branch and it is also visible to me on github.

The changes are made to the operator TA_Export::MRSP_to_MRSP_to_DMI in the TrackAtlas project.

The operator should look like this in the current state:
![dmi](https://cloud.githubusercontent.com/assets/1040937/10264953/5f5ffd2a-6a1d-11e5-82a5-3c50f4d4ce84.png)

Can you confirm that in your clone too?

Stefan

**Comment by BerndHekele** [comment]
Hi Stefan,
this change is in my copy of the master as well. looks ok.
What I'm missing is something like this workaround:
![image](https://cloud.githubusercontent.com/assets/3288918/10265151/38ec4ade-6a24-11e5-9595-ccd46b7f8619.png)

![image](https://cloud.githubusercontent.com/assets/3288918/10265155/5a0e12a6-6a24-11e5-91de-361f38c1fe1a.png)

in the trackAtlas.
Is this no longer needed?

**Comment by JakobGartner** [comment]
This is being replaced by a different approach that inserts NTC information on the input side of the TrackAtlas in order to ensure constant valid outputs to SDM

**Comment by BerndHekele** [comment]
Nice to know. This change is not in the current evc model implemented. 

I need a clear guidance on where and how this correction looks like.

**Comment by JakobGartner** [comment]
The change is doing the following:


TrackAtlas is always emitting valid MA, also in NTC mode

When in NTC mode the values reflect the expected behaviour in NTC mode (never- ending MA) and the relevant SP.


Expect it to be committed this afternoon.


(this is a solution, not a workaround …)

**Comment by JakobGartner** [comment]
awaiting the definitive solution, I have now pushed a simple one that looks good in @stefan-karg 's test environment (the push is called YAIT, af1a97d)

**Comment by BerndHekele** [comment]
I close this issue. Done.
