### ISSUE TITLE
UtrechAmsterdam::Compile Error in model

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#774]
I get 6 errors in the track model:
![image](https://cloud.githubusercontent.com/assets/3288918/10267218/b242e5d4-6a8b-11e5-9b20-dbe97e9731fe.png)

![image](https://cloud.githubusercontent.com/assets/3288918/10267220/dbfa92dc-6a8b-11e5-9416-30dab5a49b0b.png)

Can you please correct the model.

**Comment by mairamou** [comment]
done 

On 2015-10-04 11:35, Bernd Hekele wrote: 

> I get 6 errors in the track model:
> [1] 
> 
> [2] 
> 
> Can you please correct the model. 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/3288918/10267218/b242e5d4-6a8b-11e5-9b20-dbe97e9731fe.png
[2]
https://cloud.githubusercontent.com/assets/3288918/10267220/dbfa92dc-6a8b-11e5-9416-30dab5a49b0b.png
[3] https://github.com/openETCS/modeling/issues/774
