### ISSUE TITLE
DMI_Control::Compile Error in model on github

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#775]
I get the following error from DMI Compilation:
![image](https://cloud.githubusercontent.com/assets/3288918/10267313/80604292-6a8f-11e5-96e5-9b987ed97b3e.png)

![image](https://cloud.githubusercontent.com/assets/3288918/10267316/995302c6-6a8f-11e5-8786-5b6c29e97c37.png)

**Comment by BaseliyosJacob** [comment]
@BerndHekele should be fixed in the last commit
