### ISSUE TITLE
Levels:output to the DMI with wrong level in level transition.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#777]
When reaching the ack area the wrong level (ntc) is sent to the DMI.
![image](https://cloud.githubusercontent.com/assets/3288918/10276018/bf19b0f0-6b4c-11e5-8af7-4fbb7459bdb8.png)

**Comment by BerndHekele** [comment]
I have tested the following solution in Output_To_DMI:
![image](https://cloud.githubusercontent.com/assets/3288918/10280429/6c7a9c30-6b6d-11e5-9220-1e18a6967223.png)

**Comment by MariellePetitDoche** [comment]
I am not in favour of this solution. As announced level is really different that new level and shall not be considered in the same way. Besides announced_level can not be considered as simple level but with other information.

I think the best is to clarify the structured type data to dmi, and to not considered it for an output of M&L but shall be rebuild outside from the real outputs.

**Comment by BerndHekele** [comment]
I do not understand your proposal.
Do you mean you intend to change the interfaces from ML to the DMI?

**Comment by MariellePetitDoche** [comment]
Indeed in your proposal, you change the meaning of "new_level" in the structure DMI_Types_Pkg::DMI_ModesToDMI_T, which is defined in opposition of "previous_level". (it is not clearly commented, it is an interpretation on the name).

In your change you add a possible annouced level without taking into account, position, border,...
Thus you change the meaning of the ioutput.

In a more general way I think that the module which propose an output shall be in charge of the type definition of the output. It is not the case here. Thus I am in favour to change the output interface and to not use anymore external types. All the information you need to fill the structure DMI_Types_Pkg::DMI_ModesToDMI_T are given by other outputs., and I can comment them to give them clear definition.

**Comment by BerndHekele** [comment]
I propose we have a gotomeeting for the open issues.
Can we meet tomorrow (Friday). I propose we can discuss details of the solution based on the running model?

cu
Bernd

**Comment by MariellePetitDoche** [comment]
yes.

**Comment by BerndHekele** [comment]
Solution is to be provided in the evc model based on the new interfaces.

**Comment by MariellePetitDoche** [comment]
Done.

**Comment by BerndHekele** [comment]
Correction is tested.
