### ISSUE TITLE
Levels:Ack from DMI in Loop

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#779]
The ack-request for a level changes to the DMI is sent in a Loop:
Levels::Request_Ack does not remerber having sent a message before.

**Comment by MariellePetitDoche** [comment]
I do not understand, it is not a loop but a state machine, the information is send till ack is received:
![figure_5_diag](https://cloud.githubusercontent.com/assets/2233518/10362500/3c438344-6daf-11e5-807e-06c1ea3f215b.png)

**Comment by MariellePetitDoche** [comment]
thanks to  test the correction.

**Comment by janWelte** [comment]
I'm sorry to say, that the level transition is still not working properly. 
I received 2 Acknowledgement messages on the DMI and the system switched back to NTC at the BG 355.

Proper behaviour according to 5.10. would be:
- 5.10.1.3 Message to the driver when transition announcement is received
- 5.10.1.4 switch at the border marked by a balise (is in our case BG 355 with P 46), or if BG is not found switch according to  5.10.1.5

**Comment by MariellePetitDoche** [comment]
It will be nice to verify the change of the the value "valid" in entering packet 41 or 46.
Or record a test and send me it.

**Comment by janWelte** [comment]
I'm looking at it at the moment.
Which values would be most helpful, as I'm just running the intergration at the moment

**Comment by MariellePetitDoche** [comment]
occurrences and values of P41 and P46, selected transitions, next and last level...

**Comment by BerndHekele** [comment]
Correction is tested.
Since this part of level-magement is proofen to work I close the issue.

Thanks.
