### ISSUE TITLE
Trip at Balise 358: BG358 not in linking list

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#780]
The list looks like follows:
![image](https://cloud.githubusercontent.com/assets/3288918/10281248/76de639a-6b73-11e5-808c-20f3a9e1a3c0.png)

Seeing the size of the linking list in Uwe's model and the lnumber of sections to be covered before next linking data is sent I believe we now need to extend the list in the interfaces to a reasonable size.
@UweSteinkeFromSiemens 
@JakobGartner 

I propose to use at least 33 elements in the interfaces.
Uwe, can you please confirm?

**Comment by UweSteinkeFromSiemens** [comment]
This should not be functional problem. 

From the practical view of testing, I would prefer to stay with the current limited lengths instead of being snowed under long lists otherwise. An increase to 33 will lead to at least 66 elements of the list shown above and truly fill the screen. 
 
Please decide for your own, if this is really what you want.

**Comment by BerndHekele** [comment]
The size of the list is also touched in #624

**Comment by BerndHekele** [comment]
This argument is valid.
But we need to have a list which is tailored for the track requirements.

**Comment by BerndHekele** [comment]
The biggest list I can see from the track has 29 elements.
This is fairly close to 33

**Comment by BerndHekele** [comment]
@JakobGartner 
@mairamou 
Do we need changes in the track model or in the tm model as well?

**Comment by BerndHekele** [comment]
I did a check on dependencises to other models.
I can see impact in the EVC, Calculae Train Position, Manage Trackside, TM, Provide Position Report.
I would like to do this change tomorrow after a discussion in our telco.

Any objections?

**Comment by JakobGartner** [comment]
No, this should have no impact.

On the track, we can see 32 increments + the initial distance 

The operator for conversion to Uwe’s type is already based on Uwe’s dimensioning constant

**Comment by UweSteinkeFromSiemens** [comment]
The modification can be achieved by changing BG_Types_Pkg::cMaxNoOfLinkedBGs accordingly.

**Comment by BerndHekele** [comment]
As agreed in the morning session I pushed the interface change.
I see dependencies in TM @JakobGartner and calcTrainPosition @UweSteinkeFromSiemens .
I take care on Position Report dependencies.

**Comment by janWelte** [comment]
The constant cEmptyPositionedBGs has to be adopted to the new array size.

@UweSteinkeFromSiemens

**Comment by UweSteinkeFromSiemens** [comment]
@janWelte : could you please give a reference to cEmptyPositionedBGs, since it is not found within calculateTrainPosition with circumstances.

**Comment by BerndHekele** [comment]
Corrections are available. I tested the evc with this bg - works.
I close this issue.
