### ISSUE TITLE
RBC model check issue

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#788]
Dear Alexander,

since the last commit of the RBC system I face a problem checking your model. If I run the SCADE check on the top layer operator of the RBC, then I get the following error message:

Completion Error SE_EXILPA Illegal Empty Parameter

**Comment by apinnau** [comment]
Hi Stefan,
I've fixed this just a few minutes ago... pls just pull my last commit.

**Comment by stefan-karg** [comment]
Thank you for the quick reply, after the first pull I did not check again :-)
