### ISSUE TITLE
Level Transition back to NTC at wrong place

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#789]
Shortly after the correct level transition to L2 the train switches back to NTC. This is probably cause by a conditional transition.

More details will be provided.

**Comment by MariellePetitDoche** [comment]
Can be llinked to  #779 for which I am preparing a correction today.

**Comment by janWelte** [comment]
Thanks

**Comment by MariellePetitDoche** [comment]
Thanks to test the correction.

**Comment by BerndHekele** [comment]
@janWelte 
@MariellePetitDoche 

This problem is still open.
(It is hidden behind a workaround I use in the EVC model).
Do you need more information for the solution?

**Comment by janWelte** [comment]
It would be important to no what is the workaround at the current model to identify the cause for the wrong behaviour.

**Comment by BerndHekele** [comment]
Hi Jan,
the analysis I did on this error reslted in a wrong internal handling of the intial value. This an input to Level management.

My workaround makes sure the default is only used in the first cycle and later on the last valid level is used.
You can see the workaround in the evc model.

kr
Bernd

**Comment by stefan-karg** [comment]
Fixed
