### ISSUE TITLE
LevelManagement: Level jumps back to NTC after level change.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#791]
Having completed the level change Level Management jumps back to level ntc.
![image](https://cloud.githubusercontent.com/assets/3288918/10400757/f55a647c-6eba-11e5-9a7d-5d748d1cab97.png)

On a first glance it looks like a wrong use of the input MemorizedLevelIn??

**Comment by BerndHekele** [comment]
I was testing with the original Mode and Level. 
I have seen a duplicate #789 and will close this issue as soon as this is confirmed.
I need to tadopt to the new interfaces first before being able to close this issue.

Bernd

**Comment by BerndHekele** [comment]
I have tested with the newest Level-Management.
The error is still in the software.
I will look for a workaround in the evc-model.
Please let me know if you need additional information.

P.S.: I believe this default value should only be used once. at start-tp of the levels model.

**Comment by MariellePetitDoche** [comment]
I can not investigated without a test which reproduce the error.

**Comment by janWelte** [comment]
A Test will be provided next week, when I'm back in office and can have a look at the new model with a track corrections. I was not sure, whether the shift was due to Level and Mode.

Am 15.10.2015 um 10:41 schrieb MariellePetitDoche <notifications@github.com>:

I can not investigated without a test which reproduce the error.

**Comment by BerndHekele** [comment]
I can reproduce this issue in the testmodel. If you like to join ina goto-meeting I can arrange a session.

**Comment by MariellePetitDoche** [comment]
I will be available today or monday

**Comment by BerndHekele** [comment]
solution is available.
