### ISSUE TITLE
LevelAndModes:OutputManagement is indicating ML_Ack to DMI wrong for one cycle.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#793]
When changing Levels the output Acknowledge DMIis valis but has no reasonable other data:

![image](https://cloud.githubusercontent.com/assets/3288918/10412070/936406a4-6f7a-11e5-8b4b-37e627328095.png)

The valid flag is set because of the isNew:
![image](https://cloud.githubusercontent.com/assets/3288918/10412061/635d514a-6f7a-11e5-9ffb-77c074d63e7b.png)

What is the reason for this output?

**Comment by MariellePetitDoche** [comment]
It is a remaining of the old structure, I will change it.

**Comment by MariellePetitDoche** [comment]
Correction to be tested.

**Comment by BerndHekele** [comment]
solved
