### ISSUE TITLE
BG-366:inconsistent linking information in track model

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#796]
When passing BG 366 evc goes to trip.
Reason is linking inconsistency.

![image](https://cloud.githubusercontent.com/assets/3288918/10415964/db61114a-7001-11e5-9126-9a0e2c0abbe8.png)

kr
Bernd

**Comment by BerndHekele** [comment]
I propose the following correcton:
![image](https://cloud.githubusercontent.com/assets/3288918/10416001/1f4b47d0-7003-11e5-8f0d-d00dfd86cad1.png)

**Comment by mairamou** [comment]
I see that there are some problems in LRBG362_P005_x and LRBG364_P005

I will cross check with the modelled engineering data and the data in the JRU.

**Comment by mairamou** [comment]
I have corrected Packets426::LRBG362_P005_2 where the reference to BG 366 was actually missing.

**Comment by mairamou** [comment]
(the push may need some time as I have connection problems)

**Comment by BerndHekele** [comment]
I will test after the type changes are done.
Thanks.

**Comment by janWelte** [comment]
Seams to be the problem already reported in #760. Please close both issues if checked.

**Comment by BerndHekele** [comment]
Solved
