### ISSUE TITLE
MA_Request::Sending permanent Message

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#797]
Dear Christian,
I'm now looking into the communication evc - RBC with focus of the MA.
I can see some behaviour in the model which needs clarification.
Can we have a goto-meeting session in order to have a closer look at the answers?

kr
Bernd

**Comment by KlausRuedigerHase** [comment]
belongs to #248

**Comment by mahlmann** [comment]
As this is blocking `Use Case 9` (#248) please take action on this asap .

**Comment by JakobGartner** [comment]
In the course of the integration of the "bus", I have already to started to rework this module.
There was a fundamental problem (wrong initialisation of boolean activates) but I have not yet tested the new behaviour. I will take this issue as I see it mainly as an integration issue with the rest of the TrackAtlas.

**Comment by christianstahl** [comment]
@JakobGartner The issue is not fixed yet. I will work on a fix.To simplify matters, in case of MA requests shall be repeatedly sent, I will assume that there is only one pending MA request (recall that there are several events triggering an MA request).

**Comment by christianstahl** [comment]
I pushed an update that should solve the problem

**Comment by BerndHekele** [comment]
The solution is still not 100 pro correct.
We have a workaround for this problem. Therefore I reduce the priority.

**Comment by BerndHekele** [comment]
I worked on a temporary correction for the timer mechganisme.
I would like to push this solution as a basis for discussion on Wednesday.

**Comment by christianstahl** [comment]
Fine with me

**Comment by stefan-karg** [comment]
Fixed
