### ISSUE TITLE
T_TRAIN type change

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#798]
The following models need to be adjusted in or5der to cover these changes:
1. TrackMessages @mairamou 
2. UtrechtAmsterdam @mairamou 
3. evc-model @berndhekele
4. trainData model @berndhekele
5. trackAtlas @JakobGartner 
6. MA_REquest @JakobGartner @christianstahl 
7. Testbench @stefan-karg 
8. Type Definition @BerndHekele
9. RBC @apinnau 
10. MoRC @UweSteinkeFromSiemens 
11. Procedures @BaseliyosJacob 
12. ManageTrackSide @BerndHekele
13. ProvidePositionReport @christianstahl 

Please, use this issue for documentation of the changes

In case you are not available to do the corrections short-term (today afternoon) we are willing to update the corrections on Git centrally.

**Comment by UweSteinkeFromSiemens** [comment]
- [x]  MoRC: done

**Comment by jokaICS** [comment]
@BerndHekele Just to be sure: the unit of T_TRAIN now is 10ms, correct?

**Comment by JakobGartner** [comment]
yes

**Comment by BerndHekele** [comment]
Unfortunately we have a little bit of a confusion again.
We have a central type defined in SS7 and a new type defined in TM.
Is this really helpful?
I changed the central type to int as well.
can you switch to this central definition?

**Comment by JakobGartner** [comment]
I have just done a parallel definition to decouple impact from my change.

Yes, it will be changed back to the central definition.

**Comment by stefan-karg** [comment]
- [x] CheckEuroradioMessage
- [x] Toolbox
- [x] TestbenchIntegration

**Comment by jokaICS** [comment]
- [x] RBC-System

**Comment by BerndHekele** [comment]
There is still a remaining outstanding correction in the track-atlas types.
@JakobGartner 
Can you please have a second check?
![image](https://cloud.githubusercontent.com/assets/3288918/10432473/899192ee-710b-11e5-8ea5-80827e564f59.png)

Thanks.

**Comment by JakobGartner** [comment]
This was a “backlash effect”… my type change triggered yours which caused this issue (which was not there when I pushed it with only my changes.
It has been fixed in my last push.

**Comment by BerndHekele** [comment]
I just pulled the latest model.
There are still  some errors in the RBC and in the TM-part  related to the t_train type change.
Can you please have a look at these topics:
![image](https://cloud.githubusercontent.com/assets/3288918/10477907/3065e4e0-725a-11e5-8d4b-167e1119cf45.png)

@jokaICS 
@JakobGartner

**Comment by jokaICS** [comment]
I've solved the errors in the RBC project.

**Comment by JakobGartner** [comment]
done
