### ISSUE TITLE
TrackMessages: Change of Train2Track Interface to BUS

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#799]
The following parties are involved in the first step:

- evc-model @BerndHekele
- RBC @jokaICS  
- testbench @stefan-karg 

In this first step we integrate an addition wire between EVC and RBC.
After first step is completed, the BUS will be activated inside the evc model. 
Then, all functions sending radio messages are also to be changed.

I will open a second issue on parties involved when the first step is stabilized.
Please, use this issue for reporting progress and problems with the proposed change.

kr
Bernd

**Comment by BerndHekele** [comment]
I started with this activity.
Unfortunately, we have a new type definition for the packets again.
It would have been a better solution to use the existing definitions.

**Comment by BerndHekele** [comment]
Question to the setting of T_TRAIN and l_message:
Who is setting these properies?

**Comment by JakobGartner** [comment]
The existing definitions have unusable stuff like “stuffing bits” which are not at all relevant at this level…

**Comment by JakobGartner** [comment]
L_MESSAGE: ignored for now 
T_TRAIN: set by the bus functions but they need the current global t_train as input

**Comment by BerndHekele** [comment]
If the definition has errors we can correct.
Now every application using P0 has to change.
I'm just preparing a mapping operator for packets in use. I recognised a missing field in your P0 definition: D_LRBG. Can you please add?

**Comment by BerndHekele** [comment]
Findings in P001: item NID_PRVLRBG is missing.

**Comment by JakobGartner** [comment]
Fixed for P0

**Comment by JakobGartner** [comment]
Fixed for P1

**Comment by BerndHekele** [comment]
Due to the new type-definitions of packets (I jump out of the window) I had to adjust some sizes of arrays.
We need to have a second round of constant-reset. In the following models you need to become active:
- MA-Request ( @JakobGartner , @christianstahl )
- trackAtlas ( @JakobGartner )
- MoRC ( @UweSteinkeFromSiemens )

Thanks for your support.

Bernd

**Comment by BerndHekele** [comment]
Has also impact on 
 - tools, testbench ( @stefan-karg )
 - rbc (old interfaces, @jokaICS )

kr
Bernd

**Comment by JakobGartner** [comment]
which packages do I have to pull to see your changes?

**Comment by jokaICS** [comment]
I've updated the RBC for the recent type changes.
BTW: when do you want me start migrating the RBC to the new Train2Track bus?

**Comment by BerndHekele** [comment]
@JakobGartner : you should get a fresh clone of all functions. We had a couple of changes.
@jokaICS : When are you ready. You are on the critical path. We can discuss this issue in today's telco.

**Comment by JakobGartner** [comment]
OK, I will deliver the complete Train To Track and the corrected models until 1pm today…

**Comment by jokaICS** [comment]
@BerndHekele Just give me the go, and I will make it my priority.

**Comment by JakobGartner** [comment]
done for TrackAtlas and MA request for type updates in constants

**Comment by BerndHekele** [comment]
I have extended the evc model with the bus. 
Function is not fully implemented but will follow as soon as possible.

**Comment by BerndHekele** [comment]
@stefan-karg : can you please adopt the changes to the testbench?

**Comment by stefan-karg** [comment]
The testbench is corrected now. The toolbox will be updated once the RBC is capable of receiving the new datatype.

**Comment by BerndHekele** [comment]
trainData and PositionReport are using the new bus now.
What is the status  of 
   TrackAtlas (MA_Request) ?
  MoRC?
  RBC

**Comment by UweSteinkeFromSiemens** [comment]
- [x] MoRC: Bus added

**Comment by JakobGartner** [comment]
done for MA request and for EM in TrackAtlas (but MA request is faulty, I am working on it, but that's an extra issue)

**Comment by BerndHekele** [comment]
@UweSteinkeFromSiemens 
Hi Uwe,
can you please also prepare the MoRC with HO to this interface change. I would like to be prepared for a quick replacement. I assume we have two bus systems depending on the mobile HW I will define a proper interface for the API output based on your definitions when we are ready to start.

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
@JakobGartner: An operator for merging 2 busses into 1 is required for this task. Is it or wil it become available?

**Comment by BerndHekele** [comment]
EVC is prepared for testing.
I'm waiting now for the rbc contribution. @jokaICS

**Comment by jokaICS** [comment]
I've implemented the new TrainTrack interface for the RBC; it's not fully functional yet, but compiles.

@BerndHekele There are two options for integration: you can either replace the old `RBC` with `RBC_new` (in RBC_Model_Pkg); as an alternative you can keep the old RBC in the integration model and just place the operator `ToOldRadioTrainTrackMsg` in front of it (to be found in package RBC_Model_Pkg::TrainTrackMsgConversion). Currently, `RBC_new` simply wraps this conversion operator, but I will replace it with a clean implementation in the next few days.

**Comment by BerndHekele** [comment]
@JakobGartner 
Dear Jakob,
I need an operator for converting bus -> messages.
Is this already existing and where can I find it?

kr
Bernd

**Comment by jokaICS** [comment]
@BerndHekele if you prefer, we can use the bus interface for the RBC instead of the message interface

**Comment by BerndHekele** [comment]
@jokaICS 
To your proposal: Technically nice but conceptual not according to the reality.

I start testing with your updated interface now.

cu
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
@BerndHekele : I will add the bus interface to MoRC_HO as well.

**Comment by JakobGartner** [comment]
There is an operator to merge two buses but is it what you need?

It takes two buses, buffers both and merges them into one, sorted by T_TRAIN.


Don’t you rather need to interface one EVC bus to two radio channels?

**Comment by UweSteinkeFromSiemens** [comment]
Yes, the merge operator is required for MoRC_HO internal use. 

And yes, MoRC_HO splits the bus into two outputs to the radio channels and switches over between them during the hand over process.

**Comment by BerndHekele** [comment]
Done.
