### ISSUE TITLE
DMI - EVC Bus

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#801]
In interface DMI - EVC will be upgraded to a bus-structure.

Involved Models:
- DMI Messages @Farhangi 
- DMI-Manager @berndhekele
- DMI Control @Farhangi @BaseliyosJacob 

Please, use this issue for reporting the implementation.

**Comment by stefan-karg** [comment]
The integration model has also to be updated. (@stefan-karg)

**Comment by jokaICS** [comment]
The imported operators for the TCP-based EVC/DMI split also need to be updated (@jokaICS).

@stefan-karg I suggest to get the EVC/DMI-split working before we switch to the new bus.

**Comment by BerndHekele** [comment]
Can you please give an update on the status of this activity?
@stefan-karg 
@Farhangi 
@jokaICS

**Comment by stefan-karg** [comment]
Dear Bernd,

Johannes was able to solve the problems with the cycling time and the Remote DMI is now working with a cycle time of 10ms.

We are investigating some buffering issues at the moment but the Remote DMI can be soon integrated into the master branch.

**Comment by jokaICS** [comment]
Dear Bernd @BerndHekele,

would it be alright if I added a new package to the Testbench_Integration project? We'd like to start with the new visualization UI, so I need to make a ROOT operator where I can replace the RTP-based GUI.

**Comment by JakobGartner** [comment]
I spent some hours today with MEN on the Track (RBC) - EVC bus.

We discovered a need for coordination with the EVC- DMI bus as they will use the same IP stack. 

Mr. Jendrusch will participate in tomorrows morning GotoMeeting.



Jakob

**Comment by jokaICS** [comment]
> We discovered a need for coordination with the EVC- DMI bus as they will use the same IP stack.

Just to clarify: does MEN want to use our TCP messaging library on their end of the bus? If so, what OS do they use (Linux?)

**Comment by JakobGartner** [comment]
What we have done right now is just get the TrackTrain/ TrainTrack messages running across TCP IP between their OBU HW and the trackside black box.

On the OBU they run QNX, the black box is a Linux derivate (Raspberry)


While they have defined the simple transport mechanism, there is no mechanism yet to distinguish the origin or destination of a given packet.

They have used the data types as provided by the Send/Receive Message/Packet operators of TrackMessages lib.


(with that they have closed their milestone of last week)

**Comment by jokaICS** [comment]
OK, so they use their own TCP/IP implementation. Just wanted to know, if I need to provide the implementation of our messaging lib for POSIX OS (we have no demand for this right now, since DMI & EVC currently both run on WIN).

**Comment by JakobGartner** [comment]
We can discuss tomorrow. But I think the best thing would be to agree on the high-level principles (like formats of transported data, addressing scheme for the different executables ) and to use the different IP stacks locally.

At the moment, they also don’t use an imported-operator approach but are interested in understanding it

**Comment by Farhangi** [comment]
The "DMI<->EVC messages bus"  is implemented and uploaded.
This module is therefore integriereted in "DMI Control"  and in "Testbench_Integration".
