### ISSUE TITLE
activation of planning area in FS

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/modeling#808]
During the current integration while entering FS the planning area is only displayed upon driver's request (pressing an area)

According to SUBSET-026-4.4.9.1.6	`The ERTMS/ETCS on-board equipment shall display the train speed, the permitted speed, the target distance and the target speed to the driver (this list is not exhaustive – refer to chapter 4.7 “DMI depending on modes”).` there is no driver interaction defined to trigger the planning area.

Thus the planning area should be displayed immerdiately upon entering FS:

**Comment by BaseliyosJacob** [comment]
Hello Marc,

thank you very much for the remark. Is this issue not a pending CR for the SRS? I understand in older version of the SRS (3.2.xx) ther is an interaction defined where the driver can trigger the planning area.  I can try to change it tomorrow if it relevant and in time for your presentation.

**Comment by MarcBehrens** [comment]
Hi Baseliyos,

thank you for the fast reply although no need to rush.
You are talking about CRL418 relating to target speed, target distance moving from `x` to `A` in version 3.2.0 it is more related to DMI area A and B.

According to 015560 (DMI Spec) `8.3.1.1 The planning information shall be shown in area D (see Figure 72) according to the
following conditions:
a) it is available, and
b) the current mode is FS, and
c) its status is “show planning information” (see 8.3.9)`

`8.3.9.7 The last status of the planning information shall be stored. In case no status is stored
onboard, it shall be considered as “show planning information”.`

So you are right about the existence of the function to hide the planning area, just the initial value should be 'show'.

**Comment by BaseliyosJacob** [comment]
Dear Marc,

thank you very much for the clarification. 

Yes, i do not know exactly the CR. But i know that the hide of the planning area is in a very critical discussion at different IM´s and RU´s.

I understand that we have to add the initial value "show"? 

But no rush for your presentation tomorrow?

**Comment by MarcBehrens** [comment]
The presentation evening reception already took place Wednesday and the visitors took great interest in the openETCS results. Especially the amount of functionality already implemented was positively received.

**Comment by MarcBehrens** [comment]
Yes, the initial value "show" would close this issue.

**Comment by BaseliyosJacob** [comment]
Hello @MarcBehrens,

i have just checked the ERA DMI Requirements 015560 (DMI Spec) and i found:

8.3.9.4 When using touch screen technology, when the planning information is hidden in FS
mode, the whole area D shall be sensitive and behave as a [Show] button to set the
status of the planning information to “show planning information”.

In our case we have a touch screen technology and the area D is consider a [Show] button. Is the current implementation not correct according to the Spec? 

Thank you very much

**Comment by MarcBehrens** [comment]
Due to `when` this does not contradict :
 `8.3.9.7 The last status of the planning information shall be stored. In case no status is stored
 onboard, it shall be considered as “show planning information”.`

**Comment by stefan-karg** [comment]
Fixed
