### ISSUE TITLE
TIU interface for brake release from Emergency Brake

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#809]
Dear @BerndHekele ,

@jokaICS is analyzing at the moment the US 15 and 16. Last week came to the result that we need an interface definition from in the TIU according to the release of the Emergency Brake.
Do you know if this is implemented in the current version?

Thank you very much

Baseliyos

**Comment by BerndHekele** [comment]
Hi Johannes,
we have an implementation of the TIU based on SRS and the Alstom API definition.
Please have a look at this document and let me know if open questions remain.

kr
Bernd

**Comment by BaseliyosJacob** [comment]
@jokaICS @BerndHekele,   

is this issue clarified since we have to freeze the interfaces today? Do we need a furhter analysis on go2meeting for clarification? 

Thank you very much

Best Regards

Baseliyos

**Comment by jokaICS** [comment]
I don't see that there would be something missing in the TIU interface for our user stories; however, being an interface, has ERSA already verified that the interface provides all data *they* need?

**Comment by stefan-karg** [comment]
Interfaces are frozen now.
