### ISSUE TITLE
SysML / F2.5 ManageLevelAndMode overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#812]
@MariellePetitDoche 

the SysML representation of OBU block F2 consists out of 13 diagrams, one for each functional component. The diagram for _F2.5 ManageLevelAndMode_ has been created (c.f. attached screenshot). Please check if the diagram is 
- [x] complete (e.g. some links may be missing)
- [ ] correct (e.g. consistent with the SCADE Suite model)

The diagram is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC . 

In case of findings please use the issue tracker or -- if you want to implement corrections by yourself -- please inform me beforehand to avoid merge conflicts.
![capture](https://cloud.githubusercontent.com/assets/3638145/10513034/13df7228-7345-11e5-8f86-e469dc9c0477.PNG)
Relates to #489

**Comment by MariellePetitDoche** [comment]
Input "Data_From_localisation" contains also information from odometry and errors detected during localisation

input "Data_From_F2_Functions" contains data provided by other F2 functions not yet identifyed (system failure management,...)

inout "Data_From_Speed_And_Supervision" shall be connected from  output of SSM (F2.7 ?)

input "Data_From_Track_Message" shall be connected to  F2.1

Two  inputs are missing "ERTMS_capabilities_In" and "Data_From_STM".

Output " Data_To_BG_Management" is missing : this structured data contents information dedicated to  communication with trackside  including indication of various request or information to send to trackside as the position report to send

**Comment by mahlmann** [comment]
Thanks for your feedback
- "Data_From_localisation" has been corrected
- I think  "Data_From_F2_Functions" reflects the current state of the integration model
-  "Data_From_Speed_And_Supervision" is connected to some internal logic which will always produce "false" currently, therefore I did not create a connection to SSM
-  "Data_From_Track_Message" has been connected to TrackAtlas (I had to complete TrackAtlas integration first)
-  "ERTMS_capabilities_In" and "Data_From_STM" are currently connected to constants. To avoid overloaded diagrams I left out all inputs that are fed by constants currently
- Output " Data_To_BG_Management" currently is send to NIL in SCADE Suite integration model and therefore is not included in this diagram currently.

**Comment by mahlmann** [comment]
update:
- having thought about "ERTMS_capabilities_In" and "Data_From_STM" I decided to connect these to API_persistentData input of F2

**Comment by mahlmann** [comment]
current state:
![capture](https://cloud.githubusercontent.com/assets/3638145/10578760/71cb33e0-7674-11e5-91fd-43f288836fab.PNG)

**Comment by MariellePetitDoche** [comment]
Definition of "Data_From_Speed_And_Supervision"  has been made some month ago with SSP specification providers (V. Gonthier).

" Data_To_BG_Management" contents information requested by position report management function (see #476]

**Comment by mahlmann** [comment]
Release has been made, issue can be closed.
