### ISSUE TITLE
SysML / F2.6 calculateTrainPosition overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#813]
@UweSteinkeFromSiemens 

the SysML representation of OBU block F2 consists out of 13 diagrams, one for each functional component. The diagram for _F2.6 calculateTrainPosition_ has been created (c.f. attached screenshot). Please check if the diagram is 
- [ ] complete (e.g. some links may be missing)
- [x] correct (e.g. consistent with the SCADE Suite model)

The diagram is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC . 

In case of findings please use the issue tracker or -- if you want to implement corrections by yourself -- please inform me beforehand to avoid merge conflicts.
![capture](https://cloud.githubusercontent.com/assets/3638145/10513005/ed1f23b8-7344-11e5-9323-cce2251df37d.PNG)
Relates to #489

**Comment by UweSteinkeFromSiemens** [comment]
- [x]  not complete:
  - additional consumers of trainPosition: TrackAtlas
  - additional consumers of errors: ManageLevelAndMode
 
- [x]  correct

**Comment by mahlmann** [comment]
Thanks for your prompt reaction.

Unfortunately, the `TrackAtlas` issue can not be solved until #810 is solved.

The `ManageLevelAndMode` issue has been corrected. In SysML the result looks a little bit wired though, since the `ManageLevelAndMode` input `Data_From_Localisation` is now neeing fed by two different outputs of `calculateTrainPosition` (in SCADE Suite there is some additional logic inbetween of course).
![capture](https://cloud.githubusercontent.com/assets/3638145/10513738/e5d965d2-7349-11e5-8ae9-0f687c5a7876.PNG)

**Comment by mahlmann** [comment]
SysML model has been revised according to the comments.
