### ISSUE TITLE
SysML / F2.8 ProvidePositionReport overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#815]
@christianstahl 

the SysML representation of OBU block F2 consists out of 13 diagrams, one for each functional component. The diagram for _ F2.8 ProvidePositionReport _ has been created (c.f. attached screenshot). Please check if the diagram is 
- [ ] complete (e.g. some links may be missing)
- [ ] correct (e.g. consistent with the SCADE Suite model)

The diagram is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC . 

In case of findings please use the issue tracker or -- if you want to implement corrections by yourself -- please inform me beforehand to avoid merge conflicts.
![capture](https://cloud.githubusercontent.com/assets/3638145/10513143/e510b186-7345-11e5-9a4f-7a34a03d2753.PNG)
Relates to #489

**Comment by christianstahl** [comment]
@mahlmann 

except from the bus, which I guess should not be part of this model, three inputs are missing:
- RadioSafeRadioConnectionError
- SaftyCriticalFailure
- trackInfo
However, all inputs are constants in the current EVC model, meaning hiding these inputs´seems to be a proper absraction.

**Comment by mahlmann** [comment]
@christianstahl 
Thanks for your feedback. Indeed I did hide these inputs since these are constants currently.
