### ISSUE TITLE
SysML / F2.9 MoRC_Main overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#816]
@UweSteinkeFromSiemens 

the SysML representation of OBU block F2 consists out of 13 diagrams, one for each functional component. The diagram for _F2.9 MoRC_Main_ has been created (c.f. attached screenshot). Please check if the diagram is 
- [x] complete (e.g. some links may be missing)
- [x] correct (e.g. consistent with the SCADE Suite model)

The diagram is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC . 

In case of findings please use the issue tracker or -- if you want to implement corrections by yourself -- please inform me beforehand to avoid merge conflicts.
![capture](https://cloud.githubusercontent.com/assets/3638145/10513246/a2e23c8e-7346-11e5-868a-ecccd59fa965.PNG)
Relates to #489

**Comment by UweSteinkeFromSiemens** [comment]
- msgBus_out does not have a consumer actually; trainData is an arbitrary destination and should be omitted here.

Please note:
- the "message bus" is not a bus, but in fact an unidirectional chain-like pipeline.
- MoRC_Main will be replaced by MoRC_HO.

**Comment by mahlmann** [comment]
Thanks for your feedback.
