### ISSUE TITLE
Questions on ManageLevelsAndModes SysML model

### ISSUE THREAD

**Issue by MERCEmentre** [openETCS/modeling#82]
Hello,

A took a look at ManageLevelsAndModes SysML model. I have a few questions.

1. In ManageLevels diagram, "out next_Level : T_LevelTransition" (block compute_level_transition) is connected to "out level : M_LEVEL". Isn't there a typing issue?

2. In ManageLevelsAndModes diagram, "out previousMode : T_Mode" (block managemodes) is connected to "in previousLevel : M_LEVEL" (block managelevels). Isn't there a typing issue?

3. In ManageLevelsAndModes diagram, there is a mutual dependency between blocks managemodes and managelevels. How do you plan to solve this mutual dependency in the implementation (in SCADE or B)?

4. In ManageLevels diagram, "in previousLevel : M_LEVEL" is connected to "in current_Level : M_LEVEL". Isn't there a semantic issue, i.e. confusion between previous and current level?

5. In ComputeLevelTransition diagram, several part outputs are connected to the same block output, e.g. "out next_Level" of l1_to_L2_L3 and l0_to_L2_L3 connected to "out next_Level" of the block. How do you plan to manage that only one part will drive the block output at a time?

6. In ComputeLevelTransition diagram, all "out next_Level : M_LEVEL" are connected to "out next_Level : T_LevelTransition". Isn't there a typing issue?

Best regards,
david

**Comment by mgudemann** [comment]
@MERCEmentre 

thank you for your helpful comments. As most cosider the level management, I will answer these questions directly.

> In ManageLevels diagram, "out next_Level : T_LevelTransition" (block compute_level_transition) is > connected to "out level : M_LEVEL". Isn't there a typing issue?

you are right, this is now corrected and concerns also your point number 6 (it is the same block)

> In ManageLevelsAndModes diagram, "out previousMode : T_Mode" (block managemodes) is connected to "in previousLevel : M_LEVEL" (block managelevels). Isn't there a typing issue?

you are right, I removed the connection for the time being, I will see with @MariellePetitDoche how to fix this in the model

> In ManageLevelsAndModes diagram, there is a mutual dependency between blocks managemodes > and managelevels. How do you plan to solve this mutual dependency in the implementation (in SCADE or B)?

Again, this has to be analysed with @MariellePetitDoche but the principle will likely be to use FBY (followed by or delay) operators in SCADE in one of the blocks, to solve this interdependency.

> In ManageLevels diagram, "in previousLevel : M_LEVEL" is connected to "in current_Level : M_LEVEL". Isn't there a semantic issue, i.e. confusion between previous and current level?

The first one should probably read currentLevel. The point of view is that the previous (or current) level is changed to the next_level if needed. The original level might be needed, too, so therefore I named it previous_level as the output of compute_level_transition and kept that name also for the ManageLevels block.

> In ComputeLevelTransition diagram, several part outputs are connected to the same block output, > e.g. "out next_Level" of l1_to_L2_L3 and l0_to_L2_L3 connected to "out next_Level" of the block. > How do you plan to manage that only one part will drive the block output at a time?

Only one output should be available, e.g., as flows defined in the states of a SCADE state machine. The others should be undefined.

I suppose this is not as straightforward in an automatic transformation from SysML to B. Do you have a proposal how to represent  s.th. like this in SysML?

best regards
Matthias

**Comment by MariellePetitDoche** [comment]
Indded the SysML model shall be updated with the last results of analyses and design in Scade.
This task has not been done recently.

Thanks for your comments, I am goiing to have  a look in more details when I update the model.

**Comment by MERCEmentre** [comment]
Hello Matthias, thank you for fixing the SysML diagram and for your answers.

Regarding the multiple output in ComputeLevelTransition diagram, I don't know yet the impact of the SysML to B translation and how to handle it in SysML. I'll look at it.

Best regards,
david

**Comment by BerndHekele** [comment]
Is there anything open regarding modelling?
I close this issue.

**Comment by MariellePetitDoche** [comment]
Yes comments are not yet taken into account.

**Comment by MariellePetitDoche** [comment]
Simplified modelx have been provided on github : https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%203/SysML
