### ISSUE TITLE
TM_Lib_Internal:: Build not possible with DEBUG selected

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#827]
I get the following error when I just select this model in DEBUG:
![image](https://cloud.githubusercontent.com/assets/3288918/10559580/967c29be-74f4-11e5-9a23-d345ebf9a554.png)

This is blocking analysis of errors in a new and important function.

kr
Bernd

**Comment by JakobGartner** [comment]
It is unclear which variable you wanted to build from TM_Lib_Internal; I can simulate each of the new operators-
And the error message you posted only tells something that the root context is too large
