### ISSUE TITLE
TrackAtlas to SDM interface: adding MA sections 

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#828]
Hello @T12z 

I am now adding section support for the MA. 

Can you confirm that you receive ALL distance and length info relative to the current LRBG (plus "absolute" where appropriate and defined in the types) ?

In this next release I still won't carry all 3 values (nominal/minimal/maximal). I will only add that when the MRSP calculation is simplified in order to avoid further explosion of context size

**Comment by T12z** [comment]
What is currently done on MA: I sum up all sections and offset that with the LRBG at the time of `freshMA`. I do not see any absolute value in MA-type.
As discussed in a recent phone call, LRBG is currently an alien in SDM and I am happy with better solutions. But, for an odd v_release-calculation-algorithm, I need the accuracy of the LRBG related to the MA.

And on *(nominal/minimal/maximal)*, please don't :cold_sweat:. There is no mentioning in the SRS's SDM chapter, what would be the Right Way:registered:-algorithm, so this would involve some planing, thinking and discussion. I do not see the time for that at the moment. There are more pressing things on the list first, such as gamma trains and Cab-B-driving.

**Comment by T12z** [comment]
As I answered the question, I see this issue closable.
