### ISSUE TITLE
Toolbox needs Bus -> Message Operator

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#830]
In the current model the transition from Message-Bus to Messages in the interface EVC - to RBC is missing.
Do we already have such an operator in the bus implementation?

kr
Bernd

**Comment by JakobGartner** [comment]
yes,

TM_lib_internal::BufferOutput

**Comment by JakobGartner** [comment]
Actually this operator is not intended for the toolbox but defines the interface to the EVC output-

**Comment by BerndHekele** [comment]
I can take this as the output of the EVC. It is not 100% according to the intended interface but will help to make progress with the demonstrators.
I see an input write - what is the meaning of this parameter?

**Comment by JakobGartner** [comment]
Hello Bernd,

I have now just formatted in a way that was simple and based on the bus structure.
The reception side in the RBC is compatible with the format the messages are sent now.

When the “write” input is set to true, the contents of the buffer are written via its output. 
If the radio is not ready to receive messages, it must set this input to false-

**Comment by BerndHekele** [comment]
Speaking from Viewpoint of the evc this means as long as radio-communication is not established this input is set to false?

I believe it is a good idea to take the transition from bus to msg inside the evc - thanks.

**Comment by JakobGartner** [comment]
yes.
While the “write” input is set to “true”, the buffer will pop the messages from the stack

I will push a new version soon, but that will only fix a little issue with ordering of messages received during the same cycle. 

No interface change.

**Comment by BerndHekele** [comment]
solved
