### ISSUE TITLE
Message 155 sent with P0 - RBC check rejects Message

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#832]
P0 is visible at RBC - this is not according to the standard.
Analysis regarding the route cause will follow tomorrow.

@JakobGartner 
@UweSteinkeFromSiemens

**Comment by BerndHekele** [comment]
Update: error results from an error in convertPackets in the RBC.
undefined value 0 is misinterpreted as NID_PACKET = 0

![image](https://cloud.githubusercontent.com/assets/3288918/10566720/3ec44480-75ef-11e5-8e27-53ad8711d7c4.png)

**Comment by JakobGartner** [comment]
I confirm the wrong conversion (and it will be corrected)

However, for packet 155 there is no packet 0 or 1 ??

**Comment by jokaICS** [comment]
Handling of P0/P1 in RBC should now be correct.

**Comment by BerndHekele** [comment]
Msg155 has not P0 and the RBC check found a packet reasoned by a wrong use of the NID_Packet..

**Comment by BerndHekele** [comment]
solved
