### ISSUE TITLE
Refactoring EVC-Model: Steps and Status

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#833]
We are currently active in refactoring the evc - mainly with the target to switch to optimised data flows.

What has been changed:  
* new output bus: integrated and in test
* new DMI interface: in module test
* new trackAtlas and MA-Request: status unclear
* new MoRC_HO: model is in preparation with new interfaces.
* text-messages in the DMI-Controller: status unclear

Currently we investigating bugs in the message flow RBC -> EVC after having sent Message 155.

**Comment by jokaICS** [comment]
@BerndHekele Regarding the RBC: the RBC (output-)logic was not touched when we switched to the new Train2Track bus. Hence any bug introduced by the RBC_new operator must be located in the input conversion operator. If you need support I'm available on telephone or for a quick GoTo.

**Comment by jokaICS** [comment]
@stefan-karg the ROOT_IntegrationTCP needs to be adjusted as well; do you have time for this, or would it be OK if I it myself?

**Comment by BerndHekele** [comment]
Short update on todays status:
 - bus is working, 
 - communication to RBC established, session active and train data validated
 - trigger from RBC received (Msg 3)
 - shortcut of ma_request in level ntc
 - corrections in validate data direct needed for NID_LRBG

**Comment by BerndHekele** [comment]
Update on current status:

* Level Management working
* trackAtlas integrated and started to be tested.
* Currently blocked by invalid information of packet 27.
* This problem results in output of speedMonitoring.

**Comment by BerndHekele** [comment]
We now are regarding working functionality beyond the start of this exercise. 
The oustanding bis issue is MoRC_HO.

**Comment by BerndHekele** [comment]
Done.
