### ISSUE TITLE
US-10: MA sent by RBC without MA Request from OBU?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#835]
The first activity in US-10 is a MA sent from the RBC to the OBU; is this correct, or does the US miss an MA Request as the first step (@BaseliyosJacob)?

**Comment by BaseliyosJacob** [comment]
Dear Johannes,

US 10 consider the last MA before the Level transition from Level 2 to Level NTC is not requesting an MA. It also does not miss a MA Request as the first step.

**Comment by Rainer-Lampatzer** [comment]
Question has been answered
