### ISSUE TITLE
DMI shows speed of over 1000 as DMI_to_Display valuesis not adjusted correctly

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#837]
Doing some first test on the test PreIntegration to check some functionaility I've seen, that the DMI speed jumps widely as the value of DMI_to_Display is calculated incorrect. (Reaches over 1000 for speed of 140; the TIU display is correct)

**Comment by T12z** [comment]
We changed the resolution of the odometry speed. Unfortunately there is a bug left in the physics simulation which produces different outputs. Please hold a little, @BerndHekele is looking at it, or check out an earler date.
Sorry Jan!

**Comment by BerndHekele** [comment]
This model is not released for testing.
We did not finish with corrections caused by interface changes.

**Comment by BerndHekele** [comment]
Now the model is released for testing and the error is still present 
I re-open this issue.

**Comment by BerndHekele** [comment]
Correction is available now.

Closed
