### ISSUE TITLE
ADD / D3.5.3 / Section 5.2.3.5 InformationFilter

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#840]
Dear @BerndHekele @astante @christianstahl 

with respect to #651 it needs to be checked if Section 5.2.3.5 InformationFilter of the ADD document needs to be revised. Please have a brief look at the component description and check if it is up to date.
https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3

**Comment by christianstahl** [comment]
Dear @mahlmann ,

I propose to keep it as is. The changes I am going to make should be documented in the final report.

Cheers, Christian

**Comment by mahlmann** [comment]
Thanks! This issue can be closed then.
