### ISSUE TITLE
Preparing the release of TrackAtlas with new MA

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#842]
Update of TrackAtlas is done (and pushed without interface changes)

@BaseliyosJacob : I have found no sign whatsoever of changes inside the "old" MA calculation for DMI

@BerndHekele and @BaseliyosJacob : The new version differentiates two versions of MA released-

- MA_absolute: lives in the absolute train coordinate system- we must give this to DMI.
- MA_at_LRBG: normalised to the position of the current LRBG (for SDM)

Issues: Before release, we must decide whether we integrate the "MA for DMI" (1) in the structure that is specific for DMI or (2) add an output to TrackAtlas (I vote for (1) and have defined a datatype TrackAtlasTypes::NEXTGEN_DataForDMI_t. If you are OK I will change the type DataForDMI_t that way.

@T12z: Should I pipe the MA_at_LRBG into DataForSupervision?

I propose that I use tomorrow for internal testing and integrate it with Bernd in MUC on thursday.

**Comment by T12z** [comment]
I am not sure, if there is a misunderstanding:
SDM is not "interested" in handling the LRBG. I'd be happy to get the MA in *absolute train coordinates* (L_internal_Type). The only thing I need to know about the LRBG of the MA is a value `"Q_locacc_refBG"` (SRS: 3.13.9.4.8.2) which I translate to "location-accuracy-of-reference-balise-group".

Yes it would be nice to keep all changes in the complex datatype, even though it will briefly break the model as I do a flatten of that type in SDM.

**Comment by JakobGartner** [comment]
Ok absolute will make things simple and will also make the changes I proposed towards DMI obsolete

**Comment by JakobGartner** [comment]
I have pushed the new TrackAtlas version, with NO interface changes.

Todo: add the precision info for SDM, but as a first step we check if it runs with the current environment, in a next we will coordinate the interface change with @T12z 

No interface change expected with DMI ( @BaseliyosJacob )

**Comment by T12z** [comment]
so far, this runs ok somehow,
completion of todo: LRBG precision info?

**Comment by JakobGartner** [comment]
This will be contained in the next TrackAtlas release, along with M6 and P46 support.
