### ISSUE TITLE
TM_conversions: DECODE_NID_LRBG still with shortcut.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#844]
Hi,
the oparator is still making use of the shortcut:
![image](https://cloud.githubusercontent.com/assets/3288918/10646208/4607ee3c-7832-11e5-9dc2-b953e1b149cd.png)

**Comment by JakobGartner** [comment]
well there is a version of this operator in TM:: that doesn’t anymore have a workaround, this was discussed in order to have a non- disruptive transition

Apparently I did not communicate that well to everybody, sorry.

**Comment by BerndHekele** [comment]
The old operator has been in use with validatedatadirect. I replaced it with the working TM operator. Please get rid of the non-working stuff.

I did not see the operator for the reverse operation - where can I find it?

cu
Bernd

**Comment by JakobGartner** [comment]
As on the trackside we write the NID_LRBG in raw format there is no such conversion yet. I will add it now that you indicate a need.

I will check if anybody is using the "old" conversion operator and if not, remove it

**Comment by JakobGartner** [comment]
I have pushed a version of TrackMessages were also the TM_conversions operator is now correctly working. We can clean that later, important now is that everybody can continue to work, so double definitions are a smaller problem

**Comment by BerndHekele** [comment]
I close this issue since we have a solution available.
