### ISSUE TITLE
Approbation and quality review D3.5.1 and D3.6.1

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#85]
To finalize D3.5.1 and D3.6.1 "officialy" we need to have a review by the quality assessor and need to start the signature process. 

The final version of the deliverables can be found here:
https://github.com/openETCS/modeling/tree/master/deliverables

@BerndHekele 
I kindly ask you to take over the coordination of this issue and initiate the necessary actions.

**Comment by BerndHekele** [comment]
@mahlmann , @UweSteinkeFromSiemens , @idelatorre 

Dear Izaskun , dear Uwe,
I added the corrections proposed from Uwe's side. 
Can we start the signatures now?

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
:+1:

**Comment by idelatorre** [comment]
I see that in https://github.com/openETCS/modeling/tree/master/deliverables there is no the updated version. The corrections are in https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/FirstIteration, are it?

**Comment by christianstahl** [comment]
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] Approbation and quality review D3.5.1 and D3.6.1 (#85)" gesendet am 04.02.2015 10:36:34. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by idelatorre** [comment]
D3.5.1 is signed and is sent to Uwe.

Please, let me know when you receive it.

**Comment by christianstahl** [comment]
Ich kehre zur�ck am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] Approbation and quality review D3.5.1 and D3.6.1 (#85)" gesendet am 06.02.2015 09:53:59. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by UweSteinkeFromSiemens** [comment]
Dear Izaskun,
I received the document yesterday. It’s now on the way to DB.

Best
Uwe

Siemens AG
Mobility
MO MM R&D PTS RAMSS 3
Ackerstr. 22
38126 Braunschweig, Germany
Tel.: +49 531 226-3263
Mobile: +49 173 6243136
mailto:uwe.steinke@siemens.com

Siemens Aktiengesellschaft: Chairman of the Supervisory Board: Gerhard Cromme; Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer; Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Siegfried Russwurm, Ralf P. Thomas; Registered offices: Berlin and Munich, Germany; Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684; WEEE-Reg.-No. DE 23691322
Von: idelatorre [mailto:notifications@github.com]
Gesendet: Freitag, 6. Februar 2015 09:54
An: openETCS/modeling
Cc: Steinke, Uwe
Betreff: Re: [modeling] Approbation and quality review D3.5.1 and D3.6.1 (#85)


D3.5.1 is signed and is sent to Uwe.

Please, let me know when you receive it.

**Comment by BerndHekele** [comment]
Document is stored.
