### ISSUE TITLE
Speed Supervision CSG - Circular Speed Gaudge

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#854]
@JakobGartner @BerndHekele ,

the values of the first MA in Level 2 FS for Speed Supervision is

![image](https://cloud.githubusercontent.com/assets/3975810/10714977/5a3b4680-7b05-11e5-8aa3-4c9fca385947.png)

CSG - Circular Speed Gaudge

![image](https://cloud.githubusercontent.com/assets/3975810/10715001/133828d8-7b06-11e5-9f6c-5a2f030a9db2.png)

In this case the CSG of the DMI should start with 40 km/h.
But in our case the CSD on the DMI shows the 140 km/h in the first step since they are still proceeding from the 140 km/h in Level NTC Mode SN - but in this leve and mode there will be no CSG for ETCS.

Screenshot of the Simulation:
![screen shot dmi](https://cloud.githubusercontent.com/assets/3975810/10715020/a397c1e0-7b06-11e5-9610-77123f1ca99e.PNG)

**Comment by BaseliyosJacob** [comment]
Should Start with CSG of 40 km/h since this is the first V_Static Value for Level 2 Mode FS

![screen shot dmi 2](https://cloud.githubusercontent.com/assets/3975810/10715048/9be9a3ae-7b07-11e5-8540-6c98a89d1ab8.PNG)

**Comment by JakobGartner** [comment]
In the data in the MA, this is already the case.

Looking at the real track, I assume that the speed for ATB-EG vv shall also be 40 km/h.

This also applies at the end of the track, where the speed profile given in L2 is longer than the MA.
I assume this is to make sure that the braking curves match the speed limits then maintained by the ATB.


The downside of putting 40km/h as ATB speed limit is only that debugging takes longer. 

At the end of the track, I propose we put an ATB profile that matches the L2 SSP given for the track beyond the Level Change.

I will check the data again. It looks even as if the MA goes beyond the level change.

**Comment by mahlmann** [comment]
Relates to #860

**Comment by BaseliyosJacob** [comment]
can be closed
