### ISSUE TITLE
CSG Speed Supervision @km 4731

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#855]
Dear @BerndHekele @JakobGartner @ShuangjiaoCao @T12z ,

@km 4731 we get a Pre-indication on the DMI.

See Figures

![screen shot dmi 3](https://cloud.githubusercontent.com/assets/3975810/10715339/e0949f02-7b13-11e5-8b5a-1370da45e0f7.PNG)

![screen shot dmi 4](https://cloud.githubusercontent.com/assets/3975810/10715340/e4118ee2-7b13-11e5-8261-ca4054d91902.PNG)

From my point of view this is not correct. 

The Standards describes for PIM e.g. NoS 

0 km/h <= CSG <= V target = dark grey
Vtarget <=CSG<=Vperm = white

![image](https://cloud.githubusercontent.com/assets/3975810/10715354/52027592-7b14-11e5-81b4-a9f32a48b705.png)

According to the standard and the assumption that we are in PIM and NoS i do not understand why the whole CSG is white. From my point of view it should even not appear or be white from Vtarget to V perm.??

But may i have just a missunderstanding.

**Comment by BaseliyosJacob** [comment]
Same issue @ 6360 km 

![screen shot dmi 6](https://cloud.githubusercontent.com/assets/3975810/10715445/b14a6854-7b17-11e5-9e5e-cbb7b8c0f0e8.PNG)

![screen shot dmi 7](https://cloud.githubusercontent.com/assets/3975810/10715447/b786544e-7b17-11e5-9e2c-20a4d3776ee4.PNG)


Furthermore the distance bar with 6130 doesnt make sense for me 

![screen shot dmi 8](https://cloud.githubusercontent.com/assets/3975810/10715472/239a824a-7b18-11e5-8a55-c2b60ec01590.PNG)

**Comment by BaseliyosJacob** [comment]
My first thought of issue is as followed:

The Speed Supervision assumes that the next V_target between 2 MA´s is zero since may the overhand procedure will not work works properly. In this case the distance bar and a white CSG from 0 = v_target to 160 V_permitted does make sense for me. Furthermore this behaviour will change to the correct behaviour as soon the 2 MA is now "really" valid.
@JakobGartner @T12z what do you thnik about the behaviour according to my proposed analysis?
@ShuangjiaoCao can you please take care on the behaviour within the DMI controller for the CSG Speed Supervision.

Thank you very much

**Comment by JakobGartner** [comment]
When a new MA is received it should just replace the old one seamlessly. At least this is what happens locally in the TrackAtlas.

There is no gap or “procedure”.

Also, the speed profile is always “complete”, a continuous lists of targets and related speeds.

The beginning of this list is always such that it starts before the front end of the train (in fact it starts at the previously passed LRBG and ends at the last section for which we have information

**Comment by T12z** [comment]
Yes, I support J's answer. There is always ever only one MA and everything needs to be seamless, gapfree. V_target of an MA is always 0. I know SDM outputs a v_target and a v_mrdt to DMI, where I don't know what the difference is (I did not implement that). That is still on the odd-things-list.

For all today's bugs, it would be really helpful to state, what the correct expected behaviour is.

---- Jakob Gärtner schrieb ----

>When a new MA is received it should just replace the old one seamlessly. At least this is what happens locally in the TrackAtlas.
>
>There is no gap or “procedure”.
>
>Also, the speed profile is always “complete”, a continuous lists of targets and related speeds.
>
>The beginning of this list is always such that it starts before the front end of the train (in fact it starts at the previously passed LRBG and ends at the last section for which we have information 
>

**Comment by ShuangjiaoCao** [comment]
I have also found that we never came to Pre-Indication on DMI. The PacketDynamic.substatus was never came to "PIM" 

Payman and I have found the error source is in  "SDM_Commands_Pkg::CalcDMI_output"
. There are no PIM constant here 

![qq 20151026155643](https://cloud.githubusercontent.com/assets/7654856/10732486/a402ecc8-7bfa-11e5-911b-7806acb09f49.png)

**Comment by BaseliyosJacob** [comment]
can be closed
