### ISSUE TITLE
No MA Extension @km 7336

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#856]
@JakobGartner ,

seems that the MA extension is missing @km 7336
![screen shot dmi 11](https://cloud.githubusercontent.com/assets/3975810/10715522/cc32f472-7b19-11e5-9c9c-1db7065430a3.PNG)

![screen shot dmi 10](https://cloud.githubusercontent.com/assets/3975810/10715523/d2108a12-7b19-11e5-8753-8fd295ed1bd2.PNG)

In this case the CSG Speed Supervision shows the right behaviour but is not correct in the context that the MA extension is missing.

@ShuangjiaoCao can you please follow the correction on the DMI Controller side

**Comment by JakobGartner** [comment]
Hello Baseliyos,

In TrackAtlas I see that at the MAs are extended.

In Maramou’s model I found however a little error that positions the Message 3 received at BG 351 + 54,9m erroneously to BG351.

I have corrected that.

With that the MAs have an absolute position of the EOA as follows:

5044
7528
16774


Which is the same as in the XREF

**Comment by JakobGartner** [comment]
whatever I test I see the updates.

Is it again a comm problem?

Does the MA (content of P15) reach you directly or via the Supervision module?

**Comment by BerndHekele** [comment]
I'll pick this issue in priority and provide symptoms as soon as possible.

**Comment by BerndHekele** [comment]
Further Update:
 - the trigger of RBC - EVC communication is not sent in the section after Balise 371. In addition, Message 15 is also not sent.
 - the end of section sent by trackAtlas is misinterpreted as speedlimit (635 km/h) which leeads to this picture:
![image](https://cloud.githubusercontent.com/assets/3288918/10727780/ba72a912-7bdc-11e5-8369-309e4bea6a03.png)

**Comment by JakobGartner** [comment]
> the end of section sent by trackAtlas is misinterpreted as speedlimit (635 km/h) which leeads to this picture:

yes, we need to discuss with Thorsten what to do with this “magic value” which is just an end marker on packet level.

**Comment by BerndHekele** [comment]
I open a new issue for the missing message.

**Comment by JakobGartner** [comment]
the trigger value would be 371001052

**Comment by BaseliyosJacob** [comment]
Can be closed
