### ISSUE TITLE
Distance Bar on DMI is not consistent with planning area @km 7336

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#857]
@BerndHekele @ShuangjiaoCao ,

the distance bar on the DMI controller @km7336 is not consistent with the planning area.

e.g. the distance bar shows 5160
and the next target is in 250 m.

The behaviour doesnt make sense in this context.

![screen shot dmi 11](https://cloud.githubusercontent.com/assets/3975810/10715548/99d9996c-7b1a-11e5-9676-77c679bb6019.PNG)
![screen shot dmi 10](https://cloud.githubusercontent.com/assets/3975810/10715549/9bf1ad98-7b1a-11e5-97e7-08111a535809.PNG)

Either the input is wrong
or the controller has a wrong behviour.

@BerndHekele can you please check the interface.

**Comment by ShuangjiaoCao** [comment]
I am checking this issue. It seems like that the number in distance bar(@5160) is from /PacketDynamic.location  .level.  location_brake_target.  


 the position in red window(@km7336) come from ROOT_integration/DebugTrainPositionNormoninal from EVC side.

What is the relationship between the 2 numbers? Must they be the same?

**Comment by BaseliyosJacob** [comment]
can be closed
