### ISSUE TITLE
Handover issue between 2 MA´s @5000 - 5078

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#858]
@JakobGartner @T12z ,

there is on the DMI an issue according to the hand over of 2 MA´s @km 5000 - 5078.

![screen shot dmi 12](https://cloud.githubusercontent.com/assets/3975810/10715647/28c1da6a-7b1e-11e5-9232-fa5106fee2dd.PNG)

![screen shot dmi 13](https://cloud.githubusercontent.com/assets/3975810/10715648/2d2a2206-7b1e-11e5-9c8e-8cb3c6f2d9b6.PNG)

In this case the DMI CSG is first white according to the preindication on 160 km
then
jumps to dark grey 140 km/h
then 
jumps to 160 km/h.

I assume that it is the same issue as the handover from NTC to Level 2 where we get the MA.

There must be a delay in the computation or handover of MA´s between track Atlas and SDM.
From my point of view. But you are the experts.

@ShuangjiaoCao can you please support us with the bug fix on the DMI controller side.

**Comment by T12z** [comment]
This issue has lost its context with recent commits and releases. This has been superseeded with more recent issues. I close, if the basic root of the problem still persists, feel free to reopen.
