### ISSUE TITLE
Wrong behaviour of MA and Speed Supervision on DMI between km 7417 and km 8394

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#859]
Dear all, 

we have some wrong behaviour of MA and Speed Supervision on DMI between km 7417 and km 8394

as seen in the figures

![screen shot dmi 14](https://cloud.githubusercontent.com/assets/3975810/10715698/e70c0f9e-7b1f-11e5-86af-2365cd17b3db.PNG)
![screen shot dmi 15](https://cloud.githubusercontent.com/assets/3975810/10715699/e7a59ca4-7b1f-11e5-99b2-e49b9da64bd3.PNG)

- Wrong distance bar
- No extension of MA
- Wrong CSG Speed Supervision

![screen shot dmi 16](https://cloud.githubusercontent.com/assets/3975810/10715700/ea6faec0-7b1f-11e5-89e6-09289834e894.PNG)
![screen shot dmi 17](https://cloud.githubusercontent.com/assets/3975810/10715701/f23d3f14-7b1f-11e5-82b1-8c843d52ef3e.PNG)

- Wrong distance bar
- No extension of MA
- Wrong CSG Speed Supervision

![screen shot dmi 18](https://cloud.githubusercontent.com/assets/3975810/10715702/f902a730-7b1f-11e5-9696-cc6922654c88.PNG)
![screen shot dmi 19](https://cloud.githubusercontent.com/assets/3975810/10715703/00ca4324-7b20-11e5-9a5c-3e7ad8870a19.PNG)

- Wrong distance bar
- No extension of MA
- Wrong CSG Speed Supervision

Seems to be some fatal erros by end of the 2nd MA Authority.

@JakobGartner @T12z @BerndHekele can you please support with the EVC part analysis
@ShuangjiaoCao can you please support with the DMI controller analysis

**Comment by JakobGartner** [comment]
For the MA, see my  response to #856

For speed, the supervised speed to be expected at this place can be found in this table.

(done by @Mairamou)




In our speed profiles we have the different sections separate as received from the Message/Packets 

Could that be a problem if the speed doesn’t change?

The SRS doesn’t tell to filter that….


Jakob

**Comment by JakobGartner** [comment]
What do you do when you receive the distance in absolute coordinates?
Do you subtract the train position ?

**Comment by BerndHekele** [comment]
I started to analyse this issue.
Message Send_RBC_LRBG_371_D_00105_2_M003 is not sent to the EVC.
I will start a second run to analyse what the reason is.

**Comment by BaseliyosJacob** [comment]
can be closed
