### ISSUE TITLE
TrackAtlas: MRSP at Level Change

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#860]
Dear Jakob,
we observe a jump of the speed at level change 
 - the MRSP based on NTC (140) is still valifd when entering level 2 (40).

I propose to organise the profile with several sections:
- starting with 0 - 2801cm: 140 (NTC)

Next Sections are identical with MRSP from Level 2.
![image](https://cloud.githubusercontent.com/assets/3288918/10724954/94ee644c-7bc8-11e5-87cb-7715ea3e4b6c.png)

This would be standardconform since MAs have to cover the area of the level change.

kr.
Bernd

**Comment by T12z** [comment]
I cannot duplicate this.
When the switch to Full supervision happended, I was already at 3640m. While the step up to 140 km/h already happens at 3517 m -- as far as the MRSP goes, that SDM sees. No chance to touch 40 km/h there.

**Comment by T12z** [comment]
No, actually, this may even be worse:
![odd_mrsp](https://cloud.githubusercontent.com/assets/10432699/10737920/20778ad8-7c15-11e5-847f-cbbc959c6208.PNG)

**Comment by JakobGartner** [comment]
That looks really strange.

I don’t have that behaviour.

Also the distance between distance from lrbg and absolute does not at all fit with what I see.

It looks like the order of “abs” and “lrbg” values is inverted

**Comment by T12z** [comment]
On a second run, the loc_LRBG fields differ heavily, and different than the absolute ones.
![odd_mrsp2](https://cloud.githubusercontent.com/assets/10432699/10738439/c44fecfc-7c17-11e5-8c10-ce90380f172f.PNG) (on a side note, I do not make use of that value).

**Comment by JakobGartner** [comment]
OK,

I will check them (but as nobody needs them, I may just remove that value)

but the repetition of the values is very strange, and we have never seen that before.


Maybe we can try and reproduce that while looking into the Build SSP part of the TrackAtlas model?

I can’t reproduce that. It looks like the reference (the train position) is out of sync with my calculations.

**Comment by T12z** [comment]
There are actually operations / chnges on MRSP (probably loaction corrections due to balises) that are *not* accompanied by a .fresh-flag.
And what happens at ~4990m? the MA is shortened by ~230m, just before it is extended only 5m further on track.

**Comment by JakobGartner** [comment]
these are all things that we never saw.

I can’t reproduce any of this


I suggest that we coordinate with Bernd, in order to have one “run” that works.


I don’t recalculate the MRSP when the position of a BG is corrected.
This is the reason why we need to ultimately work with the tolerances when supervising.

**Comment by BerndHekele** [comment]
Correction Available.
