### ISSUE TITLE
RBC-System: Radio Connection is broken

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#863]
After adding some corrections the RBC connection set-up does not work any more.
Do I need to look for symptoms or is this general statement sufficient?

kr
Bernd

**Comment by jokaICS** [comment]
Do you mean by "broken" that the message triggering does not work any more?

**Comment by BerndHekele** [comment]
I mean session management is not possible any more.
I send 155 and get no response from RBC.

**Comment by jokaICS** [comment]
Hmm, strange. I'm quite sure, that I didn't change anything near the session management (or at least I thought so...). @UweSteinkeFromSiemens  made same changes to MoRC_HO could it be related somehow?

@Rainer-Lampatzer since you currently have the "token" for modifying the RBC, could you please take a look (or we do it together tomorrow morning)?

**Comment by T12z** [comment]
no, sorry,
without your recent commits the simu runs fine.

**Comment by Rainer-Lampatzer** [comment]
Bin morgen ab etwa 9:15 hier.

**Comment by jokaICS** [comment]
AFAIS the session management works fine on the RBC side (there is an outgoing Msg 32 in response to Msg 155). However, I don't see any triggered radio messages, so there's definitely something off. Are you sure that the session mgmt is the problem?

**Comment by JakobGartner** [comment]
Many things seem to have disintegrated recently .

we definitely need to discuss a profound strategy tomorrow

**Comment by UweSteinkeFromSiemens** [comment]
@jokaICS : The modification of MoRC_HO yesterday comprises the addition of the new message output bus. But in fact, MoRC_HO is currently not part of the EVC. The EVC uses the former MoRC component instead.

**Comment by BerndHekele** [comment]
Analysis shows the check in the RBC is wrong again:
![image](https://cloud.githubusercontent.com/assets/3288918/10752920/92c1347c-7c8d-11e5-81af-02ab0ce50dbb.png)

Do we have a fallback to an older versiuon?

**Comment by jokaICS** [comment]
Hmm, it seems like the last merge re-introduced this bug. We really should establish a process to ensure that there are no merges ....

**Comment by T12z** [comment]
Technically git is always merging, else you get a one-man-show. But since the first day of git'ing Scade, merging on line-level breakes models. So we always have to take care only to modify the own modules.

**Comment by jokaICS** [comment]
@BerndHekele I've corrected T_TRAIN_MAX

**Comment by BerndHekele** [comment]
solved
