### ISSUE TITLE
SDM_Input_Wrappers::SDM_InputWrapper: MRSP removed too early?

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#866]
If I got the function idea correctly, removeOverpassedMRSP removes an MRSP item from targetList when the train's max safe front end operpasses the MRSP item location. Since the max safe front end is the most ahead front end position, the train front end is expected to reside somewhat astern of this location. When the MRSP item is removed as implemented, the speed restriction may then be deleted before allowed due to safety reasons. 
Is this analysis correct?

**Comment by T12z** [comment]
Other than this correct analysis, are there any noticed effects?
The function you talk about is actually part of `TargetManagement_pkg`, so this would lead to a brake-target being removed too early. I could easily replace this by *d_minSageFrontEndPos* ...
The larger question is, isn't this play double-handling? Removing stale MRSP may already been done by @JakobGartner in TA ...

**Comment by T12z** [comment]
hahaha, believe it or not:
> 3.13.8.2.3
> A target corresponding to a speed decrease of the MRSP shall be removed from the
> list of supervised targets when the *max safe front end* of the train has passed the
> target location.

**Comment by UweSteinkeFromSiemens** [comment]
Sounds illogical, but if the SRS explicitely justifies it... :+1: 
Perhaps, the SRS might have been more concerned about track performance.
