### ISSUE TITLE
TrackMessages: Extend message 24 with packet 42

### ISSUE THREAD

**Issue by Rainer-Lampatzer** [openETCS/modeling#867]
_End of Mission_ :

The driver has closed the desk. RBC has to send a RBC session termination request. (Message 24, packet 42)

5.5.3.1.3	If a communication session with an RBC exists:
       Step 2 -	The end of mission shall be reported to the RBC by means of the message “End of Mission”.
==> Step 3 - 	The RBC shall request to terminate the communication session.
       Step 4 -	The ERTMS/ETCS on-board equipment shall terminate the communication session

RBC_Messaging_Pkg::RBC_RadioTrackTrainFactory_Pkg::RadioTrackTrainFactory__CreateMsg024_BSL2/ does not contain a way to add packet 42 to message 024
But there is an input parameter "inPacket041" that is not used. This can be seen on TrackMessages/TM_old_versions::SEND_MergeRadioPackets/diagram_SEND_MergeRadioPackets_4. It contains a **Deactivated Placeholder for future packet**.

It could be used for packet 42.

@JakobGartner 

Do you want to provide this change as the owner of the _TrackMessages_ package or shall we do the change by ourselves?

Thanks a lot in advance for responding soon.

Regards, Rainer

**Comment by JakobGartner** [comment]
RBC uses outdated library elements in some parts for historical reasons. 

We have another message 24 on the track which is adding a packet 57 and 58 (Sheet05_Amstel_RBC::SendRadioPackets_LRBG_353_D_00431_0_M024)

We could just add such an operator to the track model that you can trigger when you need it, or you can reuse this design pattern in the RBC model in case you must fill the packet and message contents dynamically. 

My proposal: @mairamou adds a function to send a M24 with P42, but with input for you to provide the message/packet contents.

**Comment by BerndHekele** [comment]
That change (message 24 - packets 57, 58) is not really helpfull.
Please, don't touch a running system.

We do not have sufficient time for playing.

**Comment by JakobGartner** [comment]
we did not change anything.

I was just pointing to a message that has been on the track since the beginning.

**Comment by JakobGartner** [comment]
done (without any impact on the track model)
