### ISSUE TITLE
DMI indication marker does not show (DMI spec 8.3.8)

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#868]
SDM outputs a valid location for `.distanceIndicationPoint`, which looks ok, but still no yellow
marker line shows up.
( We discussed today and I changed the output to a relative distance, but it still does not work)

**Comment by BaseliyosJacob** [comment]
Dear Thorsten,

thank you very much. Yes. it can be the input for the yellow marker (brake indication line).
Thanks for the comment - i have really forgot this implementation and will check it asap.

**Comment by BaseliyosJacob** [comment]
@ShuangjiaoCao ,
can you support us please with the implementation.

See Spec: 8.3.8 Indication Marker of the ERA DMI Dokument

**Comment by T12z** [comment]
Oh, I'm sorry mate.
I thought, I saw this working in earlier demos and we had it already implemented. In that case, don't rush it, if it is just missing functionality which is not critical.

**Comment by ShuangjiaoCao** [comment]
@BaseliyosJacob 
OK I will check the dokument first. 

Which output is for this Indication Marker in SCADE Display?

**Comment by BaseliyosJacob** [comment]
@ShuangjiaoCao ,

there is no output implemented currently. You have so start from scratch and we need to design in Scade Display as well. Should be a part of the planning Area in Scade Display and Speed Supervision in Scade Suite.

**Comment by ShuangjiaoCao** [comment]
@BaseliyosJacob 
I have added an IndicatorMarker in Reference Objects and variavle: PASP_IndicatorMarker with type real^4 in SCade Display.  Now I'm connecting it to Scade Suit and will test my new implement today.

**Comment by T12z** [comment]
Thanks for the progress report. :+1: 

FYI:
If it is favorable for the implementation to get the IndicationMarkerLocation as an *absolute coordinate* (in track centimeters), just give me a shout. Currently I transform the IndicationMarker into a *relative distance* from train's frontend. Either way is fine for me.

**Comment by BaseliyosJacob** [comment]
Hello @T12z and @ShuangjiaoCao ,

for the Scade implemtation today we need the absolute coordinate  (in track centimeters as the Gradient profiles). 

@ShuangjiaoCao you can check the right format of the input by comparing them with the planning area information. Good Progress.

@T12z @ShuangjiaoCao Good Progress - thank you very much.

**Comment by T12z** [comment]
There is some noise left on this topic (in #897 ), but generally this has be accomplished.
