### ISSUE TITLE
TM_old_versions with compile error. 

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#870]
Dear Jakob,
we get an compile error from TM:

![image](https://cloud.githubusercontent.com/assets/3288918/10783393/b8379456-7d57-11e5-833a-d42153161235.png)

K.R
Bernd

**Comment by JakobGartner** [comment]
done

**Comment by BerndHekele** [comment]
This fix is working now.
But - I get errors from RBC_Messaging.
Are they located in RBC or in your model?

**Comment by BerndHekele** [comment]
Solved - thanks for the quick support.
