### ISSUE TITLE
Wishlist track/train data to "optimize" demonstration

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#872]
After intense riding the track the last few days, I'd like to remark optimizations that would lead to a smoother demonstration:
@BerndHekele you might want to reassign this to @stefan-karg if apropriate.

TrainData:
* generally train data is well realistic
* though physics-simulation should not differ as much from TrainData, as it does currently
  * :arrow_forward: please set simulated train brake performance to realistic values matching TIU/trainData (an S-Bahn-like Brake-Percentage of 200 defines 1,6 m/s² for EB / 1 m/s² for SB)

NationalValues:
* M_NVKTINT could be set to 1.0 or 0.9 (default: 1.1), to reduce brake-build-up time and may push brake curves further back

Track: (I am not interested to change the track, so just explanation)
Start of Target Speed Monitoring and the DMI-Indication count down are a function of the track's permissable speed. As the track speed is much higher than reasonable for the given short MAs, Indication and TSM will start very early.

Release Speed:
Seriously, having, to see the train creep to the next MA at walking speed will trigger frowny faces. And it is just not how ETCS is meant to be.
* :arrow_right: please define a release speed
* I would prefer a NV-release-speed, but even then, the MA must contain a magic-value to use that NV-release-speed
* :exclamation: release speed has not yet been tested

**Comment by mairamou** [comment]
* I would prefer a NV-release-speed, but even then, the MA must
contain a magic-value to use that NV-release-speed

The data on the track provide the following info that we could probably
use (must use) 

Danger point at a distance of 0m from the EOL 

DP release speed: use NV value 

The NV data received from track indicate a V_NVREL of 15km/h 

@JakobGartner I think you should look what TrackAtlas does with these
data. 

 		NID_PACKET(8bits) = National Values(3)

 		Q_DIR(2bits) = Nominal(1)

 		L_PACKET(13bits) = 186bits(186)

 		Q_SCALE(2bits) = 1m(1)

 		D_VALIDNV(15bits) = 0.0m(0)

 		N_ITER(5bits) = 1(1)

 		 1: NID_C[1](10bits) = 426

 		V_NVSHUNT(7bits) = 40km/h(8)

 		V_NVSTFF(7bits) = 40km/h(8)

 		V_NVONSIGHT(7bits) = 40km/h(8)

 		V_NVUNFIT(7bits) = 10km/h(2)

 		V_NVREL(7bits) = 15km/h(3)

 		D_NVROLL(15bits) = 5.0m(5)

 		Q_NVSRBKTRG(1bits) = No(0)

 		Q_NVEMRRLS(1bits) = Release only at standstill possible(0)

 		V_NVALLOWOVTRP(7bits) = 0km/h(0)

 		V_NVSUPOVTRP(7bits) = 40km/h(8)

 		D_NVOVTRP(15bits) = 200.0m(200)

 		T_NVOVTRP(8bits) = 60s(60)

 		D_NVPOTRP(15bits) = 60.0m(60)

 		M_NVCONTACT(2bits) = Train trip(0)

 		T_NVCONTACT(8bits) = 35s(35)

 		M_NVDERUN(1bits) = Yes(1)

 		D_NVSTFF(15bits) = Infinity(32767)

 		Q_NVDRIVER_ADHES(1bits) = Allowed(1)"

 		NID_PACKET(8bits) = End of information(255)"

On 2015-10-28 12:20, Thorsten Schulz wrote: 

> After intense riding the track the last few days, I'd like to remark optimizations that would lead to a smoother demonstration:
> @BerndHekele [1] you might want to reassign this to @stefan-karg [2] if apropriate. 
> 
> TrainData: 
> 
> * generally train data is well realistic
> 
> * though physics-simulation should not differ as much from TrainData, as it does currently 
> 
> * please set simulated train brake performance to realistic values matching TIU/trainData (an S-Bahn-like Brake-Percentage of 200 defines 1,6 m/s² for EB / 1 m/s² for SB)
> 
> NationalValues: 
> 
> * M_NVKTINT could be set to 1.0 or 0.9 (default: 1.1), to reduce brake-build-up time and may push brake curves further back
> 
> Track: (I am not interested to change the track, so just explanation)
> Start of Target Speed Monitoring and the DMI-Indication count down are a function of the track's permissable speed. As the track speed is much higher than reasonable for the given short MAs, Indication and TSM will start very early. 
> 
> Release Speed:
> Seriously, having, to see the train creep to the next MA at walking speed will trigger frowny faces. And it is just not how ETCS is meant to be. 
> 
> * please define a release speed
> * I would prefer a NV-release-speed, but even then, the MA must contain a magic-value to use that NV-release-speed
> * release speed has not yet been tested
> 
> --
> Reply to this email directly or view it on GitHub [3].

 

Links:
------
[1] https://github.com/BerndHekele
[2] https://github.com/stefan-karg
[3] https://github.com/openETCS/modeling/issues/872

**Comment by JakobGartner** [comment]
TrackAtlas is evaluating the magic values and replaces them with NV release speed when needed

**Comment by mairamou** [comment]
* M_NVKTINT could be set to 1.0 or 0.9 (default: 1.1), to reduce
brake-build-up time and may push brake curves further back

This value is NOT set by the NV values received 

On 2015-10-28 12:20, Thorsten Schulz wrote: 

> After intense riding the track the last few days, I'd like to remark optimizations that would lead to a smoother demonstration:
> @BerndHekele [1] you might want to reassign this to @stefan-karg [2] if apropriate. 
> 
> TrainData: 
> 
> * generally train data is well realistic
> 
> * though physics-simulation should not differ as much from TrainData, as it does currently 
> 
> * please set simulated train brake performance to realistic values matching TIU/trainData (an S-Bahn-like Brake-Percentage of 200 defines 1,6 m/s² for EB / 1 m/s² for SB)
> 
> NationalValues: 
> 
> * M_NVKTINT could be set to 1.0 or 0.9 (default: 1.1), to reduce brake-build-up time and may push brake curves further back
> 
> Track: (I am not interested to change the track, so just explanation)
> Start of Target Speed Monitoring and the DMI-Indication count down are a function of the track's permissable speed. As the track speed is much higher than reasonable for the given short MAs, Indication and TSM will start very early. 
> 
> Release Speed:
> Seriously, having, to see the train creep to the next MA at walking speed will trigger frowny faces. And it is just not how ETCS is meant to be. 
> 
> * please define a release speed
> * I would prefer a NV-release-speed, but even then, the MA must contain a magic-value to use that NV-release-speed
> * release speed has not yet been tested
> 
> --
> Reply to this email directly or view it on GitHub [3].

 

Links:
------
[1] https://github.com/BerndHekele
[2] https://github.com/stefan-karg
[3] https://github.com/openETCS/modeling/issues/872

**Comment by T12z** [comment]
Thanks for your review @mairamou .
I am aware, that M_NVKTINT is not set, that's why it falls back to the deafult value of 1.1. I mentioned this as an optimization feature.

So far the release speed I get from TA is 0 all the way. I just hard-wired 15 and 40 km/h as v_release, ran the track, and I was genuinly suprised, my computer did not go up in a fire blast.
BUT, if one accelerates out of v_release speed, the EB kicks in (which is correct) but it does not let go again even at stand-still, so this is either a bug or the brake release must come another path -- I have not analysed. So RSM may be broken currently.

**Comment by JakobGartner** [comment]
I have now added Q_DANGERPOINT = true values for each Packet15 on the track, as this was is in the JRU data.

You should now get a release speed for the DP locations

**Comment by T12z** [comment]
seems to work, even though the model is broken again :tired_face: 
I actually found the bug I stated above, was a rather older typo in the output module.

**Comment by BerndHekele** [comment]
I just pushed an corrected evc model.
It is not tested.
But should be compilable,

**Comment by T12z** [comment]
I think this enhancement has seen some attention (esp. the Release Speed topics)
The only thing left, is to undo simulation speed-ups in releases. This is generally known and not worth an open issue. THANKS for your input.
