### ISSUE TITLE
Committer Vote for Rainer Lampatzer(ICS)

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#873]
Dear Partner,
I want to propose Rainer Lampatzer to become a committer.

Please, support this request in giving him a quick positive response.

Peyman
@openETCS/modeling-committers 
@Rainer-Lampatzer

**Comment by Farhangi** [comment]
+1

**Comment by jokaICS** [comment]
+1

**Comment by stefan-karg** [comment]
+1

**Comment by mahlmann** [comment]
:+1

**Comment by christianstahl** [comment]
+1

**Comment by T12z** [comment]
:+1:

**Comment by mairamou** [comment]
+1

**Comment by JakobGartner** [comment]
+1

**Comment by BaseliyosJacob** [comment]
+1

**Comment by BerndHekele** [comment]
+1
This is a convincing majority.
I will close this issue.
Welcome in the team, @Rainer-Lampatzer

**Comment by Rainer-Lampatzer** [comment]
Thank you very much for trusting me ...
