### ISSUE TITLE
DMI: multiple text messages after START?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#879]
With the current HEAD, I need to confirm the transition to NTC five times after pressing START. Can someone confirm (or is my DMI outdated? I'm always not sure if copying the files is sufficient...)?
(@BaseliyosJacob, @ShuangjiaoCao)

BR
Johannes

**Comment by ShuangjiaoCao** [comment]
I am using the current integration and the confirmation comes only 1 time when transiting to NTC.
I think it is because the outdated DMI?

**Comment by BaseliyosJacob** [comment]
@jokaICS ,

check it yesterday and i had 1 time after pressing start as well. Same as @ShuangjiaoCao .

Are you sure you have the updated version?

**Comment by jokaICS** [comment]
Thanks, I will check. Actually, I'm using the standalone DMI, so maybe it's due to a comm problem.

**Comment by jokaICS** [comment]
After another update the problem still remains, so I assume that the problem is located in the TCP-based EVC<->DMI comm (@jokaICS).

**Comment by jokaICS** [comment]
OK, I think I've found the reason for this behavior (the "present" flag was no set correctly by the libenvsim imported op).
@stefan-karg, @Farhangi: could you please compile the standalone DMI and check if this issue is resolved?

**Comment by stefan-karg** [comment]
Is fixed meanwhile.
