### ISSUE TITLE
US 14 Correction

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#880]
Dear @MarcBehrens ,

as discussed you wanted to modify the US 14
https://github.com/openETCS/modeling/blob/master/User%20Stories/Description%20User%20Story%2014.docx

Can you please update the US sequence diagramm since we need clear requirements and i will be just available for 5 days.

**Comment by Rainer-Lampatzer** [comment]
Can this issue be merged with #71 which is about the same user story, and here is nothing beyond to be done?

**Comment by Rainer-Lampatzer** [comment]
has been done now several weeks ago
