### ISSUE TITLE
UtrechtAmsterdam: Data Inconsistency in P42

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#881]
NID_RADIO differs between BG353 and BG354.
![image](https://cloud.githubusercontent.com/assets/3288918/10868276/5c43ce0a-8089-11e5-92bb-4904214eb1fc.png)
a

kr
Bernd

**Comment by JakobGartner** [comment]
not anymore

I will check if there are more…

**Comment by BerndHekele** [comment]
There is one:
![image](https://cloud.githubusercontent.com/assets/3288918/10869964/26b030fe-80bf-11e5-96be-a1ff9215fed9.png)

**Comment by BerndHekele** [comment]
Works now.
