### ISSUE TITLE
Testbench does not build any more

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#889]
This behaviour appeared shortly after the push of the changes to probes.
This issue is blocking the release.

kr
Bernd

**Comment by jokaICS** [comment]
I've pushed a correction for this issue (since I'm also blocked by it).

**Comment by BerndHekele** [comment]
The problem is still open.

**Comment by jokaICS** [comment]
OK, so it's a problem during compilation, not model checking/ generation? Could you please post the error message?

**Comment by BerndHekele** [comment]
In file included from TestEnvironmentSimulation_IncludingRBC_Complete_Toolbox.h:19:0,
                 from ROOT_Integration_Testbench_Integration.h:10,
                 from ROOT_Integration_Testbench_Integration.c:8:
..\..\..\..\..\..\test\EnvSim\libenvsim\src\scade/ProbeTracksideInput_EnvSim.h:15:9: warning: struct has no members [-Wpedantic]
 typedef struct {
         ^
In file included from ROOT_Integration_Testbench_Integration.h:10:0,
                 from ROOT_Integration_Testbench_Integration.c:8:
TestEnvironmentSimulation_IncludingRBC_Complete_Toolbox.h:223:3: error: unknown type name 'SV_ProbeTracksideInput_EnvSim'
   SV_ProbeTracksideInput_EnvSim _7_Context_1;
   ^
Makefile:14: recipe for target 'win32/ROOT_Integration_Testbench_Integration.o' failed
mingw32-make.exe: *** [win32/ROOT_Integration_Testbench_Integration.o] Error 1
mingw32-make.exe: *** Waiting for unfinished jobs....

**Comment by jokaICS** [comment]
OK, now I know what's the problem. I will push a correction soon; until then you can disable the checkbox "Set warnings as errors" in the "General" tab as a temporary remedy.

**Comment by BerndHekele** [comment]
I use this setting anyway in my profile.
I wait for your correction.

**Comment by jokaICS** [comment]
I've solved the "empty struct" issue, but I still get a compiler error when I use your profile to compile ROOT_Integration. I think it would be best to have a short GoTo if you also run into this problem.

**Comment by BerndHekele** [comment]
I open the weekly goto-meeting.

**Comment by BerndHekele** [comment]
The problem is solved with the simuBernd profile in Scade.
