### ISSUE TITLE
Checklist WP 3 ERTMS OBU Kernel Functions and Responsibilities

### ISSUE THREAD

**Issue by vgontier** [openETCS/modeling#89]
Hello Baseliyos,
We understand that our (G1) analysis perimeter is:
ch 3.13: F2x: Manage_Speed_Supervision_Inputs
             F2x: Perform_FS_OS_supervision_and_related_actions
ch 3.10: F2x: Manage_emergency_stop_messages
ch 3.14: F2x: Ensure_train_protection_in_FS_LS_OS
ch 3.11: F2x: Determine_MRSP_for_FS_OS (not only MRSP but all Static Speed Restrictions)
Right ?
Véronique

**Comment by vgontier** [comment]
Hello (bis!)
Have you got the break-down diagram with all your checklist functions ?
Véronique

**Comment by UweSteinkeFromSiemens** [comment]
The terms in the tables left column are mainly not defined do not refer to the ETCS spec, therefore the table cannot be understood.

@BaseliyosJacob
