### ISSUE TITLE
Testbench_Integration::ROOT_Integration: package EnvSim is undefined

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#900]
The missing package prevents code generation from the model.

**Comment by jokaICS** [comment]
When do you encounter this problem? During loading of the Testbench_Integration project?

**Comment by UweSteinkeFromSiemens** [comment]
By a fresh update from github.

**Comment by jokaICS** [comment]
Can you please check if you have test\EnvSim\Scade\EnvSim.etp?

**Comment by UweSteinkeFromSiemens** [comment]
@jokaICS : Bernd and I just analyzed the problem: 
To shorten the path length, I'm using a virtual drive starting at \modeling\model\Scade\. Therefore, \modeling\test is out of sight. 
I did not expect to find scade files - as part of the model - outside of the scade directory. :-1: 
Since these files look somewhat misplaced there: could you perhaps move them somewhere below the \modeling\model\Scade folder ?

**Comment by jokaICS** [comment]
Done.

**Comment by UweSteinkeFromSiemens** [comment]
@jokaICS: Unfortunately, the move broke the model, EnvSim.etp as well as Testbench_Integration.etp.

**Comment by jokaICS** [comment]
Could be more specific, what's the error message? Which operator/ profile did you select?

**Comment by UweSteinkeFromSiemens** [comment]
- EnvSim.etp: ProbeSDM with KCG profile: incomplete model

- Testbench_Integration.etp with profile SimuIntegrationBH:
In file included from EVC.h:15:0,
                 from ROOT_Integration_Testbench_Integration.h:9,
                 from ROOT_Integration_Testbench_Integration.c:8:
SpeedSupervision_Integration_SpeedSupervision_Integration_Pkg.h:18:29: fatal error: ProbeSDM_EnvSim.h: No such file or directory
 #include "ProbeSDM_EnvSim.h"
                             ^
compilation terminated.

**Comment by UweSteinkeFromSiemens** [comment]
Since my time frame for working with the Testbench_Integration.etp model is limited to today and tomorrow, probably it might be more appropriate to undo the move? Sorry for the inconvenience.

**Comment by jokaICS** [comment]
OK, we two options:

* moving the entire envsim project (C sources, etc) from to test/ to model/Scade
* removing the imported operators from ROOT_Integration (i.e. using a separate copies for the use cases "with probes" and "without" probes).

@BerndHekele , @stefan-karg : which do you prefer?

**Comment by jokaICS** [comment]
@UweSteinkeFromSiemens I can move it back, but wasn't the location of the SCADE model the original problem for you?

**Comment by UweSteinkeFromSiemens** [comment]
In the case of undoing the move: it would only require to move the root of my virtual drive some levels up and should not raise a problem. 

The main reason for asking for the move was simply the long term maintainability and the principle not to confuse our successors with wide spread model parts.

**Comment by jokaICS** [comment]
OK, I've moved back the EnvSim SCADe project to the previous location.

**Comment by UweSteinkeFromSiemens** [comment]
Fine, then I will try compile Testbench_Integration.etp based on this.

**Comment by UweSteinkeFromSiemens** [comment]
Is not a problem any more.
