### ISSUE TITLE
Testbench_Integration: Proper use of TIU valid flag.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#904]
Currently we have a problem in the DMI communication caused by an unproper use of the valid flag.
I want to raise the discussion to implement a conform correction in the interfaces outside the evc model (e.g., valid flag is only used when data is actually changed.

Please, comment:
@stefan-karg 
@jokaICS 

kr
Bernd

**Comment by T12z** [comment]
(my 50ct on this issue in internal interfaces):

we had a discussion on this (a few times) on the interface between TA 
and SDM.
The line includes several "fresh-flags", that indicate an update of the 
related item, technically `fresh = last 'item xor item`. The item itself 
still included a valid flag that indicates data contained within may be 
used at all.
The background is, that the fresh-flag may be used for 
run-time-optimization (boolean-activate and hold) whereas some 
components using the item may not have an additional memory and rely on 
the valid presence of the data. So not all components need to analyze 
whether they can safely cache inputs. On the other hand this may also 
avoid unnecessary duplicate memories.

Hope this adds some thoughts.

**Comment by jokaICS** [comment]
From the point of TCP comm, a valid flag would definitely help -- but only if the valid flag is not true in every cycle :-)

**Comment by BerndHekele** [comment]
I pushed a correction for this issue in the external interfaces to the evc. 
No change needed in SDM.

**Comment by BerndHekele** [comment]
Solution available
