### ISSUE TITLE
CollectRadioOutput: implausible conversion from mobileConnectionCmd to API_RTM_management

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#905]
Scenario: 
- After having passed BG 353: 
- MoRC_HO applies a mobileConnectionCmd with action=mca_connect and nid_radio=500.
- CollectRadioOutput converts this into cmd=cmdr_connection_request and networkID=2114079. 

Turning nid_radio to networkID seems to be inappropriate. Since this happens after passing BG 353, the registering to the network (networkID=2114079) has been performed long before at BG 352.

Here, the connection call to RBC with nid_radio = RBC phone number = 500 is required.

**Comment by UweSteinkeFromSiemens** [comment]
The same applies to action=mca_disconnect.

**Comment by BerndHekele** [comment]
I pushed the correction for this issue.

**Comment by UweSteinkeFromSiemens** [comment]
Done
