### ISSUE TITLE
eventsAndPhases: not set properly when closing the desk

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#906]
When closing the desk after having passed BG 353, the following flags of eventsAndPhases seem to be set inconsistent regarding this scenario: 

- driverClosesTheDeskduringStartOfMission = false
- startOfMissionProcedureIsGoingOn = true
- endOfMissionIsExecuted = true
- startOfMissionProcedureIsGoingOn = true

This combination prevents MoRC from terminating the current radio session after closing the desk. ( driverClosesTheDeskduringStartOfMission = true would cause the termination).

**Comment by UweSteinkeFromSiemens** [comment]
See also #907.

**Comment by BerndHekele** [comment]
Hi Uwe,
I can follow your advice, but I'm confused with the Start-of-mission statement. We are beyond start of mission.

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
@BerndHekele : yes, I'm confused too: Why is startOfMissionProcedureIsGoingOn = true during this period? The bouquet of flags looks not very consistent.

**Comment by BerndHekele** [comment]
I pushed the correction for this issue.

**Comment by UweSteinkeFromSiemens** [comment]
I assume, the correction was successful.
