### ISSUE TITLE
user story13 sceond MA

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#908]
The second SpeedProfile from track by the user story 13 has a value of -1.
![speedprofile](https://cloud.githubusercontent.com/assets/2284296/11095726/b65e8406-8896-11e5-9305-c45f6ac51212.PNG)

@mairamou 
@JakobGartner

**Comment by Rainer-Lampatzer** [comment]
This has certainly something to do with 

![suddenbrakeinplausibledeceleration](https://cloud.githubusercontent.com/assets/14076350/11145236/d55fdbd4-8a03-11e5-991a-fbf6bad78269.jpg)

As it can be seen on the left panel (DMI), the LRBG is 362, which is located several hundrets meters beyond

**Comment by JakobGartner** [comment]
this is fixed

**Comment by BerndHekele** [comment]
@JakobGartner 
I had a closer look at this issue today.
The LRBG of this message is not reasonable.
![image](https://cloud.githubusercontent.com/assets/3288918/11370782/8d7de840-92c5-11e5-9f2d-b997cec7ab85.png)

I did not find the model on first glance where the constants are defind.
Can you please give some guideance?

kr
Bernd

**Comment by JakobGartner** [comment]
<img width="597" alt="screen shot 2015-11-24 at 16 57 38" src="https://cloud.githubusercontent.com/assets/8400941/11372265/bc2b7656-92cc-11e5-919d-350904a2fd7c.png">

One remark: The Track Viewer shows a funny message 3 (which in reality has the variables above)

The LRBG is 354 on purpose because this is the BG that is also used in reality as reference LRBG.
I will however check the orientation and distances once more,

**Comment by Rainer-Lampatzer** [comment]
@Bernd:

UtrechtAmsterdam_oETCS

==> Messages_4261.xscade
              Messages_426::LRBG_354_D_00275_3_M003/

==> Packets426.xscade
              LRBG354_P003_1
              LRBG354_P003_2
              LRBG354_P005_1
              LRBG354_P005_2
              LRBG354_P015_1
              LRBG354_P015_2
              LRBG354_P021_1
              LRBG354_P021_2
              LRBG354_P207_1
              LRBG354_P027_2
              LRBG354_P041_1
              LRBG354_P041_2
              LRBG354_P065_1
              LRBG354_P065_2

**Comment by Farhangi** [comment]
I have written and uploaded a small scenario(scripted) for US13. It is also tested.
