### ISSUE TITLE
envSim-Demonstration: wishes

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#909]
Dear Johannes,
here are details for some items I would like to sess as an output of your demionstrator:
1. Status of Radio HW (RTM module): type RCM_Session_Types_Pkg::morcStatus_T
We have as a general principle two of those interfaces, one stays inactive.
2. Errors of BG-Passing: type TrainPosition_Types_Pck::positionErrors_T and Common_Types_Pkg::MSG_Errors_T.
Maybe those events can be shown in an textual presentation.

kr.
Bernd

**Comment by jokaICS** [comment]
Should I provide separate probe operators for radio status and BG errors, or can we extract both with a single operator?

**Comment by BerndHekele** [comment]
We can tailor this to your needs. How do you like it?

**Comment by jokaICS** [comment]
Can we extract both (radio status and errors) in the same diagram? Then I would prefer a single probe operator.

**Comment by jokaICS** [comment]
Dear Bernd,

I've now provided a new ProbeEVC operator in the EnvSim project with inputs for RCM_Session_Types_Pkg::morcStatus_T, TrainPosition_Types_Pck::positionErrors_T, and Common_Types_Pkg::MSG_Errors_T. Could you please integrate this probe into the EVC (or toolbox)?

Thanks,
Johannes

**Comment by BerndHekele** [comment]
Thanks.
Will be dann asap.

**Comment by BerndHekele** [comment]
done

**Comment by jokaICS** [comment]
I've added RTM status and some additional information (passed balises, position report data) to the "Event Log" tab. Please let me know, if you need more/other data.

**Comment by jokaICS** [comment]
I've added a simple plot of the position accuracy and some more info (sent MAs/ MA requests) to the Event Log

**Comment by jokaICS** [comment]
Update on SimCtrl / TrackView: SimCtrl now supports exporting the message log (.trk file), which subsequently may be viewed in TrackView.

**Comment by BerndHekele** [comment]
I have seen these features. Thanks.
I close the wish list with pleasure.
