### ISSUE TITLE
ObuFunctions/ManageLocationRelatedInformation/BaliseGroup: Packages missing in repository

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#91]
Missing:

- BuildBGMessage_Pkg
- ReceiveEuroBaliseFromAPI_Pkg

Operators are referenced from ManageBaliseInformationPkg::ManageBaliseInformation and cannot be found in the indicated path (nor are present in the local repository tree)

**Comment by BerndHekele** [comment]
Both parts of the model are no longer existing. We changed the structure.
Please, let me do the integration of our path first.

**Comment by JakobGartner** [comment]
Thanks for the clarification 
I will put a placeholder meanwhile 

Mit freundlichen Grüßen 
Cordialement
Best regards 

Jakob Gärtner 
GF/ PDG
Local Energy Appliances
Am Mittleren Moos 48
86167 Augsburg 
Germany
+49 821 907802-20
+49 151 25387841

Local Energy (Cameroon) Sarl 
BP 14000
Yaoundé 
Cameroun 
+237 6 98 29 16 01

j.gaertner@lea-energy.com

**Comment by MariellePetitDoche** [comment]
Definition of the data received from RBC  or BG are defined in BG_Types package (according subset 26 § 7 and 8). But where is define the information which can be use insi de the kernel software, after checking of the validity of the message ?

How is describe the structure of the data from trackside, usable by on-board function ?

**Comment by BerndHekele** [comment]
I assume you need some packets assigned to model and level management as discussed last week.
If they are location dpendent you will get the information from database.
Otherwise, you will get a special inteface in the trackside integration packet. I will check your interfaces in more detail and update this response later.

**Comment by BerndHekele** [comment]
Cleanup - Implementation completed.
