### ISSUE TITLE
PASP disappeared  after 3660m 

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#910]
after 3660m disappeared the PASP in planning area. 

The problem war probably under "DMI Controller->Planning Area->D_behavior->Diagram PASP", either the input value **PASP_SpeedPoints**  or the C Code method: **PASP::impPASPgetRelavantBreakingValues**   is not correct. As the figure 2 shows, the outputs **filteredSpeeds** and **filteredDistances** are both [0,0,0,0], which should not be.

 figure 3 shows the 2 input values(L165 and L166)
![bug3](https://cloud.githubusercontent.com/assets/7654856/11120927/4c42bcfa-8953-11e5-825a-f4cff21228da.PNG)
![bug1](https://cloud.githubusercontent.com/assets/7654856/11120932/54903338-8953-11e5-8211-8f06a73c21c7.PNG)
![bug2](https://cloud.githubusercontent.com/assets/7654856/11120934/586ff722-8953-11e5-85d4-edcbf1329711.PNG)

**Comment by stefan-karg** [comment]
This problem is resolved in the current version. The PASP does not disappear anymore. Can we close the issue @ShuangjiaoCao ?
