### ISSUE TITLE
Linking consistency errors on track

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#911]
The following linking consistency errors occur while traveling along the track: 

- BG 366: linkedBGMissed (= not found until the end of the expectation window)
- BG 365: passedBG_foundNotWhereExpected
- BG 366: passedBG_foundNotWhereExpected
- BG 365: linkedBGMissed (= not found until the end of the expectation window)
- BG 341: linkedBGMissed (= not found until the end of the expectation window)
- BG 341: passedBG_foundNotWhereExpected
- BG 370: linkedBGMissed (= not found until the end of the expectation window)
- BG 370: passedBG_foundNotWhereExpected
- BG 371: linkedBGMissed (= not found until the end of the expectation window)
- BG 371: passedBG_foundNotWhereExpected
- BG 372: linkedBGMissed (= not found until the end of the expectation window)
- BG 372: passedBG_foundNotWhereExpected
- BG 373: linkedBGMissed (= not found until the end of the expectation window)
- BG 373: passedBG_foundNotWhereExpected
- BG 374: passed, but not announced (ok, if intended)

I stop here, since the track layout from the shown range on needs readjustment.

**Comment by BerndHekele** [comment]
Hi Uwe,
I did not get any "eerors" from your function when passing these balises.
How is this possible?

**Comment by BerndHekele** [comment]
I now also see these errors.
Can you please have a look at this problem: @JakobGartner

**Comment by JakobGartner** [comment]
@Rainer-Lampatzer has pointed me to the possible source of the error:
In US_13, there was a lazy copy and paste error which made that the 3rd MA (which actually shortens the EOA) came with the wrong NID_LRBG.

Let me know if a problem persists

**Comment by BerndHekele** [comment]
We are driving US1-12 and the problem is still open.
I see two problems
1. BGs 370 and 371 are in wrong sequence in the linking data.
2. calcTrainPosition stays confused if a wrong balise has been passed.
The track:
![image](https://cloud.githubusercontent.com/assets/3288918/11145871/88fae738-8a09-11e5-88b2-9d11f54dda60.png)

And linking:
![image](https://cloud.githubusercontent.com/assets/3288918/11145848/63c97c04-8a09-11e5-8b8b-68bec24f5ce9.png)

**Comment by BerndHekele** [comment]
One additional remark: 
I dont see any problems in the new track at balises before 341.

**Comment by JakobGartner** [comment]
Lets be precise about OLD and NEW
OLD: US1-12
NEW: US13-16

I have re-checked the data defined in the track model for US1-12 and the data are defined as follows:


![screen shot 2015-11-13 at 13 45 36](https://cloud.githubusercontent.com/assets/8400941/11146280/46704292-8a0d-11e5-88b6-16394f65a7b5.png)

I don't really understand how they can get inverted.

**Comment by jokaICS** [comment]
Hmm, could this be due to an issue with q_linkorientation? BG370 and BG372 are passed in nominal direction, whereas BG372 and 374 are passed in reverse direction.

**Comment by BerndHekele** [comment]
Update on Statement regarding BG 351: If I run the model with optimisation level 1 I get the "missed" error at position (nominal) 361726.
![image](https://cloud.githubusercontent.com/assets/3288918/11147191/892dd98a-8a14-11e5-992a-5245104200b0.png)

**Comment by BerndHekele** [comment]
Data received at LRBG 364:
 - element 367 is twice in the input. 370 and 371 are in correct order
![image](https://cloud.githubusercontent.com/assets/3288918/11147488/89ed43d6-8a16-11e5-99a5-d4fb82dc9cae.png)
 - BGs at this position have gaps between 367 and 341 are missing BGs.:
![image](https://cloud.githubusercontent.com/assets/3288918/11147584/3d89dcba-8a17-11e5-974c-19d2daca3622.png)

**Comment by JakobGartner** [comment]
These data differ from the ones defined on the track.

- either we miss them during the train driving along the track (which could be linked to the triggering mechanism of the balises, but would not explain the double- 367 which should be filtered out at the front end of the EVC)
- or the filter does something
- or train position mixes up something

**Comment by BerndHekele** [comment]
The famouse filter is not involved in this function. We are talking about elements of linking data at LRBG 362.

**Comment by JakobGartner** [comment]
OK, you wrote 364

indeed there is a problem with P5 at 363, will check and correct ASAP

**Comment by BerndHekele** [comment]
I now reached LRBG 364. Obviously, the incorrect data at LRBG 362 results in a wrong linking list which is nice cause we can reproduce the problem.:
![image](https://cloud.githubusercontent.com/assets/3288918/11147801/c57a3808-8a18-11e5-9704-d49a25307a26.png)

The data received in P5 is ok:
![image](https://cloud.githubusercontent.com/assets/3288918/11147830/fe0b5cec-8a18-11e5-9d4d-62e898bed042.png)

**Comment by BerndHekele** [comment]
I was confused with this extra information at LRBG 363. I did not expect the whole data being repeated.

**Comment by JakobGartner** [comment]
yes. 

this is how it is on the track.


the copy/paste error that lead top double BG367 and other problems is fixed

**Comment by BerndHekele** [comment]
I'm a bit nervouse about the different behaviour at balise 351. here, we had an impact due to different code generator options. Are you sure information is correct at this position?

**Comment by BerndHekele** [comment]
We have another problem at 381 - again, the orer is incorrect (381, 382).
I'm now checking the data defined before this position.
At LRBG371 the last element confuses me:
![image](https://cloud.githubusercontent.com/assets/3288918/11149454/21965fc2-8a23-11e5-9816-ace44989c871.png)
Same situation at LRBG 364 - last element seems to be incomplete.

**Comment by JakobGartner** [comment]
I will check on 381

on 371, indeed the value is 0 in the JRU data.

I will see what to do: 

- remove
- or, reverse engineer the data from other infos on the track

**Comment by BerndHekele** [comment]
In principle 0 is valid as a BG.

**Comment by BerndHekele** [comment]
I'm now at LRBG 364. The data from track look fine, but the BGs have a gap (BG 374 is missing in the list:
Uwe's list:
![image](https://cloud.githubusercontent.com/assets/3288918/11150721/c084c73a-8a29-11e5-9135-938a26a153f4.png)

Input from track:
![image](https://cloud.githubusercontent.com/assets/3288918/11150782/fb534418-8a29-11e5-9eda-61f111f7dcad.png)
![image](https://cloud.githubusercontent.com/assets/3288918/11150814/38117136-8a2a-11e5-9739-4985d6dd2619.png)

**Comment by JakobGartner** [comment]
![screen shot 2015-11-13 at 17 19 54](https://cloud.githubusercontent.com/assets/8400941/11150960/f161854a-8a2a-11e5-9d15-53c9353409a4.png)

**Comment by BerndHekele** [comment]
Next Update at LRBG 42600371. Now the data get's confused:
BGs:
![image](https://cloud.githubusercontent.com/assets/3288918/11151010/1662c610-8a2b-11e5-9869-8fad7f4daf56.png)

Again, the input look nice in this situation:
![image](https://cloud.githubusercontent.com/assets/3288918/11151080/67066f5e-8a2b-11e5-8fa7-96f46559337e.png)

**Comment by BerndHekele** [comment]
I will ask Uwe for Support on this issue on Monday...

**Comment by BerndHekele** [comment]
Another positioning Error in the rear part of the track (BG438)
![image](https://cloud.githubusercontent.com/assets/3288918/11152118/0c573f88-8a31-11e5-88f6-8d5079c6d24f.png)

**Comment by JakobGartner** [comment]
fixed

**Comment by BerndHekele** [comment]
@UweSteinkeFromSiemens :
In this place the wrong sequence is seen for the first time after BG 364:
![image](https://cloud.githubusercontent.com/assets/3288918/11165820/743caf6c-8b1b-11e5-92d3-8368964d2d78.png)

**Comment by BerndHekele** [comment]
Looking into the model indexOfBG_onTrack_itr you get the following logic:
![image](https://cloud.githubusercontent.com/assets/3288918/11169712/d0ba97b4-8bbf-11e5-9591-db45bd979bec.png)

which logic I don't quite understand (which location is compared here?

**Comment by UweSteinkeFromSiemens** [comment]
Dear Bernd,
I'm on a business trip to Munich during the next week. Unfortunately, I will be offline completely on Monday and Tuesday. The next opportunity for me to analyze the problem is on Wednesday (perhaps at the Völckerstr. 5) or on Thursday.

**Comment by BerndHekele** [comment]
Dear Uwe,
I'm fine with your proposal.
I have the feelinmg the problem is triggered by some data inconsistency in the linking data which I did not find so far.
I will try to digg a bit deaper to prepare your stop in Munich Völckerstrasse.

**Comment by UweSteinkeFromSiemens** [comment]
Yes, that' also my Impression. The inconsistency in the linking data has to be fixed anyway. The problem to maintain the correct order of BGs in inconsistent linking scenarios can be fixed independently. By the way, the latter is not so easy and typically requires a safety analysis before to answer questions of required robustness against misplaced BGs, multiple BGs with the same ID, linking inconsistencies, multiple announcements of the same BG at different locations, wrong ordering etc. This seems to be more than what is specified regarding linking consistency in SRS.

**Comment by mairamou** [comment]
For the MA and the related P005 received at BG364, I have done an analysis:

- In the JRU data, the NID_BG the segment 29 is referring to has the value NID_BG=0
- I did a consistency check and incremental calculation of the linked BGs from LRBG 364
- I cross checked with the actual bails positions as corrected based on the linking data (and validated since long)

--> segment 29 of JRU data in P005 received with NID_LRBG 426,364 yields to the corrected position of BG 393. 

----> I have corrected the incomplete linking data.

Conclusion. It seems that the JRU data are illustrating a track which is was not fully engineered and validated during the travel. 
I will document that in my track model doc. 

I have pushed the solution 

I can not at all reproduce any of the other problems on the track model level. The track model is consistent with the JRU data as far as linking is concerned. (which does not totally exclude single errors, but for example there is nowhere a switch of BG 370 and BG371.

**Comment by BerndHekele** [comment]
@UweSteinkeFromSiemens : 
Dear Uwe,
I had a closer look at the way the linking information is processed.
I currently have the following understanding of the situation (based on the attached symptoms):
* we pass BG 362
* we receive Linking information relative to LRBG 362 - list gets updated.
* we pass BG 363
  - The location of the BGs in the past get adjusted with the new information?
* we receive linking information again relative to LRBG 362
  - now the routines to find BGs in the list get confused by the changed location information.

![image](https://cloud.githubusercontent.com/assets/3288918/11188343/9c8c6528-8c8a-11e5-89a2-0ae617dbdd4c.png)

![image](https://cloud.githubusercontent.com/assets/3288918/11188381/cf2f0292-8c8a-11e5-8bf8-12cb2117dab3.png)

**Comment by UweSteinkeFromSiemens** [comment]
@BerndHekele : That's great, thank's a lot for your analysis. 

Announcing a BG already passed in rear of the train is completely useless, but without no doubt calculateTrainPosition should be robust against it. When implementing I was not aware of it. 
I will fix it asap, when I get a valuable internet access.  
In fact, as I stated above, it should be clarified as part of a later follow-up project, which other useless or weird scenarios must be taken into account.

**Comment by JakobGartner** [comment]
This seems to be a very standard scenario, as ALL the MAs we receive on the track come AFTER passing the LRBG.

It seems also (I have seen that from looking at the unused JRU data we have) that only specific BGs are used as LRBGs. They are all somehow related to specific features on the track (points, signals).




I had the same issue with the other track related data, that was part of my 1st learning curve in TrackAtlas.

There is a 2-step processing in TrackAtlas:

- 1st, sort out the data relative to the LRBG (wherever the train is)
- 2nd, relate the data to the train-

**Comment by UweSteinkeFromSiemens** [comment]
Dear @JakobGartner, 
the situation for MAs is comprehensible different: A LRBG must have been passed by the train and reported to the RBC, before it is allowed to be used by the RBC as a reference BG. In contrast, announcing a BG already been passed at most may reduce location uncertainty a little, but is otherwise useless. Since this behaviour is not specified - as far a I know - we are about to investigate the system by observation ...

**Comment by JakobGartner** [comment]
the Packet 5 is sent as part of a Message 3, consistently.

That is why I said “The MAs are received…” 


The first MA (with linking data) is sent before the level transition, then again at the level transition with identical data; but in both cases after passing the ref LRBG


Yes, we are discovering the track by driving over it :-) and encounter many nice surprises

**Comment by UweSteinkeFromSiemens** [comment]
This issue is followed up by #926, #927 and can be closed from my point of view.
