### ISSUE TITLE
MA at change to level 2

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#916]
The behaviour of the DMI would be more realistic, if the Level NTC-"MA" and the profiles would be delivered by the TrackAtlas itself and not via the constants. The first L2-MA would then extend the MA, which would avoid an empty planning area on the DMI.

**Comment by JakobGartner** [comment]
I think that this would not really change the behaviour, as the DMI has a specific behaviour when in ATB mode (as seen on the video)- the planning area for example is empty in NTC.

But I will look at that, have more urgent issues now so put at prio #3 (at least until tomorrows grooming)

**Comment by JakobGartner** [comment]
We have to discard this issue as this would require integration of NTC behaviour to make it consistent with the track data and also with the SRS. 

We can argue that NTC was out of project scope.

Please close.

**Comment by stefan-karg** [comment]
Agreed.
