### ISSUE TITLE
Can SDM probe be externalized?

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#917]
Currently the code generation for the demonstrators needs manual steps to copy the C-code for imported operators to the source-directory.

Would it be possible to find another way to access the data from the SDM module for the visualization in a way, that the EVC model itself can be generated without any manual steps?

**Comment by jokaICS** [comment]
> Currently the code generation for the demonstrators needs manual steps to copy the C-code for imported operators to the source-directory.

Do you really need the C code? I'd think it's only necessary to have the symbols defined by the imported operators available during linking.

> Would it be possible to find another way to access the data from the SDM module for the visualization in a way, that the EVC model itself can be generated without any manual steps?

Sure, we can just pass on the data to the integration level via outputs. (@T12z)

**Comment by T12z** [comment]
:flushed: Don't look at me when mentioning the daunted word *interface changes*.
It's a one-liner for me, if we agree about this. Does it actually have any mentionable performance issues?

**Comment by jokaICS** [comment]
@stefan-karg is this still relevant?

**Comment by BerndHekele** [comment]
Our way to make code generation and releases is not fault proof. If we could access scade probes from outside the evc model we would not haveinterface changes and may have a more stable environement??
Yes - it is still relevant but not high prior.

**Comment by jokaICS** [comment]
Well, we could move all imported operators outside of the EVC (i.e. into the toolbox/ testbench). But I see no way to replace the imported operators completely (unless we don't need external visualization while running the model in SCADE simulator).

**Comment by JakobGartner** [comment]
Simple idea:


You just export the supervised locations from SDM (along with the target speed)
You calculate a simplified braking curve outside (or replicate the SDM calculation outside)

I see no point in transporting the arrays with all the steps

**Comment by jokaICS** [comment]
The first decision to be made here is not about the amount of data to be transported, but whether we need imported operators or not.

**Comment by stefan-karg** [comment]
From my point of view, the problem can also be solved by a script, which copies the necessary C-source code files to the directory. 

A problem which occured recently is the use of different length settings for the names. This also modifies the interface of the generated code, which does it not make so easy to just copy the code. But this problem is also occuring if the imported code is used in other parts of the model.

A reason to externalize the imported operator would be to be able to generate the EVC code with one click for the weekly  releases without any manual work (or executing a script) in order to copy the code for the imported operators.

For all other users of the generated code, manual actions for the imported code outside the EVC are necessary anyway.

**Comment by jokaICS** [comment]
> A reason to externalize the imported operator would be to be able to generate the EVC code with one click for the weekly releases without any manual work (or executing a script) in order to copy the code for the imported operators.

OK. Then @BerndHekele and @T12z need to decide what/ if interface changes are required to allow moving the ProbeSDM operator outside of the EVC. From my point of view, I don't care where the operator is located :)

**Comment by T12z** [comment]
The `MRDT is already exportet to the `target` output of SDM.
`TargetCollection` and `CurveCollection` would need redirecting to outputs. Their types are already defined in SDM_Types-Project so no redefinition or depency issues should arise. I can route these signals to outputs, delete the imported operators in SDM, import the changes to the EVC and short cut SDM's new outputs to `X` for you to do the rest. This would leave the EVC consistant through the move. Exportimg the data from EVC to outside must be done by somebody else.

Proceed? And when would be my timeslot to modify the EVC?

**Comment by BerndHekele** [comment]
Let me put this probe in the evc.
I'll check at next opportunity on the details of the data.

**Comment by jokaICS** [comment]
@stefan-karg I think we can close this issue for now (and use a more robust approach for the next evolution:)?

**Comment by stefan-karg** [comment]
I would also agree with that. For all demonstrators developed at the moment, imported code is needed anyway, so it does not make a difference in the code generation process if it's located inside or outside of the EVC. For the future we can agree on externalizing all imported code outside of the EVC.

**Comment by jokaICS** [comment]
Currently no further action necessary.
