### ISSUE TITLE
Test report

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#919]
3602 m:
![image](https://cloud.githubusercontent.com/assets/2284296/11179696/7eec9464-8c55-11e5-9eb3-0f7b869a0953.png)
4359 m
flag speed chang target at speed zero

![image](https://cloud.githubusercontent.com/assets/2284296/11179793/335bcabe-8c56-11e5-865e-6b934f8cd873.png)

LRBG: 362
4982 m
jumping speed indicator 
![image](https://cloud.githubusercontent.com/assets/2284296/11179849/9c6384d4-8c56-11e5-83be-0f126ee313b4.png)

LRBG: 362  
5014 m

![image](https://cloud.githubusercontent.com/assets/2284296/11180060/247bd1ae-8c58-11e5-9ef0-5a4a17de3eeb.png)

![image](https://cloud.githubusercontent.com/assets/2284296/11180072/351117c2-8c58-11e5-8d8f-e58192a8170c.png)

5317 m
![image](https://cloud.githubusercontent.com/assets/2284296/11180179/ebb81a2a-8c58-11e5-8b22-3d48a4b5810a.png)

5801 m and 7603 m 8800
jumping gradiant profile

26589 m

 pasp is not consist
![image](https://cloud.githubusercontent.com/assets/2284296/11181854/3452bbe8-8c66-11e5-9f06-e5cfe738a009.png)

BG 424
26872 m

jumping speed gauge

LRBG 426
27301 m

![image](https://cloud.githubusercontent.com/assets/2284296/11182040/ec0a5d1c-8c67-11e5-8ccb-fc52b7bc3945.png)

![image](https://cloud.githubusercontent.com/assets/2284296/11182051/18a420e2-8c68-11e5-8c92-d6d2057e8d48.png)

31185 m

no PIM and no Over speed warning

![image](https://cloud.githubusercontent.com/assets/2284296/11182151/da3421f8-8c68-11e5-8691-8cd3f66b2797.png)

BG 443
RBC connection is not closed

![image](https://cloud.githubusercontent.com/assets/2284296/11182188/266962d6-8c69-11e5-8fbf-c84950c8f97c.png)

**Comment by stefan-karg** [comment]
@ 4359 m (flag speed chang target at speed zero): Problem will be solved by a change in the TrackAtlas. DMI-Controller module is ok.

**Comment by stefan-karg** [comment]
@ LRBG: 362
4982 m jumping speed indicator 

@T12z Can you please have a look at this problem? After tracing the behaviour through the model, for me it looks like a wrong behaviour in the SDM module, since the data from the track atlas looks fine.

**Comment by T12z** [comment]
moin @stefan-karg ,
this is what SimCtrl has to say about this:

![sdm-target-log](https://cloud.githubusercontent.com/assets/10432699/11246457/0a090938-8e18-11e5-93da-75c6f8cf7f4a.PNG)

the jumping of EoA->SvL->EoA is exactly what I think you mean.
Sorry, out of time looking at this tonight in detail (aka debugging the model), may even quite be squeezy tomorrow.
Anyways, see that SvL is double the distance of EoA? Could a bug be when importing / converting the targets from TA, but why would it disappear shortly after? I am reeeeally in doubt of an SDM problem, even though it could always be.

**Comment by Farhangi** [comment]
Speed profile discontinuity is fixed
(speed decrease and increase) and (target at speed zero) will be displayed.

**Comment by stefan-karg** [comment]
@T12z Thanks for the correction, I don't see any jumping any more.

**Comment by T12z** [comment]
@Farhangi was what I fixed the root of this issue? I go and close it then
