### ISSUE TITLE
Performance in NTC worse than in Level 2?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#920]
I'm observing some intriguing behavior while running ROOT_Simulation (non-optimized code, debug: all): when the EVC is in NTC the CPU utilization is approx. **twice** compared to the utilization while in Level 2. A quick CPU time sampling revealed that ~45% of the cycle are spent in `CalcBrakingCurves_Pkg::InternalOperators::BCFoldOperationBackward` while in Level NTC, but ~0% while in Level 2.

It's not a problem, since we can easily keep a 10ms cycle for both levels when we use optimized code on a modern desktop PC. I'm just curious why NTC would be more computationally intensive than Level 2.

**Comment by JakobGartner** [comment]
Maybe because this is a very loooooooong section which comes in one piece?

**Comment by jokaICS** [comment]
Maybe, but why should the **length** of a section have such an impact on a fold? I'd understand if it had a lot of sections...

**Comment by JakobGartner** [comment]
It was a joke

**Comment by jokaICS** [comment]
> It was a joke

We have no user story involving jokes, so I didn't expect to encounter one on this tracker...

**Comment by T12z** [comment]
Not sure, if worth further analyzing,
but generally once *any* operator out of SDM is open for viewing in the Scade Simulator, the system slows down big times. Just Don't do it, unless Jakob is about to jump out of windows.

**Comment by jokaICS** [comment]
Actually, I didn't run it in SCADE simulator, but standalone. Anyway, it's not a problem, I was just curious.
