### ISSUE TITLE
DMI shows "TRIP" without EB active

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#925]
When driving the new Sheet14_only track, the DMI shows a TRIP directly after the transition from NTC->2 -- **but the brakes are not applied** (so I'm happily cruising on at 140 kph :)

![image](https://cloud.githubusercontent.com/assets/13429700/11247782/de010088-8e1d-11e5-9dd0-7a19d6384695.png)

**Comment by JakobGartner** [comment]
I suspect that the sequence of level transition and MA is not correct. I will try to understand

**Comment by jokaICS** [comment]
Sure, there are probably some minor glitches in the new modular track. However, I'm more intrigued by the fact, that the DMI shows TRIP, but the brakes are not applied.

**Comment by T12z** [comment]
same thing as in #903 (even though no trip there)

**Comment by jokaICS** [comment]
duplicate of #928
