### ISSUE TITLE
Even more linking consistency errors on track

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#926]
While traveling along the track, the following linking consistency errors occur:

- BG 389: BGpassedInUnexpectedDirection, afterwards linkedBGMissed (= not found until the end of the expectation window). 
- BG 0: announced between BG 400 and 401, then later linkedBGMissed (I'm not sure, if this is not an unintended zombie BG)
- BG 397 linkedBGMissed, then  passedBG_foundNotWhereExpected
- BGs  402, 403, 404, 405 passedBG_foundNotWhereExpected, then linkedBGMissed 

The track requires to be adjusted, since more consistency errors are to be expected ahead otherwise.

**Comment by BerndHekele** [comment]
I will follow-up on this issue.
@JakobGartner : the correction of BG 0 in the linking data is not on Github yet.

**Comment by BerndHekele** [comment]
You find the BG 0 in the following constants:
LRBG371_P005.
I did not see any other.

**Comment by JakobGartner** [comment]
This is done.

Again, this is wrong already in the recorded JRU data.

It is possible that this correction may also correct the following references (as they are incremental)


I wait for the next report for looking deeper.

It is unlikely that “so many” linking refs are wrong independently

**Comment by BerndHekele** [comment]
Update after integration of corrections:
 - BG389 is passed in wrong direction (Linking is nominal, track is reverse)
 - BG397 misplaced (nominal 1600988):
![image](https://cloud.githubusercontent.com/assets/3288918/11276992/b33b935a-8ee4-11e5-97b3-a0b19f280234.png)

 - BG403 (nominal 1885952):
![image](https://cloud.githubusercontent.com/assets/3288918/11277329/6faee57c-8ee6-11e5-865a-26ade800b419.png)

**Comment by JakobGartner** [comment]
We will check.


According to our XREF document with repositioned/ corrected BGs  

> On 19 Nov 2015, at 18:07, Bernd Hekele <notifications@github.com> wrote:
> 
> Update after integration of corrections:
> 
> BG389 is passed in wrong direction (Linking is nominal, track is reverse)

This should be nominal. We check the linking data 
> BG397 misplaced (nominal 1600988):
>  <https://cloud.githubusercontent.com/assets/3288918/11276992/b33b935a-8ee4-11e5-97b3-a0b19f280234.png>
> 

The calculated pos (abs) should be around 15992

> BG403 (nominal 1885952):
>  <https://cloud.githubusercontent.com/assets/3288918/11277329/6faee57c-8ee6-11e5-865a-26ade800b419.png>
The calculated pos (abs) should be around 18943


we will review the linking data.

**Comment by BerndHekele** [comment]
Can you provide a correction for BG397 in the track-atlas please, Jakob.

**Comment by BerndHekele** [comment]
I did not see any problems in the past.
I close this issue.
