### ISSUE TITLE
Alignment of ETCS_language types

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#93]
We would like to adjust some types in the ETCS_language implementation in Scade (https://github.com/openETCS/modeling/tree/master/model/Scade/System/ETCS_Language/S026_7).

In the current type definition, some types are defined as real, which does not comply to the SRS, where all values are defined as integer values with possible scaling factors. 

The table in 
https://github.com/openETCS/modeling/blob/master/model/Scade/System/ETCS_Language/Datatypecheck.pdf 
compares the types of the current implementation with the types defined in the SRS.

Are there any objections to the adjustment of the ETCS_Language types according to the SRS?

**Comment by BenjaminBeichler** [comment]
I think it's the same discussion in #92

**Comment by JakobGartner** [comment]
please refer to #92

**Comment by UweSteinkeFromSiemens** [comment]
As mentioned in #92, the reals = floats were generated to ease prototyping.

**Comment by stefan-karg** [comment]
Replaced by more recent issues on this topic.
