### ISSUE TITLE
MRSP from TrackAtals to DMI

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#931]
Hello @JakobGartner !

For the correct display of the "Speed profile discontinuity" on the DMI: 
- either MSRPs(from TrackAtlas) includes the current section,
- or DMI should store the current MRSP.

**Comment by stefan-karg** [comment]
Dear Peyman, 

Jakob is already working on a correction of this issue. There is currently a little bug in the calculation of the MRSP for the DMI. This will be resolved today.

**Comment by mairamou** [comment]
When reducing the MRSP sections (merging sections with equal speed limits), Track Atlas kept the last section instead of the first. This lead to the speed profile apparently start in front of the train and/ or displaying wrong speed. 

This has been corrected with the last commit

**Comment by BaseliyosJacob** [comment]
@Farhangi ,

in the design phase of the DMI we agree not to store any MRSP in the DMI Controller. All MRSP information will be stored on the Track Atlas and the DMI receives the "current speed profiles" from the track atlas, which will be stored until a new information is valid. 

This storagefunction is already implementent. In this case the Track Atlas is always responsible for the correct Speed profile.

**Comment by JakobGartner** [comment]
This is done on TrackAtlas side 

No change required on DMI side

**Comment by JakobGartner** [comment]
can't we close this?

**Comment by Farhangi** [comment]
Correction is available.
