### ISSUE TITLE
Trackdefinition: Findings on testrun

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#935]
In this run some problems with the track still were visible (information based on the event-log):
1. Wrond direction od BG 389
2. Wrong direction of Packet 21 in Msg 3 at LRBG 416
3. Positioning problems at balises 397 and 403.
4. Orange speed indicator at about m 21580

I will look for corrections in the packets.

[~     0m SDM] Target type: EoA  Distance: 50000.0  Speed: 0
[~     0m RTM] Registration status: 0  healthStatus: 1  nid_mn: 0  mobileDeviceNo: 0
[~     0m RTM] Connection status: 0  mobileDeviceNo: 0  nid_radio: 0  connectionLost: 0  isInRadioHole: 0  settingUpConnectionHasFailed: 0
[~     0m RTM] Session phase: 0  nid_radio: 0  nid_rbc: 0  nid_c: 0
[~   242m RTM] Registration status: 1  healthStatus: 1  nid_mn: 0  mobileDeviceNo: 0
[~   242m RTM] Registration status: 1  healthStatus: 1  nid_mn: 2114079  mobileDeviceNo: 0
[~   246m RTM] Registration status: 2  healthStatus: 1  nid_mn: 2114079  mobileDeviceNo: 0
[~  1181m RTM] Session phase: 0  nid_radio: 500  nid_rbc: 1  nid_c: 426
[~  1181m RTM] Session phase: 1  nid_radio: 500  nid_rbc: 1  nid_c: 426
[~  1184m RTM] Connection status: 0  mobileDeviceNo: 0  nid_radio: 500  connectionLost: 0  isInRadioHole: 0  settingUpConnectionHasFailed: 0
[~  1184m RTM] Connection status: 2  mobileDeviceNo: 0  nid_radio: 500  connectionLost: 0  isInRadioHole: 0  settingUpConnectionHasFailed: 0
[~  1188m RTM] Session phase: 2  nid_radio: 500  nid_rbc: 1  nid_c: 426
[~  3663m SDM] Target type: EoA  Distance: 5043.9  Speed: 0
[~  4027m SDM] Target type: SvL  Distance: 5043.9  Speed: 0
[~  4981m SDM] Target type: EoA  Distance: 5619.2  Speed: 0
[~  4995m SDM] Target type: EoA  Distance: 7529.2  Speed: 0
[~  5127m SDM] Target type: EoA  Distance: 16743.9  Speed: 0
[~  6708m SDM] Target type: EoA  Distance: 18100.2  Speed: 0
[~ 10803m SDM] Target type: EoA  Distance: 20866.8  Speed: 0
[~ 12198m ERR] Position Error: BGpassedInUnexpectedDirection
[~ 12210m ERR] Position Error: linkedBGMissed  (BG: 389)
[~ 16005m ERR] Position Error: linkedBGMissed  (BG: 397)
[~ 16009m ERR] Position Error: passedBG_foundNotWhereExpected  (BG: 397)
[~ 17800m SDM] Target type: EoA  Distance: 26931.7  Speed: 0
[~ 18855m ERR] Position Error: passedBG_foundNotWhereExpected  (BG: 403)
[~ 18954m ERR] Position Error: linkedBGMissed  (BG: 403)
[~ 22749m SDM] Target type: EoA  Distance: 32046.6  Speed: 0
[~ 27275m SDM] Target type: EoA  Distance: 33338.7  Speed: 0
[~ 29884m SDM] Target type: MRSP  Distance: 32011.7  Speed: 700
[~ 31995m SDM] Target type: EoA  Distance: 33338.7  Speed: 0
[~ 32006m SDM] Target type: EoA  Distance: 50000.0  Speed: 0
[~ 32414m RTM] Session phase: 3  nid_radio: 500  nid_rbc: 1  nid_c: 426
[~ 32414m RTM] Connection status: 0  mobileDeviceNo: 0  nid_radio: 500  connectionLost: 0  isInRadioHole: 0  settingUpConnectionHasFailed: 0
[~ 32414m RTM] Session phase: 0  nid_radio: 500  nid_rbc: 1  nid_c: 426

**Comment by JakobGartner** [comment]
am on it right now, too

we should coordinate :-)

I am comparing with JRU and XREF

**Comment by JakobGartner** [comment]
389 is corrected (is now nominal on the track)

**Comment by JakobGartner** [comment]
BG 397 is corrected (Zahlendreher)

**Comment by JakobGartner** [comment]
403 is corrected (Zahlendreher)

**Comment by BerndHekele** [comment]
fine
 thanks.

**Comment by BerndHekele** [comment]
Did you also correct diection of LRBG 416 (Packet 21).

**Comment by JakobGartner** [comment]
yeah !!!!

**Comment by Rainer-Lampatzer** [comment]
EB at km 5.039:

![message](https://cloud.githubusercontent.com/assets/14076350/11419854/7981f9a6-942a-11e5-810a-cfeba31d8fa8.jpg)

BG 362: km 4.7537; MA: 230.9 m later

![speed profile](https://cloud.githubusercontent.com/assets/14076350/11419921/d9e8ba32-942a-11e5-86c4-f04cf490340e.jpg)

Speed profile only 292 m ==> up to km 4.9957.

The train can not brake that fast, thus an EB will be triggered. 
No mode transition to TR mode, which is correct. (maybe a gap in the spec, but this is off topic here).

**Comment by Rainer-Lampatzer** [comment]
cure: set n_iter_k to 2

**Comment by jokaICS** [comment]
I still see linking errors; is the track file outdated (current date: 22.11.15 19:27)?

![image](https://cloud.githubusercontent.com/assets/13429700/11498517/2deff688-9820-11e5-9766-803be6992b2f.png)

**Comment by BerndHekele** [comment]
Working corrections
