### ISSUE TITLE
SimCtrl with inconsistency information

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#938]
Dear Johannes,
I see the following infromation in a SimCTRL error report when going UtrechAmsterdam and after passing BG 351:

invalid nid: 5 (offset: 120)
invalid nid: 5 (offset: 120)
    while executing
"error "invalid nid: $nid (offset: $offset)""
    (procedure "pkts::readBinTrainPkts" line 24)
    invoked from within
"pkts::readBinTrainPkts $os "$data""
    (procedure "msgs::parseBinTrainMsg" line 4)
    invoked from within
"msgs::parseBinTrainMsg "$data" 8"
    (procedure "handlePosReport" line 2)
    invoked from within
"handlePosReport "$data""
    (procedure "evts::handleTrainMessage" line 10)
    invoked from within
"evts::handleTrainMessage "[read $channel $len]" "
    (procedure "comm::readMsg" line 13)
    invoked from within
"comm::readMsg sock876"

**Comment by jokaICS** [comment]
Did the error "simply pop up", or did it occur after you clicked on one of the messages in the message log?

**Comment by jokaICS** [comment]
One further question: is the error reproducible, or does it occur randomly?

**Comment by jokaICS** [comment]
Hmm, I just realized, that there actually exists a train->track packet 5; does the EVC actually send a packet 5?

**Comment by jokaICS** [comment]
@BerndHekele I've pushed an update; could you please check if the problem persists?

**Comment by jokaICS** [comment]
@BerndHekele can we close this issue?
