### ISSUE TITLE
DMI freezes

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#943]
I get a frozen screen when using the test_envsim environment in scripted mode.
Have you seen this before?
![image](https://cloud.githubusercontent.com/assets/3288918/11478819/5625a008-978f-11e5-8213-3fcf58dbcd47.png)

**Comment by BerndHekele** [comment]
I made a fallback to the original settings in the profiles which solved the issue.

**Comment by jokaICS** [comment]
I'm re-opening this issue, since it probably was simply a coincidence that re-setting the profile solved the problem. I've encountered this issue regularly, though not reproducibly. It's probably a timing issue, but I'm still lost as to what is the root cause. I'll keep an eye on it.

**Comment by BerndHekele** [comment]
I have an indication it is happening especially if you enter the track file name in the phase where the DMI dialog is ongoing.

**Comment by jokaICS** [comment]
Should be solved with libenvsim 0.6.x. Can we close this issue?
