### ISSUE TITLE
Test.trk: Level Change does not work

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#944]
Hi Johannes,
issue is caused by missing packet 21 as a part of msg 3.

![image](https://cloud.githubusercontent.com/assets/3288918/11481248/97da531a-979c-11e5-9a3e-597ba6a61150.png)

kr.
Bernd

**Comment by jokaICS** [comment]
Thanks for the analysis; I've pushed a new test.trk with a Pkt21 in the MA. I've also added an additional Level Transition Order (Pkt41) to BG904 -- the EVC now executes the transition to level 2. However, since the MA seems not be processed correctly, the EB is triggered immediately after the transition. Could you please take another look? As soon as the transition + MA work, I'm going to add the Pkt80 for On-sight to the MA.

BTW: I don't understand why we need to repeat the level transition order sent with the MA by a balise; if I understand the SRS correctly, the transition order can be given by radio message OR balise, right?

**Comment by BerndHekele** [comment]
I tried the track - same error - packet 21 is stil missing (it is also not visible in the track oputput of the SimCtrl.
Repeating the MA by balise is not required by the standard. It is sufficient to have the message once.
It is a design decision by NS.
.

**Comment by jokaICS** [comment]
Hmm, do have the current version "Test Track (01.12.15 8:30)"?

![image](https://cloud.githubusercontent.com/assets/13429700/11496802/dbc77242-9814-11e5-85a5-7ceb2f72a295.png)

**Comment by jokaICS** [comment]
OK, I've pushed the track again; the version now is "10:30".

**Comment by BerndHekele** [comment]
I see a confusion in the decompression of the packet 41:
![image](https://cloud.githubusercontent.com/assets/3288918/11499425/5fbd4f66-9826-11e5-81c8-4df89a312847.png)
I also don't see P46 (Conditional Level Transition) which is in our model distributed via Track. In this packet the available Levels are defined.
I'm not 100% sure it is needed.

**Comment by jokaICS** [comment]
OK, there was an error in the encoding of Pkt41 -- should be fixed. I've also added a Pkt46 to BG902.

**Comment by BerndHekele** [comment]
Hi Johannes,
as discussed today some of the evc presentations of packets:
P21:
![image](https://cloud.githubusercontent.com/assets/3288918/11510268/2ee0fefa-9863-11e5-9841-457df2ecb21e.png)

P27:
![image](https://cloud.githubusercontent.com/assets/3288918/11510342/a0623fd0-9863-11e5-82c8-8ceaa58f6255.png)

![image](https://cloud.githubusercontent.com/assets/3288918/11510402/df667674-9863-11e5-9ae9-4dcaf50d4eac.png)

P5
![image](https://cloud.githubusercontent.com/assets/3288918/11510445/13958db8-9864-11e5-8b85-a26ce8a6e57f.png)

let me know if you need more.

**Comment by jokaICS** [comment]
Great, thanks. I see that the SSP is missing completely, which is probably the reason for the EB.

**Comment by BerndHekele** [comment]
Hi Johannes,
here comes the information for P80:
![image](https://cloud.githubusercontent.com/assets/3288918/11535146/cf1fb456-9912-11e5-89cb-34fb203392fe.png)

**Comment by jokaICS** [comment]
Thanks -- the encoding/decoding looks good to me. However, when I drive the test track with MA + Pkt80, the EB is triggered immediately after the level transition. I'm not sure about the parameters set in the MA.

@Rainer-Lampatzer could you please take a look into the the test track and check if the parameters for P080 (and the other packets in the MA) are reasonable?

**Comment by Rainer-Lampatzer** [comment]
I can only guess what confuses the EVC - we better talk before putting too many possible reasons here.

**Comment by BerndHekele** [comment]
I closed a gap in the evc data flow.

**Comment by BerndHekele** [comment]
I cannot see an trip in this testrun.
Maybe you did not confirm the level change at the DMI in time.

**Comment by BerndHekele** [comment]
I close this issue - correction is tested and available.
If the trip occurs please open a new issue.
