### ISSUE TITLE
Test report 01.12.- pointer is not syncron with CSG

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#946]
@Rainer-Lampatzer @ShuangjiaoCao @T12z 

pointer is not syncron with CSG 

3871 m
![image](https://cloud.githubusercontent.com/assets/2284296/11501160/5fad7a8a-9832-11e5-8997-db2fe57c2262.png)

4497 m

pointer is not syncron with CSG

![image](https://cloud.githubusercontent.com/assets/2284296/11507137/ee995c3a-9852-11e5-8722-f01df8678b7b.png)

**Comment by BaseliyosJacob** [comment]
Issue can be closed.
