### ISSUE TITLE
Test report 01.12.- Gradient Profile is not consistent with the length of MRSP

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#950]
@JakobGartner 

at km 14085 gradient profile is shorter than MRSP

![image](https://cloud.githubusercontent.com/assets/2284296/11508298/5186675c-9858-11e5-8b7d-8fc6728b4ffc.png)

**Comment by Rainer-Lampatzer** [comment]
The data in the track viewer say that the gradient profile is longer than the speed profile: The first sector is same length, but the next 5 sectors are missing.

Something must have gone wrong converting the data from  the model constants into a track file. There is a P027 section missing in the track file.

**Comment by jokaICS** [comment]
@Rainer-Lampatzer There seems to be a bug in the enc/decoding library used by TrackViewer/SimCtrl; please do currently not rely on TrackViewer for P027 data (#951)

**Comment by BaseliyosJacob** [comment]
@Rainer-Lampatzer thank you very much for your reply. But checking the data in the scade model we assume that the Gradient Data are to short for the current sector. This was the result in a first briefly check.

**Comment by BaseliyosJacob** [comment]
@JakobGartner can you please check the data from the track atlas. On my first check i saw that may the gradient profiles from the track atlas are not consistent with the MRSP.

**Comment by JakobGartner** [comment]
Mairamou and I will check that together in the evening

**Comment by JakobGartner** [comment]
This issue has been analyzed now on the track model.
At first I thought to have found an inconsistency in the JRU data but after deeper analysis this looks like this:


The LRBG at location (abs) 14085 is 
BG385
The EOA (abs) as in the track model is 20686
The length of the available gradient info at this point is 20918 (abs)
The end of the available MRSP info at this point is at 20918 (abs)

So at 14085 the visible profiles should have a relative length of around 6600m from the train.

I will have to see if there is a problem with TrackAtlas .



The data in the track model are consistent with the JRU data 

Are there similar problems at other places on the track ?

**Comment by JakobGartner** [comment]
at BG385, for P21, the Q_DIR was wrong. 
This has been corrected.

**Comment by BerndHekele** [comment]
Correction available
