### ISSUE TITLE
modeling/model/Scade/System/OBU_Integration: Call for participation

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#96]
We are starting to prepare the integration effort for the different submodels that are being created in a distributed way by WGs 1-4 and additional teams.

We have taken the functional breakdown from the ALSTOM ICE 406 OBU architecture (their breakdown has been published by DB/) and mapped/merged it to the breakdown we have designed since the November Munich workshop.

As a consequence from the decentralised and loosely coupled approach we have been following, we need to follow a centralised approach for models integration, meaning that LEA/Railergy will steer and actively manage the work.

As you can see, I have used the relative paths as predefined by Iteration 1 and all teams are invited to commit their models in the same directory structure. 
Each team should maintain their own model in their own directory, and we will work interactively to compose the full system.

The model basically has two layers:

- A system description layer (to be aligned with the SCADE System model).
F2 contains our kernel.
The other blocks contain external modules.
For some blocks (DMI, Radio) there is a functional split: the OBU maintains its side of management and communication, while the subsystem handles its own side and behaviour.

- A kernel software layer: Inside the kernel, I have prepared I 2nd level breakdown which specifically takes into account interoperability issues.

For the groups whose model I have a basic understanding of, I have attempted to allocate their functions to the corresponding subsystems.

This is flexible to some extent and subject to discussion.

Data types are also not yet defined on this level (on purpose).

Each group should "egoistically" expose the desired input and output formats.

We will in subsequent steps define:

- Sources and sinks for each data flow 
- Optimise data types, data structures and minimise necessary type conversions
- Finally define our "internal types" for each flow or group of flows
- Connect these flows to the ETCS language/ API data types.

Don't hesitate to contact me using this issue tracker, I will then fork new issues per thread as needed.

Jakob

**Comment by BerndHekele** [comment]
I have provided the Integration Model for the TrackSide messages input channel:
https://github.com/openETCS/modeling/tree/master/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/BaliseGroup/Manage_TrackSideInformation_Integration

The model does not yet compile.
It can be loaded without problems and show main input and outputs.
We will continue next week to make the model compilable and complete regarding the functionality for the review.

**Comment by BerndHekele** [comment]
We made good progress on the integration in the testbench-model.
I ewant to clean the issues in modelling.
Therefore, I close this request.
