### ISSUE TITLE
UserStory 14: OS -> FS not possible as described.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#960]
Hi Baseliyos,
the SRS P80 only supports OS, LS and SH - FS is not supported by this package.Can you please describe how the mode change back to FS is working?

kr
Bernd

**Comment by MariellePetitDoche** [comment]
P80, defined in the same time taht the mode profile OS is request, the area on which it is request.
When the train reach the end of this area:
- if no more information are available this end is considered as an EOA
- if an MA or other Mode profile  have been received there are taken into account.

Thus to switch to FS, you need to receive MA+SSP+gradient information before the end of area.

**Comment by BerndHekele** [comment]
Thanks for clarification.

**Comment by BaseliyosJacob** [comment]
@MariellePetitDoche thank you very much for the clarification.
@BerndHekele ,

i agree to Marielles clarification.

We have the same situation with the Mode Change from SN to FS after we are leaving the station. In this case we are reveiving and MA+SSP+.. but without an Packet 80 and the train changes automaticaly to FS.

Generally! the ETCS OBU (if everything else is setted) change to FS after receiving and MA if packet 80 is not within the information. The Packet 80 is just necessary if FS! is not foreseen.

**Comment by BerndHekele** [comment]
In this case I close this issue.

**Comment by Rainer-Lampatzer** [comment]
Can this issue be merged with https://github.com/openETCS/modeling/issues/71 ?

I already made this remark there last Wednesday.
