### ISSUE TITLE
Test report 7.12..2015_wrong behavior after brake intervention

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#965]
@T12z 
according to SRS, after brake intervention the train should brake until it reach yellow, grey or white area. 

In  the current implementation (see image below) the train is not going into the yellow area and staying in orange area after brake intervention.

![image](https://cloud.githubusercontent.com/assets/7654856/11628793/46a48198-9cf4-11e5-906c-ca06256f7636.png)

**Comment by ShuangjiaoCao** [comment]
TODO: check if the interface from SDM

**Comment by T12z** [comment]
this was due to the attempt of a limiter function, see #949 
limiter was removed in recent commit
