### ISSUE TITLE
Test report 7.12..2015_wrong behavior of SDM

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#966]
@T12z @JakobGartner 
Wrong behaviour of SDM (see image) missing CSG red and orange.

![image](https://cloud.githubusercontent.com/assets/7654856/11629359/121a7b36-9cf8-11e5-9e85-5f6bc5d2ff72.png)
![image](https://cloud.githubusercontent.com/assets/7654856/11629374/30c86624-9cf8-11e5-924d-99021460ddbe.png)

**Comment by T12z** [comment]
see comment on #949 , may be related

**Comment by ShuangjiaoCao** [comment]
TODO: screenshot for interfaces to SDM

**Comment by JakobGartner** [comment]
To debug all these issues from @ShuangjiaoCao related to discrepancies , we would lead to discrepancies in the DMI display from TrackAtlas point of view. @stefan-karg or @ShuangjiaoCao  could we do a gotomeeting tomorrow? I would need to see what happens at the TrackAtlas output in this moment.

**Comment by stefan-karg** [comment]
Since I will be busy with the demonstrator tomorrow, I would suggest a gotomeeting with @ShuangjiaoCao if possible.

**Comment by T12z** [comment]
possibly solved by recent commit,
caused by unclear SRS definition, wrong target handling when they intersect (EoA vs. SpeedLimit)
