### ISSUE TITLE
Test report 7.12..2015_target bar and CSG is not consistent with MRSP

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#967]
@T12z @JakobGartner 

as seen in the image below the target bar and CSG is not consistent with MRSP.

1. Target bar shows 820 m for speed reduction but MRSP shows over 1000 m for speed reduction

2. CSG shows 135 km/h as next speed reduction but track information is 140 km/h for next reduction.

![image](https://cloud.githubusercontent.com/assets/7654856/11629543/2259edc8-9cf9-11e5-9eac-81a17126ec1e.png)

**Comment by T12z** [comment]
(2) is related to #969

**Comment by BaseliyosJacob** [comment]
@JakobGartner can you please check the track date for this issue.

Thank you very much

**Comment by JakobGartner** [comment]
Yes 

But I doubt it comes from there as track atlas emits only one set of data and they are the same for SDM and DMI

And both are calculated from the same track model ...

**Comment by JakobGartner** [comment]
A speed of 135 km/h cannot come from TrackAtlas, as no speed calculations whatsoever are done there 
The relevant packet 27 at BG 426 contains the correct data for 140km/h (28)

**Comment by ShuangjiaoCao** [comment]
@JakobGartner  yes (2)  was a Scade Display Scala error, I have corrected it and will push it tomorrow:)

**Comment by T12z** [comment]
FYI / @JakobGartner 
intermediate update: there is some (still unidentified) glitch that flushes all MRSP-targets in SDM, I will keep debugging

**Comment by T12z** [comment]
update, ^^^ was just a mis-read, but currently it looks even more like an issue in SDM, @27227m the inputs to SDM look reasonable and valid, the output does not) This is actually the point where the little 140km/h segment is received, which seems to cause the upset ... still hunting for it ....

**Comment by JakobGartner** [comment]
Up to now I could also not identify any crazy TrackAtlas output, neither to SDM nor to DMI 

(drove 3 times)

**Comment by T12z** [comment]
update @BaseliyosJacob ,
yes, I found an issue last night, though not just a typo or copy/paste-error, rather something out of the gray zone of the SRS. I could not really run tests via remote desktop last night, please hold on a little. The nightly bug-fix is unfortunately not perfect out-of-the-box. :wink:

**Comment by T12z** [comment]
... looks good, update/push will follow shortly

**Comment by T12z** [comment]
possibly solved by recent commit
