### ISSUE TITLE
Test report 7.12..2015_wrong behavior of SDM and Mode

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#968]
@JakobGartner @T12z 

in the image below you can see wrong behaviour of the SDM

1. Target bar is active but SDM/CSG is not in TSM. It is in CSM.
2. Should be in TSM.
3. Target bar distance is not consistent with MRSP.

![image](https://cloud.githubusercontent.com/assets/7654856/11629680/d0221f20-9cf9-11e5-9a56-c74242af47c2.png)

![image](https://cloud.githubusercontent.com/assets/7654856/11629733/2c1caeda-9cfa-11e5-8559-5d7378e05468.png)

**Comment by T12z** [comment]
this seems completely out of sync. The whole variable looks zero-filled and the equal-to-zero value of sup_status is CSM ("unknown" is actually as integer-value 4).

**Comment by BaseliyosJacob** [comment]
@JakobGartner can you please check the track data for this issue.

**Comment by JakobGartner** [comment]
The track data are coherent with the JRU data.

Where did you probe these data exactly?

**Comment by T12z** [comment]
in the end duplicate of #967
