### ISSUE TITLE
Test report 7.12..2015_wrong scala of DMI Controller

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#969]
![image](https://cloud.githubusercontent.com/assets/7654856/11630060/f19dc486-9cfb-11e5-8391-ddbe994b08c7.png)
target speed is not right (should be 139km/h)

**Comment by T12z** [comment]
that is a pure on-screen-drawing issue. The width of the end-nipple of the CSG moves all other segments.

**Comment by ShuangjiaoCao** [comment]
I have solved it by changing the start-position of the scala in CSG in Display
![image](https://cloud.githubusercontent.com/assets/7654856/11682429/1964a196-9e65-11e5-8437-52f6661b50a3.png)
