### ISSUE TITLE
Test report 7.12..2015_wrong behavior after brake intervention Nr.2

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#970]
@T12z 

According to SRS, after brake intervention the train should brake until it reach yellow, grey or white area. 

In the current implementation (see below) the train is not going into the grey area and stay in orange area which is disappearing at the moment after brake intervention. 

![image](https://cloud.githubusercontent.com/assets/7654856/11630155/6e261332-9cfc-11e5-9cf9-fe791bd9fe8e.png)

**Comment by BaseliyosJacob** [comment]
Same as #966
