### ISSUE TITLE
Modes::PriorityManagement_FromOS no switch to FS

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#974]
In the dicision table the wrong target mode is selected:
![image](https://cloud.githubusercontent.com/assets/3288918/11654954/f999d6a8-9da9-11e5-827b-b61ea7c37913.png)

Has to be FS.

cu
Bernd

**Comment by MariellePetitDoche** [comment]
Yes,

I will not have access to the Scade licence before Thursday, so please to
correct it if you need.

2015-12-08 12:49 GMT+01:00 Bernd Hekele <notifications@github.com>:

**Comment by BerndHekele** [comment]
No problem.
I work with a private correction locally and wait for your official contribution.
cu
Bernd

**Comment by T12z** [comment]
@BerndHekele 
I cannot run any test (for the DMI/CSG-things) either. What do I have to do, or what is the last working commit?

**Comment by MariellePetitDoche** [comment]
Correction Done

**Comment by BerndHekele** [comment]
Correction Tested
