### ISSUE TITLE
Test report 9.12..2015_irregular behavior of target speed 

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#980]
@T12z 

the SDM  is in TSM and V_target is 139 km/h.

But the Planning area shows a v_target of 0 km/h.

@T12z is this behaviour by purpose or a bug?

![bug111](https://cloud.githubusercontent.com/assets/7654856/11683358/8eca5890-9e6a-11e5-91d4-ce5942bddc0a.PNG)
![bug112](https://cloud.githubusercontent.com/assets/7654856/11683370/9b113a9c-9e6a-11e5-98c0-4561aecb51b5.PNG)

**Comment by T12z** [comment]
possibly solved by recent commit

**Comment by T12z** [comment]
duplicate of #967
