### ISSUE TITLE
Test report 09.12.- irregular behavior of CSG

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#981]
@T12z 

![image](https://cloud.githubusercontent.com/assets/2284296/11684441/dd9069fe-9e71-11e5-91bb-6dbf2713ca60.png)

**Comment by ShuangjiaoCao** [comment]
![image](https://cloud.githubusercontent.com/assets/7654856/11684905/3c7a8794-9e75-11e5-9f3c-ac0916d367fb.png)

**Comment by ShuangjiaoCao** [comment]
solved in DMI Display

**Comment by T12z** [comment]
@ShuangjiaoCao please close if solution works
